### ISSUE TITLE
Examples panicked with IncompatibleDriver trying to load libvulkan.1.dylib on mac

### ISSUE THREAD

**Issue by Jbat1Jumper** [vulkano-rs/vulkano#1000]
I'm starting to learn Vulkan on mac and I ran into a problem loading the library. I already looked at #948 and #928 so I guess is directly related but I can't help much with this. I guess that the thing may be that I'm actually compiling the examples from `master` and looking at the changelog I see that this changes are not released yet. 

Anyway, if the issue is because the library was updated I guess is good to inform that. I've downloaded the version 1.1.77.0 of the library and I suppose that the dyld path is ok because it reaches the file. Here's a cap with the trace at the left, the $DYLD_LIBRARY_PATH and an ls of the vulkansdk/macOs folder:

![image](https://user-images.githubusercontent.com/2244403/43352553-83f87b54-91fb-11e8-9031-13e029841248.png)

I'll try using the library via cargo and see if I can get this thing running.. 😬

**Comment by Jbat1Jumper** [comment]
Ho, it's # 💯0 !

**Comment by Jbat1Jumper** [comment]
I confirm that running the triangle example from [vulkano-examples](https://github.com/vulkano-rs/vulkano-examples) works like a charm with the MoltenVK.framework which comes with vulkansdk 1.1.77.0 for mac.

**Comment by tomaka** [comment]
Thanks for looking into this.
I guess the issue can be closed.
