### ISSUE TITLE
Buffer from_iter method is inconsistent across buffer implementations

### ISSUE THREAD

**Issue by maplant** [vulkano-rs/vulkano#1001]
CpuAccessibleBuffer defines its from_iter method with the following signature:
```rust 
pub fn from_iter<I>(
    device: Arc<Device>, 
    usage: BufferUsage, 
    data: I
) -> Result<Arc<CpuAccessibleBuffer<[T]>>, DeviceMemoryAllocError> 
```
However, ImmutableBuffer defines it with a slightly different ordering:
```rust
pub fn from_iter<D>(
    data: D, 
    usage: BufferUsage, 
    queue: Arc<Queue>
) -> Result<(Arc<ImmutableBuffer<[T]>>, CommandBufferExecFuture<NowFuture, AutoCommandBuffer>), DeviceMemoryAllocError> 
```
The issue here is that data is the last parameter in CpuAccessibleBuffer's method, while in ImmutableBuffer's method it is the first. This ordering is inconsistent and would benefit from a change.

**Comment by Rua** [comment]
This is solved by #2127.
