### ISSUE TITLE
Allow drawing a subset of a buffer

### ISSUE THREAD

**Issue by Rua** [vulkano-rs/vulkano#1004]
The raw Vulkan draw commands, such as `vkCmdDraw`, have parameters to specify which vertex to start drawing at, and how many to draw. These parameters are exposed by `SyncCommandBufferBuilder`, and the implementation of `AutoCommandBufferBuilder` provides these values based on the size of the buffer. But there is no way to specify these directly in `AutoCommandBufferBuilder` other than by using indirect drawing. This makes it impossible to draw only a subset of a buffer, which is useful when a single buffer contains data for many different objects. Can this feature be exposed somehow?

**Comment by Limeth** [comment]
Hello, have you tried using a `BufferSlice` as the vertex buffer argument when calling `AutoCommandBufferBuilder::draw`? With the `BufferSlice::slice` function, you can specify the offset and range of the vertex data you want to pass to the draw call.

**Comment by rukai** [comment]
Same as https://github.com/vulkano-rs/vulkano/issues/1054, a valid solution has been provided. I'll make a PR to document this on the draw_* methods
