### ISSUE TITLE
build_vk_surface not in scope even after importing VkSurfaceBuild when using vulkano_win crate 0.9.0 

### ISSUE THREAD

**Issue by GoWind** [vulkano-rs/vulkano#1011]
Hi, 
I am trying to use vulkano for a project and tried using the vulkano libraries using crates.io. I am using version 0.9.0 and I tried to implement the Triangle example provided in the `examples` folder. 

I have the `VkSurfaceBuild` trait imported as per the documentation to call `build_vk_surface` on a `WindowBuilder` but I am still running into a `no method named `build_vk_surface` found for type `winit::WindowBuilder` in the current scope` from the compiler when I use `vulkano_win = 0.9.0` in my `Cargo.toml` file, but it works fine when I create a virtual workspace using `vulkano_win = { path = '../vulkano_win' }` as specified in the examples folder. Is there a mismatch between the version published to crates.io and HEAD ? 

This is my `Cargo.toml`
```
➜  testv2 git:(master) ✗ cat Cargo.toml
[package]
name = "testv2"
version = "0.1.0"
authors = ["govindarajan <petrovgovind@gmail.com>"]

[dependencies]
vulkano = "0.9.0"
vulkano-shader-derive = "0.9.0"
vulkano-win = "0.9.0"
winit = "0.16.0"
```
I have imported the `VkSurfaceBuild` in my main.rs
````
   39 use vulkano_win::VkSurfaceBuild;
   40 use vulkano::instance::Instance;
````
cargo build throws the following error
```
error[E0599]: no method named `build_vk_surface` found for type `winit::WindowBuilder` in the current scope
  --> src/main.rs:89:26
   |
89 |     let surface = window.build_vk_surface(&events_loop, instance.clone()).unwrap();
   |                          ^^^^^^^^^^^^^^^^
```

**Comment by rukai** [comment]
yes, they are out of sync. I'll make a PR to release a new version tomorrow as there hasn't been one in ages. (Then we need to wait for tomaka to merge it)
Its not abnormal for crates to be out of sync between crates.io and github. In such cases you can specify the git repository in your Cargo.toml .e.g `vulkano = { git = "https://github.com/rukai/vulkano" }` If you do this all vulkano crates need to be sourced from git.

**Comment by GoWind** [comment]
The latest commit `https://github.com/vulkano-rs/vulkano#ef8bbecc` just broke my builds and  I have started seeing the 
```
no method named `build_vk_surface` found for type `winit::WindowBuilder` in the current scope
  --> src/main.rs:34:45
   |
34 |   let surface = winit::WindowBuilder::new().build_vk_surface(&events_loop, instance.clone()).unwrap();
   |                                             ^^^^^^^^^^^^^^^^
```
errors again.
