### ISSUE TITLE
Forcing robust_buffer_access causes errors in MoltenVK when using validation layers

### ISSUE THREAD

**Issue by JohnColanduoni** [vulkano-rs/vulkano#1018]
When using MoltenVK via the standard loader with validation layers enabled, the following error is produced: 

```
[ UNASSIGNED-CoreValidation-DevLimit-InvalidFeatureRequested ] Object: VK_NULL_HANDLE (Type = 2) | While calling vkCreateDevice(), requesting feature 'robustBufferAccess' in VkPhysicalDeviceFeatures struct, which is not available on this device.
```

It appears that vulkano forces `robustBufferAccess` to be enabled (in https://github.com/vulkano-rs/vulkano/blob/6b8938fe26d3f82881d85f6a2f0f5b45e0165773/vulkano/src/device.rs#L312). MoltenVK is definitely non-compliant here, but it would be nice to be able to create a device without this feature (possibly behind an unsafe method) even for compliant implementations to avoid any associated performance penalty.

**Comment by Rua** [comment]
The feature is no longer enabled by default.
