### ISSUE TITLE
Can’t modify buffer that’s owned by a descriptor set

### ISSUE THREAD

**Issue by 64** [vulkano-rs/vulkano#1029]
Passing a buffer into a descriptor set moves it, so there is no way to alter that buffer after the set has been created. I believe that this is totally possible and common in raw vulkan, and not having this ability means that descriptor sets need to be created every time a uniform needs updating (which is very likely before each draw call).

**Comment by jonathansty** [comment]
@64  Is it not possible to clone the Arc<T> that is returned when making the buffer so that you can still access the buffer? 

The examples of vulkano-www do this:
```
    // Descriptor sets
    let set = Arc::new(PersistentDescriptorSet::start(compute_pipeline.clone(), 0)
        .add_buffer(data_buffer.clone()).unwrap()
        .build().unwrap()
);
```
Although I'm not a 100% sure.

**Comment by knappador** [comment]
@64 is this issue still alive?  Do you have a better example of a remaining issue?

**Comment by 64** [comment]
No clue @knappador. I remember trying the Arc thing and it didn’t work, but I may have just done it incorrectly and didn’t bother to investigate it as I was frustrated.

**Comment by knappador** [comment]
@64  I believe the proposed solution of cloning the Arc was what you were after.  Motion to close.

**Comment by 64** [comment]
If you say so.
