### ISSUE TITLE
Can't compile dependencies (crossbeam-utils)

### ISSUE THREAD

**Issue by torresguilherme** [vulkano-rs/vulkano#1035]
As the title says. here's the compiler output:

`
  Compiling crossbeam-utils v0.5.0
   Compiling owning_ref v0.3.3
error: the struct `#[repr(align(u16))]` attribute is experimental (see issue #33626)
  --> /home/guilherme/.cargo/registry/src/github.com-1ecc6299db9ec823/crossbeam-utils-0.5.0/src/cache_padded.rs:20:1
   |
20 | / pub struct CachePadded<T> {
21 | |     inner: T,
22 | | }
   | |_^

error: non-string literals in attributes, or string literals in top-level positions, are experimental (see issue #34981)
  --> /home/guilherme/.cargo/registry/src/github.com-1ecc6299db9ec823/crossbeam-utils-0.5.0/src/cache_padded.rs:19:1
   |
19 | #[repr(align(64))]
   | ^^^^^^^^^^^^^^^^^^

error: aborting due to 2 previous errors

error: Could not compile `crossbeam-utils`.
warning: build failed, waiting for other jobs to finish...
error: build failed
`
I'm using rustc version 1.28 and cargo version 0.22 (latest Debian testing releases)

**Comment by HadrienG2** [comment]
Hmmm... that error message really looks like something from an older release of rustc, before repr(align) stabilization (1.25). Are you sure that the rustc 1.28 installation is being used here, and not another rustc installation on your system?

**Comment by rukai** [comment]
Unless you can build [crossbeam-utils](https://github.com/crossbeam-rs/crossbeam-utils) by itself fine, this is going to ultimately come down to something on your setup. (maybe cargo is calling a different rustc to the one in your path? also cargo 0.22 is really old https://github.com/rust-lang/cargo/releases)
If you cant resolve it yourself you should try asking in a rust irc channel or discord or maybe a debian irc channel.
