### ISSUE TITLE
'unexpected error: ValidationFailed' when calling acquire_next_image

### ISSUE THREAD

**Issue by Friz64** [vulkano-rs/vulkano#1041]
I'm getting a `unexpected error: ValidationFailed` panic when calling `swapchain::acquire_next_image(self.swap_chain.clone(), None)`. I haven't found anything significant on this error on the internet, can someone explain what it means? I have already tried messing with the swapchain, but to no avail. This only happens on my project, the examples work fine.

```
   9: vulkano::swapchain::swapchain::{{impl}}::from
             at \<panic macros>:8
  10: vulkano::swapchain::swapchain::acquire_next_image_raw<winit::Window>
             at C:\Users\Friz64\.cargo\registry\src\github.com-1ecc6299db9ec823\vulkano-0.10.0\src\swapchain\swapchain.rs:1175
  11: vulkano::swapchain::swapchain::acquire_next_image<winit::Window>
             at C:\Users\Friz64\.cargo\registry\src\github.com-1ecc6299db9ec823\vulkano-0.10.0\src\swapchain\swapchain.rs:84
  12: ecsvulk::graphics::renderer::Renderer::draw
             at .\src\graphics\renderer.rs:652
```

**Comment by rukai** [comment]
Can you please provide more details? I'm guessing this is for your project https://github.com/Friz64/ecsvulk ? If you push your changes (to a seperate branch if you want) then I can take a look.

**Comment by Friz64** [comment]
Thank you for your answer!
That is indeed the right project and i have now published the changes although this issue was initially created to understand the error message.

**Comment by rukai** [comment]
Ok, I played around with your code a bit, found two issues, there could be more.

1.  you tried to create too many queues for a given family. I would just do what the triangle example does here.
2   You arent doing anything with acquire_future. You need to join this with other futures to ensure your previous tasks have completed. again the triangle example demonstrates this.

In general  you would be able to determine such things by comparing your code to the triangle example and also by resolving warnings.

**Comment by Friz64** [comment]
Thank you for your time, my issue is now fully resolved and it works!
