### ISSUE TITLE
Instanced rendering support

### ISSUE THREAD

**Issue by jonathansty** [vulkano-rs/vulkano#1044]
I've been doing some digging but can't find a way to do instanced rendering using vulkano. 

Is this already supported? How would be the expected way of implemented instanced rendering? 

From having a quick look at the C++ samples provided by Sascha Willems it looks like he explictely defines which locations to bind to. 

Any help would be greatly appreciated.

**Comment by jonathansty** [comment]
Alright, I got it working using a `OneVertexOneInstanceDefinition` struct as the `vertex_input`. This struct contains a TODO and a comment saying it's unstable and it's "a bad way to do things".

What are the plans for these features?

**Comment by rukai** [comment]
I believe they should be replaced by something more generic. However there is no one working on it so don't expect to see it any time soon.

**Comment by JohnDoneth** [comment]
Correct. The buffer definition section could greatly benefit from varadic generics but Rust does not yet support that feature.

I have tried to work on it myself but unless that section is refactored or varadics come out it will be dificult to do so.

**Comment by yanlipnican** [comment]
How about to solve buffer definition with macro?

**Comment by Rua** [comment]
`OneVertexOneInstanceDefinition` is now gone, and you can specify the number of instances directly with `draw`.
