### ISSUE TITLE
`ImageLayout` is not changed for mipmaps before the `blit_image` command

### ISSUE THREAD

**Issue by Limeth** [vulkano-rs/vulkano#1045]
As seen in [this example](https://github.com/SaschaWillems/Vulkan/blob/master/examples/texturemipmapgen/texturemipmapgen.cpp#L270-L299), when creating image mipmaps, it is required that the mipmap that is currently being written to has an initial (SRC) layout of ~~`VK_IMAGE_LAYOUT_UNDEFINED`~~ `VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL`. Note that this requirement only affects the single mipmap subresource of the image. AFAIK, this functionality is currently missing in the safe API of Vulkano, as the implementation of `AutoCommandBufferBuilder::blit_image` does not handle the layout of image subresources.

Trying to implement the equivalent of what is shown in the example mentioned above yields the following output from the debug layers:
```
VUID-VkImageMemoryBarrier-oldLayout-01197(ERROR / SPEC): msgNum: 167774554 - For image 0x34 you cannot transition the layout of aspect=1 level=0 layer=0 from VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL when current layout is VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL. The spec valid usage text states 'oldLayout must be VK_IMAGE_LAYOUT_UNDEFINED or the current layout of the image subresources affected by the barrier' (https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VUID-VkImageMemoryBarrier-oldLayout-01197)
    Objects: 1
       [0] 0x7efebb416308, type: 6, name: (null)
Validation(ERROR): msg_code: 167774554:  [ VUID-VkImageMemoryBarrier-oldLayout-01197 ] Object: 0x7efebb416308 (Type = 6) | For image 0x34 you cannot transition the layout of aspect=1 level=0 layer=0 from VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL when current layout is VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL. The spec valid usage text states 'oldLayout must be VK_IMAGE_LAYOUT_UNDEFINED or the current layout of the image subresources affected by the barrier' (https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VUID-VkImageMemoryBarrier-oldLayout-01197)
```

Any suggestions as to how this would be implemented using the `SyncCommandBufferBuilder` or `UnsafeCommandBufferBuilder` would be appreciated.

**Comment by SiebenCorgie** [comment]
Hi, I had a similar problem. The only way to make it run returns a buggy image, see her: https://github.com/vulkano-rs/vulkano/issues/989

**Comment by Limeth** [comment]
Thanks for the response. Looks like my issue is a duplicate, then. I will continue to follow the conversation in your issue.
