### ISSUE TITLE
Debug markers using AutoCommandBufferBuilder

### ISSUE THREAD

**Issue by jonathansty** [vulkano-rs/vulkano#1051]
Hi, 

I want to add some custom debug markers in my command buffer to make it easier and more organised. I've found that AutoCommandBufferBuilder does not allow me to do this. Is this intentional or just not been added yet, seeing as the UnsafeCommandBufferBuilder does expose a way to set these. 

Just looking for some info about this as it's not very well documented, (I think).

Thanks!

**Comment by Rua** [comment]
This is implemented now.
