### ISSUE TITLE
Writing to a range of a buffer while drawing another range causes an AccessError

### ISSUE THREAD

**Issue by ghost** [vulkano-rs/vulkano#1070]
Hi there,

I think I'm hitting a limitation with how the GPU lock is implemented in Vulkano. I'm trying to write to a buffer range (let's say 0..36), while another command buffer is drawing another range (say 36..72) of the same buffer. Since the ranges do not overlap, this should be safe, but executing the command buffer fails with an `AccessError`, telling me that the buffer is already in use.

From glancing at the code, it looks like `BufferSlice` locks the entire buffer in `try_gpu_lock` instead of only locking a range of the buffer. Indeed, if I comment out the function for debugging purposes, my code seems to work as expected.

Obviously, I can work around this by waiting for the write to complete before drawing the buffer, but that's not ideal.

My first thought was that this is a bug in Vulkano, but perhaps I'm supposed to do this some other way? Or maybe some of my assumptions are incorrect, and it's a bug in my code instead?

**Comment by Rua** [comment]
This should now be fixed, as GPU locks use ranges now.
