### ISSUE TITLE
Deferred example issue (linux, nvidia)

### ISSUE THREAD

**Issue by skemps** [vulkano-rs/vulkano#1073]
Hi!

The example starts fine but after drawing first frame winit event triggers recreate swapchain which in the next frames fail with SwapchainCreationError::UnsupportedDimensions and than it loops forever since it never successfully recreates swapchain.
I am not actually resizing or moving window.

Any ideas?

**Comment by aleksijuvani** [comment]
This example doesn't work properly for me on Windows either. I'm not sure what's supposed to happen, but it just seems to freeze indefinitely. I also have an Nvidia GPU.

**Comment by rukai** [comment]
I ran the example on linux + nvidia using vulkano 0.10 and the latest git master.
It runs fine for me.

Can you print out the dimensions it is attempting to use and let me know?
Your window manager might be giving it invalid dimensions.
Which window manager are you using?
I have had an issue on windows before where it was attempting to use dimensions of (0, 0)

If this is the case, the solution here is probably to just remove the line
`winit::Event::WindowEvent { event: winit::WindowEvent::Resized (_), .. } => recreate_swapchain = true,`
Try that and let me know how it goes.

**Comment by skemps** [comment]
Here it just seems that it runs fine because I can see the triangle. But actually it's not. For example CloseRequested doesn't trigger because of constant UnsupportedDimension loop.

Dimensions are [1195, 896]. This is probably 1024x768 + decoration.

If I remove the handling of the resized event than it works, but crashes if I actually resize the window (Result::unwrap()` on an `Err` value: OutOfDate on `let after_frame = after_future.unwrap()...`)

**Comment by rukai** [comment]
Oh huh, the deferred example doesnt handle the swapchain being out of date like the other examples do.
I'll fix that.

**Comment by rukai** [comment]
Can you give this PR a go? https://github.com/vulkano-rs/vulkano/pull/1074

**Comment by rukai** [comment]
Thanks!

**Comment by rukai** [comment]
@skemps what window manager are you using? X11 or wayland?
Looks like someone else has run into an issue where something similar to the old implemenation is required and I want to be able to reproduce this issue so i don't introduce a regression.

**Comment by skemps** [comment]
I'm using X11.

**Comment by rukai** [comment]
What window manager?

**Comment by skemps** [comment]
I think it's kwin. I'm not sure. I'm not at my computer right now. It's the default debian stretch with kde I'm using.

**Comment by rukai** [comment]
@skemps I sadly cant reproduce it on my machine using vulkano commits before the fix. Can you verify that I havent created a regression by testing the triangle example on this branch https://github.com/rukai/vulkano/tree/fix_wayland_resize

**Comment by skemps** [comment]
I tested triangle example from your branch and it works ok.
