### ISSUE TITLE
Panic `Wrong value for vk::PresentModeKHR` on Android

### ISSUE THREAD

**Issue by LachlanHogan** [vulkano-rs/vulkano#1078]
I am able to compile and run the teapot example in the `examples` directory using 
`cargo apk run --bin teapot`

The program panics when attempting to check the surface capabilities here: 
`let caps = surface.capabilities(physical).expect("failed to get surface capabilities");` 
with the panic error 
`thread 'main' panicked at 'Wrong value for vk::PresentModeKHR'`.

I have tried enabling the `khr_android_surface` instance extension with no extra luck

Do I perhaps need to create the surface from the native Android surface?

Any help would be appreciated, thanks!

**Comment by rukai** [comment]
It looks like some present modes arent implemented yet, should be fairly easy to fix. Just need to handle all of the possible VkPresentModeKHR in capabilities.rs

**Comment by LachlanHogan** [comment]
> It looks like some present modes arent implemented yet, should be fairly easy to fix. Just need to handle all of the possible VkPresentModeKHR in capabilities.rs

I thought `PresentMode::Fifo` was required to be supported by every platform? As it mentions in the LunarG docs 

>  VK_PRESENT_MODE_FIFO_KHR: ... This is the only value of presentMode that is required to be supported.

Source: https://vulkan.lunarg.com/doc/view/1.0.26.0/linux/vkspec.chunked/ch29s05.html

**Comment by rukai** [comment]
It's not that `PresentMode::Fifo` is not supported.
The issue is that Vulkano is panicking if vulkan even mentions it supports a present mode that vulkano doesn't know about. https://github.com/vulkano-rs/vulkano/blob/master/vulkano/src/swapchain/capabilities.rs#L106

Can you please test this PR https://github.com/vulkano-rs/vulkano/pull/1079 ? Thanks.

**Comment by LachlanHogan** [comment]
@rukai Tested the changes on your branch and the app now successfully runs! Thanks!

**Comment by rukai** [comment]
Thanks!
