### ISSUE TITLE
New vulkano_shader! macro -> how to make resulting mod pub?

### ISSUE THREAD

**Issue by Unmoving** [vulkano-rs/vulkano#1090]
Hello!

The question is basically in the title and I am sorry if this is more of a rust question (I am not sure).

I migrated all my old `#[derive(VulkanoShader)]`s to `vulkano_shader!`, one problem I have is that I used to define them like so:

```
pub mod vs {
    #[derive(VulkanoShader)]
    #[ty = "vertex"]
    #[path = "path_to_vertex_shader"]
    struct Dummy;
}
```

which became

```
vulkano_shader!{
    mod_name: vs,
    ty: "vertex",
    path: "path_to_vertex_shader"
}
```

the problem now is, that throughout my application I get import errors, because the created `vs` `mod` is not `pub` anymore.

I tried with `mod_name: pub vs` and `pub mod_name: vs` and even `pub vulkano_shader!{` but all just results in compile errors.

So I am wondering: What's the right way to handle this? (Apart from completely refactoring my whole application)

**Comment by rukai** [comment]
While I could just add a `pub` flag to the `vulkano_shader!` macro, it would start to get messy and harder to understand.

I'm thinking I'll change it back to not create the module for you that way you can easily make it pub or not pub yourself.
The initial intent was to make it harder to get wrong by forcing people to put it in a `mod`, but the worst that could happen if they don't put in a `mod`, is a compile error for duplicate definitions.

**Comment by rukai** [comment]
Working on a PR now

**Comment by Unmoving** [comment]
Thanks @rukai,

I was just wondering, as you're blocked with the right approach, could we just add another attribute to the macro, like "visibility" and allow "pub" as one value? Or even a boolean-flag is fine to me.

I understand that's not the way you want to go with this for the final solution and that's totally fine by me ofc, but I wonder what we can do as an intermediate step.

**Comment by rukai** [comment]
Yeah definitely, I'll just remove the reexport from the `vulkano` main crate.
As otherwise we would be waiting for rust 0.31 >.>
