### ISSUE TITLE
Reexport `shader!` from vulkano

### ISSUE THREAD

**Issue by rukai** [vulkano-rs/vulkano#1095]
Reexport `shader!` from vulkano
Change all the documentation such that this is the correct way to access the macro.

This will have to wait till rust 1.31 because of https://github.com/rust-lang/cargo/issues/6224
I cant really make more progress because I'm not sure how the docs are even supposed to be handled here because I cant play around with it.

**Comment by Rua** [comment]
I don't think this is possible. Vulkano-shaders depends on vulkano, and if vulkano then depended on vulkano-shaders, you'd get a circular dependency.
