### ISSUE TITLE
vk-sys: Why are there no DebugUtils functions?

### ISSUE THREAD

**Issue by rokit** [vulkano-rs/vulkano#1098]
I'm following this guide to setup validation layers to get warnings and errors:
https://vulkan-tutorial.com/Drawing_a_triangle/Setup/Validation_layers

I actually have already set up a function that looks like this:
```
pub extern "system" fn callback(
    _flags: vk::DebugReportFlagsEXT,
    _object_type: vk::DebugReportObjectTypeEXT,
    _object: u64,
    _location: usize,
    _message_code: i32,
    _p_layer_prefix: *const c_char,
    p_message: *const c_char,
    _p_user_data: *mut c_void,
) -> u32
```
It works fine, but I'm not getting all the error reporting I want with this function. Vulkan still seems like a black box. There is another function in the tutorial that has different parameters:

```
static VKAPI_ATTR VkBool32 VKAPI_CALL debugCallback(
    VkDebugUtilsMessageSeverityFlagBitsEXT messageSeverity,
    VkDebugUtilsMessageTypeFlagsEXT messageType,
    const VkDebugUtilsMessengerCallbackDataEXT* pCallbackData,
    void* pUserData)
```

But it requires `DebugUtils` stuff that vk-sys doesn't seem to have. Am I just missing something?

**Comment by rukai** [comment]
It will be added in this PR: https://github.com/vulkano-rs/vulkano/pull/1066
