### ISSUE TITLE
Question: Streaming raw data to surface

### ISSUE THREAD

**Issue by Timmmm** [vulkano-rs/vulkano#1102]
Hi, this is just a vulkan(o) question, not actually a bug (although I do have a bug too if segfaults with safe code count) - hope that is ok!

Suppose I am writing something like a video player or a VLC client and I have raw image data on the host and want to display it in a `winit` window as quickly as possible - what is the best way to do that?

I would assume:

1. Using Vulkano should be the fastest method.
2. I should use a `CpuBufferPool` and each frame call [`next()`](https://docs.rs/vulkano/0.10.0/vulkano/buffer/cpu_pool/struct.CpuBufferPool.html?search=#method.next) on it with my frame's data.
3. Then I should execute a copy from that buffer to an Image buffer.
4. Then I render the Image as a texture on a single quad.

My questions are:

1. In the `CpuBufferPool` example there's this code:

```
        // For the sake of the example we just call `update_buffer` on the buffer, even though
        // it is pointless to do that.
        .update_buffer(sub_buffer.clone(), [0.2, 0.3, 0.4, 0.5])
```

Why is it pointless to do that exactly? Also [the documentation for `vkCmdUpdateBuffer()`](https://vulkan.lunarg.com/doc/view/1.0.33.0/linux/vkspec.chunked/ch17s05.html) says it can only be used with small buffers - does that limitation apply to `next()` too?

2. How exactly does the data get from the host to device memory by calling `next()`? Shouldn't I have to execute some kind of transfer in a command queue?

3. If I already have the fully rendered image data in a buffer, do I still have to use the full rendering pipeline to get it on the screen, or is there some way to copy a buffer directly to a framebuffer?

**Comment by rukai** [comment]
For the segfaulting we will need a minimal `main.rs` demonstration of the issue, so we can reproduce it. 
1. I think it says its pointless because its a contrived example.
2. I asssume it copies to vram as soon as the image or buffer is created, you can read the source code to see what vulkan calls it makes - I cant atm because i'm about to get off this train
3. From a quick search it looks like you copy directly to the swapchain with vulkan, not sure if vulkano supports this.

**Comment by Timmmm** [comment]
> I asssume it copies to vram as soon as the image or buffer is created, you can read the source code to see what vulkan calls vulkano makes

As far as I can tell it doesn't make *any* vulkan calls. Very confusing. Is `CpuBufferPool` on the host or the device? Could do with clarifying how this is supposed to work in the documentation, or an example (or both!).

> From a quick search it looks like you copy directly to the swapchain with vulkan, not sure if vulkano supports this.

Ah yeah it does seem like this is possible, something like this:

    let buffer = CpuBufferPool::upload(device.clone());
    let data: [u8; 4] = [5, 10, 100, 255];
    let sub_buffer = buffer.next(data).unwrap();

		let cb = vulkano::command_buffer::AutoCommandBufferBuilder::primary(device.clone(), queue.family()).unwrap()
			.copy_buffer_to_image(sub_buffer, images[image_num]).unwrap()
			.build().unwrap();

However no matter what I do I can't get this to compile because of type errors calling `.copy_buffer_to_image()`. It seems the issue is with `Content = [Px]` here:

    pub fn copy_buffer_to_image<S, D, Px>(self, source: S, destination: D)
                                          -> Result<Self, CopyBufferImageError>
        where S: TypedBufferAccess<Content = [Px]> + Send + Sync + 'static,
              D: ImageAccess + Send + Sync + 'static,
              Format: AcceptsPixels<Px>

No matter what I feed to `buffer.next()` I always get `Content = [u8; 4]` or `Content = &[u8]`, neither of which are apparently acceptable. Is it even possible to have a type `[u8]`? I though you can't do that in Rust? I can't find any examples for this function either.

**Comment by newpavlov** [comment]
Take a look at my [cam-vis](https://github.com/SkoltechRobotics/cam-vis) app. It displays video from v4l2 camera device,buttt currently code is not the most efficient, as it copies data from buffer to a texture at each frame, even if texture data is left unchanged.

**Comment by Timmmm** [comment]
Thanks - that looks helpful! Looks like maybe the difference is that you are using `CpuBufferPool::chunk()` and I am using `CpuBufferPool::next()`. The documentation for those methods is literally identical though (surely a bug?) so I'm not sure what the difference is.

**Comment by newpavlov** [comment]
Take a look at methods signature, the difference is that `next` gives you access to one element (i.e. `T`), while `chunk` to a number of elements (i.e. `impl IntoIterator<Item = T>`). Though documentation can be indeed improved.

**Comment by Timmmm** [comment]
Makes sense, thanks!
