### ISSUE TITLE
vulkano triangle example consumes 100% cpu

### ISSUE THREAD

**Issue by GopherJ** [vulkano-rs/vulkano#1103]
Hello, I noticed that when I run the triangle example, it consumes 100%.

PC    :  `Alienware R13OLED`
RUST:  `rustc 1.32.0-nightly (e6c5cf923 2018-11-04)`
PLATFORM: `Ubuntu18.10`
GRAPHICS CARD: `Nvidia GTX1060`

**Comment by rukai** [comment]
This is the same issue as https://github.com/vulkano-rs/vulkano/issues/923
I think the best workaround atm is to add `future.wait(None).unwrap` like this https://github.com/rukai/incipisphere_renderer/blob/d8c06451e8dc1c4b63ea4c7fdf682270d16f4cbd/src/render.rs#L309

I've actually figured out whats going wrong here.
It was previously thought that vulkan should synchonize to the refresh rate when fifo is enabled. However he vulkan spec expliclity says it doesnt. The proper fix here is wait for the previous frame to display before requesting the next frame to display. Will take some fiddling to figure out how to actually implement this though.

Whereas the workaround I  mentioned halts all processing until the frame is displayed. This is ineffecient.
