### ISSUE TITLE
Version 0.10 fails to build after cargo upgrade

### ISSUE THREAD

**Issue by MichaelMauderer** [vulkano-rs/vulkano#1113]
I have a previously working application that uses vulkano version 0.10 and vulkano-shader-derive version 0.10. After a recent `cargo update` vulkano fails to build with 

```
error[E0422]: cannot find struct, variant or union type `MirSurfaceCreateInfoKHR` in module `vk`
   --> C:\Users\Michael\.cargo\registry\src\github.com-1ecc6299db9ec823\vulkano-0.10.0\src\swapchain\surface.rs:314:29
    |
314 |             let infos = vk::MirSurfaceCreateInfoKHR {
    |                             ^^^^^^^^^^^^^^^^^^^^^^^ did you mean `XcbSurfaceCreateInfoKHR`?

error[E0425]: cannot find value `STRUCTURE_TYPE_MIR_SURFACE_CREATE_INFO_KHR` in module `vk`
   --> C:\Users\Michael\.cargo\registry\src\github.com-1ecc6299db9ec823\vulkano-0.10.0\src\swapchain\surface.rs:315:28
    |
315 |                 sType: vk::STRUCTURE_TYPE_MIR_SURFACE_CREATE_INFO_KHR,
    |                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ did you mean `STRUCTURE_TYPE_XCB_SURFACE_CREATE_INFO_KHR`?

    Building [====================================================>  ] 123/127: vulkano
```
Might be related to issue #1108 .

**Comment by rukai** [comment]
Oh oops, I published a breaking change to vk-sys as a minor change. Maybe I should have a separate changelog for vk-sys so this doesnt happen again.

**Comment by rukai** [comment]
I cant yank vk-sys `0.3.4` because I don't have access. @tomaka 
In the meantime you can manually set to `0.3.3`in your Cargo.lock

**Comment by tomaka** [comment]
> I cant yank vk-sys 0.3.4 because I don't have access. @tomaka

Done!

**Comment by rukai** [comment]
@tomaka 
Oh no, this broke 0.11
When https://github.com/vulkano-rs/vulkano/pull/1115 is merged  can you you yank `0.11.0`?

**Comment by newpavlov** [comment]
@tomaka 
I think you forgot to yank `v0.11.0`.

**Comment by rukai** [comment]
@tomaka 0.11.0 still needs to be yanked

**Comment by tomaka** [comment]
@rukai Done!
