### ISSUE TITLE
Vulkano-shaders & vulkano-win reverted back to 0.10.0 on crates.io

### ISSUE THREAD

**Issue by TurboCartPig** [vulkano-rs/vulkano#1119]
Version 0.11.0 of vulkano-shaders and vulkano-win just disappeared from crates.io. I assume this was not intended.

**Comment by rukai** [comment]
Yeah, despite asking asking for just vulkano to be yanked, vulkano-shaders and vulkano-win were also yanked. Its going to be easier for me to just release 0.11.1 of vulknao-shaders and vulkano-win. https://github.com/vulkano-rs/vulkano/pull/1120
