### ISSUE TITLE
Swapchain panics with UnsupportedDimensions given min_image_extent

### ISSUE THREAD

**Issue by TurboCartPig** [vulkano-rs/vulkano#1141]
# Info
*   Version of vulkano: 0.11.1
*   OS: Windows 10
*   GPU (the selected PhysicalDevice): GTX 1080
*   GPU Driver: Nvidia v/ 417.22

# Issue
```
let caps = surface.capabilities()?;
swapchain.recreate_with_dimensions(caps.min_image_extent)?;
```
The above code panics with UnsupportedDimensions. min_image_extent is [0, 0]. I'm not sure if caps reports the wrong min_image_extent or what is wrong but this seems like a bug to me. Though I am unable to test it on another computer or gpu.

**Comment by mitchmindtree** [comment]
@TurboCartPig My impression is that the swapchain dimensions have to match their surface and that the min and max extent just describe what the bounds are (I could be totally wrong on this). Is it possible for you to resize the surface (or associated window) to `min_image_extent` and then then recreate the swapchain using `caps.current_extent`?

Or maybe you mean to be using `caps.current_extent` anyway?

**Comment by rukai** [comment]
On some platforms the swapchain can be any size i.e. caps.min_image_extent would work.
However that is certainly not cross platform, as some platforms (those that specify a currentExtent) need the swapchain size to equal currentExtent which will always be the window size anyway, so just set the swapchain to the window size everytime and it will be fine.

Please refer to the triangle example for window recreation https://github.com/vulkano-rs/vulkano/blob/1d83993e844e84792737f6e0c2a3819e3912e844/examples/src/bin/triangle.rs#L333
and also this comment for initial window creation is very useful https://github.com/vulkano-rs/vulkano/blob/1d83993e844e84792737f6e0c2a3819e3912e844/examples/src/bin/triangle.rs#L146

**Comment by TurboCartPig** [comment]
My code looks something like this at the moment
```
let dimensions = {
            let caps = self
                .surface
                .capabilities(self.device.physical_device())?;

            let current_extent = caps.current_extent.unwrap_or(caps.min_image_extent);

            if current_extent < caps.min_image_extent {
                caps.min_image_extent
            } else if current_extent > caps.max_image_extent {
                caps.max_image_extent
            } else {
                current_extent
            }
        };

        let (new_swapchain, new_images) = self.swapchain.recreate_with_dimension(dimensions)?;
```
So my swapchain dimensions should match the surface dimensions. The problem is that when I minimize the window, the current extent becomes [0, 0], same as min_image_extent, Causing a panic.

So should I pass some arbitrary minimum dimensions. That works as far as I have tested. But how would I know that those dimensions will be supported. I thought that was min_image_extent was for.

**Comment by rukai** [comment]
My solution is to stop rendering when the window is minimized. i.e. when we get a dimension of (0, 0)

**Comment by TurboCartPig** [comment]
That seems reasonable. I will close the issue then as this does not seem to have anything to do with vulkano.
