### ISSUE TITLE
moltenvk 1.1.92 causes empty screen and validation errors

### ISSUE THREAD

**Issue by m4b** [vulkano-rs/vulkano#1146]
# Template

*   Version of vulkano: 0.11
*   OS: macOS
*   GPU (the selected PhysicalDevice):  Intel Iris Graphics (type: IntegratedGpu)
*   GPU Driver: moltenVK 1.1.92.1

# Issue

Running teapot or triangle on macOS has a "blue screen of death", e.g., nothing is rendered except screen with blue background. On my own project I know that events are received, etc., but the vulcan backend rendering does nothing, likely because validation errors are causing UB somewhere?

When run with validation layers, we see:
```
    Objects: 1
       [0] 0x8, type: 8, name: (null)
Validation(ERROR): msg_code: 0:  [ VUID-VkMappedMemoryRange-size-01390 ] Object: 0x8 (Type = 8) | vkInvalidateMappedMemoryRanges: Size in pMemRanges[0] is 0x18, which is not a multiple of VkPhysicalDeviceLimits::nonCoherentAtomSize (0x100). The Vulkan spec states: If size is not equal to VK_WHOLE_SIZE, size must either be a multiple of VkPhysicalDeviceLimits::nonCoherentAtomSize, or offset plus size must equal the size of memory. (https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VUID-VkMappedMemoryRange-size-01390)
VUID-VkMappedMemoryRange-size-01390(ERROR / SPEC): msgNum: 0 - vkFlushMappedMemoryRanges: Size in pMemRanges[0] is 0x18, which is not a multiple of VkPhysicalDeviceLimits::nonCoherentAtomSize (0x100). The Vulkan spec states: If size is not equal to VK_WHOLE_SIZE, size must either be a multiple of VkPhysicalDeviceLimits::nonCoherentAtomSize, or offset plus size must equal the size of memory. (https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VUID-VkMappedMemoryRange-size-01390)
```

**NOTE**: switching back to at least 1.1.85.0 has no validation errors and there are no problems; so this could be a moltenVK issue? Not sure.

Running the same project on linux with validation layers does not have these warnings, so I'm more inclined to think this could be a moltenVK issue?

**Comment by seivan** [comment]
Getting the same for the triangle. 

```
Revisions used to build this SDK on Tue Nov 27 20:20:53 UTC 2018
114c3546e195819bd53a34b39f5194b2989a5b12 : https://github.com/KhronosGroup/Vulkan-Headers.git
4cd7e44fc1ca6c4d8361720b43a3588ddf9fc4b6 : https://github.com/KhronosGroup/Vulkan-Loader.git
6e6da6ccab8931f7c30815966ef839b1155e5bec : https://github.com/KhronosGroup/Vulkan-ValidationLayers.git
9bbdd552f0fd62741aa1f1e02ab3eafc45cf3c1e : https://github.com/KhronosGroup/Vulkan-Tools.git
2c3ba0a4ff3b64f53849f57e96332e3a45d73e71 : https://github.com/KhronosGroup/MoltenVK.git
1bc601c674aecc2fee0dee8ff7a118db76b4c439 : https://github.com/KhronosGroup/glslang.git
a29a9947ac96d811b310f481b24e293f67fedf32 : https://github.com/KhronosGroup/SPIRV-Tools
a2c529b5dda18838ab4b52f816acfebd774eaab3 : https://github.com/KhronosGroup/SPIRV-Headers
1adaaba74e73aa3d590e4367720f089455c07cc5 : https://github.com/KhronosGroup/SPIRV-Cross.git
ed101c227f8bc3ff54fa395574042c466a52f916 : https://github.com/google/shaderc.git
c24b84795f6c083df107d8639286881a23894679 : https://github.com/KhronosGroup/Vulkan-Docs.git
```

**Comment by m4b** [comment]
So what should we do here ? I’d like to test on a recent moltenvk but not sure how. I’m pretty sure this is a moltenvk issue ...

**Comment by m4b** [comment]
Upgrading to 1.1.97 no longer has a blue screen; I believe my suspicion was correct, and this was a regression in moltenvk which appears to have been fixed up stream. I will re-open this issue if next moltenvk release has a regression, and if so, I'll file directly in moltenvk and link to this issue, if you don't mind.

**Comment by damienwoods** [comment]
I'm seeing this same issue (blue screen when I run triangle or teapot example), on a much later version of Vulkan, any thoughts? 

vulkan 1.2.141
vulkano v0.19.0
MacOS  10.15.5
