### ISSUE TITLE
Shaderc does not compile with MSVC, results in multiple LNK2038 errors on build

### ISSUE THREAD

**Issue by WarpspeedSCP** [vulkano-rs/vulkano#1150]
Here's what the log looks like when I try building in VS2017-

[pastebin](https://pastebin.com/2bBDb4uU)

I am not sure of how to fix this as I can't find any way to set the proper CRT as detailed in [this stackoverflow answer](https://stackoverflow.com/questions/14714877/mismatch-detected-for-runtimelibrary/18635749) which outlines my problem. Is there any fix for this?

**Comment by rukai** [comment]
Can you try the changes to the instructions here https://github.com/vulkano-rs/vulkano/pull/1153
Lokathor on rust discord was able to fix his build issues via this change.

**Comment by rhzk** [comment]
Renaming python3.exe to python.exe solved this issue for me. I suppose you could also make a shortcut to python3.exe called python.exe or install python2

**Comment by knappador** [comment]
@rhzk  recommend closing.  issue will remain in google search results for posterity.
