### ISSUE TITLE
MipMapping not supported outside of ImmutableImage

### ISSUE THREAD

**Issue by Kurble** [vulkano-rs/vulkano#1154]
*   Version of vulkano: 0.11.1
*   OS: any
# Issue
It's currently not possible to use mipmapping for anything else than immutable images.
As I wanted to implement a form of image based lighting, I need to be able to render to cubemaps and then blur the contents of that cubemap into it's mipmaps in order to simulate varying degrees of roughness.

Are there any plans on supporting mipmaps or is help wanted?

**Comment by rukai** [comment]
Help is certainly wanted, feel free to research the issue yourself, present your findings and make a PR. The better you present your findings/reasoning  of the change the easier it is for me to review and more likely to merge, as I don't have any experience with advanced graphics programming topics like this.

**Comment by Kurble** [comment]
This is going surprisingly easy, seems like the only thing that was needed was to add an extra constructor to `StorageImage`. I'll create a pull request of my work once I have tested all use cases.

In the meantime anyone who needs it already (highly doubt it though) can use my fork:
https://github.com/Kurble/vulkano/tree/storage_mipmap

**Comment by knappador** [comment]
Did a PR get associated with this issue yet?

**Comment by Kurble** [comment]
Not yet. The project I needed this for has kind of stalled. I'll see if I can make this into a pull request later this week.
