### ISSUE TITLE
Examples of instancing with vulkano?

### ISSUE THREAD

**Issue by mitchmindtree** [vulkano-rs/vulkano#1162]
Hi folks, just wondering if anyone has a simple example of doing instancing with vulkano?

I've noticed that there's an "unstable" [`OneVertexOneInstanceDefinition`](https://docs.rs/vulkano/0.11.1/vulkano/pipeline/vertex/struct.OneVertexOneInstanceDefinition.html) `VertexDefinition` type but I haven't looked closely yet at how it's expected to be used. If no-one has an example, I may do some experimenting until I can work out how to setup the `GraphicsPipeline` etc.

@tomaka do you happen to have a snippet lying around where you tested instancing? No worries if it's not complete or buggy, I'm willing to dig in and work out what needs to be done.

**Comment by mitchmindtree** [comment]
@tomaka ahh thanks for the tip!

So for the types `T` and `U` in `OneVertexOneInstanceDefinition<T, U>`:
  - `T` refers to the vertex type that will be unique per instance and
  - `U` refers to the vertex type used to describe the geometry that we want to make instances of?

If that's the case, I'm guessing we then pass a `vec![t_buffer, u_buffer]` as the vertex buffer argument for the `draw` command function, where `t_buffer` is a buffer of `T` vertices and `u_buffer` is a buffer of `U` vertices. Then, the vertex shader is called `t_buffer.len() * u_buffer.len()` times, and we don't need to use `gl_InstanceIndex` because our unique data per instance is already being passed to the shader via the `T` vertex attributes.

Am I on the right track?

**Comment by mitchmindtree** [comment]
Ahh, using renderdoc I was able to work out that I have the vertex and instancedata buffers the wrong way around :) I've got everything working nicely now, time for a PR.

**Comment by knappador** [comment]
https://github.com/vulkano-rs/vulkano/issues/1044
