### ISSUE TITLE
Help understanding memory management

### ISSUE THREAD

**Issue by gdelazzari** [vulkano-rs/vulkano#1167]
Hello, I'm learning Vulkan with Vulkano (not sure if that's a good idea or I should first learn the unsafe/official API), and I have a doubt regarding memory management.

I'm playing around with some code and I'm trying to get MSAA on a window. I started from the `triangle.rs` example and changed various parts based on `msaa-renderpass.rs`, and I actually succeded in getting an MSAA rendered triangle on a window. I'm not sure, however, if I'm doing it correctly. My render pass obviously needs one more attachment which is the 4-samples image (I used an `AttachmentImage` as in the example) which I have to re-create every time the window size changes (because the dimensions of the attachments need to match). The images from the swapchain are already being recreated to the correct size with `swapchain.recreate_with_dimension(dimensions)` (which actually recreates the entire swapchain if I'm understanding it correctly) and I'm sure the old images/swapchain are deleted correctly etc.. however, every time the window size changes and I have to create a new framebuffer, I also have to create the `AttachmentImage`, but what about freeing up those? This is the relevant code I have:

```rust
fn window_size_dependent_setup(
    device: Arc<Device>,
    format: vulkano::format::Format,
    images: &[Arc<SwapchainImage<Window>>],
    render_pass: Arc<RenderPassAbstract + Send + Sync>,
    dynamic_state: &mut DynamicState,
) -> Vec<Arc<FramebufferAbstract + Send + Sync>> {
    let dimensions = images[0].dimensions();

    let viewport = Viewport {
        origin: [0.0, 0.0],
        dimensions: [dimensions[0] as f32, dimensions[1] as f32],
        depth_range: 0.0..1.0,
    };
    dynamic_state.viewports = Some(vec![viewport]);

    images
        .iter()
        .map(|image| {
            let intermediary =
                AttachmentImage::transient_multisampled(device.clone(), dimensions, NUM_SAMPLES, format)
                    .unwrap();

            Arc::new(
                Framebuffer::start(render_pass.clone())
                    .add(intermediary.clone())
                    .unwrap()
                    .add(image.clone())
                    .unwrap()
                    .build()
                    .unwrap(),
            ) as Arc<FramebufferAbstract + Send + Sync>
        })
        .collect::<Vec<_>>()
}
```

A new `AttachmentImage` is created for every swapchain image every time the window is resized, but I'm not sure if those are freed when the window gets resized the next time. It doesn't seem to happen since I can see the memory usage of my application increasing by 50/100 KBs when I'm resizing the window and not decreasing anymore. If I keep resizing the window I can reach +1/2MB with respect to the initial memory usage. But I'm not sure if that means anything. I even experienced a system crash/freeze at some point, after keeping to resize the window for some time, (on Linux) but that may be a driver issue because I wasn't able to reproduce it.

I know this is probably not an issue with Vulkano, I'm just asking for some help understanding Vulkan and Vulkano to someone more experienced, I hope it's not a problem.

Can someone tell me if this is the right way or if there's something wrong and how I can do this correctly? Thank you very much in advance, and keep up the good work!

**Comment by knappador** [comment]
I read so far that the general pattern is that a lot of the types are behind ARC's so that cloning is not a full copy.  You might drill down the image type and see if it's similarly not actually cloning.
