### ISSUE TITLE
Dependabot

### ISSUE THREAD

**Issue by knappador** [vulkano-rs/vulkano#1180]
Dependecy version management automation is hopefully taking us forward with respect to dependency hell.

I'm cleaning up a round on E-Nguyen.  They look like this:
https://github.com/e-nguyen/e-nguyen/pull/6

vulkano-winit has to put a trait on Window or else our applications fail to compile since Window from the crate won't have SafeDeref implemented for it.

**Comment by rukai** [comment]
vulkano-winit / winit version mismatch is annoying, I cant see a way to fix that though.
You can always copy the vulkano-winit code directly into your own project to alleviate the issue.
