### ISSUE TITLE
shaderc dep fails to build on MSCV

### ISSUE THREAD

**Issue by AustinJ235** [vulkano-rs/vulkano#1181]
*   Version of vulkano: 3518268b7f8080f44c06daf33c90c5b8cb4986d4
*   OS: Windows 10 Pro
*   GPU (the selected PhysicalDevice): Vega 56
*   GPU Driver: 19.2.3
*   Upload of a reasonably minimal complete `main.rs` file that demonstrates the issue: https://github.com/vulkano-rs/vulkano/blob/master/examples/src/bin/triangle.rs

# Issue
Vulkano did previously build on this install of Windows. Not sure if one of the later commits caused this issue or if I am missing something on this install.

**CMakeError.log** https://gist.github.com/AustinJ235/636396929f96c28b35d73cb3d8bc0ace

**Comment by rukai** [comment]
Thats no good... Can you report it upstream? https://github.com/google/shaderc-rs/issues

**Comment by AustinJ235** [comment]
My visual studio installation seems to have gotten corrupted at some point.
