### ISSUE TITLE
draw call requires a Vec of buffers (expected struct `std::vec::Vec`, found struct `std::sync::Arc`)

### ISSUE THREAD

**Issue by FuujSama** [vulkano-rs/vulkano#1182]
mismatched types

# Template

*   Version of vulkano: most recent
*   OS: Windows
*   GPU (the selected PhysicalDevice): NVidea GTX960M (

# Issue
When I create a command buffer with a draw command:

`let command_buffer = AutoCommandBufferBuilder::primary_one_time_submit(self.device.clone(), self.get_queue().family()).unwrap()
            
            .begin_render_pass(self.framebuffers[image_num].clone(), false, clear_values)
            .unwrap()
            .draw(self.pipeline.clone(), &self.state.dynamic_state, self.buffer.clone(), (), ())
            .unwrap()
            .end_render_pass()
            .unwrap()
            .build().unwrap();`

The compiler returns an error on the draw() call: 

> mismatched types
expected struct `std::vec::Vec`, found struct `std::sync::Arc`
note: expected type `std::vec::Vec<std::sync::Arc<(dyn vulkano::buffer::traits::BufferAccess + std::marker::Send + std::marker::Sync + 'static)>>`
         found type `std::sync::Arc<dyn vulkano::buffer::traits::BufferAccess + std::marker::Send + std::marker::Sync>`

Checking all the examples provided, that are currently compiling on my machine, the type of the buffer I'm providing seems to be "correct" as no example indicates using a vector of Arc<...> instead of the Arc<...> itself. So I'm quite confused.

I suspect the problem might be from the instantiation of the RenderPass and GraphicsPipeline objects, but I emulate the triangle tutorial almost entirely:

      `let render_pass = Arc::new(vulkano::single_pass_renderpass!(
            device.clone(),
            attachments: { 
                color: {
                    load: Clear,
                    store: Store,
                    format: swapchain.format(),
                    samples: 1,
                }
            },
            pass: {
                color: [color],
                depth_stencil: {}
            }
            `).unwrap());`

        `let pipeline = Arc::new(GraphicsPipeline::start()
            .vertex_input_single_buffer::<entity::Vertex2d>()
            .vertex_shader(vs.main_entry_point(), ())
            .triangle_list()
            .viewports_dynamic_scissors_irrelevant(1)
            .fragment_shader(fs.main_entry_point(), ())
            .render_pass(Subpass::from(render_pass.clone(), 0).unwrap())
            .build(device.clone())
            .unwrap());`

I've already provided the type of the buffer itself so I don't believe it's construction should be relevant as my main issue seems to be that the draw() function has decided that the TypeParameter V should equal a `Vec<Arc<Buffer...>>` Rather than an `Arc<Buffer...>`

I'm sorry if this is a duplicate issue but I couldn't find anyone with a similar issue.

**Comment by knappador** [comment]
I ran into the exact same problem while adapting my code.  I'll fix this in about ten hours.

**Comment by WarpspeedSCP** [comment]
I've noticed this while I was working on my project, but I didn't think much of it.

**Comment by knappador** [comment]
I dug into this and had difficulty finding the type of the bind, but basically whenever we bind via `let` vs binding to a Struct with explicit type, we're not quite hitting the same inference path.

`CpuAccessibleBuffer` implements for `TypedBufferAccess`
https://docs.rs/vulkano/0.11.1/vulkano/buffer/cpu_access/struct.CpuAccessibleBuffer.html

`SingleBufferDefinition` has implementations from `VertexSource<B> where B: TypedBufferAccess<Content=[Vertex]>
https://docs.rs/vulkano/0.11.1/vulkano/pipeline/vertex/struct.SingleBufferDefinition.html

I attempted to get a let binding working but I don't yet have a grip on trait implementations deep enough to find the correct bind.

I don't see a bug, but the binding is hard to specify correctly.

**Comment by AlmightyFloppyFish** [comment]
I'm currently having this issue in one of my two projects, despite the graphicspipeline, CpuAccessibleBuffer and Vertex being almost identical.

**Comment by AlmightyFloppyFish** [comment]
Here's my code in case we find some correlations
```rust
error[E0308]: mismatched types
  --> src/renderer/main/draw.rs:68:21
   |
68 |                     vertex_buffer,
   |                     ^^^^^^^^^^^^^ expected struct `std::vec::Vec`, found struct `std::sync::Arc`
   |
   = note: expected type `std::vec::Vec<std::sync::Arc<(dyn vulkano::buffer::traits::BufferAccess + std::marker::Send + std::marker::Sync + 'static)>>`
              found type `std::sync::Arc<vulkano::buffer::cpu_access::CpuAccessibleBuffer<[renderer::vertex::Vertex]>>
```
Compile error stems from here
```rust
    let vertex_buffer = CpuAccessibleBuffer::<[Vertex]>::from_iter(
        self.device.clone(),
        BufferUsage::all(),
        Vertex::square((0.2, 0.2), (0.2, 0.2)).iter().cloned(),
    )
    .unwrap();

    let mut draw_set = draw_buffer[i].lock().unwrap();
    if draw_set.waiter.is_some() {
        gpu_fut = Box::new(gpu_fut.join(Box::new(draw_set.waiter.take().unwrap())));
    }

    command_buffer = command_buffer
        .draw(
            self.draw_pipeline.clone(),
            &self.render_target.dynamic_state,
            vertex_buffer,
            draw_set.loaded.clone().unwrap(),
            (),
        )
        .unwrap()
```
I create my graphics pipeline with this
```rust
pub fn render_pass(
    device: Arc<device::Device>,
    swapchain: Arc<swapchain::Swapchain<winit::Window>>,
) -> Arc<framebuffer::RenderPassAbstract + Send + Sync> {
    Arc::new(
        vulkano::single_pass_renderpass!(
            device,
            attachments: {
                color: {
                    load: Clear,
                    store: Store,
                    format: swapchain.format(),
                    samples: 1,
                }
            },
            pass: {
                color: [color],
                depth_stencil: {}
            }
        )
        .unwrap(),
    ) as Arc<framebuffer::RenderPassAbstract + Send + Sync>
}

pub fn graphics_pipeline(
    device: Arc<device::Device>,
    render_pass: Arc<framebuffer::RenderPassAbstract + Send + Sync>,
) -> DrawGraphicsPipeline {
    let vs = shader::vs::Shader::load(device.clone()).unwrap();
    let fs = shader::fs::Shader::load(device.clone()).unwrap();
    Arc::new(
        pipeline::GraphicsPipeline::start()
            .vertex_input_single_buffer::<Vertex>()
            .vertex_shader(vs.main_entry_point(), ())
            .triangle_strip()
            .viewports_dynamic_scissors_irrelevant(1)
            .fragment_shader(fs.main_entry_point(), ())
            .blend_alpha_blending()
            .render_pass(framebuffer::Subpass::from(render_pass, 0).unwrap())
            .build(device)
            .unwrap(),
    )
}
```
where `DrawGraphicsPipeline` is
```rust
pub type DrawGraphicsPipeline = Arc<pipeline::GraphicsPipelineAbstract + Send + Sync>;
```

**Comment by Rua** [comment]
I'm running into the same problem, and I'm unable to figure out how to do instanced drawing because of it. I want to specify a tuple like in the instancing example, but it keeps asking for a Vec. And I can't put the two buffers in the Vec because they don't have the same type.

**Comment by AustinJ235** [comment]
have you tried casting the buffers into ``Arc<BufferAccess + Send + Sync>``

**Comment by Rua** [comment]
This API is redesigned now, so it's no longer an issue.
