### ISSUE TITLE
ShaderC Compile & CI

### ISSUE THREAD

**Issue by knappador** [vulkano-rs/vulkano#1183]
Our CI server currently failed one of the builds due to shaderc compile stalling.   I believe we need the option to use pre-compiled shaderC for the shaderc Rust package and am chasing this over to the ShaderC repo.

Gathering up some info here.

https://travis-ci.org/vulkano-rs/vulkano/jobs/506588484
```
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
```

Packages exist:
https://packages.gentoo.org/packages/media-libs/shaderc
https://www.archlinux.org/packages/extra/x86_64/shaderc/

This might be a lie on our CI setup:
[`# The shaderc dependencies are already installed on the base images`](https://github.com/vulkano-rs/vulkano/blob/5233221ad908bfffbd9379da025e8cb62c9a84ea/.travis.yml#L1)

**Comment by knappador** [comment]
https://github.com/google/shaderc-rs/issues/44

Going to try to kill this at the Rust package level.

**Comment by knappador** [comment]
https://github.com/google/shaderc-rs/pull/46

Headline change is using a static build path instead of the dynamic ones that cargo generates for `out` directory.

I don't know an Ubuntu package to make this process easy.  Who even controls the keys to the CI servers?  @rukai @tomaka

**Comment by Rua** [comment]
This seems to have been addressed by ShaderC?
