### ISSUE TITLE
Vertex Attribute Indices

### ISSUE THREAD

**Issue by rileylyman** [vulkano-rs/vulkano#1186]
When we use an `AutoCommandBufferBuilder` and call `draw_indexed`, I see that we can pass in multiple buffers, such as vertices and normals in the case of the `teapot` example. However, I only see one place where we can input an indices buffer to specify vertices.

If we want every vertex to be passed to the shaders along with some attributes, such as normals, do we have to rearrange our buffers so that the attributes are all at the same indices as their respective vertices? For instance, in the `.obj` file format, a face definition could be `f 10/12/14`, saying that the tenth vertex is associated with the fourteenth normal. In this case, would we just rearrange our buffers so that this was the case, or is there a way to specify this layout when building the command buffer and specifying indices.

**Comment by knappador** [comment]
https://www.khronos.org/registry/vulkan/specs/1.1-extensions/man/html/vkCmdDrawIndexed.html

I'm still getting up to speed on both the Vulkano and Vulkan API.  Can you confirm that the vanilla Vulkan call (which we will call via Vulkano Sys) supports / does not support the arguments you want to specify?

**Comment by Rua** [comment]
There can only be one index buffer bound at a time, you can't bind multiple like you can with vertex buffers.
