### ISSUE TITLE
vulkano.rs white on black eye strain

### ISSUE THREAD

**Issue by norru** [vulkano-rs/vulkano#1194]
Is there an option to get black text on white background? Reading the documentation in white text on black causes me eye strain.

**Comment by skyne98** [comment]
Yeah, I think having an option for that is a fair point.

**Comment by knappador** [comment]
Recommend browser plugin.  This is an n = 1 issue for an n = (m > 1) problem.

Recommend close.

**Comment by norru** [comment]
@knappador Tried one browser plugin. Only changes the color of the code samples. Descriptive text stays black on white.

Can you recommend browser plugin (for Firefox?)

**Comment by knappador** [comment]
No, if there is no available option for your plugin, then what you want is to find the absolute best option for "night mode" where the author is willing to work with you, and then just invert the logic around detection and mapping to create a "bright mode."

Recommend closing.

**Comment by norru** [comment]
Leaving open for a while just in case anyone has a better solution.

**Comment by knappador** [comment]
Recommend closing.  r/firefox and similar communities will have more informative and relevant feedback.

**Comment by norru** [comment]
Who is the maintainer of vulkano.rs? Is that you, @knappador?

**Comment by knappador** [comment]
No, but if I were, I would only have one thing to say.  "Closed, not
Vulkano."

**Comment by norru** [comment]
Anyone has any idea how to contact vulkano.rs's webmaster?

**Comment by rukai** [comment]
I'm not opposed to adding a javascript toggle for this, but I don't have time to do it myself. Filing an issue or making a PR at https://github.com/vulkano-rs/vulkano-www would be the way forward.

**Comment by AustinJ235** [comment]
If this is still an issue you are concerned about make an issue at ``vulkano-www``.
