### ISSUE TITLE
How to sync read-write dependency between command buffers?

### ISSUE THREAD

**Issue by knappador** [vulkano-rs/vulkano#1196]
I feel like this should be a really simple API use case, but I'm not getting it to either execute correctly or validate.  I can't tell how the API is designed to be used.  Will go in and document things and make an example if anyone has a clue what's intended design.

Intended operation between fence calls for frames:

1.  Create storage image
2.  Get execution future for compute commands to write to the image
3.  Get execution future for graphics command buffer to copy image to a destination 
4.  Execute compute, then command buffer, expecting automatic memory barriers or some basic combination of semaphore etc to prevent simultaneous access.

```rust

// storage image creation
let out_buf = StorageImage::with_usage(
    device.clone(),
    Dimensions::Dim2d { width: 1, height: source.tex_height as u32 },
    Format::R32G32B32A32Sfloat,
    ImageUsage { transfer_source: true, storage: true, ..ImageUsage::none() },
    vec![queue.family()],
)?;

// Descriptor set for input-output buffer
let set = Arc::new(
    PersistentDescriptorSet::start(pipeline.clone(), 0)?
        .add_image(out_buf.clone())
        .build()?,
);

// compute command buffer writing to image 
let compute_cb = AutoCommandBufferBuilder::primary_single_use(
    device.clone(),
    queue.family())?
    .dispatch([2, 1, 1], pipeline.clone(), set.clone(), None)?
    .build()?;

// create copy image & rectangle draw command buffer
let mut cbb: AutoCommandBufferBuilder = AutoCommandBufferBuilder::primary_one_time_submit(
            swap_win.device.clone(),
            swap_win.window_queue.family())?  
  
let copy_image_cb = cbb
    .copy_image(
        r.buffer.clone(),
        [0, 0, 0],
        0,
        0,
        self.fft_texture.clone(),
        [ux, 0, 0],
        0,
        0,
        [1 as u32, 1024, 1],
        1,
    )?
    .begin_render_pass(self.framebuffers[image_num].clone(), false, clear_values)?
    .draw(
        self.pipeline.clone(),
        &swap_win.dynamic_state,
        vec![self.background_rect.clone()],
        self.set.clone(),
        push_constants,
    )?
    .end_render_pass()?
    .build()?;

// execute the buffers in order (?)  
let mut new_frame: Box<dyn GpuFuture> = Box::new(previous_frame.join(acquire_future));
new_frame.then_execute(queue.clone(), compute_cb)?
     // need some synchronization calls here?  No idea what the API wants.
    .then_execute(queue.clone(), copy_image_cb)?
    .then_swapchain_present(
        swap_win.window_queue.clone(),
        swap_win.swapchain.clone(),
        image_num,
    )
    .then_signal_fence_and_flush();
```

Frequent error type
```
[0] 0x7f5870094c00, type: 6, name: NULL
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: AccessError { error: AlreadyInUse, command_name: "vkCmdCopyImage", command_param: "source", command_offset: 0 }', src/libcore/result.rs:997:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
```
My actual setup is not incredibly complex.  The way it runs on my master branch is pretty evil and breaks on some drivers.  I can't tell how it's supposed to actually be run when there's a read/write dependency between command buffers.

**Comment by knappador** [comment]
Closing.  Adding lots of semaphores created code that validates.

**Comment by Denzo77** [comment]
This has been driving me mad! 

My understanding from https://docs.rs/vulkano/0.11.1/vulkano/sync/index.html#executing-an-operation-after-a-future is that `then_execute()` should take care of the synchronisation if both command buffers are on the same queue, and that you need to call `then_signal_semaphore()` if you're copying between queues.

I haven't been able to get either case to work without sticking a big delay between submitting the command buffers though.

**Comment by knappador** [comment]
@Denzo77   Thanks for corroboration.  I have no idea where you found `then_signal_semaphore()` but I also observe it to work in practice.  I used `then_signal_semaphore_and_flush()`

**Comment by knappador** [comment]
Reopening as behavior has not been resolved in https://github.com/e-nguyen/e-nguyen/issues/23

**Comment by Denzo77** [comment]
It's here:
https://docs.rs/vulkano/0.11.1/vulkano/sync/index.html#between-two-different-gpu-queues

Unfortunately, I haven't been able to get it to work. To clarify, what works for me is something like this (adapting your example):
```rust
new_frame.then_execute(queue.clone(), compute_cb)?
    .then_signal_semaphore_and_flush();

// Do a bunch of stuff here that means the compute finishes and the buffer is released.

copy_image_cb.execute(queue.clone())?
    .then_swapchain_present(
        swap_win.window_queue.clone(),
        swap_win.swapchain.clone(),
        image_num,
    )
    .then_signal_fence_and_flush();

// Do a bunch of stuff here that means the draw finishes and the buffer is released.
```
Obviously this is not ideal!

**Comment by knappador** [comment]
I'm going to have to jump over to the lower level ash crate or perhaps gfx for now depending on the WSI difficulty.  I've seen where Vulkano ends up tossing these kinds of decisions between tons of layers, and without enough low level Vulkan experience, I'm going to get toasted trying to bargain a high level dependency that is still half implemented.
