### ISSUE TITLE
Setting CACHED_BIT for CpuAccessibleBuffer

### ISSUE THREAD

**Issue by Julusian** [vulkano-rs/vulkano#1205]
# Template

*   Version of vulkano: 0.11.1
*   OS: ubuntu18.04
*   GPU: Quadro P4000
*   GPU Driver: 390.116
*   Upload of a reasonably minimal complete `main.rs` file that demonstrates the issue: [cached-bit.zip](https://github.com/vulkano-rs/vulkano/files/3220322/cached-bit.zip) Compare the result against unmodified vulkano and with https://github.com/Julusian/vulkano/commit/eb6a8c8c8588720013edf4de9b27d2d862bca8f7 cherry picked to see the difference

# Issue

I have discovered that on my machine, the CpuAccessibleBuffer uses the memory pool without the host_cached flag enabled. This makes is inefficient for doing GPU -> CPU transfers
For comparison, copying a frame of 1920x1080 video out of the buffer (with `.to_vec()`takes around 25ms. By changing the memory pool selection to prefer host_cached, this drops down to 4ms.

I do not see a way of specifying which of the optional memory type flags a buffer should have, so I cannot choose this myself without modifying the vulkano code

**Comment by AustinJ235** [comment]
https://github.com/vulkano-rs/vulkano/pull/1307 has been merged.
