### ISSUE TITLE
Implement Eq for Queue & QueueFamily

### ISSUE THREAD

**Issue by milkey-mouse** [vulkano-rs/vulkano#1206]
While working on [a project](https://github.com/milkey-mouse/planets) using vulkano there were several times where it would have been useful to check for equality of `Queue`s or `QueueFamily`'s directly, among other structs. It seems like it would be pretty easy to implement [`Eq`](https://doc.rust-lang.org/std/cmp/trait.Eq.html) for these.

Looks like `Queue` has an `is_same` function already, so all you'd have to do is call it in the trait implementation.

I haven't dug into the code, but `QueueFamily`'s implementation of `Eq` would probably be as simple as `family.id() == other.id() && family.physical_device().id() == other.physical_device().id()`.

**Comment by AustinJ235** [comment]
Completed via https://github.com/vulkano-rs/vulkano/pull/1306
