### ISSUE TITLE
Shader compilation fails with: "No Rust equivalent for a floating-point of width 32"

### ISSUE THREAD

**Issue by dthul** [vulkano-rs/vulkano#1207]
*   Version of vulkano: 0.12
*   OS: Windows 10
*   GPU (the selected PhysicalDevice): GTX 1080
*   GPU Driver: 418.96

# Issue

I updated to the latest Rust nightly (1.37.0-nightly (1d9981f04 2019-06-20)) and now shader compilation doesn't work anymore:

```rust
vulkano_shaders::shader! {
    ty: "vertex",
    path: "src/render/diffuse/vertex.glsl"
}
```

fails with:

```
error: proc macro panicked
  --> viewer\src\render\checkerboard\mod.rs:10:5
   |
10 | /     vulkano_shaders::shader! {
11 | |         ty: "vertex",
12 | |         path: "src/render/diffuse/vertex.glsl"
13 | |     }
   | |_____^
   |
   = help: message: No Rust equivalent for a floating-point of width 32
```

It seems like this issue was also reported in [nannou-org/nannou_timeline#1](https://github.com/nannou-org/nannou_timeline/issues/1) and [nannou-org/nannou#338](https://github.com/nannou-org/nannou/issues/338).

**Comment by milkey-mouse** [comment]
I have the same issue. Oddly on [my project](https://github.com/milkey-mouse/planets) `cargo build` works fine, but `cargo build --release` does not, even after running `cargo clean`.

I am using rustc `1.37.0-dev (8d6f4b96d 2019-06-21)` & vulkano `0.12.0` on Linux.

**Comment by rukai** [comment]
A quick look at the code shows that this is either some evil UB somewhere in vulkano or rustc is miscompiling things.

https://github.com/vulkano-rs/vulkano/blob/master/vulkano-shaders/src/structs.rs#L294 This branch can never be taken when width = 32, and yet it is taken...

**Comment by norru** [comment]
Just been bitten by this. Only happens in `build --release`. I see @rukai has worked this out already, when is the fix scheduled to be release on `crates.io`? :)

```
cargo 1.37.0-nightly (4c1fa54d1 2019-06-24)
rustc 1.37.0-nightly (17e62f77f 2019-07-01)
vulkano-shaders v0.11.1
```
