### ISSUE TITLE
examples/triangle.rs running as fast as 3378 fps, locks up PC

### ISSUE THREAD

**Issue by SongWithoutWords** [vulkano-rs/vulkano#1210]
*   Version of vulkano: 0.12.0
*   OS: Linux, Ubuntu 18.10
*   GPU (the selected PhysicalDevice): GTX 1050
*   GPU Driver: Nvidia 390.116
*   Upload of a reasonably minimal complete `main.rs` file that demonstrates the issue: `vulkano/examples/src/bin/triangle.rs`
* Device: Laptop (Dell XPS 15 9570)

I launched the `triangle.rs` example and it locked up my machine.

I then googled around for this issue, and followed the advice in #923 by calling wait on the future after `signal_fence_and_flush()`, but the issue remained.

I then added some timing code to it and found that it was running as fast as 3378 fps.

Can this library be made to work with Nvidia drivers on Linux?

**Comment by SongWithoutWords** [comment]
I just tried to repro this on another machine, a desktop rather than a laptop using a GTX 1070 instead of a GTX 1050, but with the same versions of the same drivers and operating system.

Without the call to `wait()` after `signal_fence_and_flush()`, it monopolized one core of the CPU (utilizing 25%) without locking up the whole machine. After calling `wait()` after `signal_fence_and_flush()`, it now uses 1-2% of the CPU time.

So this issue seems hardware dependent.

**Comment by faulesocke** [comment]
This sounds definitely like a bug in the Nvidia driver. At least with the wait call you should never get a lockup and of course you shouldn't without the wait. Maybe point Nvidia towards this issue?

**Comment by AustinJ235** [comment]
This is a known issue, please refer to https://github.com/vulkano-rs/vulkano/issues/1247
