### ISSUE TITLE
Timestamp query example

### ISSUE THREAD

**Issue by aschrein** [vulkano-rs/vulkano#1215]
# Issue

Couldn't find a way to query a timestamp. [this method](https://github.com/vulkano-rs/vulkano/blob/fc6ac6fec135cbd3162e06542ebb2e61be116846/vulkano/src/command_buffer/sys.rs#L1466) looks like the right path to the underlying vulkan API function but I couldn't find a way to use it. I think an example of canonical usage of queries in Vulkano would be nice.

A workaround is to use some performance analyzer e.g. RenderDoc(poor man's perf analyzer), vtune, Nsight...

Thanks

**Comment by dobrakmato** [comment]
Are there any plans to implement queries into `vulkano`? 

I have look at docs for `query` package and there seems to be some implementation but I cannot find a way to submit queries (and then retrieve their results) trough safe `vulkano` api. Are there any long-term plans with supporting queries in vulkano? What needs to be done to support timestamp, occlusion and statistics queries trough safe command builder?

Related to this issue: https://github.com/vulkano-rs/vulkano/issues/293

**Comment by Rua** [comment]
A bit old, but #1542 may interest you.
