### ISSUE TITLE
Running any Vulkano projects results in a freeze and crash

### ISSUE THREAD

**Issue by Ldash4** [vulkano-rs/vulkano#1217]
*   OS: Arch 5.1.15-arch1-1-ARCH
*   GPU: NVIDIA GeForce GTX 1070
*   GPU Driver: nvidia-430.26-7

Running any Vulkano project (I tried several from the examples repo) results in the following:
```
➜  vulkano-examples git:(master) cargo run --release --bin triangle
    Finished release [optimized] target(s) in 0.07s
     Running `target/release/triangle`
Using device: GeForce GTX 1070 (type: DiscreteGpu)
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: OutOfHostMemory', src/libcore/result.rs:997:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```
The backtrace contains no useful information. The exact same results are shown on any example.

The project renders one frame, shows the above message, hangs for ~4 seconds and then crashes.

**Comment by simdimdim** [comment]
might be related: https://github.com/vulkano-rs/vulkano/pull/955

**Comment by theotherphil** [comment]
I see the same behaviour on my machine.

OS: Ubuntu 19.04
GPU: NVIDIA GeForce RTX 2070 SUPER
GPU Driver: 430.50-0ubuntu0.19.04.1

**Comment by AustinJ235** [comment]
This is a know issue at this point and has yet to be corrected in the examples. On nvidia systems you need to call ``wait`` after ``then_signal_fence_and_flush``.

**Comment by theotherphil** [comment]
Thanks. The following change fixes the triangle example for me.

```
diff --git a/src/bin/triangle.rs b/src/bin/triangle.rs
index 172075d..e8848a0 100644
--- a/src/bin/triangle.rs
+++ b/src/bin/triangle.rs
@@ -415,6 +415,7 @@ void main() {
 
         match future {
             Ok(future) => {
+                future.wait(None);
                 previous_frame_end = Box::new(future) as Box<_>;
             }
             Err(FlushError::OutOfDate) => {
```
