### ISSUE TITLE
[CpuBufferPool Documentation] Chunk vs Subbuffer

### ISSUE THREAD

**Issue by JasonHise** [vulkano-rs/vulkano#1221]
It is unclear from the provided documentation what the difference is between a chunk and a subbuffer.  Without examples it can be very difficult to identify when using one instead of the other may be necessary.  We spent multiple days tracking down why an attempt to pass a subbuffer of vertices to a call to draw() was failing to compile.  The error message was extremely verbose, but ultimately seemed to be saying that the for some reason the requirements for implementing the VertexSource trait were not being met.

On a complete whim we finally tried switching to storing a chunk instead of a subbuffer.  The problem immediately fixed itself.

Even by looking at the source code in cpu_pool.rs it isn't obvious why there are two types.  One seems to act like a mere wrapper over the other one but both implement all the same traits.  The initial impression was that the difference was just whether the memory would be initialized with a chunk of data directly, or if it would be initialized by traversing an iterator.

I did some digging after the fact to try to understand why one data structure worked and the other did not.  My hypothesis is that the meaningful difference is whether TypedBufferAccess exposes the type Content as a slice or a single element.

I'm hoping that either the documentation can be clarified to indicate when one or the other is appropriate to use, or that example code can be provided to demonstrate the difference between the two options.

**Comment by Rua** [comment]
`CpuBufferPool` no longer exists, so this issue is moot.
