### ISSUE TITLE
Struct used in both uniform and buffer generated twice - fails to compile

### ISSUE THREAD

**Issue by nelk** [vulkano-rs/vulkano#1222]
*  Version of vulkano: 0.13.0, or commit 32b6161
* OS: Linux
* GPU (the selected PhysicalDevice): GeForce GTX 980 Ti
* GPU Driver: nvidia 430.14
*   Upload of a reasonably minimal complete `main.rs` file that demonstrates the issue: https://gist.github.com/nelk/88bfbf10fd8edbec622a80422ae11f2d

For vulkano-shaders, if you use the same struct in both a uniform and a buffer, it fails to compile with the following error:
```
error[E0428]: the name `Val` is defined multiple times
 --> src/main.rs:4:5
  |
4 |     vulkano_shaders::shader! {
  |     ^^^^^^^^^^^^^^^^^^^^^^^^
  |     |
  |     `Val` redefined here
  |     previous definition of the type `Val` here
  |
  = note: `Val` must be defined only once in the type namespace of this module
```

**Comment by AustinJ235** [comment]
I don't believe you can have struct values within an uniform struct. This is a limitation of vulkan.
