### ISSUE TITLE
Add an easy way to generate mipmaps

### ISSUE THREAD

**Issue by tomaka** [vulkano-rs/vulkano#123]
Add a trait in the `image` module that is implemented on command buffer builders:

``` rust
pub fn trait CommandBufferImageExt {
    fn generate_mipmaps<I>(self, image: &Arc<I>) -> Self where I: Image;
}

impl CommandBufferImageExt for CommandBufferBuilder {
    ...
}
```

So that users can easily do this operation without using a for loop.

**Comment by tomaka** [comment]
Should probably be named `generate_linear_mipmaps` instead, because in some situations generating mipmaps this way is bad.

**Comment by Rua** [comment]
`ImmutableImage` can now generate mipmaps.
