### ISSUE TITLE
#[derive(VulkanoShader)] panics with "No Rust equivalent for a floating-point of width 32"

### ISSUE THREAD

**Issue by MichaelMauderer** [vulkano-rs/vulkano#1233]
`#[derive(VulkanoShader)]`  panic with rust 1.37 on linux and windows with the following error message. I did not specifically check earlier versions but this started happening after upgrading.

```
error: proc-macro derive panicked
   --> [...]
    |
116 |     #[derive(VulkanoShader)]
    |              ^^^^^^^^^^^^^
    |
    = help: message: No Rust equivalent for a floating-point of width 32

error: aborting due to previous error

```
This happens with both version 0.11 and 0.10 of vulkano-shader-derive. I did not check earlier versions.  

It seems to happen only in release mode.

While the package is deprecated people might still be using this, so I'm leaving this here to find potential fixes or workarounds.

**Comment by rukai** [comment]
Update to the latest vulkano

**Comment by MichaelMauderer** [comment]
Works fine with v.14. 
Otherwise downgrading to 1.36 with `rustup override set 1.36.0` can serve as a quick workaround.
