### ISSUE TITLE
Crashing/Freezing/OutOfHostMemory with Nvidia or on MacOS systems

### ISSUE THREAD

**Issue by AustinJ235** [vulkano-rs/vulkano#1247]
This issue has been brought up many times and is possibly due to driver bugs. Further investigation is needed to see if this is an issue within vulkano. Pull request https://github.com/vulkano-rs/vulkano/pull/1246 adds a workaround in the examples so that new users aren't put off when getting started with vulkano and aren't confused as to why it isn't work on their system.

Issues related: https://github.com/vulkano-rs/vulkano/issues/1217 https://github.com/vulkano-rs/vulkano/issues/959 https://github.com/vulkano-rs/vulkano/issues/923 https://github.com/vulkano-rs/vulkano/issues/627 https://github.com/vulkano-rs/vulkano/issues/1022 https://github.com/vulkano-rs/vulkano/issues/1210 https://github.com/vulkano-rs/vulkano/issues/1136 https://github.com/vulkano-rs/vulkano/issues/1135
Pull request related: https://github.com/vulkano-rs/vulkano/pull/1246 https://github.com/vulkano-rs/vulkano/pull/955 https://github.com/vulkano-rs/vulkano/pull/1027

**Comment by nickwilcox** [comment]
Has anybody done a deep dive on what the possible causes are?

**Comment by AustinJ235** [comment]
https://github.com/vulkano-rs/vulkano/pull/955 is about the deepest we have gone. Original thought it was an nvidia bug, but somebody posted about a validation error. Something may be incorrect about our GpuFuture handling. So if you cared to do any investigation sanity checking the gpu future code would be a good place to start.

**Comment by nickwilcox** [comment]
I found that the issue with the triangle example was fixed by an upgrade to MoltenVK 1.1.126 from 1.1.101.

Before that when I took our the workaround I was seeing the MoltenVK swapchain code constantly leaking CAMetalDrawables at 12MiB each.

**Comment by Ella-0** [comment]
I'm still having issues with this. I've tried a couple solutions and my program still only works reliably on my Intel GPU. It crashes after a few seconds on the Nvidia GPU. I am making a new `ImmutableImage` every frame which probably isn't the best of ideas but I don't think that's what is causing it.

**Comment by AustinJ235** [comment]
Id make sure you are using cleanup_finished and waiting for each future as nvidia might have issues yet it seems.

**Comment by Ella-0** [comment]
Yeah I've tried both of those and it still crashes. As for memory usage, it states it was 1.6% of memory before it crashed.

**Comment by Ella-0** [comment]
I think it must be my code because I've_ never had issues like this before when using an Nvidia gpu with vulkano though I've never been copying lots of data each frame with vulkano.

**Comment by AustinJ235** [comment]
Creating an image every fram the driver may not like that. I would recommend create a storage image a copy from a buffer every frame.

**Comment by Ella-0** [comment]
Yeah, I'll do that and see if the errors still persist.

**Comment by Ella-0** [comment]
Well I switched everything to use `StorageImage` so now the nvidia driver doesn't crash, but no images are loaded when using the nvidia card. it works fine with my intel card though. weird.

**Comment by AimainaHito** [comment]
Hi, I'm getting memory leaks at around 1mb/s which makes my program practically unusable at the moment.

I'm using an `ImmutableImage` which is updated only rarely when needed, a `CpuAccessibleBuffer` with `storage` usage of which I create a new one every frame and push constants (potential related to #1118). Given the size of the leaks I assume that most likely the main culprit is that the `CpuAccessibleBuffer` memory somehow isn't released properly. I'm using both `future.wait(None).unwrap()`, without which I get OOM very quickly with `PresentMode::Immediate`, and `cleanup_finished` after every draw call.

Any advice for what I should be looking for to fix this?

**Comment by AimainaHito** [comment]
I haven't noticed it yesterday, but it seems like I'm also running into leaks caused by `ImmutableImage` even though I only replace it when the window is resized

**Comment by Rua** [comment]
Is this still an issue?

**Comment by Ella-0** [comment]
I have no idea. I don't have nvidia hardware to test with anymore.

**Comment by AustinJ235** [comment]
Should be closed with https://github.com/vulkano-rs/vulkano/pull/1246

https://github.com/vulkano-rs/vulkano/pull/1246#issuecomment-544291409
> Can you update your comments to refer to #1247 instead.
