### ISSUE TITLE
Linking error in cross compile triangle example

### ISSUE THREAD

**Issue by luisvgs** [vulkano-rs/vulkano#1263]
*   Version of vulkano:  0.14
*   OS: Windows 10
*   GPU (the selected PhysicalDevice): AMD Radeon HD 7560D
*   GPU Driver: 

# Issue
I'm currently trying to run the triangle example, but unfortunately I'm getting the following error:

Compiling vulkano-shaders v0.13.0

error: linking with `gcc` failed: exit code: 1

= note: "gcc" "-Wl,--enable-long-section-names" "-fno-use-linker-plugin" "-Wl,--nxcompat" "-nostdlib" "-m64" "C:\\Program Files\\Rust stable GNU 1.36\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\dllcrt2.o" "C:\\Program Files\\Rust stable GNU 1.36\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\rsbegin.o" "-L" "C:\\Program Files\\Rust stable GNU 1.36\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib"...

error: Could not compile `vulkano-shaders`.

Here's the full error: https://pastebin.com/9FZP1d3f

I'm running the said binary with the --target=x86_64-pc-windows-gnu flag, since the windows-gnu toolchain is not supported. I did make sure that I have the msys2 and mingw64 binary path in my PATH environment. I don't know what else I could be missing. Any idea of what could be causing this error? I kindly ask for help. Thanks in advance.

**Comment by AustinJ235** [comment]
i'd refer you to https://github.com/google/shaderc-rs and look at the build instructions

**Comment by bluretrece** [comment]
> i'd refer you to https://github.com/google/shaderc-rs and look at the build instructions

Thanks. I'd say it's a similar issue, though I already make sure that I have CMake, Git, Python and also Ninja, like the build instructions says.

**Comment by AustinJ235** [comment]
The errors that you are getting are to shaderc files so, so I'd say that it is definitionally source of the issue.
