### ISSUE TITLE
Cannot close triangle example window reliably

### ISSUE THREAD

**Issue by heeen** [vulkano-rs/vulkano#1266]
# Template

*   Version of vulkano: master/08d635c97765678ac7604095950fb6ba5b10dd3c
*   OS: Linux, XOrg, KWin (kubuntu)
*   GPU (the selected PhysicalDevice): RTX2080
*   GPU Driver: nvidia 435
*   Upload of a reasonably minimal complete `main.rs` file that demonstrates the issue: examples: cargo run --bin triangle

# Issue

You cannot close the example window. sometimes it closes after 20-30 seconds, sometimes not at all. The WM complains about a hung application. Resizing still works though.

adding println! to the event handlers in the event loop shows that those events are not received or received much later, while the loop spins happily on. resizing through outdated swapchain works ok-ish.

**Comment by heeen** [comment]
I tried the simples winit example and it seems to work without issues:

```
use winit::{
    event::{Event, WindowEvent},
    event_loop::{ControlFlow, EventLoop},
    window::WindowBuilder,
};

fn main() {
    let event_loop = EventLoop::new();
    let window = WindowBuilder::new().build(&event_loop).unwrap();

    event_loop.run(move |event, _, control_flow| {
        println!("loop");
        match event {
            Event::EventsCleared => {
                // Application update code.

                // Queue a RedrawRequested event.
                window.request_redraw();
            },
            Event::WindowEvent {
                event: WindowEvent::RedrawRequested,
                ..
            } => {
                // Redraw the application.
                //
                // It's preferrable to render in this event rather than in EventsCleared, since
                // rendering in here allows the program to gracefully handle redraws requested
                // by the OS.
            },
            Event::WindowEvent {
                event: WindowEvent::CloseRequested,
                ..
            } => {
                println!("The close button was pressed; stopping");
                *control_flow = ControlFlow::Exit
            },
            // ControlFlow::Poll continuously runs the event loop, even if the OS hasn't
            // dispatched any events. This is ideal for games and similar applications.
                _ => *control_flow = ControlFlow::Poll,
                // ControlFlow::Wait pauses the event loop if no events are available to process.
                // This is ideal for non-game applications that only update in response to user
                // input, and uses significantly less power/CPU time than ControlFlow::Poll.
                // _ => *control_flow = ControlFlow::Wait,
        }
    });
}
```

**Comment by AustinJ235** [comment]
I am waiting on winit to be released officially before we update vulkano to use it. It appears to have many bugs yet that I feel like shouldn't be in a released product. So in order to not block further releases, we will not be updating to winit 0.20 for the time being.

**Comment by AustinJ235** [comment]
Now that I have winit 0.20 back into master is this still an issue?
