### ISSUE TITLE
Missing documentation for vulkano-shaders 0.16.0

### ISSUE THREAD

**Issue by Griffone** [vulkano-rs/vulkano#1270]
# Issue

The docs.rs documentation for [0.16.0](https://docs.rs/crate/vulkano-shaders/0.16.0) version of vulkano-shaders crate is missing.

**Comment by nickwilcox** [comment]
On the basis of last person to touch the code is responsible for breakages I've put up #1267 

The invalid markdown didn't stop the docs being generated locally, so I don't actually know if that's the cause of the issue. If someone with access the crates.io account has a more detailed log of what went wrong generating the docs I'll be happy to try fix it.

**Comment by AustinJ235** [comment]
@tomaka is the only person with crates.io power at this time. I'll go ahead and accept the pull request, but I don't think doc.rs is going to update until another release is made
