### ISSUE TITLE
Git tags for Vulkano releases

### ISSUE THREAD

**Issue by jbit** [vulkano-rs/vulkano#1278]
In a production environment it's useful to fork vulkano and add minor changes on top of a specific version.
To facilitate this use case it'd be useful to have upstream git tags that correlate to the versions on crates.io.

It's unfortunate that `vulkano`, `vulkano-shaders`, and `vulkano-win` releases sometimes have different hashes, because it would be nice to have tags such as `0.16.0`.
Maybe we can have a tag like `0.16.0` point to the latest commit of the various crates (so `ea9aa8e95d2d435952ea8597f54a8a3474966e7c` in the case of `0.16.0)?

Below is a list of commands to add tags for the last few release:
You can see how these would look here: https://github.com/jbit/vulkano/releases
```
git tag vulkano-0.11.1 d6e313e2fe2a6e145da6c282d64f7ad6869f762b
git tag vulkano-0.12.0 bb6beb89958774daad38db9a9c399cd42637f1db
git tag vulkano-0.13.0 e93dff0bd3011fb467a8e7fdbfec15ddefe0e9c2
git tag vulkano-0.14.0 814dacdab923771f8a818f7925785d347ddd4866
git tag vulkano-0.16.0 2e6868a0c0817b45106a2f04f0dd8f7d057dbba8
git tag vulkano-shaders-0.11.1 0c85863eb7427af57c0c77e715c77be01fa51246
git tag vulkano-shaders-0.12.0 bb6beb89958774daad38db9a9c399cd42637f1db
git tag vulkano-shaders-0.13.0 e93dff0bd3011fb467a8e7fdbfec15ddefe0e9c2
git tag vulkano-shaders-0.14.0 814dacdab923771f8a818f7925785d347ddd4866
git tag vulkano-shaders-0.16.0 ea9aa8e95d2d435952ea8597f54a8a3474966e7c
git tag vulkano-win-0.11.1 0c85863eb7427af57c0c77e715c77be01fa51246
git tag vulkano-win-0.12.0 bb6beb89958774daad38db9a9c399cd42637f1db
git tag vulkano-win-0.13.0 e93dff0bd3011fb467a8e7fdbfec15ddefe0e9c2
git tag vulkano-win-0.14.0 814dacdab923771f8a818f7925785d347ddd4866
git tag vulkano-win-0.16.0 2e6868a0c0817b45106a2f04f0dd8f7d057dbba8
```
And then you should be able to push the tags with, for example: `git push --tags origin`

I generated this list with the following (kinda hacky) script (which uses `jq`). If there's a better way to do this, please let me know :)

```
$ cd ~/.cargo/registry/src/github.com-1ecc6299db9ec823
$ for dir in vulkano-*; do
    NAME="${dir%-*}"
    VERSION="${dir##*-}"
    COMMIT="$(jq --raw-output .git.sha1 $dir/.cargo_vcs_info.json)"
    echo git tag "$dir" "$COMMIT" 
done
```

**Comment by jbit** [comment]
(Also, it would be nice if future releases have a tag created too 😄)

**Comment by eisterman** [comment]
It would be really convenient as a thing, I wondered why they were missing!

**Comment by jameslee-twobulls** [comment]
This can be closed, there are tags now 😄 https://github.com/vulkano-rs/vulkano/tags
