### ISSUE TITLE
Implement checks on shaders to make sure they are compatible with the device

### ISSUE THREAD

**Issue by AustinJ235** [vulkano-rs/vulkano#1280]
As pointed out in https://github.com/vulkano-rs/vulkano/pull/1279 sometimes an incompatible shader can be used within a pipeline which will lead to undefined behavior that is hard to debug.

I purpose that we implement some checks when loading a shader in the ``Shader::load`` function that makes sure the shader being loaded is compatible with the device that is being used.

Things such as device limitations should at least be checked here.

**Comment by Rua** [comment]
I believe this is fixed to some degree, as compatibility is checked. Shaders still aren't validated though.
