### ISSUE TITLE
Surface::from_raw_surface: glfw-rs

### ISSUE THREAD

**Issue by adschwab** [vulkano-rs/vulkano#1286]
With glfw-rs crate, many of the modification methods require mutable Window objects. Since there's no Surface::mut_window() I'm not sure how to properly construct a Surface. I assume the proper way is to have Surface own the Window object created by the windowing library (winit does this it seems). Without a mut_window is there an idiomatic way of doing this? Could glfw retain ownership of the window and make the field win blank ()?

This is the object I'd like to use:
https://docs.rs/glfw/0.34.0/glfw/struct.Window.html

**Comment by AustinJ235** [comment]
You may be interested in https://crates.io/crates/vulkano-glfw-v2
