### ISSUE TITLE
Surface::capabilities blocks indefinitely

### ISSUE THREAD

**Issue by SamHSmith** [vulkano-rs/vulkano#1288]
# Template

If you dont understand something just leave it.
If you can provide more detailed information than the template allows for, please ignore the template and present all of your findings.

*   Version of vulkano: 0.16.0
*   OS: Fedora 31
*   GPU (the selected PhysicalDevice): RX 5700 XT
*   GPU Driver: radv in kernel 5.3.16

´

    fn main(){

    init_glfw();

    let monitorcount = get_monitor_count();

    let window = VulkanWindow::new_windowed("Yo", 512, 512);

    use glfw_native::*;

    println!("{:?}", get_vulkano_extensions());

    let inst = Instance::new(Option::None, get_vulkano_extensions(), Option::None).expect("Failed to create vulkan instance");

    let surface = window.get_vulkano_surface(&inst);

    let physical = PhysicalDevice::enumerate(&inst).next().expect("Oops, there is no device");

    let queue_family = physical.queue_families().find(|q| q.supports_graphics()).expect("There is no queue family that support graphics");

    let device_ext = vulkano::device::DeviceExtensions {
        khr_swapchain: true,
        ..vulkano::device::DeviceExtensions::none()
    };

    let (device, mut queues) =
        Device::new(physical,
                    &Features::none(),
                    &device_ext,
                    [(queue_family, 0.5)].iter().cloned()).expect("Could not create device.");

    let queue = queues.next().unwrap();

    println!("pre pre start");

    let caps = surface.capabilities(physical)
        .expect("failed to get surface capabilities");

    println!("pre start");

    let dimensions = caps.current_extent.unwrap_or([1280, 1024]);
    let alpha = caps.supported_composite_alpha.iter().next().unwrap();
    let format = caps.supported_formats[0].0;

    let (swapchain, images) = Swapchain::new(device.clone(), surface.clone(),
                                             caps.min_image_count, format, dimensions, 1, caps.supported_usage_flags, &queue,
                                             SurfaceTransform::Identity, alpha, PresentMode::Fifo, true, Option::None)
        .expect("failed to create swapchain");

    while !window.should_close() {
        unsafe {
            glfwPollEvents();
        }
        println!("start!");

        let (image_num, acquire_future) = vulkano::swapchain::acquire_next_image(swapchain.clone(), Option::None).unwrap();

        let cmdbuf = AutoCommandBufferBuilder::new(device.clone(), queue_family).unwrap()
            .clear_color_image(images[image_num].clone(), ClearValue::Float([0.0, 0.0, 1.0, 1.0]))
            .unwrap();

        let future = acquire_future.then_execute(queue.clone(), cmdbuf.build().unwrap()).unwrap();

        let present = future.then_swapchain_present(queue.clone(), swapchain.clone(), image_num).then_signal_fence_and_flush();

        println!("looop");

        std::thread::sleep(Duration::new(1, 0));
    }
    }
´

The program outputs 

´

     pre pre start

´

Does anyone know why this could be?

Ps: it's a xcb surface

**Comment by AustinJ235** [comment]
I think your use of glfw may be playing a part here. My guess is that an extension that is needed isn't being loaded. I'd question what ``get_vulkano_extensions`` is doing as with winit we do ``vulkano_win::required_extensions()`` which the source is:
```rust
pub fn required_extensions() -> InstanceExtensions {
    let ideal = InstanceExtensions {
        khr_surface: true,
        khr_xlib_surface: true,
        khr_xcb_surface: true,
        khr_wayland_surface: true,
        khr_android_surface: true,
        khr_win32_surface: true,
        mvk_ios_surface: true,
        mvk_macos_surface: true,
        ..InstanceExtensions::none()
    };

    match InstanceExtensions::supported_by_core() {
        Ok(supported) => supported.intersection(&ideal),
        Err(_) => InstanceExtensions::none(),
    }
}
```

**Comment by SamHSmith** [comment]
In that case my conversion from strings to vulkano extension objects must not be working properly. I will investigate this at a later date. For now I will just use vulkano_win and winit.

**Comment by SamHSmith** [comment]
I have since properly integrated glfw and vulkano and I can safely say there is no issue.
