### ISSUE TITLE
Generate Default impl for shader uniform blocks

### ISSUE THREAD

**Issue by Rua** [vulkano-rs/vulkano#1291]
When `vulkano_shaders` generates Rust data types for each uniform block in the shader, it would be useful if it could also generate an implementation of `Default` for those types. That way, they can be initialised without knowing all the values up front. And more importantly, the user can skip having to initialise "dummy" values that are only for padding and don't matter otherwise.

**Comment by AustinJ235** [comment]
This isn't as easy as I thought to implement. Large arrays do not implement ``Default`` so this makes it much more challeging then just adding a ``#[derive(Default)]``. It may be possible with if the struct had less a length less than or equal to 32 which I am looking to see how I can implement that.

**Comment by Eliah-Lakhin** [comment]
@Rua This issue resolved in #1460 .
