### ISSUE TITLE
Implement barrier insertions in between dispatch calls

### ISSUE THREAD

**Issue by AustinJ235** [vulkano-rs/vulkano#1297]
Originally brought up under https://github.com/vulkano-rs/vulkano/issues/1265

> 
> 
> I think I'm hitting a similar issue where I have two dispatch calls to two different compute shaders in one command buffer, where the first one writes to a buffer and the second one reads from it, and there's no pipeline barrier call between the two according to RenderDoc. The code looks like this:
> 
> ```rust
> let layout = self.pipeline.descriptor_set_layout(0).unwrap();
> let set = PersistentDescriptorSet::start(layout.clone())
>     .add_buffer(prev.clone())
>     .unwrap()
>     .add_buffer(curr.clone())
>     .unwrap()
>     .add_buffer(next.clone())
>     .unwrap()
>     .build()
>     .unwrap();
> 
> let vertex_layout = self.vertex_pipeline.descriptor_set_layout(0).unwrap();
> let vertex_set = PersistentDescriptorSet::start(vertex_layout.clone())
>     .add_buffer(next.clone())
>     .unwrap()
>     .add_buffer(self.vertex_buffer.clone())
>     .unwrap()
>     .build()
>     .unwrap();
> 
> let command_buffer =
>     AutoCommandBufferBuilder::new(self.device.clone(), self.queue.family())
>         .unwrap()
>         .dispatch(
>             [SIZE, SIZE, 1],
>             self.pipeline.clone(),
>             set,
>             self.drop.take().unwrap_or((-1., -1.)),
>         )
>         .unwrap()
>         // vulkano doesn't insert a barrier here for some reason?
>         .dispatch(
>             [SIZE, SIZE, 1],
>             self.vertex_pipeline.clone(),
>             vertex_set,
>             (),
>         )
>         .unwrap()
>         .build()
>         .unwrap();
> let future = command_buffer.execute(self.queue.clone()).unwrap();
> future
>     .then_signal_fence_and_flush()
>     .unwrap()
>     .wait(None)
>     .unwrap();
> ```

Currently from looking around the code pertaining to dispatch calls, there doesn't seem to be any resource checks between dispatch calls, therefore no barrier insertions when the user may expect them.

**Comment by SamHSmith** [comment]
I am also facing this issue. My current workaround is to copy the image in question to a junk image which forces a pipeline barrier.

**Comment by SamHSmith** [comment]
@AustinJ235 Is there a timeline on this? If not I would be willing to put some effort into this but would need some hints and pointers to what needs to be done.

**Comment by AustinJ235** [comment]
The code around barrier insertion is pretty complicated. It might be in need of a rethink. The main code you'll be looking at is here: https://github.com/vulkano-rs/vulkano/blob/315f63abe586f7d9e98f86b9fb7436e36abf8804/vulkano/src/command_buffer/synced/base.rs#L477

I don't have any immediate intentions of doing this, so you are to make an attempt. It is probably going to be some for of a hack to get the desired behavior; otherwise, we can just look at reworking this whole part of the code.

**Comment by SamHSmith** [comment]
What would be the easiest way to force a barrier between each and every command? I want to know because as far as I can tell flushing after each command is not solving the problem.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by SamHSmith** [comment]
@AustinJ235 Okay I think I have narrowed down the problem.

1. The Accessmask passed to prev_cmd_resource for the dispatch commands only include the shader_read flag even though I am writing to images from the compute shader.

2. Forcing exclusive to true always inside prev_cmd_resource by `let exclusive = true;` at the top of the function has some effects. When the two dispatch commands are in the same command buffer the synchronization is still broken. But if separated into two separate command buffers that are submitted to the queue after each other it does fix the issue. However without exclusive set to true there is still no synchronization between the two commands in separate command buffers.

**Comment by SamHSmith** [comment]
@AustinJ235 I have given it my best attempt. And I have failed. My gut feeling says that the code needs to be reworked since it's not handling inter command-buffer dependencies very well.

**Comment by AustinJ235** [comment]
I might give this a go later tonight or tomorrow. I am probably going to end up rewriting a large portion of the backend for the command buffers and potentially some of the GpuFuture related things. So there'll need to be a lot of testing from basic usage to full on advance usages before I am comfortable releasing this.

**Comment by AustinJ235** [comment]
Sorry for the late update, but I did look around at the code the next day. There should be already be automatic barrier insertion as it seems to work similar to how to renderpass's. So at this point I think we are looking a bug. I think adding manual barriers would be kinda of a hack/workaround, so I don't think I want to go that route anymore.

**Comment by SamHSmith** [comment]
I absolutely agree that they would be a work around. But if it is a bug like you say how am I supposed to know if barriers are being inserting and how can I insert a barrier manually for testing purposes? Right now the code feels really unwieldy to debug, if their was a way to insert a "blocks everything" barrier I think it would make hunting down the bug easier.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
