### ISSUE TITLE
build_vk_surface should take EventLoopWindowTarget instead of EventLoop

### ISSUE THREAD

**Issue by dbartussek** [vulkano-rs/vulkano#1302]
In winit, `Window::new()`and `WindowBuilder::build()` now take a reference to `EventLoopWindowTarget` instead of `EventLoop`.

`EventLoop` coerces to `EventLoopWindowTarget`, so the current functions work, but do not allow for creation of new windows after `EventLoop::run()` has been called.
 Calling run consumes the `EventLoop` and only hands out an `EventLoopWindowTarget` reference to the event handler.

**Comment by AustinJ235** [comment]
Didn't know you could have multiple windows with winit. I did the change in the mentioned pull request. Also I added an example showing how one might implement multiple windows.
