### ISSUE TITLE
Implement Eq and Hash for buffers and images

### ISSUE THREAD

**Issue by Rua** [vulkano-rs/vulkano#1309]
I would like to have these traits implemented on all buffer and image types in Vulkano. It's often useful to group render batches by texture or buffer. To allow for this, they should be allowed to be used as the key in hashmaps, or inserted into hashsets. These traits should be implemented not just on the concrete buffer and image types, but also ideally on `dyn BufferAccess` and `dyn ImageAccess`, so that these trait objects can also be used in hashable contexts.

I can give implementing this a try, but I'm not sure what would be a suitable source of an equality test/hash. `BufferAccess` and `ImageAccess` both have methods to return an inner unsafe object, which implements `VulkanObject` and thus can give you a raw Vulkan object handle. This seems like it would be suitable, but I'd like to have verification by someone who knows Vulkan better than I do.

**Comment by AustinJ235** [comment]
yes VulkanObject is generally how you do eq, you also have to make sure they are on the same device.
