### ISSUE TITLE
vk_sys::AllocationCallbacks UB due to wrong field types

### ISSUE THREAD

**Issue by Evrey** [vulkano-rs/vulkano#1312]
*   Version of vulkano: `vk-sys v0.5.0`
*   OS: doesn't matter, but Ubuntu 19.10
*   GPU (the selected PhysicalDevice): doesn't matter
*   GPU Driver: doesn't matter
*   Upload of a reasonably minimal complete `main.rs` file that demonstrates the issue: none

# Issue

Hi guys!

So, I'm working with bare `vk-sys` and noticed an error in the definition of the struct [`vk_sys::AllocationCallbacks`](https://docs.rs/vk-sys/0.5.0/vk_sys/struct.AllocationCallbacks.html). The error lies in *both* fields `pfnInternalAllocation` and `pfnInternalFree`.

- Both fields are defined to be pointers to functions returning `*mut c_void` in `vk-sys`. However, neither [`PFN_vkInternalAllocationNotification`](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/PFN_vkInternalAllocationNotification.html) nor [`PFN_vkInternalFreeNotification`](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/PFN_vkInternalFreeNotification.html) are defined to return *anything* in the official docs. On x86_64, the return value register is caller-saved, but this may cause serious faults on other platforms.
- Put another way: Someone blindly following the struct definition enters UB land.
- Both fields are defined to be `fn`s. However, the official docs for [`VkAllocationCallbacks`](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VkAllocationCallbacks.html) state that two cases are valid: Both fields being set to a function pointer, or both fields being set to `ptr::null()`. So, instead of both fields being typed `fn`, they should instead be `Option<fn>`.

Well, that's all for this issue.

Of course this issue will be insta-fixed when https://github.com/vulkano-rs/vulkano/issues/89 is implemented.

**Comment by AustinJ235** [comment]
As vk-sys isn't really suppose to impose any safety, I don't think this is necessary. I think if you are for some reason using these bindings you should be aware of what these functions do.

**Comment by Evrey** [comment]
I'm not sure what this has to do with safety. This is about incorrect API definitions, which apart from being UB worsens Vulkan API ergonomics.

**Comment by Rua** [comment]
vk-sys is not used anymore, so this should be fixed.
