### ISSUE TITLE
Triangle example broken on latest arch on wayland.

### ISSUE THREAD

**Issue by SamHSmith** [vulkano-rs/vulkano#1317]
Recently updated my arch install and now the windows of all vulkano apps are broken. On X they still work but on wayland there is no way to interact with the window bar or resize the window. There are also graphical glitches around the window.

[Link to video](https://youtu.be/G9bHCTnB4Uo)

*   Version of vulkano: latest git
*   OS: Arch Linux
*   GPU (the selected PhysicalDevice): RX 5700 XT
*   GPU Driver: AMDVLK

This is both an issue in version 16 and the latest git.

**Comment by Rua** [comment]
This may be an issue with Winit rather than Vulkano?

**Comment by SamHSmith** [comment]
I guess so although I am not the person to make that call. Since it's wayland you need to render to the window for it to display. I don't know how you would test that.

**Comment by AustinJ235** [comment]
I have replicated the issue. Before the latest arch update it worked now it doesn't. If use the super key and the arrow keys the window responds as expected to move around. But title bar appears to be missing. I don't think this is a vulkano issue. Noteworthy upgrades:
```
mutter (3.34.3-1 -> 3.34.3+14+g59e9b073a-1)
vulkan-icd-loader (1.1.130-1 -> 1.2.132-1)
```

I don't think that `mesa`, `linux`, or driver implemenation `radv` vs `amdvlk` is to blame here as I am using different versions.

**Comment by AustinJ235** [comment]
Downgrading mutter fixes the issue. So this appears to be a mutter issue.

**Comment by SamHSmith** [comment]
I have now opened a mutter issue on [gitlab](https://gitlab.gnome.org/GNOME/mutter/issues/1028) so hopefully they might know whats causing the problem.

**Comment by AustinJ235** [comment]
might want to notify arch that there is an issue with vulkan apps and wayland mutter. Not sure why they decided to ship a git version. Before doing so it wouldn't hurt to check if the behavior is the same with other vulkan apps that dont use xwayland.

**Comment by SamHSmith** [comment]
I can say this is no longer an issue.
