### ISSUE TITLE
Can't build instances: OomError(OutOfHostMemory)

### ISSUE THREAD

**Issue by mkhan45** [vulkano-rs/vulkano#1319]
*   Version of vulkano: 0.16.0
*   OS: Void Linux
*   GPU (the selected PhysicalDevice): none (should be integrated graphics on i7-5600U)
*   GPU Driver: mesa-vulkan-intel
*   Upload of a reasonably minimal complete `main.rs` file that demonstrates the issue: 
```
use vulkano::instance::{Instance, InstanceExtensions};

fn main() {
    let instance = match Instance::new(None, &InstanceExtensions::none(), None) {
        Ok(i) => i,
        Err(err) => panic!("Couldn't build instance: {:?}", err)
    };
}

```
I can't get past this step on my laptop with an iGPU; it always panics. sorry if I missed anything.

**Comment by AustinJ235** [comment]
`vulkano_win::required_extensions()`

**Comment by mkhan45** [comment]
Unfortunately it still doesn't work:
```
use vulkano::instance::Instance;

fn main() {
    let instance = match Instance::new(None, &vulkano_win::required_extensions(), None) {
        Ok(i) => i,
        Err(err) => panic!("Couldn't build instance: {:?}", err)
    };
}
```
```
thread 'main' panicked at 'Couldn't build instance: OomError(OutOfHostMemory)', src/main.rs:6:21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

**Comment by AustinJ235** [comment]
out of host memory is kinda a bit weird. Are you low on memory? I don't have any alive intel cpus to test with so I can't really help much. I would verify that you are on vulkan 1.1 spec for your driver and that your graphics stack is up to date. 

Do you have any issues if you use vulkano 0.15?

**Comment by mkhan45** [comment]
Well I have 8 GB of RAM and I doubt I usually run anything that uses vram so I'd thought that I wasn't just low on memory, but closing everything fixed the problem. Thanks for your help!
