### ISSUE TITLE
IncompatibleDriver -- what now?

### ISSUE THREAD

**Issue by josh2112** [vulkano-rs/vulkano#1325]
*   Version of vulkano: 0.17
*   OS: Windows 10
*   GPU (the selected PhysicalDevice): Radeon RX 580
*   GPU Driver: AMD driver packaging version 18.50 
  ** Vulkan driver version 2.0.68 
  ** Vulkan API version 1.1.96
*   Upload of a reasonably minimal complete `main.rs` file that demonstrates the issue:
```
use vulkano::instance::Instance;
use vulkano::instance::InstanceExtensions;

fn main() {
    let instance = Instance::new(None, &InstanceExtensions::none(), None).expect("failed to create instance");
}
```

# Issue

Although a Vulkan driver is present and functional on my system, running the first lesson on vulkan.rs (creating an instance) fails with `IncompatibleDriver`.  No other information is given.  How do I go about tracking this down?

**Comment by AustinJ235** [comment]
`IncompatibleDriver` is returned when the requested version, which in vulkano case is 1.1.0, is generally to new for the driver installed. Your driver version of 18.50 is pretty old, nearly 2 years at this point, have you considered upgrading to a newer version? Or should I ask is there a reason you are holding back on updating the driver?

**Comment by josh2112** [comment]
Thanks for the response @AustinJ235 !  I was unaware that my driver was so old; the "check for updates" feature said I was up-to-date.  Got the latest driver (19.50 I believe) and all is well.
