### ISSUE TITLE
Update guide to version 0.17 of the API

### ISSUE THREAD

**Issue by croraf** [vulkano-rs/vulkano#1330]
# Template

*   Version of vulkano: 0.17
*   OS: Ubuntu 19.10
*   GPU (the selected PhysicalDevice): TODO
*   GPU Driver: TODO
*   Upload of a reasonably minimal complete `main.rs` file that demonstrates the issue: TODO

# Issue

The guide is written for v0.13. It does not work for 0.17. 

The two things that have changed are:
1.

        CpuAccessibleBuffer::from_iter(device.clone(), BufferUsage::all(), false, data_iter)

which now requires another argument (3rd argument above was added), and 

2.

`PersistentDescriptorSet::start(compute_pipeline.clone(), 0)`

which I cannot manage to set up.

Can you update the guide? Or at least tell me how to fix the second issue.

**Comment by flaghacker** [comment]
The second one now looks more like this:

```
let set_layout = compute_pipeline.layout().descriptor_set_layout(0).unwrap();
PersistentDescriptorSet::start(set_layout.clone())
```

There are up-to-date examples in the `examples` folder of this repository.

**Comment by SuperSamus** [comment]
Shouldn't issues about the website posted [here](https://github.com/vulkano-rs/vulkano-www)?
Also there's already a pull request to update to 0.18 on there.

**Comment by AndrewShen31** [comment]
Also, the author of the guide should continue the remaining section of the WIndowing. It's the most confusing part.

**Comment by louisgjohnson** [comment]
Also the winit examples are quite out of date. I really appreciate the guide though, it was really helpful.

**Comment by AustinJ235** [comment]
Guides should be up to date for 0.18; therefore, I am closing this.
