### ISSUE TITLE
Swapchain::new/with_old_swapchain - awkward usage with Option for previous swapchain

### ISSUE THREAD

**Issue by q3k** [vulkano-rs/vulkano#1333]
# Template

*   Version of vulkano: 0.17.0+

# Issue

In #1268, `Swapchain::new(..., old: Option)` was split into `::new(...) `and `::with_old_swapchain(..., old)`. This change makes usage awkward for library users that already have the previous swapchain in an Option, ie. when using a single codepath for both swapchain creation and recreation.

For example, I have to now do this:

```
    let (chain, images) = match prev.as_ref() {
        None => vs::Swapchain::new(
            surface_binding.device.clone(),
            surface_binding.surface.clone(),
            image_count,
            surface_format.0,
            extent,
            1,
            image_usage,
            sharing,
            capabilities.current_transform,
            vs::CompositeAlpha::Opaque,
            present_mode,
            vs::FullscreenExclusive::Default,
            true,
            vs::ColorSpace::SrgbNonLinear,
        ),
        Some(p) => vs::Swapchain::with_old_swapchain(
            surface_binding.device.clone(),
            surface_binding.surface.clone(),
            image_count,
            surface_format.0,
            extent,
            1,
            image_usage,
            sharing,
            capabilities.current_transform,
            vs::CompositeAlpha::Opaque,
            present_mode,
            vs::FullscreenExclusive::Default,
            true,
            vs::ColorSpace::SrgbNonLinear,
            p.clone(),
        ),
    }.expect("could not create swap chain");
```

I think it would be nice for users to expose the old-style Option-based API, eg. by making `Swapchain::new_inner` public (under a different name). Naturally, users can alleviate this code duplication using macros, but I would think the library should have a low impedance API for this usecase (especially as there's a bunch of existing code/examples/documentation that uses the Option approach).

**Comment by Rua** [comment]
I've been thinking that maybe a `SwapchainBuilder` would be good here. A builder could be constructed fresh, but there would also be another method. When constructing a new swapchain based on the old one, there would be an `into_builder` method on `Swapchain` that consumes the swapchain and turns it into a `SwapchainBuilder`. The builder would own the old swapchain, and have all the properties of the swapchain it was created from by default, which saves having to save/respecify them, but you'd be free to modify them using the standard builder methods. Building it would then use the owned swapchain and the modified settings to make a new one.

**Comment by q3k** [comment]
Sounds good! Do you wanna prototype this in a branch somewhere? I would gladly test/review it.

**Comment by Rua** [comment]
Thanks for the offer! I've put my code at https://github.com/Rua/vulkano/tree/swapchainbuilder. I'm not currently able to make the examples work, because for they seem to always use the latest stable version of Vulkano as the base, and I'd rather not mess with that.

`SwapchainBuilder` has two ways to start building, `new` and `from_existing`. I originally wanted to do it like I described above, with an `into_builder` method on `Swapchain` itself, but because they're normally passed around in an `Arc`, it's not possible to outright consume the swapchain object. I suppose it would be possible for the builder to borrow the old swapchain, but that has its own downsides.

**Comment by AustinJ235** [comment]
Perhaps the examples are not using the best methods available. Personally I don't see any problem with the current methods as is. There are two methods related to recreation that would remove the more advance, cumbersome `with_old_swapchain` method. For the vast majority of use cases the provided methods [`Swapchain.recreate()`](https://docs.rs/vulkano/0.18.0/vulkano/swapchain/struct.Swapchain.html#method.recreate) and [`Swapchain.recreate_with_dimensions()`](https://docs.rs/vulkano/0.18.0/vulkano/swapchain/struct.Swapchain.html#method.recreate_with_dimensions) should handle most recreation needs.

**Comment by AustinJ235** [comment]
ie
```rust
let (mut swapchain, mut swapchain_images) = Swapchain::new(...).unwrap();
let mut recreate = false;

loop {
	if recreate {
		let (new_sc, new_sc_imgs) = swapchain.recreate().unwrap();
		swapchain = new_sc;
		swapchain_images = new_sc_imgs;
		recreate = false;
	}
}
```
