### ISSUE TITLE
using the khr_display InstanceExtension causes a crash

### ISSUE THREAD

**Issue by Raz-Hemo** [vulkano-rs/vulkano#1334]
I want to enumerate available resolutions on my monitor. AFAIK I need to enable the `khr_display` extension, but using it (specifically it - other extensions work) crashes my process with this error:

`error: process didn't exit successfully (exit code: 0xc0000005, STATUS_ACCESS_VIOLATION)`

using a debugger, the culprit is `lib.rs:2745` (way inside the `Instance::new` function).

*   Version of vulkano: 0.18.0
*   OS: Windows 10 version 1903
*   GPU (the selected PhysicalDevice): NVidia GTX 1060
*   GPU Driver: 442.59

Here's how to create an instance and crash this way:
```
let instance = Instance::new(
            None,
            &InstanceExtensions {
                khr_display: true,
                .. vulkano_win::required_extensions()
            },
            None).expect("Failed to create Vulkan instance");
```

**Comment by AustinJ235** [comment]
How does your cpu memory usage look?

**Comment by Rua** [comment]
Does this crash still happen?
