### ISSUE TITLE
Triangle example panics when run in Wine

### ISSUE THREAD

**Issue by Rua** [vulkano-rs/vulkano#1337]
When I compile the triangle example on Windows and then run the binary in Wine, I get this panic:

`thread 'main' panicked at 'called Result::unwrap() on an Err value: LoadingError(MissingEntryPoint("vkGetInstanceProcAddr"))', examples\src\bin\triangle.rs:50:20`

This suggests to me that it loaded the DLL, but it wasn't a valid Vulkan driver. This is strange to me, because Wine is supposed to support Vulkan for a while now, and someone told me they got other Vulkan programs to run in Wine without any problems. So is this an issue with how Vulkano is loading the driver, or is it a Wine problem?

**Comment by FreeFull** [comment]
I have ran into this issue too. I have downloaded and installed the Vulkan SDK in Wine, in case the info from its vulkaninfo tool would be helpful: 
[vulkaninfowine.txt](https://github.com/vulkano-rs/vulkano/files/4408615/vulkaninfowine.txt)

For comparison, here's also the output of vulkaninfo when ran natively on linux: 
[vulkaninfolinux.txt](https://github.com/vulkano-rs/vulkano/files/4408618/vulkaninfolinux.txt)

**Comment by AustinJ235** [comment]
I personally don't see the point of using wine to run vulkano apps. I don't see this as an issue that the vulkano project should be concerned about. Take it up with wine and maybe you can have some luck there. If there is something minor we can change in the this project, sure I might consider it.
