### ISSUE TITLE
Input Attachments Don't Transition Their Image Layouts (and another possible issue related to descriptors and layouts)

### ISSUE THREAD

**Issue by Kimchy101** [vulkano-rs/vulkano#1343]
# My Setup
I have a command buffer that looks something like this: 

```
(various other passes and copy operations have been edited out for brevity)

AutoCommandBufferBuilder::primary_one_time_submit(
render_ctx.logical_device.clone(), render_ctx.queue.family()
).unwrap()
.begin_render_pass(
color_framebuffers[img_num].clone(), false,
vec!([0.0, 0.0, 1.0, 1.0].into(), [0.0, 0.0, 1.0, 1.0].into())
).unwrap()
.draw(
pipeline_color.clone(),
&win_ctx.dynamic_state,
vertex_buffer.clone(),
vox_set.clone(),
pc
).unwrap()
.end_render_pass().unwrap()
// final tonemapping and gamma correction
begin_render_pass(
post_framebuffers[img_num].clone(), false, 
vec!([0.0, 0.0, 1.0, 1.0].into(), vulkano::format::ClearValue::None),
).unwrap()
draw(
pipeline_post.clone(),
&win_ctx.dynamic_state,
vertex_buffer.clone(),
 post_set.clone(), ()
 ).unwrap()
 .end_render_pass().unwrap()
.build().unwrap();
```
In short, I am performing two render passes: one for generating a rendered image and another for making a post-processed image from the original render. The second render pass's shader has a line that looks like this:
`layout (input_attachment_index = 0, set = 0, binding = 0) uniform subpassInput inputColor;`
Here I am reading an attachment image that was used in the previous render pass and using it to generate a color-corrected image. However, the validation layer informs me that the imagelayout was not properly transitioned as indicated by fig. 1. I tried to circumvent this by instead utilizing a storage image, which has a guaranteed general layout, but apparently that didn't work, which is indicated by fig 2.

# Another Potential issue?
Previously, I have negated these issues by not treating the attachment image as an input attachment, but as a regular binding to a descriptor for the second render pass. Here's an alternate line for that shader I mentioned:
`layout (set = 0, binding = 0, rgba32f) uniform image2D inputColor`
This method is not without consequence as indicated by fig. 3, which is outputted when creating a descriptor set from the pipeline layout and attachment. This hasn't been too much of a problem for me because I used to just generate the image descriptor sets before entering a render loop, but now I can't ignore it any longer as I am now dealing with dynamic resolution adjustments.

# Closing Remarks
Bear in mind that the program I am developing still works in run time, albeit with instabilities and uncertainties that I believe to be indicated in the validation layer outputs.
Regardless, I would be happy to hear if someone could indicate if this whole issue has a fix, if the issue is a clear fault of the api, or if I am just incompetently misusing vulkan, which wouldn't be surprising seeing how this is my first project involving a graphics API.

# Validation Layer Errors
Fig. 1
```
VUID-VkDescriptorImageInfo-imageLayout-00344(ERROR / SPEC): msgNum: 0 - vkCmdDraw(): Cannot use VkImage 0x42bf70000000032[] (layer=0 mip=0) with specific layout VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL that doesn't match the previous known layout VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL. The Vulkan spec states: imageLayout must match the actual VkImageLayout of each subresource accessible from imageView at the time this descriptor is accessed as defined by the image layout matching rules (https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VUID-VkDescriptorImageInfo-imageLayout-00344)
    Objects: 1
        [0] 0x216f23003e0, type: 6, name: NULL
UNASSIGNED-CoreValidation-DrawState-DescriptorSetNotUpdated(ERROR / SPEC): msgNum: 0 - VkDescriptorSet 0x2f99810000000044[] bound as set #0 encountered the following validation error at vkCmdDraw() time: Image layout specified at vkUpdateDescriptorSet* or vkCmdPushDescriptorSet* time doesn't match actual image layout at time descriptor is used. See previous error callback for specific details.

```
Fig. 2
```
[0] 0x2f99810000000044, type: 23, name: NULL
VUID-VkDescriptorImageInfo-imageLayout-00344(ERROR / SPEC): msgNum: 0 - vkCmdDraw(): Cannot use VkImage 0x42bf70000000032[] (layer=0 mip=0) with specific layout VK_IMAGE_LAYOUT_GENERAL that doesn't match the previous known layout VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL. The Vulkan spec states: imageLayout must match the actual VkImageLayout of each subresource accessible from imageView at the time this descriptor is accessed as defined by the image layout matching rules (https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VUID-VkDescriptorImageInfo-imageLayout-00344)
    Objects: 1
        [0] 0x138cc57dab0, type: 6, name: NULL
UNASSIGNED-CoreValidation-DrawState-DescriptorSetNotUpdated(ERROR / SPEC): msgNum: 0 - VkDescriptorSet 0x2f99810000000044[] bound as set #0 encountered the following validation error at vkCmdDraw() time: Image layout specified at vkUpdateDescriptorSet* or vkCmdPushDescriptorSet* time doesn't match actual image layout at time descriptor is used. See previous error callback for specific details.
```
Fig. 3
```
UNASSIGNED-CoreValidation-DrawState-InvalidImageView(ERROR / SPEC): msgNum: 0 - vkUpdateDescriptorSets() failed write update validation for VkDescriptorSet 0x2f99810000000044[] with error: Write update to VkDescriptorSet VkDescriptorSet 0x2f99810000000044[] allocated with VkDescriptorSetLayout VkDescriptorSetLayout 0x7876fe000000001b[] binding 
#0 failed with error message: Attempted write update to image descriptor failed due to: ImageView (VkImageView 0x7e7cff000000003a[]) of VK_DESCRIPTOR_TYPE_STORAGE_IMAGE type is being updated with layout VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL but according to spec section 13.1 Descriptor Types, 'Load and store operations on storage images can 
only be done on images in VK_IMAGE_LAYOUT_GENERAL layout.'.
    Objects: 1
        [0] 0x2f99810000000044, type: 23, name: NULL
```

**Comment by Kimchy101** [comment]
Update:
I've kinda given up on trying to further test and solve this issue, and I am now just using a number of alternative solutions that evade some of the dead ends brought up here.

If anyone is having similar issues brought up in this post, I have some advice that may help you.

1. If you're getting the error listed in fig 3, try replacing your image2Ds with samplers. I have no idea why, but it somehow fixed my descriptor set initialization. 
2. Input attachments, at least from what information I can gather, are used for subpasses. I haven't tested this thoroughly, but I am guessing that you shouldn't use input attachments to easily use image data from previous whole render passes. Instead, use samplers as previously said.
3. For some ungodly and lovecraftian reason, copying images from a framebuffer output to a shader sampler input and then redoing the renderpass that generates the framebuffer output occasionally generates errors when recreating the descriptor sets, and I mean **occasionally**. Seriously, I have had times where the descriptor sets are recreated hundreds of times, and nothing happens. Then, I have the descriptor sets recreated like 4 times, and I immediately get a panic. Do yourself a favor and create two framebuffers and two descriptor sets that alternate render targets and samplers for two images and build your command buffer with those two render passes. This avoids copying images altogether. If you do this, you will avoid hours of cosmic horror.

**Comment by AustinJ235** [comment]
Yeah I think input attachments are something do with passing other images around within a renderpass, but I am not completely sure. I have always bound the previous results to a set. Curious though as you stated having issues with that. Are you use the persistent variant, are the pool? The pool is ideal when you need to recreate them often with the same layout.

**Comment by Kimchy101** [comment]
> Yeah I think input attachments are something do with passing other images around within a renderpass, but I am not completely sure. I have always bound the previous results to a set. Curious though as you stated having issues with that. Are you use the persistent variant, are the pool? The pool is ideal when you need to recreate them often with the same layout.

I was passing images between render passes rather than within them. I expect that this was the issue I had, but I am not sure, and I haven't tested it. For now I am shelving the idea of using them until multi-subpass renderpasses are a concern.

Also, I now use fixed sized descriptor set pools instead of just using the persistent descriptor set. Again, I have no idea as to how this changes things in relation to the issue because I haven't tested it, but I am going with the common consensus for now.

**Comment by AustinJ235** [comment]
Previously there was allocation issues with the persistent variant. They are not intended to be recreated every frame, but it shouldn't cause issues. There should be a notable performance gain with the pools also.
