### ISSUE TITLE
Outdated documentation

### ISSUE THREAD

**Issue by Ruannilton** [vulkano-rs/vulkano#1348]
In the topic Device Creation, the following form of creation is instructed:
```
let (device, mut queues) = {
    Device::new(physical, &Features::none(), &DeviceExtensions::none(),
                [(queue_family, 0.5)].iter().cloned()).expect("failed to create device")
};
```

However in the topic Compute pipelines it is necessary that the device contains the extension khr_storage_buffer_storage_class, being as follows:
```
let (device, mut queues) = Device::new(
        physical,
        &Features::none(),
        &DeviceExtensions {
            khr_storage_buffer_storage_class: true,
            ..DeviceExtensions::none()
        },
        [(queue_family, 0.5)].iter().cloned(),
    ).expect("failed to create device");
```
But this is not reported in the documentation

**Comment by WSeegers** [comment]
I see it was fixed here https://github.com/vulkano-rs/vulkano-www/pull/74.

**Comment by AustinJ235** [comment]
As per the last comment this appears to be resolved.
