### ISSUE TITLE
Shader macro not recompiling on change

### ISSUE THREAD

**Issue by WSeegers** [vulkano-rs/vulkano#1349]
```
[dependencies]
vulkano = "0.18"
vulkano-shaders = "0.18"
```

# Issue
When compiling shaders using the path.

```
vulkano_shaders::shader! {
    ty: "compute",
    path: "somepath/someshder.glsl"
}
```
The compilation seems to be cached and does not detect changes to the file. This results in shaders not being updated in subsequent runs.

The same is does not happen when using `src: "some glsl"`.

**Comment by AustinJ235** [comment]
I recall some previous issues about this. But if you use the `include!` macro just to have the compiler watch it that seems to be a workaround.

**Comment by SamHSmith** [comment]
@WSeegers Surely this is a rust issue and not a vulkano one? As in it is up to the rust compiler and cargo to recompile the file at which point you shader gets recompiled.

**Comment by AustinJ235** [comment]
I think there is something that we can hint to the compiler but it might be only available in the build.rs

⁣Get BlueMail for Android ​

**Comment by SamHSmith** [comment]
I'm not so sure. If the compilation has been done and none of the rust source code has changed then a cargo run will completely side-step the compilation stage and run the executable it compiled last time. Fixing this would involve loading and compiling the shaders at runtime. Which may be a feature that someone wants to implement, dynamic runtime spirv compilation. If it isn't already implemented upstream.

**Comment by est31** [comment]
cc https://github.com/rust-lang/rust/issues/73921 and #890

**Comment by Rua** [comment]
I believe this is now fixed?
