### ISSUE TITLE
how to support Vulkan 1.2 with vulkano?

### ISSUE THREAD

**Issue by imkow** [vulkano-rs/vulkano#1351]
ATS. Thx.

**Comment by AustinJ235** [comment]
You'd have to fork vulkano and modify this file here: https://github.com/vulkano-rs/vulkano/blob/48109761a852b4ae7fb8d4a9ba819be3c77ad8ca/vulkano/src/instance/instance.rs#L225

I don't forsee opening this as using newer versions of vulkan make break some functionality of vulkano. Well probably update in the near future, but it is 1.1 for the time being. shaderc may also lack support for this version, although I am not sure about that.

**Comment by Rua** [comment]
Is Vulkano capable of supporting multiple versions?

**Comment by AustinJ235** [comment]
I think we could allow specifying it but as an unsafe function. If I recall correctly there was a couple of things that broke from 1.0 to 1.1. But that may have been just the additional extension needed the storage buffer one.

⁣Get BlueMail for Android ​

**Comment by Rua** [comment]
Vulkano now supports 1.3, although not all features are implemented yet.
