### ISSUE TITLE
Ability to read images

### ISSUE THREAD

**Issue by Rua** [vulkano-rs/vulkano#1356]
Vulkano does not appear to provide the tools to read images from the GPU in safe code currently. All of the safe image types available in Vulkano use optimal tiling rather than linear and have no way to change this. If you were to copy such an image to a `CpuAccessibleBuffer`, you'd just get garbage. In order to create a linear-tiled image and retrieve the `LinearLayout` needed to interpret the pixel data properly, you have to fall back to `UnsafeImage` with all of its pitfalls. It would be great if a safe alternative were added to Vulkano. Perhaps in the form of a `CpuAccessibleImage`?

**Comment by SamHSmith** [comment]
@Rua Not possible in vulkan. Therefore not possible in vulkano. Images on the gpu are stored in an opaque format. It is not our business how they are stored. The answer is that you do not get garbage data. When you ask vulkan to copy from an image into a buffer the format gets converted to linear form. The data you end up with in the buffer is in perfectly readable form. Ex
[coordinate x, coordinate y]
[0, 0] [1, 0] [2, 0] [0, 1] [1, 1] [2, 1] [0, 2] [1, 2] [2, 2]

Does that answer your questions?

**Comment by Rua** [comment]
It does, and I didn't realise that copying an image to a buffer converts it. Could that be added to the documentation?

**Comment by SamHSmith** [comment]
I think it's definatly implied in the compute shader [example](https://vulkano.rs/guide/image-export). That's a good idea. I'm on it.

**Comment by SamHSmith** [comment]
Here's the [pr](https://github.com/vulkano-rs/vulkano/pull/1361)

**Comment by SamHSmith** [comment]
@Rua The PR got merged. Can this issue be considered closed?
