### ISSUE TITLE
Manual pipeline barrier in AutoCommandBuffer for debugging and workarounds

### ISSUE THREAD

**Issue by SamHSmith** [vulkano-rs/vulkano#1360]
Would it be possible to add the ability to force a pipeline barrier in an autocommandbuffer. Currently in issues such as [this](https://github.com/vulkano-rs/vulkano/issues/1297) one must play around with other commands to try force a barrier in the case vulkano isn't insterting one automatically.

Would be nice with buffer_barrier and image_barrier functions for debugging purposes.

**Comment by Rua** [comment]
The proposal in #1917 would allow this, once it is implemented.
