### ISSUE TITLE
Allowing the user to specify a target Vulkan spec.

### ISSUE THREAD

**Issue by AustinJ235** [vulkano-rs/vulkano#1365]
There does seem to be some interest in allowing the user to specify their own version they want (See https://github.com/vulkano-rs/vulkano/issues/1351). This would allow the user to upgrade the spec without having to wait on a vulkano release. Current we target `1.1.0` there may be future patch version that is useful the user may want to target. This does induce some problems though if a minor version would be breaking. Say an extension that we use gets deprecated in a version that the user specifies.

Currently a user can upgrade the spec used by modifying these locations:
https://github.com/vulkano-rs/vulkano/blob/4e3d38ac5b0bfb861a35355c99ca9e58e790d087/vulkano/src/instance/instance.rs#L239 https://github.com/vulkano-rs/vulkano/blob/4e3d38ac5b0bfb861a35355c99ca9e58e790d087/vulkano-shaders/src/codegen.rs#L155

The first location would be fairly simple to allow user to specify the version; however, the second location isn't so primitive. There is currently no way to get the version from the instance as we don't have access to it. We could add another field to the `vulkano_shader!` macro that could be optional and specify the spec to target. For instance:

```rust
mod fs {
	shader!{
		target_vk_spec: 1.2,
		ty: "fragment",
		src: "...."
	}
}
```

**Comment by Rua** [comment]
Should now be implemented by #1569.
