### ISSUE TITLE
How to extract this code in teapot example into a function?

### ISSUE THREAD

**Issue by zhouhang95** [vulkano-rs/vulkano#1366]
I want extract below code to fn?
But I don't know what the correct type of return value.

https://github.com/vulkano-rs/vulkano/blob/master/examples/src/bin/teapot/main.rs
Line 197
```
let uniform_buffer_subbuffer = {
    let elapsed = rotation_start.elapsed();
    let rotation =
        elapsed.as_secs() as f64 + elapsed.subsec_nanos() as f64 / 1_000_000_000.0;
    let rotation = Matrix3::from_angle_y(Rad(rotation as f32));

    // note: this teapot was meant for OpenGL where the origin is at the lower left
    //       instead the origin is at the upper left in Vulkan, so we reverse the Y axis
    let aspect_ratio = dimensions[0] as f32 / dimensions[1] as f32;
    let proj = cgmath::perspective(
        Rad(std::f32::consts::FRAC_PI_2),
        aspect_ratio,
        0.01,
        100.0,
    );
    let view = Matrix4::look_at(
        Point3::new(0.3, 0.3, 1.0),
        Point3::new(0.0, 0.0, 0.0),
        Vector3::new(0.0, -1.0, 0.0),
    );
    let scale = Matrix4::from_scale(0.01);

    let uniform_data = vs::ty::Data {
        world: Matrix4::from(rotation).into(),
        view: (view * scale).into(),
        proj: proj.into(),
    };

    uniform_buffer.next(uniform_data).unwrap()
};

let layout = pipeline.descriptor_set_layout(0).unwrap();
let set = Arc::new(
    PersistentDescriptorSet::start(layout.clone())
        .add_buffer(uniform_buffer_subbuffer)
        .unwrap()
        .build()
        .unwrap(),
);
```

**Comment by jeffw387** [comment]
Are you trying to return the layout and the set? Or just the set?

If I remember right, the set can be referred to as `Arc<dyn DescriptorSet>` where 'DescriptorSet' is `vulkano::descriptor::descriptor_set::DescriptorSet`. I can't remember for sure, but it's possible you need to append `+ Send + Sync` to `DescriptorSet`

**Comment by zhouhang95** [comment]
> Are you trying to return the layout and the set? Or just the set?
> 
> If I remember right, the set can be referred to as `Arc<dyn DescriptorSet>` where 'DescriptorSet' is `vulkano::descriptor::descriptor_set::DescriptorSet`. I can't remember for sure, but it's possible you need to append `+ Send + Sync` to `DescriptorSet`

Thank you!
