### ISSUE TITLE
Versatile Error type

### ISSUE THREAD

**Issue by nifker** [vulkano-rs/vulkano#1369]
What about an error type which sums up all other error types and also implements "From < SubVulkanoError > for VulkanoError" for all of them?

Like in this example:
pub enum VulkanoError{
  A(VulkanoErrorA),
  B(VulkanoErrorB),
  ..
  Z(VulkanoErrorZ)
}

**Comment by nifker** [comment]
I improved the description of this now. Any opinion on this? @AustinJ235

**Comment by AustinJ235** [comment]
I don't know if this is really needed.

**Comment by nifker** [comment]
@AustinJ235 I thought this might make it easier for application to use different errors types without caring about packing them themselves together in a new enum.

**Comment by Rua** [comment]
I have been thinking of taking all the different Vulkan runtime error types and unifying them into a single enum that any function can return. This will mean that the enum will include errors that only certain functions can return, so the user can no longer tell from looking at the error type which errors a particular function can return. However, there are a few reasons for doing this anyway:
- It's a lot simpler, a lot fewer error types are needed and much less duplication.
- Vulkan implementations are known to sometimes return errors that are not mentioned in the spec as one of the allowed error types for that function. In those cases, the current way Vulkano handles these is just by panicking, which is not helpful.
- An analogy is with [`std::io::ErrorKind`](https://doc.rust-lang.org/std/io/enum.ErrorKind.html) which also covers all possible errors regardless of whether a function will return them or not.

**Comment by Rua** [comment]
The beginning of this is now implemented with #1952, which adds a single generic error type that is applicable to all functions that can return Vulkan runtime errors. Existing error types should be adjusted in the coming time to incorporate it.
