### ISSUE TITLE
'windows-msvc Specific Setup' leads to compilation error of compute example.

### ISSUE THREAD

**Issue by JonathanWoollett-Light** [vulkano-rs/vulkano#1370]
# Details

*   Version of vulkano: 0.18.0
*   OS: Windows
*   GPU (the selected PhysicalDevice): AMD Radeon 7
*   GPU Driver: https://www.amd.com/en/support/kb/release-notes/rn-rad-win-20-4-2
*   Minimal reproducible example: [vulkano-test.zip](https://github.com/vulkano-rs/vulkano/files/4707742/vulkano-test.zip)

# Issue

Upon compilation of the project (see minimal reproducible example) using `cargo run` the compilation errors occur:

![image](https://user-images.githubusercontent.com/16856679/83354175-3aa72d80-a34f-11ea-96d5-8dc82f2b32ad.png)

Clicking 'OK' leads to:

![image](https://user-images.githubusercontent.com/16856679/83354242-4db9fd80-a34f-11ea-88c7-6c22d3a0652d.png)

And a continuous series of said errors until it exits (https://pastebin.com/cMYPNB9W):

![image](https://user-images.githubusercontent.com/16856679/83354269-65918180-a34f-11ea-8b6e-403628a36784.png)
 
# Installation
To illustrate steps taken in installation:

## 1: Rust toolchain:
```
C:\Users\jonat>rustup show
Default host: x86_64-pc-windows-msvc
rustup home:  C:\Users\jonat\.rustup

installed toolchains
--------------------

stable-x86_64-pc-windows-gnu
stable-x86_64-pc-windows-msvc (default)

active toolchain
----------------

stable-x86_64-pc-windows-msvc (default)
rustc 1.41.1 (f3e1a954d 2020-02-24)
```

## 2: Build tools for visual studio 2017 installed:

![image](https://user-images.githubusercontent.com/16856679/83354388-42b39d00-a350-11ea-8499-e11c0416816d.png)

## 3+4: MSYS2 installed and given command ran:

```
jonat@DESKTOP-JFC6RHS MSYS ~
$ pacman --noconfirm -Syu mingw-w64-x86_64-cmake mingw-w64-x86_64-python2 mingw-w64-x86_64-ninja:: Synchronising package databases...
 mingw32 is up to date
 mingw64 is up to date
 msys is up to date
warning: mingw-w64-x86_64-cmake-3.17.3-1 is up to date -- reinstalling
warning: mingw-w64-x86_64-python2-2.7.18-1 is up to date -- reinstalling
warning: mingw-w64-x86_64-ninja-1.10.0-1 is up to date -- reinstalling
:: Starting core system upgrade...
 there is nothing to do
:: Starting full system upgrade...
resolving dependencies...
looking for conflicting packages...

Packages (3) mingw-w64-x86_64-cmake-3.17.3-1  mingw-w64-x86_64-ninja-1.10.0-1
             mingw-w64-x86_64-python2-2.7.18-1

Total Installed Size:  133.02 MiB
Net Upgrade Size:        0.00 MiB

:: Proceed with installation? [Y/n]
(3/3) checking keys in keyring                                  [#################################] 100%
(3/3) checking package integrity                                [#################################] 100%
(3/3) loading package files                                     [#################################] 100%
(3/3) checking for file conflicts                               [#################################] 100%
(3/3) checking available disk space                             [#################################] 100%
:: Processing package changes...
(1/3) reinstalling mingw-w64-x86_64-cmake                       [#################################] 100%
(2/3) reinstalling mingw-w64-x86_64-python2                     [#################################] 100%
(3/3) reinstalling mingw-w64-x86_64-ninja                       [#################################] 100%

jonat@DESKTOP-JFC6RHS MSYS ~
$
```

## 5: MSYS2 MINGW64 binary path added to `path` variable:

![image](https://user-images.githubusercontent.com/16856679/83354509-13516000-a351-11ea-8d7b-85dc2c470384.png)
 

### So, what have I done wrong?

**Comment by AustinJ235** [comment]
I would definitely lean toward something be wrong in the setup of your environment. I would suggest using build tools 2019, and installing cmake, python3, and ninja from their dedicated installers rather than through mingw.

**Comment by Rua** [comment]
It seems that the problem is occurring when it tries to build ShaderC. You could also opt to install a pre-built version of the ShaderC library, so that it can skip that step. It makes future compilation faster on your system, too.

**Comment by JonathanWoollett-Light** [comment]
> It seems that the problem is occurring when it tries to build ShaderC. You could also opt to install a pre-built version of the ShaderC library, so that it can skip that step. It makes future compilation faster on your system, too.

Haven't included libraries not using Cargo in Rust yet, how would I do this?

**Comment by Rua** [comment]
You can download your version of the library [here](https://github.com/google/shaderc/blob/master/downloads.md). Then, you need to put it somewhere and set the `SHADERC_LIB_DIR` environment variable to the full path of the `lib` directory (e.g. `C:\shaderc\lib`). If it's done correctly, Vulkano will use that library instead of trying to compile its own, and you will presumably not get any error.

**Comment by JonathanWoollett-Light** [comment]
I can't seem to get it to work/find the correct directory for setting `SHADERC_LIB_DIR` to.

I initially tried `SHADERC_LIB_DIR = install\include\shaderc` and removed `vulkano-shaders = "0.18.0"` from `Cargo.toml`.

I tried setting `SHADERC_LIB_DIR` to a couple other things but none worked.

What should I set `SHADERC_LIB_DIR` to and what change(s) if any do I need to make to `Cargo.toml` or the code?

**Comment by Rua** [comment]
You want `install\lib`, the place where the library itself actually is. It needs to be an absolute path, so including the drive name. And you'll still need vulkano-shaders in your project, since that's what invokes the library.

**Comment by JonathanWoollett-Light** [comment]
I get the same errors, I think it is still trying to compile shaderc itself.

Variable set (rest of project is same as in the initial `.zip`):
![image](https://user-images.githubusercontent.com/16856679/83684182-815e8700-a5de-11ea-943e-548d79617f2b.png)

Apologies if this is tedious, I really have no idea what I'm doing here.

**Comment by JonathanWoollett-Light** [comment]
(@Rua  Just thought I'd throw you a notification in case you might've missed my recent comment, apologies if you didn't and this is just bothering)

**Comment by Rua** [comment]
I'm just not sure where to go from here, so I figured I'd wait for others to reply.

**Comment by AustinJ235** [comment]
I have no issues on windows msvc following this procedure when I reinstall windows about ever 3 months. 
- Install the latest build tools
- Install cmake from [direct link](https://github.com/Kitware/CMake/releases/download/v3.17.3/cmake-3.17.3-win64-x64.msi). Make sure to check option to add to PATH.
- Install python3 from [direct link](https://www.python.org/ftp/python/3.8.3/python-3.8.3-amd64.exe). Make sure to check option to add to PATH. Check optional path length tweak. (Probably not required, but I do it anyway)
- Install git [direct link](https://github.com/git-for-windows/git/releases/download/v2.27.0.windows.1/Git-2.27.0-64-bit.exe). Generally you need git on your system for other things. I use their bash for all compilation.
- Download/extract ninja [direct link](https://github.com/ninja-build/ninja/releases/download/v1.10.0/ninja-win.zip). I generally just slap it in the Windows folder, it is bad practice, but I am too lazy to add another PATH variable.

This works generally without fail for me. I don't touch any of the mingw stuff. With that all done I just open a git bash in my project folder and run cargo to build.

**Comment by JonathanWoollett-Light** [comment]
@AustinJ235  Done this, still get same errors.

Example of everything installed:

![image](https://user-images.githubusercontent.com/16856679/83912470-d1b42100-a765-11ea-9b43-b91f9d94e977.png)

(and got both VS 2017 and VS 2019 installed which with their respective build tools)

**Comment by AustinJ235** [comment]
Would you be able to provide the log from building shaderc out of the target directory. Also are you able to compile shaderc by itself. If you can't compile it by itself then you might have better luck opening an issue over there as they might know these kind of quirks better.

**Comment by JonathanWoollett-Light** [comment]
@AustinJ235 

> the log from building shaderc out of the target directory.

I'm not familiar, how would I get this?

**Comment by AustinJ235** [comment]
I think there may be a log in the folder `target/debug/build/shaderc-sys-xxxxxxxx`

**Comment by JonathanWoollett-Light** [comment]
@AustinJ235  There 2 folders for `target/debug/build/shaderc-sys-xxxxxxxx` ([shaderc-sys-6af8000a76e5421d](https://github.com/vulkano-rs/vulkano/files/4738237/shaderc-sys-6af8000a76e5421d.zip)
and [shaderc-sys-6379ac77334259e4](https://github.com/vulkano-rs/vulkano/files/4738240/shaderc-sys-6379ac77334259e4.zip)). Neither of these seems to contain a log file.

**Comment by AustinJ235** [comment]
Are you able to build https://github.com/google/shaderc-rs independently? If not I would suggest maybe opening an issue there as I am out of ideas.

**Comment by AustinJ235** [comment]
I did another fresh install of windows as window's bricked itself while I was oc'ing. Following my procedure I don't have any issues with setup and building.

**Comment by JonathanWoollett-Light** [comment]
> Are you able to build https://github.com/google/shaderc-rs independently? If not I would suggest maybe opening an issue there as I am out of ideas.

In cloning the `https://github.com/google/shaderc-rs` and running `cargo build` on both the `shaderc-sys` and `shaderc-rs` neither work

Resulting in these errors respectively:

#### `shaderc-sys` errors:

![image](https://user-images.githubusercontent.com/16856679/83978592-926e0780-a900-11ea-910b-de538967e7bb.png)


#### `shaderc-rs` errors:

![image](https://user-images.githubusercontent.com/16856679/83978588-7f5b3780-a900-11ea-81da-b89354346035.png)

Is this something I should open an issue about on the shaderc-rs repo?

**Comment by JonathanWoollett-Light** [comment]
@AustinJ235 

> Are you able to build https://github.com/google/shaderc-rs independently? If not I would suggest maybe opening an issue there as I am out of ideas.

In cloning the `https://github.com/google/shaderc-rs` and running `cargo build` on both the `shaderc-sys` and `shaderc-rs` neither work

Resulting in these errors respectively:

#### `shaderc-sys` errors:

![image](https://user-images.githubusercontent.com/16856679/83978592-926e0780-a900-11ea-910b-de538967e7bb.png)


#### `shaderc-rs` errors:

![image](https://user-images.githubusercontent.com/16856679/83978588-7f5b3780-a900-11ea-81da-b89354346035.png)

Is this something I should open an issue about on the shaderc-rs repo?

**Comment by JonathanWoollett-Light** [comment]
### An update

The results of compilation have changed and I have no idea why. I haven't manually changed anything.

![image](https://user-images.githubusercontent.com/16856679/84455170-89f53400-ac54-11ea-94b0-929b0c93d331.png)

(Image cropped most the result, see hastebin link)

New result: https://hastebin.com/qafomumeti.php

New result with `--verbose`: https://hastebin.com/ojomupeyuv.js

This seems like a step forward, although as before, I have no real idea what I could do to fix this.

**Comment by JonathanWoollett-Light** [comment]
### Another update

So I reset my pc.
Reinstalled everything.
Now adding a couple missing `use`s and running `cargo run` I get:

```
C:\Users\jonat\Projects\vulkano-test>cargo run
   Compiling autocfg v1.0.0
   Compiling lazy_static v1.4.0
   Compiling cfg-if v0.1.10
   Compiling maybe-uninit v2.0.0
   Compiling libc v0.2.71
   Compiling cc v1.0.54
   Compiling proc-macro2 v1.0.17
   Compiling scopeguard v1.1.0
   Compiling unicode-xid v0.2.0
   Compiling syn v1.0.29
   Compiling vulkano v0.18.0
   Compiling smallvec v1.4.0
   Compiling vk-sys v0.5.1
   Compiling half v1.6.0
   Compiling fnv v1.0.7
   Compiling crossbeam-utils v0.7.2
   Compiling memoffset v0.5.4
   Compiling crossbeam-epoch v0.8.2
   Compiling shared_library v0.1.9
   Compiling cmake v0.1.44
   Compiling quote v1.0.6
   Compiling crossbeam-queue v0.2.2
   Compiling crossbeam-channel v0.4.2
   Compiling shaderc-sys v0.6.2
   Compiling crossbeam-deque v0.7.3
   Compiling crossbeam v0.7.3
   Compiling shaderc v0.6.2
   Compiling vulkano-shaders v0.18.0
   Compiling vulkano-test v0.1.0 (C:\Users\jonat\Projects\vulkano-test)
    Finished dev [unoptimized + debuginfo] target(s) in 1m 13s
     Running `target\debug\vulkano-test.exe`
Hello, world!
Physical devices:
         PhysicalDevice { instance: <Vulkan instance 1773064021968>, device: 0 }
Queues families:
         1 queue(s)      Supports graphics: true         Support compute: true
         2 queue(s)      Supports graphics: false        Support compute: true
         2 queue(s)      Supports graphics: false        Support compute: false
thread 'main' panicked at 'Device extension "khr_storage_buffer_storage_class" required', src\main.rs:117:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: process didn't exit successfully: `target\debug\vulkano-test.exe` (exit code: 101)

C:\Users\jonat\Projects\vulkano-test>
```
Slightly changed project files: [vulkano-test.zip](https://github.com/vulkano-rs/vulkano/files/4775898/vulkano-test.zip)

Got no idea what `'Device extension "khr_storage_buffer_storage_class" required'` means, but atleast it's progress.

**Comment by JonathanWoollett-Light** [comment]
Updated to using `vulkan="0.19.0"` error remains.

**Comment by AustinJ235** [comment]
You need to load that extension when you create the device.
```rust
DeviceExtensions {
    khr_storage_buffer_storage_class: true,
    .. DeviceExtensions::none()
}
```

**Comment by JonathanWoollett-Light** [comment]
@AustinJ235  I'm not sure where you meant to put that code, where do I put this?

**Comment by AustinJ235** [comment]
It is a parameter in the method [`Device::new()`](https://docs.rs/vulkano/0.19.0/vulkano/device/struct.Device.html#method.new).

**Comment by JonathanWoollett-Light** [comment]
@AustinJ235  Okay, that seems to have worked (finaly!). Thank you 👍 .

Do you know of an explanation of why `DeviceExtensions` is needed?

Also, is the tutorial from http://vulkano.rs/guide/device-creation wrong here then since it doesn't have this?

**Comment by AustinJ235** [comment]
The extension isn't always needed. Unless I have the website incorrect, but I don't think it is needed there.

**Comment by JonathanWoollett-Light** [comment]
@AustinJ235  When is it needed?
