### ISSUE TITLE
Is pass-by-move in AutoCommandBufferBuilder really practical?

### ISSUE THREAD

**Issue by Rua** [vulkano-rs/vulkano#1371]
Being able to chain method calls, and end with a final `build`, is presumably the reason for passing `self` by move in the methods of `AutoCommandBufferBuilder`, like it is with other builder-types. But in practice, I find that it's more of a hindrance than a help in this case.

The builder pattern works well if you are building the entire object in one go, but with a command buffer I find it quite common to add commands to the builder in different spread-out parts of a function, which means I have to assign a new variable each time I do so. Adding new commands to the builder in a loop is even more awkward, as you have to put it in an `Option` and then `take()` it each time and put the result back in. Passing it to functions is also impractical as you have to return it back to the caller.

To me, this is a bad fit for the builder pattern. Yes, being able to chain method calls is convenient, but the ways in which I typically use `AutoCommandBufferBuilder`, and I presume others do too, makes it a net convenience loss. I think it would be more useful to have the methods accept `&mut self` instead of `self`. `SyncCommandBufferBuilder` already works this way, too.

**Comment by AustinJ235** [comment]
I think this would probably be a good switch. I don't think this would break the current style either would it if we made it so it took `&mut self` and return `&mut self` I think rust is smart enough now to know that if we chain that together and then use `self` for the build it work. Correct me if I am wrong, but either way for anything aside from basic use cases, this would be an improvement for sure.
