### ISSUE TITLE
A bind-based alternative API for AutoCommandBufferBuilder?

### ISSUE THREAD

**Issue by Rua** [vulkano-rs/vulkano#1377]
Another ergonomics gripe I've been running into recently. Whenever you issue a draw call, you have to give the entire draw state, and this means that wherever draw calls are being issued, you have to have all this state on hand, and have to pass it around everywhere. Even if the state never actually changes. This seems slightly odd when you know that `AutoCommandBufferBuilder` actually remembers the previous state, and only binds what differs in each call. It only needs all that state for comparison purposes, not for binding.

I think it would be more ergonomic if the API of draw calls were changed, so that state is bound before the call, and the draw call uses the currently-bound state, like it is in `SyncCommandBufferBuilder` and raw Vulkan. It would still check the current state before drawing (`check_descriptor_sets_validity` and friends). `StateCacher` would be run when bind calls are made, and the bind would be skipped if already bound. So you'd still get all of the benefits.

I can see about making a PR for this, but I wanted to get feedback first. Especially as this is yet another breaking change.

**Comment by AustinJ235** [comment]
I don't know if I'd see the benefit of this too much. It would add complexity on vulkano part possibility and generally speaking the resources are stored together. You can take all the resources of a renderpass and store with within a struct to make passing them around easier if you need to do so.

**Comment by Rua** [comment]
That's what I ended up doing, but I wondered if it would be possible to avoid doing that.

**Comment by Rua** [comment]
This is implemented by #1684, so closing this.
