### ISSUE TITLE
How to create Instance, Device, CommandBuffer from raw pointers

### ISSUE THREAD

**Issue by lehmanju** [vulkano-rs/vulkano#1384]
We want to use vulkano in a Qt application but as Qt already provides an instance, device and commandbuffer object, we cannot create additional objects in vulkano. Instead it would be necessary to use the objects provided by Qt. Additionally, I have never worked with Vulkan before, so I don't know whether there is another way. Maybe it's also possible to use a second Vulkan instance and somehow expose that to Qt? There are some raw pointer getter functions after all.

Thanks in advance!

**Comment by AustinJ235** [comment]
Look at the [`with_loader`](https://docs.rs/vulkano/0.19.0/vulkano/instance/struct.Instance.html#method.with_loader) method from [`Instance`](https://docs.rs/vulkano/0.19.0/vulkano/instance/struct.Instance.html). For the `loader` param the [`FunctionPointers`](https://docs.rs/vulkano/0.19.0/vulkano/instance/loader/struct.FunctionPointers.html) struct is needed. You can create this via the [`new`](https://docs.rs/vulkano/0.19.0/vulkano/instance/loader/struct.FunctionPointers.html#method.new) method on that struct. That method takes anything which implements the [`Loader`](https://docs.rs/vulkano/0.19.0/vulkano/instance/loader/trait.Loader.html) trait. That trait has the method [`get_instance_proc_addr`](https://docs.rs/vulkano/0.19.0/vulkano/instance/loader/trait.Loader.html#tymethod.get_instance_proc_addr`) which you implement for the [`QVulkanInstance`](https://doc.qt.io/qt-5/qvulkaninstance.html) type. That type has the function [`getInstanceProcAddr`](https://doc.qt.io/qt-5/qvulkaninstance.html#getInstanceProcAddr) which you would be calling to give to vulkano.

I have never done this, but I think this is how you go about doing something like that.

**Comment by lehmanju** [comment]
Thanks so much for that.
