### ISSUE TITLE
Getting pointer to vk_sys::Instance?

### ISSUE THREAD

**Issue by colinmarc** [vulkano-rs/vulkano#1388]
Once I have an `Instance`, how do I get the underlying pointer/`vk_sys` object?

I'm trying to use vulkano with [glfw](https://github.com/PistonDevelopers/glfw-rs), which has a [wrapper for glfwCreateWindowSurface](https://www.glfw.org/docs/3.3/group__vulkan.html#ga1a24536bec3f80b08ead18e28e6ae965) that [uses `vk_sys::Instance`](https://github.com/PistonDevelopers/glfw-rs/blob/master/src/lib.rs#L2026-L2034). My plan was to call that, and then use `Surface::from_raw_surface`.

The glfw example would have me create the instance myself, but that seems a bit of a waste.

**Comment by AustinJ235** [comment]
So you want the vk-sys version from an vulkano instance? The vulkano version implements `VulkanObject` which calling `internal_object` on using that trait will give a `vk_sys::Instance`.

https://docs.rs/vulkano/0.19.0/vulkano/instance/struct.Instance.html#impl-VulkanObject

**Comment by Rua** [comment]
This issue seems to be answered now.
