### ISSUE TITLE
How would I implement the blas operation `SSCAL` (multiply vector by scalar)?

### ISSUE THREAD

**Issue by JonathanWoollett-Light** [vulkano-rs/vulkano#1389]
This is just a question of me learning and asking for help with this.

Seeing the example compute code given in the tutorial it multiplies every value in a given array by 12 (as written into the glsl):

```
mod cs {
    vulkano_shaders::shader!{
        ty: "compute",
        src: "
        #version 450

        layout(local_size_x = 64, local_size_y = 1, local_size_z = 1) in;

        layout(set = 0, binding = 0) buffer Data {
            uint data[];
        } buf;

        void main() {
            uint idx = gl_GlobalInvocationID.x;
            buf.data[idx] *= 12;
        }"
    }
}
```

How can I modify this and the rest of the example code to multiply every value in an array by a given value (replacing `12` with some `x`)?

In a more general sense, how do you pass multiple variables/buffers?

(Apologies about this question being bit dumb, I can't seem to find any good examples).

Current project simply implementing compute tutorial code: [vulkano-test.zip](https://github.com/vulkano-rs/vulkano/files/4781231/vulkano-test.zip)

**Comment by JonathanWoollett-Light** [comment]
So I think I've made some progress but I'm still a bit stuck.

I have rewritten the GLSL code:

```
mod sscal {
    vulkano_shaders::shader!{
        ty: "compute",
        src: "
        #version 450

        layout(local_size_x = 64, local_size_y = 1, local_size_z = 1) in;

        layout(set = 0, binding = 0) buffer Buffer {
            uint x[];
        };
        layout(set = 0, binding = 1) uniform UniformBuffer {
            uint a;
        };

        void main() {
            uint indx = gl_GlobalInvocationID.x;
            x[indx] *= a;
        }"
    }
}
```

I create 2 buffers:

```
let data_iter = 0..5u16;
let data_buffer = CpuAccessibleBuffer::from_iter(device.clone(), BufferUsage::all(), false,data_iter).expect("failed to create buffer");
let val = 2u16;
let val_buffer = CpuAccessibleBuffer::from_data(device.clone(),BufferUsage::uniform_buffer(),false,val).expect("failed to create buffer");
```

Now at this point my first area of issue comes up, when trying to read `data_buffer` the following code works:

```
let content = data_buffer.read().unwrap();
for (i, a) in content.iter().enumerate() {
    println!("{} | {}",i,a);
}
```

Outputting:
```

0 | 0
1 | 1
2 | 2
3 | 3
4 | 4
```

When trying to run the exact same code but replacing `data_buffer` for `val_buffer` it does not work. Resulting in the compilation error:

![image](https://user-images.githubusercontent.com/16856679/85204231-f8985880-b30a-11ea-934a-a991fb4a8386.png)

So to try and see the data another way I did `println!("{:.?}",val_buffer);` in looking at the output:

`CpuAccessibleBuffer { inner: <Vulkan buffer 2292350406064>, memory: Generic(StdMemoryPoolAlloc { inner: HostVisible(StdHostVisibleMemoryTypePoolAlloc { pool: StdHostVisibleMemoryTypePool { device: <Vulkan device 2292351624864>, memory_type: 1, occupied: Mutex { data: [(MappedDeviceMemory(DeviceMemory { device: <Vulkan device 2292351624864>, memory_type: MemoryType { physical_device: PhysicalDevice { instance: <Vulkan instance 2292322404816>, device: 0 }, id: 1 }, size: 8388608 }), [0..16, 16..32])] } }, memory: MappedDeviceMemory(DeviceMemory { device: <Vulkan device 2292351624864>, memory_type: MemoryType { physical_device: PhysicalDevice { instance: <Vulkan instance 2292322404816>, device: 0 }, id: 1 }, size: 8388608 }), offset: 16, size: 16 }), pool: StdMemoryPool { device: <Vulkan device 2292351624864>, pools: Mutex { data: {(1, Linear, Map): HostVisible(StdHostVisibleMemoryTypePool { device: <Vulkan device 2292351624864>, memory_type: 1, occupied: Mutex { data: [(MappedDeviceMemory(DeviceMemory { device: <Vulkan device 2292351624864>, memory_type: MemoryType { physical_device: PhysicalDevice { instance: <Vulkan instance 2292322404816>, device: 0 }, id: 1 }, size: 8388608 }), [0..16, 16..32])] } })} } } }), access: RwLock { data: NonExclusive { num: 0 } }, queue_families: [], marker: PhantomData }`

I see `data: NonExclusive { num: 0 }` which seems odd.

I setup the shader, compute pipeline, descriptor set and command buffer as such:
```
let shader = sscal::Shader::load(device.clone()).expect("failed to create shader module");

let compute_pipeline = Arc::new(ComputePipeline::new(device.clone(), &shader.main_entry_point(), &())
        .expect("failed to create compute pipeline"));

let layout = compute_pipeline.layout().descriptor_set_layout(0).unwrap();
let set = Arc::new(PersistentDescriptorSet::start(layout.clone())
    .add_buffer(data_buffer.clone()).unwrap()
    .add_buffer(val_buffer.clone()).unwrap()
    .build().unwrap()
);

let mut builder = AutoCommandBufferBuilder::new(device.clone(), queue.family()).unwrap();
builder.dispatch([1,1,1],compute_pipeline.clone(),set.clone(),()).unwrap();
let command_buffer = builder.build().unwrap();
```

I then submit the command buffer:
```
let finished = command_buffer.execute(queue.clone()).unwrap();
finished.then_signal_fence_and_flush().unwrap()
        .wait(None).unwrap();
```

Then output the data buffer after running:

```
let content = data_buffer.read().unwrap();
for (i, a) in content.iter().enumerate() {
    println!("{} | {}",i,a);
}
```

Which now outputs: 

```
0 | 0
1 | 0
2 | 0
3 | 0
4 | 4
```

I'm really grasping at straws for why this result occurs.

Doing a bit of experimentation and changing the line in GLSL from `x[indx] *= a;` to `x[indx] = a + 1;` results in the out:

```
0 | 1
1 | 0
2 | 1
3 | 0
4 | 4
```

Now I really have no idea what is going on here.

While I've made a bit of progress, I'm still at a loss for what I'm doing, I would greatly appreciate any help.

**Comment by vadixidav** [comment]
It looks like you might want to use https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/vkCmdPushConstants.html. Vulkan documentation here: https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/vkCmdPushConstants.html

On usage, see these slides: http://web.engr.oregonstate.edu/~mjb/vulkan/Handouts/PushConstants.1pp.pdf

I haven't used Vulkan before, but it looks like you might need to do:

```glsl
layout( push_constant ) uniform multiplier{float x;} Multiplier;
...
```

**Comment by JonathanWoollett-Light** [comment]
Solved.


GLSL code:

```GLSL
mod sscal {
    vulkano_shaders::shader!{
        ty: "compute",
        src: "
        #version 450

        layout(local_size_x = 64, local_size_y = 1, local_size_z = 1) in;

        layout(set = 0,binding = 0) buffer Buffer {
            uint x[];
        };
        layout(push_constant) uniform PushConstantData {
            uint a;
        };

        void main() {
            uint indx = gl_GlobalInvocationID.x;
            x[indx] *= a;
        }"
    }
}
```

Rust code:

```Rust
let data_iter = 0..24u32;
let data_buffer = CpuAccessibleBuffer::from_iter(device.clone(), BufferUsage::all(), false,data_iter).expect("failed to create buffer");
let push_constant = 2u32;

let shader = sscal::Shader::load(device.clone()).expect("failed to create shader module");

let compute_pipeline = Arc::new(ComputePipeline::new(device.clone(), &shader.main_entry_point(), &())
.expect("failed to create compute pipeline"));


let layout = compute_pipeline.layout().descriptor_set_layout(0).unwrap();
let set = Arc::new(PersistentDescriptorSet::start(layout.clone())
    .add_buffer(data_buffer.clone()).unwrap()
    .build().unwrap()
);

let mut builder = AutoCommandBufferBuilder::new(device.clone(), queue.family()).unwrap();
builder.dispatch([1024,1,1],compute_pipeline.clone(),set.clone(),push_constant).unwrap();

let command_buffer = builder.build().unwrap();

let finished = command_buffer.execute(queue.clone()).unwrap();

finished.then_signal_fence_and_flush().unwrap()
.wait(None).unwrap();

println!();
let content = data_buffer.read().unwrap();
for (i, a) in content.iter().enumerate() {
    println!("{} | {}",i,a);
}
```
