### ISSUE TITLE
How should I dynamically add textures in to the texture arrays?

### ISSUE THREAD

**Issue by AndrewHC36** [vulkano-rs/vulkano#1391]
*   Version of vulkano: v0.19.0
*   OS: TODO
*   GPU (the selected PhysicalDevice): TODO
*   GPU Driver: TODO
*   Upload of a reasonably minimal complete `main.rs` file that demonstrates the issue: TODO

I have question about how to dynamically add textures in to the texture arrays. Since each time I add the `.add_simpled_image()`, the type seems to recursively gets deeper, or the type changes. Which makes it very difficult to loop over `Vec<ImmutableImage>` to add it to the descriptor sets.

So I decided to just use the builder to add the images which causes the error `[E0382]: use of moved value: txtr_set_enter`. I don't know if there are any other ways to avoid the error. The texture automation code is shown as below:

```rust
let layout0 = self.grph_pipe.descriptor_set_layout(0).unwrap();

let mut txtr_set_enter = PersistentDescriptorSet::start(layout0.clone())
    .enter_array().unwrap()
    .add_sampled_image(self.textures[0].clone(), self.sampler.clone()).unwrap();

for txtr in self.textures.iter() {
    txtr_set_enter.add_sampled_image(txtr.clone(), self.sampler.clone()).unwrap();
}

let txtr_set = Arc::new(
    txtr_set_enter
        .leave_array().unwrap()
        .build().unwrap()
);
```

### Edit

I found out that this question might confuses you guys what I'm trying to ask. So what I'm trying (hopefully) is to add textures or remove textures before each new instance of a Graphical Pipeline. But that also begs a questions whether you can dynamically change the size of the list of textures (`sampler2d`) in the shader via specialization constants.

**Comment by Eliah-Lakhin** [comment]
@AndrewHC36 Why not just using `sampler2DArray` and put all relevant textures on texture array layers? You can dynamically sample appropriate texture from shader with the 3rd uvw parameter in `texture` function(s)

**Comment by AndrewHC36** [comment]
Sorry, been taking a break lately. I never know there was this type `sampler2DArray` exists in GLSL as a dynamically sized array of samplers. I'll take a look on how to implement a `sampler2DArray` in Vulkano.
