### ISSUE TITLE
Validation error on image usage when creating swapchain

### ISSUE THREAD

**Issue by Rua** [vulkano-rs/vulkano#1392]
I create a swapchain with the following parameters:
```Rust
Swapchain::new(
	device,
	surface,
	4,
	B8G8R8A8Unorm,
	[800, 600],
	1,
	ImageUsage {
		transfer_destination: true,
		..ImageUsage::none()
	},
	SharingMode::Exclusive,
	SurfaceTransform::Identity,
	CompositeAlpha::Opaque,
	PresentMode::Mailbox,
	FullscreenExclusive::Default,
	true,
	ColorSpace::SrgbNonLinear,
)
```
The Vulkan implementation then gives me these validation errors:
```
UNASSIGNED-CoreValidation-MemTrack-InvalidUsageFlag: Invalid usage flag for VkImage 0x40000000004[] used by vkCreateImageView(). In this case, VkImage should have VK_IMAGE_USAGE_[SAMPLED|STORAGE|COLOR_ATTACHMENT|DEPTH_STENCIL_ATTACHMENT|INPUT_ATTACHMENT|SHADING_RATE_IMAGE|FRAGMENT_DENSITY_MAP]_BIT set during creation.
UNASSIGNED-CoreValidation-MemTrack-InvalidUsageFlag: Invalid usage flag for VkImage 0x50000000005[] used by vkCreateImageView(). In this case, VkImage should have VK_IMAGE_USAGE_[SAMPLED|STORAGE|COLOR_ATTACHMENT|DEPTH_STENCIL_ATTACHMENT|INPUT_ATTACHMENT|SHADING_RATE_IMAGE|FRAGMENT_DENSITY_MAP]_BIT set during creation.
UNASSIGNED-CoreValidation-MemTrack-InvalidUsageFlag: Invalid usage flag for VkImage 0x60000000006[] used by vkCreateImageView(). In this case, VkImage should have VK_IMAGE_USAGE_[SAMPLED|STORAGE|COLOR_ATTACHMENT|DEPTH_STENCIL_ATTACHMENT|INPUT_ATTACHMENT|SHADING_RATE_IMAGE|FRAGMENT_DENSITY_MAP]_BIT set during creation.
UNASSIGNED-CoreValidation-MemTrack-InvalidUsageFlag: Invalid usage flag for VkImage 0x70000000007[] used by vkCreateImageView(). In this case, VkImage should have VK_IMAGE_USAGE_[SAMPLED|STORAGE|COLOR_ATTACHMENT|DEPTH_STENCIL_ATTACHMENT|INPUT_ATTACHMENT|SHADING_RATE_IMAGE|FRAGMENT_DENSITY_MAP]_BIT set during creation.
UNASSIGNED-CoreValidation-MemTrack-InvalidUsageFlag: Invalid usage flag for VkImage 0x80000000008[] used by vkCreateImageView(). In this case, VkImage should have VK_IMAGE_USAGE_[SAMPLED|STORAGE|COLOR_ATTACHMENT|DEPTH_STENCIL_ATTACHMENT|INPUT_ATTACHMENT|SHADING_RATE_IMAGE|FRAGMENT_DENSITY_MAP]_BIT set during creation.
```
`Capabilities::supported_usage_flags` is:
```Rust
ImageUsage {
    transfer_source: true,
    transfer_destination: true,
    sampled: true,
    storage: true,
    color_attachment: true,
    depth_stencil_attachment: false,
    transient_attachment: false,
    input_attachment: false,
}
```

If I add the `color_attachment` flag to the creation, these errors go away. But it's not clear to me which part of the Vulkan spec says the flags cannot be only `transfer_destination`.

**Comment by AustinJ235** [comment]
I would assume `transfer_destination` and `storage` to true would also not return errors? I think the message is saying any one of these ``VK_IMAGE_USAGE_[SAMPLED|STORAGE|COLOR_ATTACHMENT|DEPTH_STENCIL_ATTACHMENT|INPUT_ATTACHMENT|SHADING_RATE_IMAGE|FRAGMENT_DENSITY_MAP]_BIT`` need to be set to true.

Seems to line up the other usage quirks lately. I think maybe we should add a check for this case, but importantly figure out where this is stated in spec.

**Comment by Rua** [comment]
After some digging I found it. The restriction is specific to image views, not swapchain images:
https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VkImageViewCreateInfo.html
> image **must** have been created with a usage value containing at least one of `VK_IMAGE_USAGE_SAMPLED_BIT`, `VK_IMAGE_USAGE_STORAGE_BIT`, `VK_IMAGE_USAGE_COLOR_ATTACHMENT_BIT`, `VK_IMAGE_USAGE_DEPTH_STENCIL_ATTACHMENT_BIT`, `VK_IMAGE_USAGE_INPUT_ATTACHMENT_BIT`, `VK_IMAGE_USAGE_SHADING_RATE_IMAGE_BIT_NV`, or `VK_IMAGE_USAGE_FRAGMENT_DENSITY_MAP_BIT_EXT`

So this is something Vulkano should definitely enforce.

It's not entirely clear to me which of these is appropriate in my situation though, when all I do is blit onto the image and then present it. Does it make sense to have an image without a view? `vkCmdBlitImage` only requires `vkImage` arguments, and `AutoCommandBufferBuilder::blit_image` likewise requires `ImageAccess`. So the creation of image views for the swapchain is entirely unnecessary for my use case.
