### ISSUE TITLE
Optimize the memory pool

### ISSUE THREAD

**Issue by tomaka** [vulkano-rs/vulkano#14]
Using a memory pool to manage memory is encouraged in Vulkan.
Not only it is encouraged, but since the number of simultaneous allocations is limited in Vulkan it can also be mandatory on some systems if you don't want to run into OOM errors.

**Comment by tomaka** [comment]
Some mentoring.

We need two memory pools:

- One for host-visible memory, whose algorithm is allowed to read/write the memory that is going to be allocated.
- One for non-host-visible memory, whose algorithm doesn't have access to the content of the memory.

The objects must be in submodules of `src/memory` and must wrap around either the `MappedDeviceMemory` struct (for the former), or the `DeviceMemory` struct (for the latter).

**Comment by White-Oak** [comment]
@tomaka excuse me, can you explain why one would need non-host-visible memory? I'm not too expereinced with Vulkan, so this may be obvious, but not clear to me :(

**Comment by tomaka** [comment]
@White-Oak The memory that is directly on the video card is the fastest possible memory, but it may not be visible for the host.

When you have data that is used many times and that the host doesn't need to modify (for example a 3D model), you can copy it to this kind of memory to get better performances.

**Comment by tomaka** [comment]
I just realized how important this is. On my system one deallocation takes between 100 and 200ms.

**Comment by White-Oak** [comment]
@tomaka I would be eager to help, but unfortunately I don't have a clue, how some object that is a wrapper around `(Mapped)DeviceMemory` would allow one to pool a memory.
My example: 
1. I took 200KB of memory from pool, pool allocated 200KB of memory, gave it to me.
2. I released that memory back to pool, pool marked it as free.
3. I requested 150KB of memory from pool. Pool would be happy to reuse previous 200KB to pool me 150KB of that, but can't, since it's a wrapper around `DeviceMemory`! So I need to allocate a new chunk of memory.

Where am I wrong?

**Comment by White-Oak** [comment]
Ah, wait, maybe we got "wrapper" a bit wrong. Maybe a wrapper meaning it would give `DeviceMemory` out, but use its own structure inside?

**Comment by tomaka** [comment]
The `DeviceMemory` is used internally by the pool but is not exposed at all.

**Comment by pczarn** [comment]
Is there a pattern that we can use? Are allocation sizes usually powers of 2, or are they similar?

**Comment by tomaka** [comment]
@pczarn That's a good question. I don't think there's a precise pattern.

Buffers can be used at the same time to store big chunks of data, or just a few bytes to store a matrix.
Images are for the most part textures, in which case the size of the texture can vary a lot.

**Comment by tomaka** [comment]
I think I'm going to write a dummy implementation of this.

**Comment by tomaka** [comment]
I merged my draft. It's of course very slow and can be greatly improved.

**Comment by branan** [comment]
There's an impl period hack day here in Portland on Sunday. I know Vulkano's not officially part of that effort, but I'll probably take the opportunity to prototype some of my thoughts on allocator plugability for this ticket as well as #673.

**Comment by branan** [comment]
https://github.com/branan/vulkano/commit/5425be7419ed122f954fd5b9f4465be7ce5ef165 is a first pass at this for `CpuAccessibleBuffer`. That struct was already generic across its allocation type, so it was mostly a matter of adding the right new fns to accept a custom `MemoryPool` implementation. I'll open a PR for this once I've had some more time to play with how this actually works in a real application.

I've also started looking into what it would take to allow `Device` to be parameterized on its pool type. The actual logic in `Device` around the memory pool is pretty simple, but getting all of Vulkano to handle a generic `Device` type is going to be "fun". I may save this one for another rainy day ;)

And finally I'm contemplating whether it makes sense to make `StdMemoryPool` generic over its host- and non-host-visible internal pool types. `StdMemoryPool` handles a lot of boiler plate around vulkan memory types, so it'd be nice if custom pools could re-use it it.

**Comment by tomaka** [comment]
Great!

> I've also started looking into what it would take to allow Device to be parameterized on its pool type. The actual logic in Device around the memory pool is pretty simple, but getting all of Vulkano to handle a generic Device type is going to be "fun". I may save this one for another rainy day ;)

I don't think that's going to be really possible or practical though, but I may be wrong.

If we compare this to the CPU memory allocator, on the CPU side the allocator is chosen globally for the whole program, probably because there is some sort of agreement that having to pass an allocator as parameter to every single function that allocates would be too cumbersome.

**Comment by Rua** [comment]
This is improved by the new memory memory allocator in 0.32.
