### ISSUE TITLE
Link errors when including vulkano-shaders on Windows 10

### ISSUE THREAD

**Issue by Rafagd** [vulkano-rs/vulkano#1402]
# Template

If you dont understand something just leave it.
If you can provide more detailed information than the template allows for, please ignore the template and present all of your findings.

*   Version of vulkano: 0.19
*   OS: Windows 10
*   GPU (the selected PhysicalDevice): n/a
*   GPU Driver: n/a
*   Upload of a reasonably minimal complete `main.rs` file that demonstrates the issue:
https://pastebin.com/4T9J97Le

# Issue

Trying to compile this on windows without success. Linker complains about missing implementations, but the message is not descriptive enough for me to do anything about it.
Log: https://pastebin.com/JGtGLzGs

**Comment by AustinJ235** [comment]
what version of vs tools are you using?  are you using msvc? I dont many people have good luck with mingw.

**Comment by Rafagd** [comment]
VS Tools 2019, msvc.

**Comment by Gosuo** [comment]
@Rafagd Do you still have issues with linking? I had the same error, after I reinstalled the C++ Build Tools via the Visual Studio Installer it worked for me.

**Comment by Rafagd** [comment]
Haven't tried again ever since. I'll create a new issue if I try it again.
