### ISSUE TITLE
How to create a shader+pipeline from a SPIR-V file?

### ISSUE THREAD

**Issue by JonathanWoollett-Light** [vulkano-rs/vulkano#1409]
My current progress is:

```rust
let bytes:Vec<u8> = std::fs::read("C:/Users/jonat/Projects/glsl.spv").expect("failed to opne spirv file");
let shader = ShaderModule::new(device.clone(),&bytes).expect("failed to create shader module");

// Compute pipeline holder list of shaders to run seqeuntially.
// Sets the compute pipeline (list of shaders).
let compute_pipeline = Arc::new(ComputePipeline::new(device.clone(), &shader, &())
.expect("failed to create compute pipeline"));
```

The issue I'm facing is on `ComputePipeline::new` with the error:

```
the trait bound `std::sync::Arc<vulkano::pipeline::shader::ShaderModule>: vulkano::pipeline::shader::EntryPointAbstract` is not satisfied

the trait `vulkano::pipeline::shader::EntryPointAbstract` is not implemented for `std::sync::Arc<vulkano::pipeline::shader::ShaderModule>`rustc(E0277)
compute_pipeline.rs(66, 13): required by this bound in `vulkano::pipeline::compute_pipeline::ComputePipeline::<()>::new`
lib.rs(211, 41): the trait `vulkano::pipeline::shader::EntryPointAbstract` is not implemented for `std::sync::Arc<vulkano::pipeline::shader::ShaderModule>`
```

I imagine the solution to this is to do with the function [`ShaderModule::compute_entry_point`](https://docs.rs/vulkano/0.19.0/vulkano/pipeline/shader/struct.ShaderModule.html#method.compute_entry_point), I am however unsure of how to use this, as such I'm asking this question (I imagine it might be a trivial thing, but I'm only a novice, help a learner out),

The GLSL code of the file from which the SPIR-V file has been compiled (not sure if this is all neccessary but I thought it best to add, it's just something basic for testing):

```glsl
#version 450

layout(local_size_x = 64, local_size_y = 1, local_size_z = 1) in;

layout(set = 0,binding = 0) buffer Buffer {
    uint x[];
};

void main() {
    uint indx = gl_GlobalInvocationID.x;
    x[indx] += 1;
}
```

**Comment by JonathanWoollett-Light** [comment]
#### Update

Got code to:

```rust
let bytes:Vec<u8> = std::fs::read("C:/Users/jonat/Projects/glsl.spv").expect("failed to opne spirv file");
let shader = ShaderModule::new(device.clone(),&bytes).expect("failed to create shader module");
        
let entry_point = shader.compute_entry_point(&CString::new("main").expect("CString::new failed"),/* No idea what should be the layout */);

let compute_pipeline = Arc::new(ComputePipeline::new(device.clone(), &entry_point, &())
        .expect("failed to create compute pipeline"));
```

Now when I'm stuck on what I should pass as the `Layout` for `compute_entry_point`. I see it's some struct which implements the trait `PipelineLayoutDesc`. And here I'm once again a bit stuck

**Comment by Rua** [comment]
It may help to try out the `shader!` macro from [`vulkano_shaders`](https://docs.rs/vulkano-shaders/0.19.0/vulkano_shaders/) with your shader. If you give it the `dump: true` argument, the compiler will crash (by design) and dump out all the code that the macro would generate. With that, you can see what kind of things you need to write and perhaps spot what pieces you're missing.

**Comment by JonathanWoollett-Light** [comment]
@Rua The reason I'm pursuing this path is becuase of my issue https://github.com/vulkano-rs/vulkano/issues/1395. Vulkano (or perhaps ShaderC) lacks support for a GLSL extension I need, as far as I can tell this is simply a feature they are unaware of and actually running the compiled SPIR-V should circumvent this lacking (using the VulkanSDK it compiles from GLSL to SPIR-V easily).

**Comment by Rua** [comment]
What if you removed the extension and the part of the code that relies on it, then tried the macro expansion? The goal is just to have an example macro expansion that you can work from, the exact code of the shader can probably vary a bit without affecting the macro output.

**Comment by JonathanWoollett-Light** [comment]
@Rua I don't think I understand what you are saying, I don't see how it accomplishes the goal. I would also add that, that seems more complex than just using the method I am trying.

**Comment by adrianisuru** [comment]
vulkano-shaders should support this. Have you tried using the `bytes` field of `vulkano_shaders:shader!`?
```rust
mod cs {
    vulkano_shaders::shader! {
        ty: "compute",
        bytes: "C:/Users/jonat/Projects/glsl.spv"
    }
}
```

**Comment by Rua** [comment]
I think this issue is either fixed or no longer relevant?
