### ISSUE TITLE
Vulkano guide out of date with example

### ISSUE THREAD

**Issue by CraftSpider** [vulkano-rs/vulkano#1411]
# Template

*   Version of vulkano: 0.19.0
*   OS: Windows
*   GPU (the selected PhysicalDevice): GeForce RTX 2080
*   GPU Driver: Unknown

# Issue

When running the Compute pipelines example from the vulkano.rs tutorial, an error occurs about a missing extension `khr_storage_buffer_storage_class`. The example in the code base was fixed in #1275, but it seems that the tutorial was not updated to include it

**Comment by dmyTRUEk** [comment]
For me the solution was to add required DeviceExtensions:

```
    let required_device_extensions = DeviceExtensions {
        khr_storage_buffer_storage_class: true,
        .. DeviceExtensions::none()
    };

    let (device, mut queues) = {
        Device::new(
            physical,
            &Features::none(),
            RawDeviceExtensions::from(&required_device_extensions),
            [(queue_family, 0.5)].iter().cloned()
        ).expect("failed to create device")
    };
```

**Comment by Rua** [comment]
The Vulkano website should now be up to date and maintained regularly.
