### ISSUE TITLE
`GpuFuture` and `Future`

### ISSUE THREAD

**Issue by timothee-haudebourg** [vulkano-rs/vulkano#1412]
Hi,

I was wondering if you had any plans on making the `GpuFuture` trait compatible with the now standard `Future` trait? Being able to use `async`/`await` with vulkano would be great.

**Comment by Eliah-Lakhin** [comment]
@timothee-haudebourg Hi!

I didn't hear if someone is planning to implement something like this, but I think it would be a good idea. You can start working on the featue.

There are a lot of open questions on how to make the interoperability between the CPU concurrent model and Vulkan GPU concurrent model transparent from the API design point of view. But probably this is doable. I have a wrapper in my personal project(still in a private repo) that makes such interoperability with Tokio, but for only a few cases specific to the project's domain. However, I think it could be extended to a general case.

**Comment by Eliah-Lakhin** [comment]
Maybe as a first prototype solution you can make a `Future` trait wrapper around the existing `GpuFuture` API to persist the API back-compatibility.
