### ISSUE TITLE
Vulkano_shaders documentation mentions non-existent attribute

### ISSUE THREAD

**Issue by CraftSpider** [vulkano-rs/vulkano#1413]
# Template

*   Version of vulkano: 0.19.0
*   OS: Windows
*   GPU (the selected PhysicalDevice): GeForce RTX 2080
*   GPU Driver: 

# Issue

In the vulkano_shaders documentation, there's a reference to "the module specified by `mod_name: foo`", which is confusing, as the shader macro does not accept a `mod_name` attribute, and panics if one is provided. Was this for an old version, or a feature never added?

**Comment by Rua** [comment]
Closing this issue as it's probably fixed or no longer relevant with the changes that have happened since.
