### ISSUE TITLE
vulkano::features::Feature.shader_f3264 is incorrectly named

### ISSUE THREAD

**Issue by TJYSunset** [vulkano-rs/vulkano#1415]
*   Version of vulkano: 0.19.0

For some reason, [VkPhysicalDeviceFeatures.shaderFloat64](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VkPhysicalDeviceFeatures.html) is [exposed as `f3264`](https://github.com/vulkano-rs/vulkano/search?q=f3264&unscoped_q=f3264) in vulkano API.

**Comment by AustinJ235** [comment]
Does seem a bit weird. Perhaps this is easy as a simple rename. This would be breaking though.

**Comment by Eliah-Lakhin** [comment]
#1440 fixes this issue. It was probably a bug due to Vulkan's doc, not just inconvenient name.
