### ISSUE TITLE
simple texture example

### ISSUE THREAD

**Issue by lattice0** [vulkano-rs/vulkano#1420]
I'm coming from OpenGL to Vulkan. On C++ I find the code to ugly/big to understand. This library makes it more readable. I've read and understood the triangle.rs example.

However I don't know anything about sending textures. I kindly ask if someone has an example of sending textures.

Thank you very much!

**Comment by AustinJ235** [comment]
take a look at the image example in the repository.

**Comment by blacksailer** [comment]
Hello, thank you for vulkano lib.

I can't add texture since pipeline.layout() method became private. Is there any other option to get descriptorsetlayout?
