### ISSUE TITLE
Inconsistent parameter types in AutoCommandBufferBuilder APIs

### ISSUE THREAD

**Issue by GarfieldZHU** [vulkano-rs/vulkano#1421]
*   Version of vulkano: 0.19.0
*   OS: macOS
*   GPU (the selected PhysicalDevice): any
*   GPU Driver: any
*   Upload of a reasonably minimal complete `main.rs` file that demonstrates the issue:

Like the examples below, the chaining of AutoCommandBufferBuilder fails at `build` with error:
"***cannot move out of a mutable reference***", which worked well in earlier versions like 0.18.0.

```rust
AutoCommandBufferBuilder::new(device, queue_family)
    .unwrap()
    .begin_render_pass(framebuffer, false, vec![[0.0, 0.0, 0.0, 1.0].into()])
    .unwrap()
    .draw(graphics_pipeline, &DynamicState::none(), vertices, (), ())
    .unwrap()
    .end_render_pass()
    .unwrap()
    .build()
    .unwrap()
```

### Description

Compared the API docs, I found that all member methods of AutoCommandBufferBuilder were binded to `self` in 0.18.0. 
Since 0.19.0, most of them were updated to `&mut self`, like `begin_render_pass`, `end_render_pass` used in the example. But only that `build` keeps using "self". It breaks the above chaining calls when self reference is inconsistent. 

Not sure if it is expected or not. If it is by design, any suggestion for chaining the build of command buffer?

**Comment by AustinJ235** [comment]
This is intentional. It allows for more conditional building of commands.

**Comment by GarfieldZHU** [comment]
@AustinJ235, thanks for response. 

So it seems we need to update like this,
```rust
let mut builder = AutoCommandBufferBuilder::primary_simultaneous_use(self.device.clone(), queue_family).unwrap();

builder.begin_render_pass(framebuffer.clone(), false, vec![[0.0, 0.0, 0.0, 1.0].into()])
    .unwrap()
    .draw(self.graphics_pipeline.clone(), &DynamicState::none(),
        vertices, (), ())
    .unwrap()
    .end_render_pass()
    .unwrap();

builder.build().unwrap()
```
