### ISSUE TITLE
Use precompiled shaders

### ISSUE THREAD

**Issue by Balgy** [vulkano-rs/vulkano#1425]
Is there a way for me to use precompiled shaders (.spv) files so that I do not have to use the vulkano-shaders crate?

**Comment by Eliah-Lakhin** [comment]
@Balgy Yes. This example showing how to load a precompiled shader: https://github.com/vulkano-rs/vulkano/blob/master/examples/src/bin/runtime-shader/main.rs

**Comment by AustinJ235** [comment]
I believe there is a way to use raw spirv check the examples we might have one.
