### ISSUE TITLE
Make AutoCommandBufferBuilder::execute_commands safe to use

### ISSUE THREAD

**Issue by Rua** [vulkano-rs/vulkano#1430]
This is marked as unsafe in the documentation, but it is a pretty important function to have. Can it be made safe to use, or at least have a good documentation on what a user needs to do in order to produce sound code? Specifically, if the command buffer provided as the argument is another `AutoCommandBuffer`.

**Comment by AustinJ235** [comment]
I think it may be unsafe to the nature that fences are not automatically inserted like they are on the rest of the methods on `AutoCommandBufferBuilder`. If were were to change how fences are done, which is fairly complicated in its current state, it may be possible to check this. But in its current state, I think this isn't possible.

**Comment by Rua** [comment]
For future implementors, these checks as detailed in [the documentation of `vkCmdExecuteCommands`](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/vkCmdExecuteCommands.html) still need to be implemented as of #1431:

* [ ] If any element of `pCommandBuffers` was not recorded with the `VK_COMMAND_BUFFER_USAGE_SIMULTANEOUS_USE_BIT` flag, and it was recorded into any other primary command buffer which is currently in the executable or recording state, that primary command buffer becomes invalid.
* [ ] Each element of `pCommandBuffers` **must** be in the pending or executable state
* [ ] If any element of `pCommandBuffers` was not recorded with the `VK_COMMAND_BUFFER_USAGE_SIMULTANEOUS_USE_BIT` flag, it **must** not be in the pending state
* [ ] If any element of `pCommandBuffers` was not recorded with the `VK_COMMAND_BUFFER_USAGE_SIMULTANEOUS_USE_BIT` flag, it **must** not have already been recorded to `commandBuffer`
* [ ] If any element of `pCommandBuffers` was not recorded with the `VK_COMMAND_BUFFER_USAGE_SIMULTANEOUS_USE_BIT` flag, it **must** not appear more than once in `pCommandBuffers`
* [ ] Each element of `pCommandBuffers` **must** have been allocated from a `VkCommandPool` that was created for the same queue family as the `VkCommandPool` from which `commandBuffer` was allocated

The checks related to the execution state of the secondary command buffers could be implemented in `SyncCommandBufferBuilderExecuteCommands::submit` by calling `lock_submit` on the secondary command buffer before `vkCmdExecuteCommands` is called and `unlock` afterwards. Some changes need to be made to ensure that only the command buffer itself is locked for access, not the resources as these don't need to be locked for `vkCmdExecuteCommands`. Moreover, a one-time-use command buffer isn't rendered "used" by this operation, so this flag should not be set when locking.

Some checks are not implemented, but currently don't need to be:
* Checks related to `VK_COMMAND_BUFFER_USAGE_RENDER_PASS_CONTINUE_BIT` aren't needed as long as the current command buffer types add this flag automatically when creating secondary graphics command buffers.
* Checks related to `VkRenderPassTransformBeginInfoQCOM` aren't needed as long as this feature remains unused.
* Checks related to queries aren't needed as long as this feature remains unused.

Finally, the following synchronisation-related aspects need to be implemented in `SyncCommandBufferBuilder`:
* [ ] Synchronisation of the resources in the secondary command buffer. This is probably as simple as calling `lock_submit` and `unlock` recursively on all secondary command buffers whenever those functions are called on the parent primary command buffer.
* [ ] Synchronisation of the secondary command buffer itself, to ensure it isn't used concurrently if its usage flags don't allow it. This can also be handled by calling `lock_submit` and `unlock` recursively.
* [ ] Synchronisation of the resources in the secondary buffer with respect to the primary. If the two share resources, there probably needs to be some mechanism to protect them across the boundary inside `SyncCommandBufferBuilder`? Not sure on this one though, needs expert review!

**Comment by Rua** [comment]
I've been staring at the third checkbox a bit more for the last few days, and have come to the following conclusions:
- `SyncCommandBufferBuilderExecuteCommands::submit` needs to implement the `image` and `buffer` trait methods on the `Command` and `FinalCommand`.
- It also needs to call `prev_cmd_resource` for each resource (buffer, image) that the secondary command buffer uses.
- In order to do this, the `CommandBuffer` trait needs additional methods to query this information from the secondary buffer being added. It needs to return the access flags, pipeline stages and (for images) layout information.
- This is similar to how `SyncCommandBufferBuilderBindDescriptorSets::submit` works, so perhaps the same trait methods can be used: `num_buffers`/`num_images` and `buffer(num)`/`image(num)`. This interface maps straight to what `Command`/`FinalCommand` expects.
- Presumably, `SyncCommandBuffer` would therefore have `buffer: Vec` and `image: Vec` inside of it somewhere, to easily return this information.

It is unclear to me, however, how to construct these two lists. Things are complicated by the `CbKey` mechanism, which seems to be written to be very smart and efficient, but it's also very unclear how it actually works. For example, does every buffer and image appear exactly once in `SyncCommandBuffer::resources`, or can there be duplicates? Are duplicates a problem for `Command::buffer`/`image`? If not, then the lists could probably be done simply with a `filter_map` + `collect` on the existing `resources` hashmap.

@AustinJ235 @Eliah-Lakhin if you have the time, I'd really appreciate it if you could help me crack this one. It's quite challenging but it bugs me to no end that this isn't implemented yet, as I am quite eager to use secondary command buffers in my project. Any thoughts, tips or analysis would be very helpful.

**Comment by Rua** [comment]
@Eliah-Lakhin I think I almost have this working in a crude form, but I'm running into a bit of a design oddity. A secondary command buffer needs to be able to give references to its buffers and images for the primary to check and synchronise, via the `Command` and `FinalCommand` traits. The resources are held inside the `SyncCommandBuffer::commands` member, but unfortunately this is protected by a mutex, so returning references is impossible. A `MutexGuard` could be returned, sure, but that doesn't match the signatures of those two traits.

However, the mutex never actually protects against write accesses. It's only ever locked for read access, and if I strip out the mutex then everything still compiles. So I'm a bit confused about what this mutex is actually there to protect. It doesn't seem to be documented at all. Its current effect seems to be to turn the `lock_submit` and `unlock` functions into critical sections, so only one thread can be there at a time, but I have no idea if that's necessary. In the end, it would save me a lot of time if I could remove this mutex, but then I have to be sure it doesn't break anything. Any thoughts?
