### ISSUE TITLE
Finish the implementation of the PipelineCache

### ISSUE THREAD

**Issue by Gosuo** [vulkano-rs/vulkano#1442]
I stumbled over [`vulkano::pipeline::cache::PipelineCach`](https://docs.rs/vulkano/0.19.0/vulkano/pipeline/cache/struct.PipelineCache.html) and noticed that it isn't fully implemented yet.

I dug through the code base and I think only a few parts are missing. A field in the *PipelineBuilder and a method to add a Cache to the builder and the call to the vk-sys function needs to be changed from 0 to the [`cache`](https://docs.rs/vulkano/0.19.0/src/vulkano/pipeline/cache.rs.html#42) field of the `PipelineCache`. The heavy work should be done by the Vulkan implementation, right?

If I got this right and you are interested I could try to implement this.

**Comment by Rua** [comment]
I think Vulkano can use all the help it can get at the moment!
