### ISSUE TITLE
Add support for building for Windows targets without proprietary software

### ISSUE THREAD

**Issue by john01dav** [vulkano-rs/vulkano#1456]
According to the readme on crates.io, Vulkano only supports compilation to the windows-msvc target and not to windows-gnu. This is *highly* problematic because, in effect, anyone who wants to use Rust with Vulkan now has to deal with the proprietary nature of MSVC. While it's not particularly bad as far as proprietary programs go, it is still far from good. It would be much better if Vulkano supported compilation to Windows targets (ideally cross compilation from Linux too) using only FOSS tools, like the windows-gnu toolchain.

**Comment by Rua** [comment]
I haven't had any trouble cross-compiling with windows-gnu so far. Maybe it's not officially supported, but it seems to work for me.

**Comment by john01dav** [comment]
Thanks for the reply! Are you cross compiling from Linux or Mac OS?

**Comment by Rua** [comment]
Linux, using the mingw linker.
