### ISSUE TITLE
Outcommented rasterizer_discard() function

### ISSUE THREAD

**Issue by p0lunin** [vulkano-rs/vulkano#1462]
https://github.com/vulkano-rs/vulkano/blob/dea9a421d0f18bddd06332569752691039953fec/vulkano/src/pipeline/graphics_pipeline/builder.rs#L1613-L1619

There are outcommented function in library with `TODO: this won't work correctly`.
I think there are need to describe what exactly won't work correctly or uncomment this method.

**Comment by Eliah-Lakhin** [comment]
@p0lunin Git blame saying it was commented out ~4 years ago: https://github.com/vulkano-rs/vulkano/commit/2b8048a22b4a6efc91290b68e1ad6ebfceb0e1d9#diff-693b40e11d74f1df68d088edbaa6bc8c8bb2c05deb4244af43ec12a4f63a06eaR432 I can't tell why it was done, but I think there were uncovered use cases.

Would you like to take a lead in research and fix?

**Comment by Rua** [comment]
This has been re-enabled via #1724, so this issue can be closed.
