### ISSUE TITLE
Window example two errors. https://vulkano.rs/guide/window

### ISSUE THREAD

**Issue by ShaunKulesa** [vulkano-rs/vulkano#1465]
[main.zip](https://github.com/vulkano-rs/vulkano/files/5767014/main.zip)
*   Version of vulkano: vulkano-win = "0.19"
*   OS: Windows
*   GPU (the selected PhysicalDevice): 1660 Ti
*   GPU Driver: Nividia 
*   Upload of a reasonably minimal complete `main.rs` file that demonstrates the issue: 

error[E0609]: no field `shaderf3264` on type `PhysicalDeviceFeatures`
   --> C:\Users\Home\.cargo\registry\src\github.com-1ecc6299db9ec823\vulkano-0.19.0\src\features.rs:459:28
    |
459 |     core { shader_f3264 => shaderf3264 },
    |                            ^^^^^^^^^^^ help: a field with a similar name exists: `shaderInt64`

error[E0308]: mismatched types
    --> C:\Users\Home\.cargo\registry\src\github.com-1ecc6299db9ec823\vulkano-0.19.0\src\command_buffer\sys.rs:1455:38
     |
1455 |         vk.CmdSetBlendConstants(cmd, constants); // TODO: correct to pass array?
     |                                      ^^^^^^^^^
     |                                      |
     |                                      expected `&[f32; 4]`, found array `[f32; 4]`
     |            

Me and another person tried the open window example and we both get the errors above.

Code:
```use vulkano_win::VkSurfaceBuild;
use winit::EventLoop;
use winit::WindowBuilder;

fn main(){
    let events_loop = EventLoop::new();
    let surface = WindowBuilder::new().build_vk_surface(&events_loop, instance.clone()).unwrap();

    let instance = {
        let extensions = vulkano_win::required_extensions();
        Instance::new(None, &extensions, None).expect("failed to create Vulkan instance")
    };

    events_loop.run(|event, _, control_flow| {
        match event {
            winit::Event::WindowEvent { event: winit::WindowEvent::CloseRequested, .. } => {
                *control_flow = ControlFlow::Exit;
            },
            _ => ()
        }
    });
}```




https://vulkano.rs/guide/window

**Comment by Rua** [comment]
Try Vulkano 0.20 and see if it still happens?

**Comment by ShaunKulesa** [comment]
@Rua which one?

vulkano-win = "0.19"
winit = "0.22"

**Comment by Rua** [comment]
Vulkano.

**Comment by ShaunKulesa** [comment]
gives me different and more errors if i set
vulkano-win = "0.20"

**Comment by ShaunKulesa** [comment]
@Rua i see these people had the same errors, https://github.com/vulkano-rs/vulkano/issues/1464.

**Comment by gurchetansingh** [comment]
@ShaunKulesa "vulkano" (core functionality) and "vulkano-win" (window system integration) are two different crates, no?  I would try setting both to the latest version.

**Comment by ShaunKulesa** [comment]
@gurchetansingh so i updated all of the crates:
```[dependencies]
vulkano-win = "0.20.0"
winit = "0.24.0"
vulkano = "0.20.0"```
```
````

then i get different errors
```error[E0432]: unresolved import `winit::EventLoop`
 --> src\main.rs:2:5
  |
2 | use winit::EventLoop;
  |     ^^^^^^^---------
  |     |      |
  |     |      help: a similar name exists in the module: `event_loop`
  |     no `EventLoop` in the root

error[E0432]: unresolved import `winit::WindowBuilder`
 --> src\main.rs:3:5
  |
3 | use winit::WindowBuilder;
  |     ^^^^^^^^^^^^^^^^^^^^ no `WindowBuilder` in the root

error[E0433]: failed to resolve: could not find `Event` in `winit`
  --> src\main.rs:16:20
   |
16 |             winit::Event::WindowEvent { event: winit::WindowEvent::CloseRequested, .. } => {
   |                    ^^^^^ could not find `Event` in `winit`

error[E0433]: failed to resolve: could not find `WindowEvent` in `winit`
  --> src\main.rs:16:55
   |
16 |             winit::Event::WindowEvent { event: winit::WindowEvent::CloseRequested, .. } => {
   |                                                       ^^^^^^^^^^^ could not find `WindowEvent` in `winit`

error[E0433]: failed to resolve: use of undeclared type `ControlFlow`
  --> src\main.rs:17:33
   |
17 |                 *control_flow = ControlFlow::Exit;
   |                                 ^^^^^^^^^^^ use of undeclared type `ControlFlow`

error[E0425]: cannot find value `instance` in this scope
 --> src\main.rs:7:71
  |
7 |     let surface = WindowBuilder::new().build_vk_surface(&events_loop, instance.clone()).unwrap();
  |                                                                       ^^^^^^^^ not found in this scope

error[E0433]: failed to resolve: use of undeclared type `Instance`
  --> src\main.rs:11:9
   |
11 |         Instance::new(None, &extensions, None).expect("failed to create Vulkan instance")
   |         ^^^^^^^^ not found in this scope
   |
help: consider importing this struct
   |
1  | use vulkano::instance::Instance;
   |

warning: unused import: `vulkano_win::VkSurfaceBuild`
 --> src\main.rs:1:5
  |
1 | use vulkano_win::VkSurfaceBuild;
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default```


this was the tutorial i used to open a window in Vulkano 
https://vulkano.rs/guide/window

**Comment by gurchetansingh** [comment]
Try winit::event_loop::{ControlFlow, EventLoop}, not winit::Eventloop.

**Comment by ShaunKulesa** [comment]
@gurchetansingh on every winit::Eventloop?

**Comment by gurchetansingh** [comment]
use winit::event_loop::Eventloop instead

**Comment by ShaunKulesa** [comment]
nope now errors to do with importing the stuff you stated in that line.

**Comment by adumbidiot** [comment]
I got one of my projects to work by setting 
```toml
vk-sys = "=0.5.2"
```
Does `0.5.3` contain a breaking change?

**Comment by ShaunKulesa** [comment]
@adumbidiot could you send me the project files? i tried what you said but no difference.

**Comment by adumbidiot** [comment]
I don't use this library directly, only transitively through `conrod_vulkano`. I forked `conrod_vulkano` from master and set `vk-sys = "=0.5.2"` under the dependencies section in the file `conrod/backends/conrod_vulkano/Cargo.toml`. Before, running `cargo test` would fail with the above errors as it would try pulling in `0.5.3`, but pinning the version to `0.5.2` seems to allow tests to pass.

**Comment by Eliah-Lakhin** [comment]
@adumbidiot `vk-sys` contains breaking changes that conflict with `0.19.0`. My bad, vk-sys probably had to be raised to `0.6.0`. Sorry for the issue, I will fix it in the nearest few days(when get back to the project). For now please use `=0.5.2` workaround.

**Comment by WhyNotHugo** [comment]
I'm also trying to get the example to work (related to  #1464 too).

The example seems to have a lot of references to outdated APIs, and older versions no longer build (likely bad pinned dependencies?). There's also references to variables defined in an example a few paragraphs down, which is kinda tricky to figure out as one reads along, and those also have missing parameters.

The closest I've come to is:

```rust
use vulkano::instance::Instance;
use vulkano::instance::Version;
use vulkano_win::VkSurfaceBuild;
use winit::event_loop::EventLoop;
use winit::window::WindowBuilder;

fn main() {
    let instance = Instance::new(
        None,
        Version::V1_1,
        &vulkano_win::required_extensions(),
        None,
    )
    .expect("failed to create Vulkan instance");


    let events_loop = EventLoop::new();
    let surface = WindowBuilder::new()
        .build_vk_surface(&events_loop, instance.clone())
        .unwrap();
}
```

This uses these updated versions which _do_ build:

```toml
[dependencies]
vulkano = "0.27"
vulkano-win = "0.27"
winit = "0.26"
```

Note that `vulkano` **must** be specified too, since the code uses modules from that crate too.

I was about to make a PR to fix the example, but unfortunately I'm stuck getting this error trying to build:

```
error[E0599]: no method named `build_vk_surface` found for struct `WindowBuilder` in the current scope
  --> src/main.rs:16:10
   |
16 |         .build_vk_surface(&events_loop, instance.clone())
   |          ^^^^^^^^^^^^^^^^ method not found in `WindowBuilder`

warning: unused import: `vulkano_win::VkSurfaceBuild`
 --> src/main.rs:3:5
  |
3 | use vulkano_win::VkSurfaceBuild;
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

For more information about this error, try `rustc --explain E0599`.
```

At this point, everything _seems_ correct, and I've no idea why building fails. Any hints?
