### ISSUE TITLE
Unable to pass mat3 into shader correctly

### ISSUE THREAD

**Issue by Tnze** [vulkano-rs/vulkano#1473]
*   Version of vulkano: 0.19 or 0.20
*   OS: MacOS
*   GPU (the selected PhysicalDevice): Intel(R) Iris(TM) Graphics 6100
*   GPU Driver: MoltenVK version 1.1.2. Vulkan version 1.1.162.

Also test on:

*   Version of vulkano: 0.20
*   OS: Windows
*   GPU (the selected PhysicalDevice): GeForce GTX 1060 6GB
*   GPU Driver: Vulkan 1.2.155.

Upload of a reasonably minimal complete `main.rs` file that demonstrates the issue:

 [main.rs.zip](https://github.com/vulkano-rs/vulkano/files/5807514/main.rs.zip)

# Issue

I cannot use a uniform mat3. When I send this to shader:

```rust
Matrix3::new(
        1.0, 0.0, 0.0,
        0.0, 1.0, 0.0,
        0.0, 0.0, 1.0,
).into()
```

It becomes this:

```glsl
mat3(
    1.0, 0.0, 0.0,
    1.0, 0.0, 0.0,
    1.0, 0.0, 0.0
)
```

**Comment by Rua** [comment]
Confusingly, a GLSL shader expects a `mat3` uniform to be sent as three columns of `vec4`, as if it had an extra row (which the shader then ignores), so it wants 12 elements total. By using `.into()` on a 3x3 matrix you are only sending 9, and things get misaligned. You can work around it by converting your matrix to 4x3, then calling `.into()` on that. You may also find the [glsl-layout](https://github.com/rustgd/glsl-layout) crate useful.

**Comment by Tnze** [comment]
This answers my doubts. Thanks very much. I had solved this problem.

  Looks like your solution cannot work because Matrix4x3 cannot be `.into()` a `[[f32; 3]; 3]`. Just guessing, but no testing.  
  I am using `rapier2d::na::Matrix3` and `.fixed_resize(0.0)` it to a `Matrix4` and use `mat4` in the shader. It seems that the math library of the physics engine I use is compatible with it, and it's very convenient for me to use.
