### ISSUE TITLE
Error: vkCreateDevice: VK_KHR_portability_subset must be enabled when calling Device::new

### ISSUE THREAD

**Issue by drhaynes** [vulkano-rs/vulkano#1482]
# Template

*   Version of vulkano: 0.20
*   OS: macOS (using MoltenVK)
*   GPU (the selected PhysicalDevice): GTX 680
*   GPU Driver: 
*   Upload of a reasonably minimal complete `main.rs` file that demonstrates the issue: TODO

# Issue
When trying to create a logical device on macOS, it's giving the following error:

`Validation layer: "Validation Error: [ VUID-VkDeviceCreateInfo-pProperties-04451 ] Object 0: handle = 0x7f8115c2d8f0, type = VK_OBJECT_TYPE_PHYSICAL_DEVICE; | MessageID = 0x3a3b6ca0 | vkCreateDevice: VK_KHR_portability_subset must be enabled because physical device VkPhysicalDevice 0x7f8115c2d8f0[] supports it The Vulkan spec states: If the [VK_KHR_portability_subset] extension is included in pProperties of vkEnumerateDeviceExtensionProperties, ppEnabledExtensions must include \"VK_KHR_portability_subset\". (https://vulkan.lunarg.com/doc/view/1.2.162.1/mac/1.2-extensions/vkspec.html#VUID-VkDeviceCreateInfo-pProperties-04451)"`

`VK_KHR_portability_subset` does not appear to be present in the repo or documentation. Is there 1. A way to detect this is required, and 2. A way to enable it manually?

**Comment by Eliah-Lakhin** [comment]
@drhaynes This is default behavior when the user is trying to use some feature from not-included extension.

> A way to detect this is required

It would shade more light on the issue if you provide a code snippet. It's sometimes tricky and implementation-wise.

> A way to enable it manually

Device extensions(and Instance extensions too) are specifying during initialization: https://github.com/vulkano-rs/vulkano/blob/master/examples/src/bin/triangle.rs#L131 I don't see if we support this particular extension in Vulkano (there is unfortunately only a small subset of Vulkan extensions that we currently support), but if you need this one you can implement it and contribute to the project. It's usually not too difficult, the list of extensions reside here: https://github.com/vulkano-rs/vulkano/blob/master/vulkano/src/device/extensions.rs#L106

**Comment by DaAitch** [comment]
hey,

I read the same on MacOS. According to the vulkan docs, `VK_KHR_portability_subset` has to be set if supported by a device, I made a PR fixing that, but the user doesn't have to check this. It's automatically detected.

Please check.

**Comment by drhaynes** [comment]
Great. Nice that it can be auto detected too.

**Comment by DaAitch** [comment]
@drhaynes This issue should be fixed.
#1489 has landed, but without auto-detection (you can read about it in the PR discussion).

Please check the `debug.rs` [example](https://github.com/vulkano-rs/vulkano/blob/master/examples/src/bin/debug.rs#L124). Error message should now be gone: new fn `DeviceExtension::required_extension(phys)` is now helping.

**Comment by Rua** [comment]
I think this is done now, so this issue can be closed.
