### ISSUE TITLE
CpuAccessibleBuffer::from_data is unsound

### ISSUE THREAD

**Issue by stephan-cr** [vulkano-rs/vulkano#1484]
# Issue

Issue #1478 revealed that [`CpuAccessibleBuffer::from_data`](https://github.com/vulkano-rs/vulkano/blob/63aaa853ff894081a5f93e5cb3a098047d078094/vulkano/src/buffer/cpu_access.rs#L104) is unsound. It could be called like this:

```rust
let data_out: Vec<f64> = vec![0.0; data_in_size];
let data_buffer_out = CpuAccessibleBuffer::from_data(
    device.clone(),
    BufferUsage::all(),
    false,
    data_out
).expect("failed to create buffer");
```

The code example above compiles just fine, but it shouldn't. At runtime it invokes undefined behavior. This is because, `from_data` treats `data_out` as a flat memory structure, which can be read or written by simply taking its size and copying its bits.

The [documentation for `from_data`](https://docs.rs/vulkano/0.20.0/vulkano/buffer/cpu_access/struct.CpuAccessibleBuffer.html#method.from_data) states that

> Only allowed for sized data.

but `Vec` seems to be `Sized` as well.

Not sure which kind of types can safely be allowed for `from_data`, maybe all types which implement [`Copy`](https://doc.rust-lang.org/std/marker/trait.Copy.html).

**Comment by jdrcode** [comment]
I think the data that is being copied over is the 24 bytes used to describe the Vec. The pointer, size, and capacity.
mem::size_of::<T>() returns 24 bytes if you put in a Vec. I don't think ptr::write will call for a slice or the pointer to the data you're actually interested in. 

Copy seems like a good trait to restrict the type to.

**Comment by stephan-cr** [comment]
@jdrcode Thank you for your feedback.

> I think the data that is being copied over is the 24 bytes used to describe the Vec. The pointer, size, and capacity.
mem::size_of::() returns 24 bytes if you put in a Vec, so in that way Vec is sized.

Exactly.

> Copy seems like a good trait to restrict the type to.

Yes, that's what I think as well, after some research. Someone might argue, that there is some copy overhead, but I found out, that LLVM elides copies if possible (haven't found a good primary source for this). The only downside is, that the [documentation](https://vulkano.rs/guide/buffer-creation) needs to be adapted, like this:

```rust
#[derive(Copy)]
struct MyStruct {
    a: u32,
    b: bool,
}

let data = MyStruct { a: 5, b: true };

let buffer = CpuAccessibleBuffer::from_data(device.clone(), BufferUsage::all(), false,
                                            data).unwrap();
```
