### ISSUE TITLE
Make image views a separate type from images

### ISSUE THREAD

**Issue by Rua** [vulkano-rs/vulkano#1492]
Mentioned in https://github.com/vulkano-rs/vulkano/issues/1392#issuecomment-653622619, https://github.com/vulkano-rs/vulkano/pull/1444#issue-529094324, https://github.com/vulkano-rs/vulkano/pull/1444#discussion_r572160885 and https://github.com/vulkano-rs/vulkano/pull/1449#issuecomment-740042773. I propose making a separate `ImageView` type, that is created from an image (presumably with an `Arc`, as one image can have many views). Images would no longer contain image views inside them, but instead the user would have to create a view, if their use case requires it.

This would lift some restrictions on particular use cases. Vulkano currently creates views for every image, whether a view is needed or not, and views bring limitations with them. In particular, certain image usage flags are required when creating a view, but not every image needs such usage in practice (e.g. swapchain images that are only transferred onto).

The new type would be a safe wrapper around the current `UnsafeImageView`, and most likely the safety checks currently in the latter should be in this new type, and implemented in a better way than with `assert`s. This follows the Vulkano practice that the low-level "unsafe" types do not check for correctness, but leave this to higher-level wrappers. `ImageViewAccess` would naturally no longer be implemented on the images, but rather on this new type, although it may no longer be necessary if there is only one single view type.

**Comment by Eliah-Lakhin** [comment]
I like this idea :+1:
