### ISSUE TITLE
Dimensions versus ImageDimensions, what's their function? Can they be merged?

### ISSUE THREAD

**Issue by Rua** [vulkano-rs/vulkano#1494]
Vulkano has had two types for representing the dimensions of an image, `Dimensions` and `ImageDimensions`. Originally there was just one, but the split between these types was added already in 2016 in #260.

Neither of the types is documented, so it's not clear what their function is, nor which is to be used for which purpose. The result is a lot of duplication and an IMO very confusing situation. For example, `ImageAccess::dimensions()` and `UnsafeImage::dimensions()` both give you an `ImageDimensions`, while `ImageViewAccess::dimensions()` and `ImmutableImage::dimensions()` return `Dimensions`. `Dimensions` has a function to convert to `ImageDimensions`, but there is no function to perform the reverse operation. Either that simply never got added, or the conversion is lossy and `Dimensions` contains more information.

I would find it a lot clearer if there was just one type, or if the purpose of each one were documented. Does anyone who has worked with Vulkano longer have any idea what's going on? If there is a clear distinction, can they be renamed to make that clearer? If nobody knows, I'm going to try changing all instances of `ImageDimensions` to `Dimensions` in a future PR.

**Comment by Eliah-Lakhin** [comment]
@Rua I agree there seem to be some inconsistency in implementation or maybe naming.  `vulkano::image::Dimensions` is capable of describing wider range of options. This might be a reason why they were split. So, maybe we can't just merge them together. Also if I not mistaken they used not only in function returns but in some function arguments too.

I don't mind about refactoring, but just a few brief notes to take into consideration.

**Comment by Rua** [comment]
I had another look at the situation and these are my observations:
- Vulkan's `vkImage` type fits `ImageDimensions` perfectly in the data it needs.
- Vulkan's `vkImageView` fits `ViewType`, which has the same enum variants as `Dimensions` but without the numbers.

A `Dimensions` could therefore be understood as a combination of `ImageDimensions` and `ViewType`, so it would only be needed in contexts that work with image views. The `cubemap_compatible` flag on `ImageDimensions` is an oddity, however. This is really a property of the image object, and has nothing to do with dimensions.

All in all I propose the following changes:

- `Dimensions` is renamed to `ImageViewDimensions`.
- `ViewType` is renamed `ImageViewType` just for clarity's sake.
- The `cubemap_compatible` member is removed from `ImageDimensions::Dim2d`.
- `UnsafeImage` takes a cube compatibility flag upon creation, either as a simple `bool` or, perhaps more future-proof, as a `struct`. `UnsafeImageView` checks for this flag when the user requests a cube map.

**Comment by Rua** [comment]
If #1499 is merged, then the point is moot because it removes `Dimensions` altogether.
