### ISSUE TITLE
Updating from 0.20 -> 0.21

### ISSUE THREAD

**Issue by korteland** [vulkano-rs/vulkano#1505]
*   Version of vulkano: 0.21.0
*   OS: Linux
*   GPU (the selected PhysicalDevice): GTX 1080
*   GPU Driver: proprietary nvidia

# Issue

Sorry if this is the wrong place - I had a look on Gitter and the most recent message I saw was a recommendation to open an issue instead of posting there.

The changelog states that "On AutoCommandBufferBuilder and SyncCommandBufferBuilder, the update_buffer method now takes data by reference". I have some code written for a previous version of vulkano that looks like this:

```
fn get_uniform_buffer() -> UniformBufferObject {
    ...
    UniformBufferObject { foo, bar, baz }
}

...
cmd_buf_builder.update_buffer(..., get_uniform_buffer());
...
```
Now that `update_buffer` takes a reference to the `data` argument, how is this meant to work? It no longer takes ownership of `data`, so in this case the "obvious" fix of writing `cmd_buf_builder.update_buffer(..., &get_uniform_buffer())` leads to lifetime issues, since it's a temporary and `update_buffer` needs `data` to have a lifetime of `'static`.

I read the documentation for both `update_buffer` and `SafeDeref` - it doesn't seem like implementing `SafeDeref` is the way to go here, but I couldn't find any code that uses it, and it's unsafe which made me think twice. I also couldn't find any users of `update_buffer` in the `examples/` directory.

I don't use Rust particularly often, so I might be missing an obvious ownership gotcha here - apologies if that's the case.

As an aside - I've found the rest of the library to be very pleasant to work with. Thanks for all your work on vulkano.

**Comment by Rua** [comment]
Pinging @Arc-blroth as the one who made that change.

**Comment by stephan-cr** [comment]
@korteland I think you should be able put the result of `get_uniform_buffer()` into an `Arc`, like this:

```rust
cmd_buf_builder.update_buffer(..., Arc::new(get_uniform_buffer()));
```

`Box` should be possible as well, see https://docs.rs/vulkano/0.21.0/vulkano/trait.SafeDeref.html#foreign-impls.

I haven't tried it out, I merely derived that from the type signature.

**Comment by korteland** [comment]
@stephan-cr ah, my inexperience is showing. you're totally right and that fixed my problem immediately. thanks!

**Comment by Arc-blroth** [comment]
> Pinging @Arc-blroth as the one who made that change.

Whoops, sorry for not seeing this until now! Stephan's solution is correct - wrapping the data in a Box or Arc should work. On that note, we should probably write some better documentation for SafeDeref for the future.

**Comment by Eliah-Lakhin** [comment]
@korteland Also, I think you can use an ordinary reference to the `get_uniform_buffer()` object in your code too. Creating an `Arc` is not necessary.

**Comment by korteland** [comment]
@Eliah-Lakhin i mentioned that in my original comment, it has lifetime issues. the compiler complains that doing `cmd_buf_builder.update_buffer(..., &get_uniform_buffer())` "creates a temporary which is freed while still in use".
