### ISSUE TITLE
Should Vulkano try to support multiple Vulkan core versions?

### ISSUE THREAD

**Issue by Rua** [vulkano-rs/vulkano#1509]
Vulkano is currently written to require version 1.1 of the spec. However, several parts of the code use extensions that were promoted to core in 1.1. In some cases Vulkano has alternative code paths depending on whether such a promoted extension is supported, for example in the case `VK_KHR_get_physical_device_properties2` in the instance creation code. The question I have is what to do with such cases now and in the future.

Choosing a specific Vulkan version makes work easier for Vulkano, as it can make certain assumptions about what is available and there is less to maintain. Alternative code paths such as the one mentioned above can be eliminated. On the other hand, allowing the user to choose is more flexible, and makes Vulkano less opinionated. But it also means there have to be alternative code paths to support different levels of support on the end user's machine. It may be infeasible to support several versions for other reasons I'm not aware of.

So is each Vulkano version intended for just one specific Vulkan version, or is it desirable to allow the user to choose in the future? Whatever is ultimately chosen, this should be documented for the user.

**Comment by AustinJ235** [comment]
I have looked into this before, https://github.com/vulkano-rs/vulkano/issues/1365. We'd need someway to get the version to vulkano-shaders which is independent from vulkano pretty much.

**Comment by Rua** [comment]
What do you mean by "get the version to vulkano-shaders"?

**Comment by AustinJ235** [comment]
The vulkan version used by vulkano-shaders/shaderc is hardcoded atm. vulkano-shaders doesn't currently have a means of accessing the vulkano instance therefore no access to knowing what version is set. If you looked at the issue I linked, it contains the two locations where the vulkano version is set from. 

I purposed adding an additional optional field to the shader! macro. I feel this is kinda clunky though.

**Comment by Rua** [comment]
In principle, the version passed to Vulkano-shaders is a compile-time constant. That means whatever version is given to Vulkano itself during Vulkan initialisation should also be a compile-time constant, in order to match the shaders. Is there some kind of user-specified configuration option that can be passed to the compiler of both crates? Something the user can set in their Cargo.toml to tell both Vulkano and Vulkano-shaders what Vulkan version to compile for?

**Comment by Rua** [comment]
@AustinJ235 @Eliah-Lakhin Once #1569 lands, SPIR-V and Vulkan version will be checked against each other, so there is no longer a reason to synchronise the two. That means that Vulkano-shaders can emit whatever SPIR-V version the user wants. I asked around on the Vulkan Discord, and there appears to be no reason for using an older SPIR-V version if your shader doesn't need the newer features. Newer Vulkan versions can read older shaders just fine. The shader compiler that Vulkano uses defaults to SPIR-V 1.0 as well.

Therefore I propose changing the `shader!` macro so that its behaviour mirrors that of the compiler: it will emit SPIR-V 1.0 by default, and it will get two additional parameters, `vulkan-version` and `spirv-version`. These parameters allow the user to specify what code the compiler should emit, but the idea is that for shaders that use only SPIR-V 1.0 features, these parameters can be left unspecified. The compiler will catch shader code that needs a higher version, and Vulkano itself will catch shaders with a version too high for the Vulkan version, so Vulkano doesn't need to worry about that.

**Comment by AustinJ235** [comment]
I think giving the user the option of using their own version is great. I have wanted to implement that somehow in the past, but never really thought of a good way to do it. I always kept the vulkan/spirv version lagged behind to avoid conflict with drivers. The open source drivers on the linux side of things tend to be a bit behind in terms of version so wanted to avoid issues for those users.

**Comment by Rua** [comment]
This is now implemented, so I'm closing this issue.
