### ISSUE TITLE
Remove the format specification structs

### ISSUE THREAD

**Issue by Rua** [vulkano-rs/vulkano#1518]
At the moment, the `format` module in Vulkano has two different ways to specify formats: either the `Format` enum, or a long list of individual structs. Both of these do the exact same thing. I feel it's kinda silly to have both of these existing side by side, and would like to remove one of them, specifically the individual structs. The `Format` enum would become the only way to specify formats.

It would make downstream code in Vulkano a bit simpler because it doesn't have to deal with the different ways the user may want to specify formats. `ImmutableImage` for example has an `F` type parameter for the format, which is unneeded if `Format` is always used. Some of the traits in the `format` module may no longer be needed either.

**Comment by Eliah-Lakhin** [comment]
@Rua Yes, I totally agree. In most cases we current use `Image<Format>` form, and the type parameter doesn't actually distinct anything between two specializations. I believe it should be removed from the signature.

**Comment by Rua** [comment]
I tried this out and then found that there is one specific case that causes trouble. The `StrongStorage` trait is implemented for a subset of the format structs, but not for the depth/stencil formats. And it's not implemented at all for the enum. The only thing that uses this trait is the `BufferView` constructor, but I can't figure out why it has this particular restriction against depth/stencil formats. The Vulkan standard doesn't seem to say anything about this class of formats in relation to buffer views, other than that support is implementation-dependent.

Aside from that, the trait prevents using a buffer that has the "wrong" element type for a format, e.g. `u16` for the `R8G8B8A8Unorm` format. While this is theoretically useful, in practice there are way more formats than there are Rust types, and not every format necessarily maps cleanly to a Rust type. `AutoCommandBufferBuilder::copy_buffer_to_image`, another function that translates buffers to images, accepts any buffer element type that is implemented by `AcceptsPixels`, which is a long list in the case of the `Format` enum!

So if I implement this, I'm going to get rid of `StrongStorage` and replace it with `AcceptsPixels`.
