### ISSUE TITLE
[Troubleshooting] Migration to Version "0.22" ... "0.24"

### ISSUE THREAD

**Issue by Eliah-Lakhin** [vulkano-rs/vulkano#1527]
The [recent releases](https://github.com/vulkano-rs/vulkano/blob/master/CHANGELOG_VULKANO.md) had a lot of breaking, but important changes. The migration could be a bit confusing for the users at the beginning. Here is a summary of the most notable things in the high level API to review during migration:

 - [Since 0.22.0] The Image and ImageView interfaces were split. Images are no longer implement View interface by default.

    If you face **compilation errors like** ```the trait bound `AttachmentImage: SafeDeref` is not satisfied``` in the DescriptorSet builder, you need to pass ImageView wrapper of the attachment instead of attachment itself, e.g:

    ```rust
     let image: ImmutableImage<..> = ...;
     let view = ImageView::new(image).unwrap();

     let set = PersistentDescriptorSet::start(layout.clone())
       .add_sampled_image(view, ...) // view instead of image
       .unwrap()
       .build()
       .unwrap();
    ```
 - [Since 0.22.0] `ImageDimensions` and `Dimensions` interfaces **joined together**. Always use new `ImageDimensions` interface.
 - [Since 0.22.0] Vulkano Shader macro from now on generates named layouts. **Default layout type name** from the shader's module is `MainLayout` instead of just `Layout` when using glsl as a source.
 - [Since 0.22.0] ~If glsl code contains unused layout bindings(never referred in the glsl source code) they are excluded from the descriptor sets. If the **DescriptorSet builder fails to build**, review unused bindings in the glsl source code.~ (this is no longer relevant **since 0.23.0**. In 0.23.0 this feature is optional).
 - [Since 0.22.0] If you have read only buffers in glsl code that are not tagged as `readonly`, from now on they must be tagged to ensure Vulkano puts barriers correctly.
 - [Since 0.23.0] `framebuffer` module was renamed to `render_pass`. Most of the high level API is more or less the same, but you need to refactor imports module in your code accordingly.
 - [Since 0.23.0] `AutoCommandBufferBuilder::new` renamed to`AutoCommandBufferBuilder::primary/secondary`. For `primary` form there is a new additional 3rd parameter. Use `CommandBufferUsage::MultipleSubmit` for this parameter to fulfill the same behavior you previously had with old `new` constructor.
 - [Since 0.23.0] `Format` template-type removed from all Image constructors(as it was practically useless in most cases). For example instead of `Arc<StorageImage<Format>>` you can write just `Arc<StorageImage>`.
 - [Since 0.23.0] `Swapchain::new` replaced with `Swapchain::start` and the Swapchain from now on is constructing within a builder with more precise named builder functions, e.g.:
   ```rust
     let (swapchain, swapchain_images) = Swapchain::start(queue.device().clone(), surface.clone())
       .num_images(surface_capabilities.min_image_count)
       .format(swapchain_format.0)
       .dimensions(surface_dimensions)
       .build()
       .unwrap();
   ```
 - **[Since 0.24.0]** Vulkano is now uses Ash instead of vk-sys(we still maintain vk-sys for back compatibility for a while).
 - **[Since 0.24.0]** `PhysicalDevice` properties structure has been changed and unified. Most of the properties are now fetching from the `PhysicalDevice::properties` function, and returning complete list of available features of the device based on Vulkan specification.

   **Properties access cheatsheet**:
      * `device.name()` became `device.properties().device_name()`;
      * `device.extended_properties().subgroup_size` became `device.properties().subgroup_size`;
      * `device.ty()` became `device.properties().device_type` (returning an `Option` with the same values from `PhysicalDeviceType` enum values).
 - **[Since 0.24.0]** Vulkan, SpirV and Instance **versions must be explicitly specified**:
   * `Instance::new(None, Version::major_minor(1, 1), extensions, layers)`. Here `Version` is `vulkano::Version`;
   * ```vulkano_shaders::shader! { ty: "compute",path: "./shader.glsl", vulkan_version: "1.1", spirv_version: "1.3" }```.

**Comment by Rua** [comment]
Do you want to keep this open?
