### ISSUE TITLE
Using samplerCube with PersistentDescriptorSet

### ISSUE THREAD

**Issue by hellux** [vulkano-rs/vulkano#1539]
I am trying to add an `ImmutableImage` for a `samplerCube` cubemap to a `PersistentDescriptionSet`and I can't manage to do it without failing requirements set by Vulkano. I am creating an `ImageView` with `ImageViewType::Cubemap` and at `image/view.rs:132` it is enforced that the `cube_compatible` flag is set and `array_layers` is 6:
```
            (ImageViewType::Cubemap, ImageDimensions::Dim2d { .. }, 6, _)
               if flags.cube_compatible =>
            {
              ()
            }
```
When adding the image view to a `PersistentDescriptionSet` with `add_sampled_image`, the descriptor of the binding
```
layout(binding = 0) uniform samplerCube cubemap;
```
returned at `descriptor/descriptor_set/persistent.rs:770` has a `CombinedImageSampler` that is `NonArrayed`:
```
&desc = DescriptorDesc {
    ty: CombinedImageSampler(
        DescriptorImageDesc {
            sampled: true,
            dimensions: Cube,
            format: None,
            multisampled: false,
            array_layers: NonArrayed,
        },
    ),
    array_count: 1,
    stages: ShaderStages {
        vertex: false,
        tessellation_control: false,
        tessellation_evaluation: false,
        geometry: false,
        fragment: true,
        compute: false,
    },
    readonly: true,
}
```
The `image_match_desc` function is then called which returns an error because the image is `NonArrayed` but has 6 layers:
```
        DescriptorImageDescArray::NonArrayed => {                                               
            if num_layers != 1 {
                return Err(PersistentDescriptorSetError::ArrayLayersMismatch {   
                    expected: 1,
                    obtained: num_layers,                                        
                }); 
            }   
        }   
```

So am I missing something or is it impossible to add a sampled cubemap to a `PersistentDescriptorSet`? Cubemaps seem to work fine after removing the last requirement.

Example main file that triggers the error: [main.txt](https://github.com/vulkano-rs/vulkano/files/6259159/main.txt).

**Comment by Rua** [comment]
I think that the `DescriptorImageDesc` should really set the number of array layers to 6 here? That would be a bug in Vulkano-shaders.

**Comment by hellux** [comment]
As the specification says that it is not an array but has 6 layers, I am not sure what is an appropriate value for the `array_layers` field in the descriptor. Modifying `image_match_desc` might be a better idea, yes.
