### ISSUE TITLE
wgpu and Vulkano safety descriptions in README are incorrect

### ISSUE THREAD

**Issue by kvark** [vulkano-rs/vulkano#1549]
The "Comparison" says:
> Partially unsafe high-level Rust API with multiple backends.

I don't know why "Partially unsafe" part is here. Is this referring to `unsafe fn create_surface`?
I don't think a single entry point used at initialization is a good reason to describe the whole API as "Partially unsafe". It's not like any other library (including Vulkano) does any steps for surface creation to make it safer.
Besides, it can be considered a bug, not a design, see https://github.com/gfx-rs/wgpu-rs/issues/674
So conceptually, wgpu *is* fully safe.

And for Vulkano the description says:
> Fully safe high-level Rust API wrapping Vulkan/Metal APIs.

This is wrong on many levels. Vulkano isn't wrapping a Metal API at all, this is just plain wrong.
The "fully safe" part can *at most* be said about the host API usage. But shaders are part of the API, and I can do a whole lot of unsafe stuff in shaders, writing to random memory, potentially. So Vulkano API as a whole is not safe.
You can say specifically that "it's host Vulkan API usage safe" or something like this, taking a note about shaders - that would be fair.

**Comment by Eliah-Lakhin** [comment]
@kvark Thank you for review.

Due to controversial opinions on the "safety" topic I decided to remove mentions of API unsafety from comparison table.
