### ISSUE TITLE
Image Loading Fails on Intel Xe Graphics

### ISSUE THREAD

**Issue by Cognoscan** [vulkano-rs/vulkano#1551]
*   Version of vulkano: v0.22.0
*   OS: ArchLinux - Linux version 5.11.11-arch1-1 (linux@archlinux) (gcc (GCC) 10.2.0, GNU ld (GNU Binutils) 2.36.1)
*   GPU (the selected PhysicalDevice): Intel(R) Xe Graphics (TGL GT2) (type: IntegratedGpu)
*   GPU Driver: vulkan-intel package, 21.0.1-1
*   Upload of a reasonably minimal complete `main.rs` file that demonstrates the issue: See the image example in this repo

# Issue

Trying to load images goes poorly when trying to do so on an Intel Xe Graphics card. The image becomes almost completely garbled, though it does still load some image portions. See the attached images - one shows the example Rust logo failing to load properly, the other shows a piece of code I put together that loads an image of my dog. It's easier to tell with the dog image, but it looks like portions of the image are being loaded, but something about the image structure is wrong. Only strong edges seem to be preserved, which to me hints at some kind of alternate sub-sample friendly memory layout.

I'm reasonably sure this isn't a graphics driver issue, as the [Vulkan texture loading examples](https://github.com/KhronosGroup/Vulkan-Samples/blob/master/samples/api/texture_loading/texture_loading.cpp) in C++ work fine.

If I switch to using a `StorageImage` and read the data back out to a buffer, the buffer contains data different from what I originally used to create the image. Instead, it appears to match up with the pixels as displayed.

I think this is also tangentially reported in #1468 - in that issue, the reporter mentions their integrated graphics card produces "confetti", but things work fine when using a dedicated card. That sounds like the same issue I'm having here.

My best guess so far is that the image memory barriers used to transition between layouts aren't set up right. Somehow we're copying data to the image when its layout is not correct for that operation, or it is getting treated as though its layout is different than what is actually in memory. I've done some probing into the Vulkan API calls, looking for differences between how Vulkano and the C++ example works, and that's about all I've come up with so far... well, that and the memory allocations & mapping seem to be handled slightly differently. The copy operations and buffer initialization seem to be basically the same.

The command buffer API calls from Vulkano are:
```
Thread 0, Frame 0, Time 17382 us:
vkBeginCommandBuffer(commandBuffer, pBeginInfo) returns VkResult VK_SUCCESS (0):
    commandBuffer:                  VkCommandBuffer = 0x563c2d05cd80
    pBeginInfo:                     const VkCommandBufferBeginInfo* = 0x7ffc251f8168:
        sType:                          VkStructureType = VK_STRUCTURE_TYPE_COMMAND_BUFFER_BEGIN_INFO (42)
        pNext:                          const void* = NULL
        flags:                          VkCommandBufferUsageFlags = 0
        pInheritanceInfo:               const VkCommandBufferInheritanceInfo* = UNUSED

Thread 0, Frame 0, Time 17430 us:
vkCmdPipelineBarrier(commandBuffer, srcStageMask, dstStageMask, dependencyFlags, memoryBarrierCount, pMemoryBarriers, bufferMemoryBarrierCount, pBufferMemoryBarriers, imageMemoryBarrierCount, pImageMemoryBarriers) returns void:
    commandBuffer:                  VkCommandBuffer = 0x563c2d05cd80
    srcStageMask:                   VkPipelineStageFlags = 8192 (VK_PIPELINE_STAGE_BOTTOM_OF_PIPE_BIT)
    dstStageMask:                   VkPipelineStageFlags = 4096 (VK_PIPELINE_STAGE_TRANSFER_BIT)
    dependencyFlags:                VkDependencyFlags = 1 (VK_DEPENDENCY_BY_REGION_BIT)
    memoryBarrierCount:             uint32_t = 0
    pMemoryBarriers:                const VkMemoryBarrier* = 0x7ffc251fd4a8
    bufferMemoryBarrierCount:       uint32_t = 0
    pBufferMemoryBarriers:          const VkBufferMemoryBarrier* = 0x7ffc251fd4e8
    imageMemoryBarrierCount:        uint32_t = 1
    pImageMemoryBarriers:           const VkImageMemoryBarrier* = 0x7ffc251fd6b8
        pImageMemoryBarriers[0]:        const VkImageMemoryBarrier = 0x7ffc251fd6b8:
            sType:                          VkStructureType = VK_STRUCTURE_TYPE_IMAGE_MEMORY_BARRIER (45)
            pNext:                          const void* = NULL
            srcAccessMask:                  VkAccessFlags = 0 (VK_ACCESS_NONE_KHR)
            dstAccessMask:                  VkAccessFlags = 4096 (VK_ACCESS_TRANSFER_WRITE_BIT)
            oldLayout:                      VkImageLayout = VK_IMAGE_LAYOUT_UNDEFINED (0)
            newLayout:                      VkImageLayout = VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL (7)
            srcQueueFamilyIndex:            uint32_t = 4294967295
            dstQueueFamilyIndex:            uint32_t = 4294967295
            image:                          VkImage = 0x563c2d06fbb0
            subresourceRange:               VkImageSubresourceRange = 0x7ffc251fd6e8:
                aspectMask:                     VkImageAspectFlags = 1 (VK_IMAGE_ASPECT_COLOR_BIT)
                baseMipLevel:                   uint32_t = 0
                levelCount:                     uint32_t = 1
                baseArrayLayer:                 uint32_t = 0
                layerCount:                     uint32_t = 1

Thread 0, Frame 0, Time 17720 us:
vkCmdCopyBufferToImage(commandBuffer, srcBuffer, dstImage, dstImageLayout, regionCount, pRegions) returns void:
    commandBuffer:                  VkCommandBuffer = 0x563c2d05cd80
    srcBuffer:                      VkBuffer = 0x563c2d057030
    dstImage:                       VkImage = 0x563c2d06fbb0
    dstImageLayout:                 VkImageLayout = VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL (7)
    regionCount:                    uint32_t = 1
    pRegions:                       const VkBufferImageCopy* = 0x7ffc251fc178
        pRegions[0]:                    const VkBufferImageCopy = 0x7ffc251fc178:
            bufferOffset:                   VkDeviceSize = 0
            bufferRowLength:                uint32_t = 0
            bufferImageHeight:              uint32_t = 0
            imageSubresource:               VkImageSubresourceLayers = 0x7ffc251fc188:
                aspectMask:                     VkImageAspectFlags = 1 (VK_IMAGE_ASPECT_COLOR_BIT)
                mipLevel:                       uint32_t = 0
                baseArrayLayer:                 uint32_t = 0
                layerCount:                     uint32_t = 1
            imageOffset:                    VkOffset3D = 0x7ffc251fc198:
                x:                              int32_t = 0
                y:                              int32_t = 0
                z:                              int32_t = 0
            imageExtent:                    VkExtent3D = 0x7ffc251fc1a4:
                width:                          uint32_t = 93
                height:                         uint32_t = 93
                depth:                          uint32_t = 1

Thread 0, Frame 0, Time 18375 us:
vkCmdPipelineBarrier(commandBuffer, srcStageMask, dstStageMask, dependencyFlags, memoryBarrierCount, pMemoryBarriers, bufferMemoryBarrierCount, pBufferMemoryBarriers, imageMemoryBarrierCount, pImageMemoryBarriers) returns void:
    commandBuffer:                  VkCommandBuffer = 0x563c2d05cd80
    srcStageMask:                   VkPipelineStageFlags = 4096 (VK_PIPELINE_STAGE_TRANSFER_BIT)
    dstStageMask:                   VkPipelineStageFlags = 1 (VK_PIPELINE_STAGE_TOP_OF_PIPE_BIT)
    dependencyFlags:                VkDependencyFlags = 1 (VK_DEPENDENCY_BY_REGION_BIT)
    memoryBarrierCount:             uint32_t = 0
    pMemoryBarriers:                const VkMemoryBarrier* = 0x7ffc251fc748
    bufferMemoryBarrierCount:       uint32_t = 0
    pBufferMemoryBarriers:          const VkBufferMemoryBarrier* = 0x7ffc251fc788
    imageMemoryBarrierCount:        uint32_t = 1
    pImageMemoryBarriers:           const VkImageMemoryBarrier* = 0x7ffc251fc958
        pImageMemoryBarriers[0]:        const VkImageMemoryBarrier = 0x7ffc251fc958:
            sType:                          VkStructureType = VK_STRUCTURE_TYPE_IMAGE_MEMORY_BARRIER (45)
            pNext:                          const void* = NULL
            srcAccessMask:                  VkAccessFlags = 4096 (VK_ACCESS_TRANSFER_WRITE_BIT)
            dstAccessMask:                  VkAccessFlags = 0 (VK_ACCESS_NONE_KHR)
            oldLayout:                      VkImageLayout = VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL (7)
            newLayout:                      VkImageLayout = VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL (5)
            srcQueueFamilyIndex:            uint32_t = 4294967295
            dstQueueFamilyIndex:            uint32_t = 4294967295
            image:                          VkImage = 0x563c2d06fbb0
            subresourceRange:               VkImageSubresourceRange = 0x7ffc251fc988:
                aspectMask:                     VkImageAspectFlags = 1 (VK_IMAGE_ASPECT_COLOR_BIT)
                baseMipLevel:                   uint32_t = 0
                levelCount:                     uint32_t = 1
                baseArrayLayer:                 uint32_t = 0
                layerCount:                     uint32_t = 1

Thread 0, Frame 0, Time 18417 us:
vkEndCommandBuffer(commandBuffer) returns VkResult VK_SUCCESS (0):
    commandBuffer:                  VkCommandBuffer = 0x563c2d05cd80
```

Compare and contrast with the API calls from the C++ example:
```
Thread 0, Frame 0, Time 23076 us:
vkBeginCommandBuffer(commandBuffer, pBeginInfo) returns VkResult VK_SUCCESS (0):
    commandBuffer:                  VkCommandBuffer = 0x55a6ab3b7280
    pBeginInfo:                     const VkCommandBufferBeginInfo* = 0x7ffcd4cd7000:
        sType:                          VkStructureType = VK_STRUCTURE_TYPE_COMMAND_BUFFER_BEGIN_INFO (42)
        pNext:                          const void* = NULL
        flags:                          VkCommandBufferUsageFlags = 1 (VK_COMMAND_BUFFER_USAGE_ONE_TIME_SUBMIT_BIT)
        pInheritanceInfo:               const VkCommandBufferInheritanceInfo* = UNUSED

Thread 0, Frame 0, Time 23101 us:
vkCmdPipelineBarrier(commandBuffer, srcStageMask, dstStageMask, dependencyFlags, memoryBarrierCount, pMemoryBarriers, bufferMemoryBarrierCount, pBufferMemoryBarriers, imageMemoryBarrierCount, pImageMemoryBarriers) returns void:
    commandBuffer:                  VkCommandBuffer = 0x55a6ab3b7280
    srcStageMask:                   VkPipelineStageFlags = 16384 (VK_PIPELINE_STAGE_HOST_BIT)
    dstStageMask:                   VkPipelineStageFlags = 4096 (VK_PIPELINE_STAGE_TRANSFER_BIT)
    dependencyFlags:                VkDependencyFlags = 0
    memoryBarrierCount:             uint32_t = 0
    pMemoryBarriers:                const VkMemoryBarrier* = NULL
    bufferMemoryBarrierCount:       uint32_t = 0
    pBufferMemoryBarriers:          const VkBufferMemoryBarrier* = NULL
    imageMemoryBarrierCount:        uint32_t = 1
    pImageMemoryBarriers:           const VkImageMemoryBarrier* = 0x7ffcd4cd7020
        pImageMemoryBarriers[0]:        const VkImageMemoryBarrier = 0x7ffcd4cd7020:
            sType:                          VkStructureType = VK_STRUCTURE_TYPE_IMAGE_MEMORY_BARRIER (45)
            pNext:                          const void* = NULL
            srcAccessMask:                  VkAccessFlags = 0 (VK_ACCESS_NONE_KHR)
            dstAccessMask:                  VkAccessFlags = 4096 (VK_ACCESS_TRANSFER_WRITE_BIT)
            oldLayout:                      VkImageLayout = VK_IMAGE_LAYOUT_UNDEFINED (0)
            newLayout:                      VkImageLayout = VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL (7)
            srcQueueFamilyIndex:            uint32_t = 0
            dstQueueFamilyIndex:            uint32_t = 0
            image:                          VkImage = 0x55a6ab3297d0
            subresourceRange:               VkImageSubresourceRange = 0x7ffcd4cd7050:
                aspectMask:                     VkImageAspectFlags = 1 (VK_IMAGE_ASPECT_COLOR_BIT)
                baseMipLevel:                   uint32_t = 0
                levelCount:                     uint32_t = 1
                baseArrayLayer:                 uint32_t = 0
                layerCount:                     uint32_t = 1

Thread 0, Frame 0, Time 23515 us:
vkCmdCopyBufferToImage(commandBuffer, srcBuffer, dstImage, dstImageLayout, regionCount, pRegions) returns void:
    commandBuffer:                  VkCommandBuffer = 0x55a6ab3b7280
    srcBuffer:                      VkBuffer = 0x55a6ab325a50
    dstImage:                       VkImage = 0x55a6ab3297d0
    dstImageLayout:                 VkImageLayout = VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL (7)
    regionCount:                    uint32_t = 1
    pRegions:                       const VkBufferImageCopy* = 0x55a6ab4661c0
        pRegions[0]:                    const VkBufferImageCopy = 0x55a6ab4661c0:
            bufferOffset:                   VkDeviceSize = 0
            bufferRowLength:                uint32_t = 0
            bufferImageHeight:              uint32_t = 0
            imageSubresource:               VkImageSubresourceLayers = 0x55a6ab4661d0:
                aspectMask:                     VkImageAspectFlags = 1 (VK_IMAGE_ASPECT_COLOR_BIT)
                mipLevel:                       uint32_t = 0
                baseArrayLayer:                 uint32_t = 0
                layerCount:                     uint32_t = 1
            imageOffset:                    VkOffset3D = 0x55a6ab4661e0:
                x:                              int32_t = 0
                y:                              int32_t = 0
                z:                              int32_t = 0
            imageExtent:                    VkExtent3D = 0x55a6ab4661ec:
                width:                          uint32_t = 512
                height:                         uint32_t = 256
                depth:                          uint32_t = 1

Thread 0, Frame 0, Time 24231 us:
vkCmdPipelineBarrier(commandBuffer, srcStageMask, dstStageMask, dependencyFlags, memoryBarrierCount, pMemoryBarriers, bufferMemoryBarrierCount, pBufferMemoryBarriers, imageMemoryBarrierCount, pImageMemoryBarriers) returns void:
    commandBuffer:                  VkCommandBuffer = 0x55a6ab3b7280
    srcStageMask:                   VkPipelineStageFlags = 4096 (VK_PIPELINE_STAGE_TRANSFER_BIT)
    dstStageMask:                   VkPipelineStageFlags = 128 (VK_PIPELINE_STAGE_FRAGMENT_SHADER_BIT)
    dependencyFlags:                VkDependencyFlags = 0
    memoryBarrierCount:             uint32_t = 0
    pMemoryBarriers:                const VkMemoryBarrier* = NULL
    bufferMemoryBarrierCount:       uint32_t = 0
    pBufferMemoryBarriers:          const VkBufferMemoryBarrier* = NULL
    imageMemoryBarrierCount:        uint32_t = 1
    pImageMemoryBarriers:           const VkImageMemoryBarrier* = 0x7ffcd4cd7020
        pImageMemoryBarriers[0]:        const VkImageMemoryBarrier = 0x7ffcd4cd7020:
            sType:                          VkStructureType = VK_STRUCTURE_TYPE_IMAGE_MEMORY_BARRIER (45)
            pNext:                          const void* = NULL
            srcAccessMask:                  VkAccessFlags = 0 (VK_ACCESS_NONE_KHR)
            dstAccessMask:                  VkAccessFlags = 32 (VK_ACCESS_SHADER_READ_BIT)
            oldLayout:                      VkImageLayout = VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL (7)
            newLayout:                      VkImageLayout = VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL (5)
            srcQueueFamilyIndex:            uint32_t = 0
            dstQueueFamilyIndex:            uint32_t = 0
            image:                          VkImage = 0x55a6ab3297d0
            subresourceRange:               VkImageSubresourceRange = 0x7ffcd4cd7050:
                aspectMask:                     VkImageAspectFlags = 1 (VK_IMAGE_ASPECT_COLOR_BIT)
                baseMipLevel:                   uint32_t = 0
                levelCount:                     uint32_t = 1
                baseArrayLayer:                 uint32_t = 0
                layerCount:                     uint32_t = 1

Thread 0, Frame 0, Time 24244 us:
vkEndCommandBuffer(commandBuffer) returns VkResult VK_SUCCESS (0):
    commandBuffer:                  VkCommandBuffer = 0x55a6ab3b7280
```

The full API call dumps are also attached.

I'll keep trying to tweak things, but I don't really know anything about pipeline barriers, so I'm mostly making wild guesses as to how this can be fixed.

![2021-04-10T13:32:38,317578437-04:00](https://user-images.githubusercontent.com/4312872/114279786-5ca81c80-9a04-11eb-866f-1c802e9c364b.png)
![2021-04-10T13:30:22,210279536-04:00](https://user-images.githubusercontent.com/4312872/114279790-60d43a00-9a04-11eb-9009-8dd505546ec3.png)
[vulkan_samples.txt](https://github.com/vulkano-rs/vulkano/files/6290504/vulkan_samples.txt)
[capture.txt](https://github.com/vulkano-rs/vulkano/files/6290505/capture.txt)

**Comment by Rua** [comment]
What Rust code were you running for the Vulkano version?

Looking at the two dumps side by side, I see some potentially significant differences. For the first barrier:

- `srcStageMask`: Vulkano `VK_PIPELINE_STAGE_BOTTOM_OF_PIPE_BIT`, C++ `VK_PIPELINE_STAGE_HOST_BIT`.
- `srcQueueFamilyIndex` and `dstQueueFamilyIndex`: Vulkano `4294967295` (whatever that is), C++ `0`

For the copy:
- `imageExtent`: Vulkano 93x93, C++ 512x256. What's the actual size of the image here, why are they different?

Second barrier:
- `dstStageMask`: Vulkano `VK_PIPELINE_STAGE_TOP_OF_PIPE_BIT`, C++ `VK_PIPELINE_STAGE_FRAGMENT_SHADER_BIT`.
- `srcAccessMask`: Vulkano `VK_ACCESS_TRANSFER_WRITE_BIT`, C++ `0`
- `dstAccessMask`: Vulkano `0`, C++ `VK_ACCESS_SHADER_READ_BIT`.

Also noteworthy is that for both barriers, Vulkano sets `dependencyFlags = VK_DEPENDENCY_BY_REGION_BIT`, while C++ sets `dependencyFlags = 0`.

I suspect the stagemasks and accessmasks are what's making the difference here, but it's hard to tell. Since you're experiencing this with your particular driver, would you be willing to investigate further? Something you could try is to start off with the C++ example, but setting all the masks the way they are being set by Vulkano, then see if that reproduces the issue. If so, you can then change the values one by one to what they should be in the C++ version, and see at what point the image fixes itself.

**Comment by Cognoscan** [comment]
Thanks for responding so quickly!

For the vulkano version, I started with some code of my own, but after running into the problem I was able to see the same behavior in the [Image example](https://github.com/vulkano-rs/vulkano/blob/master/examples/src/bin/image/main.rs). That's where the API call dump came from, as well as the blue image that should contain the Rust logo, but instead has a bunch of random color confetti.

For the copy - Vulkano's example image is 93x93, while the C++ example is loading a 512x256 image. I might be able to get them to load the same image, but figured that wouldn't help, as the issue appears to be between having the raw RGB data in a buffer and loading it into an Image. For what it's worth, I did try using various image sizes - 1x1, 8x1, 1x8, 8x8, 93x93, and 512x512. They all had variations of the same issue - a heavily corrupted image whose data on readback (using copy_image_to_buffer) doesn't match the original buffer.

I'll try to get a handle on the C++ example and try flipping the stagemask and accessmask bits around, or see if I can get vulkano to make calls that look the same.

Do you think I'm on the right track at all with probing these barrier calls? I'm quite new to Vulkan, so it's really just a guess on my part.

**Comment by Rua** [comment]
It may be the right track, it may not be. I'm puzzled as you are! Vulkan synchronisation is hard, and it's never very helpful in pointing out your mistakes. I'm eager to hear about your results.

Did you try running the code with validation enabled? The vkconfig utility is good for this. It may point out things we missed.

**Comment by Cognoscan** [comment]
I did try using the validation layer - it didn't show anything with the core checks, only some stuff from the "best practices" which were mostly duplicate warnings like:

```
UNASSIGNED-BestPractices-vkCreateCommandPool-command-buffer-reset(WARN / PERF): msgNum: -2027362524 - Validation Performance Warning: [ UNASSIGNED-BestPractices-vkCreateCommandPool-command-buffer-reset ] Object 0: handle = 0x55d55c5054e0, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x8728e724 | vkCreateCommandPool(): VK_COMMAND_POOL_CREATE_RESET_COMMAND_BUFFER_BIT is set. Consider resetting entire pool instead.
    Objects: 1
        [0] 0x55d55c5054e0, type: 3, name: NULL
```
Probably the most useful layer, "synchronization checks", is missing from my install for some reason - the layer is completely missing from the package I thought would provide it (which provides all the other layers vkconfig uses). I'll see if I can get it straight from the LunarG downloads, since it seems like the one most likely to catch the problem I think I'm running into.

**Comment by Cognoscan** [comment]
Alas, the synchronization layer checks didn't reveal anything either. Seems they're a relatively recent addition to the SDK, so perhaps that's why they weren't in the ArchLinux package.

Back to probing the pipeline barrier settings.

**Comment by 187Qrly** [comment]
Hey, I this still a bug? I want to learn Vulkan, but I have Iris Xe Graphics. I am on gentoo linux, is this also an issue here or is it caused on arch linux, linux drivers in general or on Vulkano?

Also, I have one question: I am trying to decide rather I should use ash or Vulkano. Is there a big performance loss on Vulkano compared to ash or is it just some fps (I heard due to validation there is a bit performance loss)?

**Comment by Rua** [comment]
Try compiling the image example and see if the problem occurs there. It would be helpful if you report on what happens. :)

The validation that Vulkano does is entirely on the CPU side, so as long as your program is not CPU bound, there probably won't be too much of an effect. There might be a little bit of GPU slowdown due to inefficient usage of pipeline barriers and such. In the end it depends a lot on what you're intending to do.

If you're learning Vulkan for the first time, then using Vulkano first is a much easier learning curve, even if you later decide to migrate to Ash. I would be interested to learn of your experiences if you do migrate from Vulkano to Ash at some point, for the purposes of improving how easily Vulkano concepts map to raw Vulkan concepts. I've been doing a lot of refactoring lately to expose more of Vulkan in Vulkano, but there's always room for more.

**Comment by 187Qrly** [comment]
Does it work for you, @Rua?

**Comment by Rua** [comment]
I've not had any problems like this. But I'm on AMD hardware.

**Comment by 187Qrly** [comment]
Hmm, are you using Windows?

**Comment by Rua** [comment]
Linux Mint 20.2.

**Comment by Cognoscan** [comment]
@187Qrly unfortunately no. I couldn't figure out any place pipeline barriers would make a difference, and I couldn't spot any important differences in the command streams between the vulkano and the Vulkan C++ examples. It's still occurring in v0.25.0 and with the vulkan-intel 21.2.1-1 driver. 

My plan had been to try and recreate the C++ calls using vk-sys and start figuring out what differences, exactly, between that and vulkano's vk-sys calls created the issue. Honestly though, I lost motivation, because I started using vulkano specifically to avoid making direct Vulkan calls. Eventually I'll have the bandwidth and desire to learn the Vulkan API more directly, and I'll continue troubleshooting then if this is still an issue.

**Comment by 187Qrly** [comment]
Thanks for your answer. 
Btw, here is a video me Playing some Doom game with @Rua 's engine [ferret](https://github.com/Rua/ferret).
I don't know if that helps, but maby you see somethink special there which could be the issue. Thanks!
https://www.youtube.com/watch?v=wuv4OxdLeOE (Btw, sorry for the awful recording :joy:)

**Comment by 187Qrly** [comment]
Ok, so its been more than 4 months now - here is an Update:

So first, something seems to be changed from the drivers side or vulkano's side (I will try to find out and tell you then).
The Rust logo on the example Image gets rendered correctly. Unfortunately, images with colors still don't seem to work.
Here is an example Image:
![image](https://qrly.wtf/example_wall.png)
And here is how it gets Rendered with vulkano (latest version, ofc.)
![image](https://qrly.wtf/vulkano_render.png)

As you can see, its getting rendered a lot darker. I am pretty sure that this is a Problem related to Vulkano and not any
libary you are using. I tried other file formats, other image loaders, all are showing the same results.

**Comment by Rua** [comment]
Somewhat grasping at straws, but what format are you using for the image and the swapchain? I'm thinking it may be a colour space issue (linear/UNORM vs SRGB).

**Comment by Cognoscan** [comment]
Fantastic, I also just did a quick test with the "image" example and see that it's rendering correctly now. I can also see the darkening when I replace the Rust logo in the example with a color image.

Quick check of the swapchain surface supported formats:

```
supported_formats: [
    (
        A2R10G10B10_UNORM_PACK32,
        SrgbNonLinear,
    ),
    (
        B8G8R8A8_SRGB,
        SrgbNonLinear,
    ),
    (
        B8G8R8A8_UNORM,
        SrgbNonLinear,
    ),
    (
        R8G8B8A8_SRGB,
        SrgbNonLinear,
    ),
    (
        R8G8B8A8_UNORM,
        SrgbNonLinear,
    ),
    (
        R5G6B5_UNORM_PACK16,
        SrgbNonLinear,
    ),
],
```

The image example just chooses the first format available instead of looking for the "right" one, so it picks `(A2R10G10B10_UNORM_PACK32, SrgbNonLinear)`. It should actually check for a format with _SRGB specifically, or handle _UNORM, though maybe that's beyond the scope of a simple example test.

When I modify it to pick the `B8G8R8A8_SRGB` format, the colors look correct.

So, I think the issue is fixed! Don't know why or how, but it's good enough for me. @187Qrly can you check the swapchain format and see if forcing a _SRGB format does the trick? I'm planning on closing this issue soon regardless, since color space problems are different than what I was experiencing.

**Comment by 187Qrly** [comment]
I did a lot of testing yesterday and today, and I can confirm that some Images work (when changing them to the correct color space) to display while others don't. 
From that what I could find out, there is defenetly something wrong with Vulkano.
While the image, that I originally posted works, there are a lot that don't (Actually, I couldn't find any online that are getting displayed correctly.)

There are many other issues too. 
For example, all Programms written in Vulkano (that I could find) have all wird rendering.
I couldn't find any Program using Vulkano that works correctly. 

In a previus post I showed the game Ferret and what bugs I am getting. Nothing has changed regarding this. Also, I tried the game Sandbox (https://github.com/hakolao/sandbox) and this is how it looks:
![20220128_13h09m53s_grim](https://user-images.githubusercontent.com/56300140/151544703-0038580f-7445-4e9b-ad33-abea064282d4.png)

As you can see, the Fonts are looking very wird and Textures aren't getting rendered correctly.
(They are installed and should work correctly)

Here are some other screenshots of images that don't work (I tried all the color stuff, ofc.):
![20220128_13h18m12s_grim](https://user-images.githubusercontent.com/56300140/151545703-65086a25-cf0f-433e-a57e-3a328eb88a5e.png)
Here is the Image that should be displayed:
![another_example](https://user-images.githubusercontent.com/56300140/151545864-7cb84587-a989-402e-a50b-c496df43c2c8.png)

I think closing the Issue is not a good idea, because its not fixed.

**Comment by 187Qrly** [comment]
@Cognoscan 
Could you please also try using the image that I showed in my previus post and see if you can render it correctly?
Also, if possible, could you try running https://github.com/hakolao/sandbox and see if you get the same rendering issues as me? (To get it running, you might need to apply this patch: https://qrly.wtf/iris.patch because, at least for me, the Present mode Immediate is not supported)

Thanks in Advance!

**Comment by Cognoscan** [comment]
Shoot, yeah. I get the same issue with the image you provided, same rendering misbehavior and all. At least now we've got a comparison to make - why does one image work and another fail? Is this a texture data format issue? A colorspace issue? Image dimensions? More to check, for sure.

I see your issue with the sandbox game as well. Textures and font rendering is messed up for me. However, interestingly, the game area itself seems to behave correctly. The material brush works right, the particles clump correctly, the objects are rendered right. It really seems like there's now a specific subset of texture modes that don't work still, though it's not yet clear what those modes are.

**Comment by Cognoscan** [comment]
I don't have time to track this down right now, but it is suspicious to me that the swapchain format for this game is `A2R10G10B10_UNORM_PACK32` when I start it. I would not be surprised if the font looks odd because there's only 2 bits of alpha transparency. Switching to `B8G8R8A8_SRGB` might fix this.

Text rendering is also tricky in general. `egui`, which seems to the source for the user interface of the game, has a brief bit of troubleshooting for text rendering that might be worth checking if fixing the swapchain format doesn't do the trick:

> My text is blurry
> 
>     Make sure you set the proper pixels_per_point in the input to egui.
>     Make sure the texture sampler is not off by half a pixel. Try nearest-neighbor sampler to check.

**Comment by 187Qrly** [comment]
The Image example is working on mesa-21.3, however its not working mesa-22 while other programms still work. 
With mesa-22 its looking like the first images that @Cognoscan provided. Mesa-21.3 works as expected.

Ash is working. I assume noone has the time to futher investigate in this bug (and also doesn't have the necessary hardware)
so how do I investigate futher? @Rua do you have some suggestions for me where to look in the source code?

I will try to find the commit in mesa that caused this change. 
If you have any ideas please just tell me and I will see what I can do, I have a lot of time and want to get this fixed as fast as possible.

Thanks in Advance for your time and ideas!

**Comment by Rua** [comment]
I'm not even sure where the problem lies at the moment. But with this kind of weirdness I might suspect image layouts or synchronization. You could also go to the official Vulkan discord server and ask if anyone has ideas there. Trying the validation layer again in vkconfig, making sure that all validation options are enabled including synchronization, could also give some clues. And if nothing shows up, then who knows, maybe the bug is not in Vulkano at all.

**Comment by Cognoscan** [comment]
There isn't a 4th image in this example. It just creates the upper left image, demonstrates copying by making the lower right one, and demonstrates blitting by making the upper right one - see the builder code [here](https://github.com/vulkano-rs/vulkano/blob/3ad03f85932a7c29add3ae13d711e66c03607e35/examples/src/bin/image-self-copy-blit/main.rs#L197-L242)

**Comment by 187Qrly** [comment]
It seems like it is caused on this commit: `9c0388b7` https://gitlab.freedesktop.org/mesa/mesa/-/commit/9c0388b7ff2d78b36906fbfd043a890381df38bd

@Cognoscan can you try compiling mesa from this commit and test if this commit is breaking the image example for you too? (It still works in `cbb35dbb`)
Thanks!

**Comment by 187Qrly** [comment]
CCS means Single-sampled Color Compression:
https://gitlab.freedesktop.org/mesa/mesa/-/blob/main/docs/isl/ccs.rst

I did (yet) find out what the _E means.

**Comment by CatCode79** [comment]
I found the meaning of CCS_E here:
https://docs.mesa3d.org/isl/aux-surf-comp.html?highlight=isl_surf_get_ccs_surf#_CPPv413isl_aux_state
`CCS_E: Single-sample render target compression (also called CCS_E in ISL) is capable of being in almost all of the above states. THe only exception is that it does not have separate resolved and pass- through states. Instead, the CCS_E full resolve operation does both a resolve and an ambiguate so it goes directly into the pass-through state. CCS_E also provides fast clear and partial resolve operations which work as described above.`

Perhaps the note immediately below is also of interest which says:
`The state machine above isn’t quite correct for CCS on TGL. There is a HW bug (or feature, depending on who you ask) which can cause blocks to enter the fast-clear state as a side-effect of a regular draw call. This means that a draw in the resolved or compressed without clear states takes you to the compressed with clear state, not the compressed without clear state.`

**Comment by Cognoscan** [comment]
@187Qrly can confirm, changing between the previous commit and the commit you linked does indeed break the image example for me. And that mesa-21.3.6 has the example failing again.

**Comment by 187Qrly** [comment]
Just a small update: StorageImage works (for me). Immutable image seems to be broken somehow. Not sure why I didn't try earlier.

**Comment by 187Qrly** [comment]
Thanks very much that you looked over this issue @nanley it really helps! 

 @Rua For me, #1833 doesn't fix the issue.

**Comment by Cognoscan** [comment]
Fantastic, I can confirm the change in https://github.com/vulkano-rs/vulkano/pull/1833 also fixes things for me.

**Comment by Rua** [comment]
Well that's good news then! But it also confirms that synchronisation and image initialisation are parts of Vulkano that really need some more love soon.

**Comment by 187Qrly** [comment]
This seems to be fixed now. @Cognoscan can you close the issue?

**Comment by Cognoscan** [comment]
@187Qrly absolutely, thanks for reminding me it was still open.
