### ISSUE TITLE
Storage images are unsafe without Robust Image Access

### ISSUE THREAD

**Issue by kvark** [vulkano-rs/vulkano#1552]
Currently, Vulkano [enables robustBufferAccess](https://github.com/vulkano-rs/vulkano/blob/4f009c3c93b1f68e9e54a29e50fd3fdaacce02bb/vulkano/src/device/mod.rs#L273) unconditionally in order to make buffer access safe. However, this feature doesn't guard against storage images.
Therefore, unless `VK_EXT_image_robustness` is required and `robustImageAccess` is force enabled, any operations on storage images are unsafe and should be tagged in the API accordingly.

**Comment by Eliah-Lakhin** [comment]
It's a good point. Images access are somewhat unsafe from the shader code point of view since the user can currently address points outside of provided image bounds, and as such all shader usages are somewhat unsafe too in the Rust code. In my personal opinion tagging of all related APIs as unsafe would be unnecessary as the issue is practically minor. But I would left the decision to community.

**Comment by Rua** [comment]
I don't think Vulkano should require any features that aren't available on the vast majority of drivers. Here's a quick overview from the Vulkan hardware database:
- `robustBufferAccess` feature: very near 100% on Windows, Linux and Android, but 0% on MacOS and iOS.
- `robustImageAccess` feature: 36% on Windows, 17% on Linux, 1.6% on Android, 60% on MacOS, 100% on iOS.
- `robustImageAccess2` feature: 40% on Windows, 23% on Linux, no data on Android, 60% on MacOS, 100% on iOS.
- `robustBufferAccess2` feature: 40% on Windows, 23% on Linux, no data on Android, MacOS or iOS.

It's pretty clear to me that the only one with good support is the first, but it's odd that MacOS and iOS return no support for it when they do support version 2. Maybe a driver bug.

In any case, Rust can never hope to be 100% safe when interfacing with code it doesn't control and can't check. This doesn't just apply to shaders, but with any FFI. A rogue Vulkan driver could overwrite all of Rust's stack for example. There is always a certain amount of trust involved. So I don't think Vulkano should try to enforce safety in the shaders. It should of course offer the _option_ to the user, but it's already there in the form of these features. The user can always activate them if desired and available.

**Comment by kvark** [comment]
@Rua 
> I don't think Vulkano should require any features that aren't available on the vast majority of drivers.

Agreed!

> It's pretty clear to me that the only one with good support is the first

It has good support because a conformant Vulkan implementation *has to* support it.

>  it's odd that MacOS and iOS return no support for it when they do support version 2. Maybe a driver bug.

It's not a bug. There are *no* conformant Vulkan implementations on Apple platforms. MoltenVK doesn't have plans to address this, AFAIK. gfx-portability may be able to support this on Apple once wgpu-related shader infrastructure is in place, which needs bounds checking anyway.

The reason why macOS/iOS report `robustBufferAccess2` to be available is because you are confusing Vulkan extensions with Vulkan features. MoltenVK supports the extension that has flags saying whether some of the features can be enabled, but it doesn't magically support the *actual* flags being true. So it has exactly zero RBA support.

> In any case, Rust can never hope to be 100% safe when interfacing with code it doesn't control and can't check. This doesn't just apply to shaders, but with any FFI.

Vulkano is not the first library to talk to FFI, you should have a look at how this is done elsewhere.
The main principle to draw the "unsafe" line is that there are "valid usage" rules, and the code is safe it it follows them. Vulkan is better documented than many other FFI APIs, so you are luck the "valid usage" is spelled out clearly. If Vulkano can follow it - great, then the exposed APIs are safe. If you can't follow the valid usage, then nothing can save you. You have to make it `unsafe` to reflect the "no guarantees" semantic.

> A rogue Vulkan driver could overwrite all of Rust's stack for example.

That's a question of Vulkan conformance. If you are dealing with a non-conformant Vulkan driver, it's the responsibility of the Vulkan loader, which can be considered a part of the system configuration. I.e. if the user system is configured in an unsafe way, there is nothing you can do about it, and no way you can discover it.

This also applies to MoltenVK. If you hook it up, you are explicitly breaking the Vulkan conformance, and it's basically that rogue Vulkan driver.

> It should of course offer the option to the user, but it's already there in the form of these features. The user can always activate them if desired and available.

Please read @tomaka 's comment again.

Overall, just because you can't get what you want (safe API without much effort making the shaders safe) doesn't mean that you can slap "safe" label on your API and pretend there is no problem.
