### ISSUE TITLE
Allow multiple regions for copy operations

### ISSUE THREAD

**Issue by Rua** [vulkano-rs/vulkano#1553]
Vulkan's copy operations allow specifying multiple regions to copy over, and the `blit_image`, `copy_buffer`, `copy_image`, `copy_buffer_to_image` and `copy_image_to_buffer` methods of `SyncCommandBufferBuilder` already support this. But `AutoCommandBufferBuilder` doesn't support it yet. It would be nice if it did.

I investigated a bit whether I could make a PR for this. Ideally, the functions would take `IntoIterator` of some kind, but a few issues got in my way:
- Arrays don't implement `IntoIterator` yet. That's being worked on in https://github.com/rust-lang/rust/pull/65819, but until then, you have to use something else (`Vec`, `ArrayVec`, `SmallVec` or whatever else the user has on hand).
- The function has to validate the regions, which means using up the iterator. In order to pass the regions on to `SyncCommandBufferBuilder`, it then has to build a new container.
- It would be nice to have only one function, instead of separate `_dimensions` ones that Vulkano currently has. But for that to work, it should be ergonomic to use in the common case, where the dimensions are the whole image.

**Comment by MarijnS95** [comment]
> * Arrays don't implement `IntoIterator` yet.

The trait isn't implemented yet (because of conflicting use) but you _can_ already get such an iterator with `std::array::IntoIter::new`, it's just a matter for applications to call `std::array::IntoIter::new([some, items])` instead of passing the array verbatim or by calling `.into_iter()`.

**Comment by Rua** [comment]
I think the most complex part is actually going to be the validation itself. Any byte that's written by the command can't alias with anything else, whether that's another write or a read. At first glance, the complexity of that check goes up by the square of the number of destination regions, plus the source regions if the source image is the same as the destination. How do you validate that kind of data without making it too slow?

**Comment by neumond** [comment]
It's not only validation of API call, looks like the task of picking multiple disjoint regions requires some helping code. I would like to have some automated thing that accumulates all updated regions

```rust
let regions = DisjointRegions1D::new();
regions.add(5, 8);  // these three automatically join into single region
regions.add(6, 15);
regions.add(8, 9);
regions.add(48, 56);
regions.iter()  // (5, 15), (48, 56)
```
