### ISSUE TITLE
Allow the user to implement `VertexMember` for custom types

### ISSUE THREAD

**Issue by Rua** [vulkano-rs/vulkano#1572]
The `VertexMember` trait is used for the `impl_vertex` macro, and is currently implemented by Vulkano for a bunch of array and tuple types. But there are several libraries out there that have custom types for vectors. For example, I use Nalgebra in my project, and its `Vector3<T>` type has the exact same layout as `[T; 3]`, so in theory this would be valid as a drop-in replacement. But because of Rust's orphan rules, the user is not allowed to implement Vulkano's `VertexMember` on Nalgebra's `Vector3`.

Is there some way around this, so that users can use types like Nalgebra's in their vertex types?

It looks like #1133 and #1326 tried to implement this or something similar, but were ultimately closed. Unfortunate. What would be needed to make such changes acceptable?

**Comment by Eliah-Lakhin** [comment]
Adding another dependency(even optional) would complicate maintainability.

As an alternative we might consider looking at some interop basis libraries such as [Mint](https://docs.rs/mint/0.5.6/mint/index.html) for example. But this is controversial too.
