### ISSUE TITLE
Allow graphics pipelines without a fragment shader

### ISSUE THREAD

**Issue by Rua** [vulkano-rs/vulkano#1573]
It is perfectly valid to have a graphics pipeline consisting of a vertex shader alone. You don't actually need a fragment shader. This just means that no colour output is generated, but you still get depth/stencil writes. However, Vulkano doesn't currently allow this combination, it unwraps the fragment shader in the builder assuming it is valid. It would be nice if this were allowed. I had a look at the code, and it's rather convoluted due to the presence of lots of type parameters on the builder...

**Comment by Eliah-Lakhin** [comment]
Yes, I believe it would definitely be a good idea to extend Vulkano to support vertex-shaders-only pipeline capabilities :+1:
