### ISSUE TITLE
assertion on limits().max_uniform_buffer_range() fails

### ISSUE THREAD

**Issue by Adamih** [vulkano-rs/vulkano#1575]
*   Version of vulkano: 0.22.0
*   OS: Manjaro Linux
*   GPU (the selected PhysicalDevice): GeForce GTX 860M
*   Vulkan Instance Version: 1.2.177  

A beginner who is going through the vulkano.rs tutorial and examples. 
This is the code from the "basic-compute-shader.rs" example:
```
const DEVICE_EXTENSIONS: DeviceExtensions = DeviceExtensions {
    ..DeviceExtensions::none()
};

const BUFFER_USAGE: BufferUsage = BufferUsage {
    uniform_buffer: true,
    ..BufferUsage::none()
};

fn main() {
    let instance = Instance::new(None, &InstanceExtensions::none(), None).unwrap();
    let physical = PhysicalDevice::enumerate(&instance).next().unwrap();
    let queue_family = physical
        .queue_families()
        .find(|&q| q.supports_compute())
        .unwrap();

    let (device, mut queues) = Device::new(
        physical,
        physical.supported_features(),
        &DEVICE_EXTENSIONS,
        [(queue_family, 0.5)].iter().cloned(),
    )
    .unwrap();

    let queue = queues.next().unwrap();

    let pipeline = Arc::new({
        mod cs {
            vulkano_shaders::shader! {
                ty: "compute",
                src: "
                    #version 450

                    layout(local_size_x = 64, local_size_y = 1, local_size_z = 1) in;

                    layout(set = 0, binding = 0) buffer Data {
                        uint data[];
                    } data;

                    void main() {
                        uint idx = gl_GlobalInvocationID.x;
                        data.data[idx] *= 12;
                    }
                "
            }
        }
        let shader = cs::Shader::load(device.clone()).unwrap();
        ComputePipeline::new(device.clone(), &shader.main_entry_point(), &(), None).unwrap()
    });

    let data_buffer = {
        let data_iter = (0..65536u32).map(|n| n);
        CpuAccessibleBuffer::from_iter(device.clone(), BUFFER_USAGE, false, data_iter).unwrap()
    };

    let layout = pipeline.layout().descriptor_set_layout(0).unwrap();
    let set = Arc::new(
        PersistentDescriptorSet::start(layout.clone())
            .add_buffer(data_buffer.clone())
            .unwrap()
            .build()
            .unwrap(),
    );
}
```

# Issue

`thread 'main' panicked at 'assertion failed: size <=\n    buffer.device().physical_device().limits().max_uniform_buffer_range() as\n        usize'`

The only similar issue I found was from #1495 which makes me think that this also is a volcano issue, but since user-space API changes seem to be introduced on a regular basis, I'm not sure if this is a bug or if I'm doing something wrong.

**Comment by Rua** [comment]
Can you check using the `vulkaninfo` command line utility, what value of the `maxUniformBufferRange` limit is being reported for your system? Also, what file and line does it say the failed assertion is on?

**Comment by Adamih** [comment]
grep from vulkaninfo: `maxUniformBufferRange                           = 65536`

Full error message: `thread 'main' panicked at 'assertion failed: size <=\n    buffer.device().physical_device().limits().max_uniform_buffer_range() as\n        usize', /home/adamh/.cargo/registry/src/github.com-1ecc6299db9ec823/vulkano-0.22.0/src/descriptor/descriptor_set/sys.rs:958:9`

**Comment by Adamih** [comment]
Perhaps...

Jokes aside, I get it. Thank you for the help when I'm being clueless. Still not getting examples working though but that is another problem. Thanks again, closing.
