### ISSUE TITLE
Docs.rs missing documentation for `SwapchainBuilder` struct.

### ISSUE THREAD

**Issue by CABrinegar** [vulkano-rs/vulkano#1591]
*   Version of vulkano: 0.23.0
*   OS: Firefox 88 and Chrome 90

The `SwapchainBuilder` struct introduced in vulkano 0.23.0 from https://github.com/vulkano-rs/vulkano/blob/01fcd53faa6980d2bfbaf1542afeecabccb74d87/vulkano/src/swapchain/swapchain.rs#L502-L521 is not present in [https://docs.rs/vulkano/0.23.0/vulkano/swapchain/index.html#structs](https://docs.rs/vulkano/0.23.0/vulkano/swapchain/index.html#structs)
and [https://docs.rs/vulkano/0.23.0/vulkano/swapchain/struct.SwapchainBuilder.html](https://docs.rs/vulkano/0.23.0/vulkano/swapchain/struct.SwapchainBuilder.html) does not exist.

Searching the docs.rs for `SwapchainBuilder` only yields the two functions with a `SwapchainBuilder` return type:
- [vulkano::swapchain::Swapchain::start](https://docs.rs/vulkano/0.23.0/vulkano/swapchain/struct.Swapchain.html#method.start)
- [vulkano::swapchain::Swapchain::recreate](https://docs.rs/vulkano/0.23.0/vulkano/swapchain/struct.Swapchain.html#method.recreate)

**Comment by Rua** [comment]
Ah, because it's not re-exported. I submitted a PR to fix it.
