### ISSUE TITLE
Multisampling may be broken

### ISSUE THREAD

**Issue by AustinJ235** [vulkano-rs/vulkano#1595]
*   Version of vulkano: 0.23
*   OS: Void Linux - Kernel 5.12.5
*   GPU (the selected PhysicalDevice): AMD RADV VEGA10 (ACO)
*   GPU Driver: Mesa v21.0.3
*   Upload of a reasonably minimal complete `main.rs` file that demonstrates the issue: msaa-renderpass

# Issue

Example fails to start at all, no output. In Basalt using MSAA results in an `ImageNotInitialized` on the multisampled `AttachmentImage` during the `begin_render_pass` call. Not sure if there was a recent change that effected the behavior of multisamping coming from version 0.20, but it was working on my system with that version.

I'll investigate this further, but I am done for the night. Bit of lengthy process updating Basalt to the newest version.

**Comment by AustinJ235** [comment]
This is related to https://github.com/vulkano-rs/vulkano/issues/1578 & https://github.com/vulkano-rs/vulkano/pull/1588

**Comment by Timbals** [comment]
This is fixed for me with #1588. Can you checkout the branch and confirm on your machine?

**Comment by Rua** [comment]
@AustinJ235 is this still a problem for you?

**Comment by AustinJ235** [comment]
@Rua The example still fails to launch for whatever reason.

**Comment by AustinJ235** [comment]
Example doesn't actually render anything, closing.
