### ISSUE TITLE
[Feature Request] Multiview/custom RenderPass

### ISSUE THREAD

**Issue by funmaker** [vulkano-rs/vulkano#1596]
I want to make a render pass utilizing VK_KHR_multiview extension, but the current RenderPass implementation doesn't support it.
Since RenderPass is a structure, it's also not possible to create custom one as every function in vulkano expects the concrete type.

Are there any plans to implement multiview support or at least an unsafe constructor to create RenderPass from raw parts?

**Comment by Rua** [comment]
I have no experience with the feature, but I can see if I can implement it once I've finished working on better support for Vulkan versions/extensions in general. Do you have particular points of design that you think should be taken into account?

**Comment by funmaker** [comment]
It seems there are 3 structures that can extend render pass [1](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VkRenderPassFragmentDensityMapCreateInfoEXT.html) [2](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VkRenderPassInputAttachmentAspectCreateInfo.html) [3](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VkRenderPassMultiviewCreateInfo.html). It could probably be handled similarly to device's extensions/features. Also if we are going to use concrete types instead of traits, ability to unsafely construct structures like RenderPass from raw parts would be good for future proofing. Also if multiview extension is requested it could be checked if device has VK_KHR_multiview extension enabled.

However I'm not very knowledgeable about vulkan and vulkano's internals, so it's just a suggestion. I'll implement this feature in my fork, but it's not going to be pretty or implement any other extension except multiview, but it could act as a working example.

**Comment by Timbals** [comment]
I've actually partially implemented `VK_KHR_multiview` two weeks ago. I just opened a PR (#1598) for it. Some validation is still missing but it's already functional and includes a new example. I will probably finish it in the next few days or so.
