### ISSUE TITLE
Upcoming 0.24 release regression

### ISSUE THREAD

**Issue by Eliah-Lakhin** [vulkano-rs/vulkano#1600]
After migration of Pipeline layout refactoring #1581 (already merged) I unfortunately missed the fact that we effectively removed a capability for the end-user to choose between the shader layouts.

Previously it was possible to choice between layouts for the pipeline by specifying such layout through the generated `shader!` macro module layout types. From now on `shader!` is no longer generating `MainLayout` type, and there is no way to specify the layout if there are several of them in the shader.

This feature is irrelevant for the users who use glsl generating shaders, but is an issue to those who use sprv source directly in the `shader!` macro. The SPIR-V code may have several layouts(for example, when produced from RustGPU source).

I believe this issue is a regression for us, and is a blocker for the next release until we fixed it.

@Rua I want to ask you, as an author of #1581, to make a workaround for this case.

@AustinJ235 fyi.

**Comment by Rua** [comment]
The `EntryPointAbstract` trait has a `layout_desc` method, and you can get the entry point struct for `foo` by calling the `foo_entry_point` function on the shader module, like [here](https://github.com/vulkano-rs/vulkano/blob/master/examples/src/bin/triangle.rs#L304). Is this the functionality you were looking for, or am I misunderstanding?

**Comment by Eliah-Lakhin** [comment]
hm... so the entry-points at least are not the issue.

@Rua What layout are we receiving here then: https://github.com/vulkano-rs/vulkano/blob/master/examples/src/bin/dynamic-local-size.rs#L182 Is it entry-point's layout dependent?

**Comment by Rua** [comment]
Yes. `GraphicsPipelineBuilder` is given a specific entry point for each shader, and the `GraphicsPipelineBuilder::with_auto_layout` will then create a `PipelineLayoutDesc` by merging the descs of each shader entry point. So when you ask for the layout of a `GraphicsPipeline`, you get the combined layout of the entry points of that specific pipeline. If you were to create another pipeline with the same shaders, but with different entry points, the returned layout would also be different.

**Comment by Eliah-Lakhin** [comment]
@Rua Understood. ok, thank you for clarification. And I apologize for the false alert. I need to understand such edge cases at least to keep other users(and migration notes) up to date.
