### ISSUE TITLE
Request: Return `(u32, u32)` or a `Size` struct over `[u32; 2]` in the library.

### ISSUE THREAD

**Issue by i509VCB** [vulkano-rs/vulkano#1602]
I've noticed around the library that some methods return an array of 2 elements. The general standard I've seen with graphics libraries is to return a tuple containing the width and height or a `Size` struct. Interaction with other libraries would benefit here since most libraries that need to work with a size often implement `From<(u32, u32)>` for their own size types or takes `Into<(u32, u32>)` for parameters.

One example of this in the code base is the `display` module.

This would be a breaking change.

**Comment by Rua** [comment]
I think no matter which way Vulkano goes, it's going to be awkward for those using the "other" method. I use Nalgebra in my project, and that makes the array representation much more convenient, because you can directly convert from an array to a Nalgebra vector. An array also makes more sense to me personally, so I wonder why some libraries do it with tuples?

**Comment by AustinJ235** [comment]
I mean we could make things return a struct instead that'd implement `From` and `Into` for both `(u32, u32)` and `[u32; 2]`, but I think generally speaking it is more correct to use an array when all elements are the same type. This just seems like a needless breaking change I think. At one point in time tuples were a bit more versatile in terms of pattern matching, for example this wasn't possible before:
```rust
match size {
    [1920, 1080] => (),
    [x, y] => ()
}
```

Other than something like that I can't think of a reason other projects would use tuples. Just out of curiosity what projects are the "standard" in this regard?

**Comment by i509VCB** [comment]
Hmm I see it's a little more complicated than I thought.
