### ISSUE TITLE
AutoCommandBufferBuilder::new doesn't exist in 0.23.0

### ISSUE THREAD

**Issue by XPCMasterX** [vulkano-rs/vulkano#1604]
# Template

If you dont understand something just leave it.
If you can provide more detailed information than the template allows for, please ignore the template and present all of your findings.

*   Version of vulkano: 0.23.0
*   OS: Windows
*   GPU (the selected PhysicalDevice): Intel HD Graphics 4600
*   GPU Driver: TODO
*   Upload of a reasonably minimal complete `main.rs` file that demonstrates the issue: 
```
let buffer = AutoCommandBufferBuilder::new(...);
```

# Issue

I am following along the examples in the vulkano-rs website and at the section where it says to create an AutoCommandBufferBuilder, it says to use AutoCommandBufferBuilder::new() to create it.

However, in the latest version of vulkano-rs - 0.23.0 - this method is missing.

If I downgrade to version 0.22.0, the method exists.

So, how do I create an AutoCommandBuffer in the latest version of vulkano-rs?

**Comment by krOoze** [comment]
Per #1527 it seems you are supposed to use `primary()` or `secondary()` instead.

**Comment by Eliah-Lakhin** [comment]
@XPCMasterX Yes, as it was mentioned by the @krOoze we had to refactor this functionality and changed it's public API a little too. From now on `AutoCommandBufferBuilder::primary` function is supposed to be used to create a Primary Command Buffer. Our website examples are outdated, unfortunately we don't have capability(and honestly speaking management resources too) to keep the website up to date, but we keep all examples in our repository up to date. e.g. see Triangle example: https://github.com/vulkano-rs/vulkano/blob/master/examples/src/bin/triangle.rs#L441

```rust
let mut builder = AutoCommandBufferBuilder::primary(
    device.clone(),
    queue.family(),
    CommandBufferUsage::OneTimeSubmit,
)
.unwrap();
```

Hope that helps, and we can close this Issue.

But you raised an important topic that I was worrying about for long time too that our website is too outdated and can confuse new users. I will try to resolve the problem with the website's examples.

Thank you for raising the issue!
