### ISSUE TITLE
vulkano-win breaks with winit>=0.25

### ISSUE THREAD

**Issue by C0D3-M4513R** [vulkano-rs/vulkano#1610]
*   Version of vulkano: 0.23
*   Version of vulkano-win: 0.23
*   OS: Win 10
*   GPU (the selected PhysicalDevice): N/A
*   GPU Driver: N/A

Minimal main.rs
```rust
fn main() {
    let instance = 
        vulkano::instance::Instance::new
            (None, &vulkano::instance::InstanceExtensions::none(), None)
        .expect("Couldn't build instance!");
    let event_loop = winit::event_loop::EventLoop::new();
    winit::window::WindowBuilder::new().build_vk_surface(&event_loop,instance.clone());
}
```

# Issue
With winit 0.25 (0,24 works fine!), compiling fails, with the following error message:
```
error[E0599]: no method named `build_vk_surface` found for struct `WindowBuilder` in the current scope
 --> src\main.rs:6:41
  |
6 |     winit::window::WindowBuilder::new().build_vk_surface(&event_loop,instance.clone());
  |                                         ^^^^^^^^^^^^^^^^ method not found in `WindowBuilder`
```

**Comment by Rua** [comment]
This happens when the version of winit used in Vulkano differs from the version used in your own crate. If you match them, this error should go away. I wonder if there's a way for Vulkano to prevent this though.

**Comment by C0D3-M4513R** [comment]
> This happens when the version of winit used in Vulkano differs from the version used in your own crate. If you match them, this error should go away. I wonder if there's a way for Vulkano to prevent this though.

But then, winit = 0.24 shouldn't work.

**Comment by Rua** [comment]
Why not? Vulkano 0.23 uses winit 0.24.

**Comment by AustinJ235** [comment]
If you wish to use other window creation crates, including different versions of `winit` from what is in `Cargo.toml` of `vulkano-win` you can use `raw-window-handle`. See: 
- https://docs.rs/vulkano-win/0.23.0/vulkano_win/fn.create_vk_surface_from_handle.html
- https://docs.rs/winit/0.25.0/winit/window/struct.Window.html#impl-HasRawWindowHandle

Otherwise a more advance option would be use the `from_*` methods on `Surface`:
- https://docs.rs/vulkano/0.23.0/vulkano/swapchain/struct.Surface.html

**Comment by C0D3-M4513R** [comment]
My problem with `create_vk_surface`, is the `SafeBorrow` trait constraint, for the Window parameter.
```rust
/// Create a surface from the window type `W`. The surface borrows the window
/// to prevent it from being dropped before the surface.
pub fn create_vk_surface<W>(
    window: W,
    instance: Arc<Instance>,
) -> Result<Arc<Surface<W>>, SurfaceCreationError>
where
    W: SafeBorrow<Window>,
{
    unsafe { winit_to_surface(instance, window) }
}
```
If I do this, it says, that the Trait bounds are not statisfied.
```rust
	let window = WindowBuilder::new().build(&event_loop).unwrap();
	let surface = vulkano_win::create_vk_surface(window,instance.clone()).unwrap();
```
I can wrap the Window in an Arc, but the result is the same, eventhough:
```rust
pub unsafe trait SafeBorrow<T>: Borrow<T> {}

unsafe impl<T> SafeBorrow<T> for T {}
unsafe impl<'a, T> SafeBorrow<T> for &'a T {}
unsafe impl<'a, T> SafeBorrow<T> for &'a mut T {}
unsafe impl<T> SafeBorrow<T> for Rc<T> {}
unsafe impl<T> SafeBorrow<T> for Arc<T> {}
unsafe impl<T> SafeBorrow<T> for Box<T> {}
```

**Comment by C0D3-M4513R** [comment]
Using `create_vk_surface_from_handle` combats this issue, but then, why does `create_vk_surface` exist, if it cannot be used from outside?

**Comment by Rua** [comment]
I can use it just fine, and so can Vulkano's examples, so I think something is going wrong on your end?

**Comment by C0D3-M4513R** [comment]
Have been trying rn, to create a minimal example, but on my created project, vulkano fails to build.
errors:
```
   Compiling vulkano v0.23.0
error[E0308]: mismatched types
   --> C:\Users\timon\.cargo\registry\src\github.com-1ecc6299db9ec823\vulkano-0.23.0\src\buffer\sys.rs:167:32
    |
167 |                         pNext: ptr::null(),
    |                                ^^^^^^^^^^^ types differ in mutability
    |
    = note: expected raw pointer `*mut c_void`
               found raw pointer `*const _`

error[E0308]: mismatched types
   --> C:\Users\timon\.cargo\registry\src\github.com-1ecc6299db9ec823\vulkano-0.23.0\src\features.rs:421:25
    |
421 |                    pNext: ptr::null(),
    |                           ^^^^^^^^^^^ types differ in mutability
...
452 | / features! {
453 | |     core { robust_buffer_access => robustBufferAccess },
454 | |     core { full_draw_index_uint32 => fullDrawIndexUint32 },
455 | |     core { image_cube_array => imageCubeArray },
...   |
566 | |     },
567 | | }
    | |_- in this macro invocation
    |
    = note: expected raw pointer `*mut c_void`
               found raw pointer `*const _`
    = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0308]: mismatched types
   --> C:\Users\timon\.cargo\registry\src\github.com-1ecc6299db9ec823\vulkano-0.23.0\src\image\sys.rs:558:28
    |
558 |                     pNext: ptr::null(),
    |                            ^^^^^^^^^^^ types differ in mutability
    |
    = note: expected raw pointer `*mut c_void`
               found raw pointer `*const _`

error[E0308]: mismatched types
   --> C:\Users\timon\.cargo\registry\src\github.com-1ecc6299db9ec823\vulkano-0.23.0\src\swapchain\swapchain.rs:693:24
    |
693 |                 pNext: ptr::null(),
    |                        ^^^^^^^^^^^ types differ in mutability
    |
    = note: expected raw pointer `*mut c_void`
               found raw pointer `*const _`

error: aborting due to 4 previous errors

For more information about this error, try `rustc --explain E0308`.
error: could not compile `vulkano`
To learn more, run the command again with --verbose.
Process finished with exit code 101
```
I have tried a `cargo clean`, but no change. In one project, Vulkano compiles, and in the second, it fails.
My code essentially does this:
```rust
    let required_extensions = vulkano_win::required_extensions();
    let instance = Instance::new(None, &required_extensions, None)
        .expect("Couldn't build instance!");
    let physical = PhysicalDevice::enumerate(&instance).next().unwrap(); //unneeded, for this example
    let event_loop = EventLoop::new();
    let window = WindowBuilder::new().build(&event_loop).unwrap();
    let _ = vulkano_win::create_vk_surface_from_handle(window,instance.clone()).unwrap();```

The last line has been giving me troubles, as mentioned earlier.

**Comment by Rua** [comment]
It compiles just fine for me, and always has. Something very strange is going on here.

**Comment by Eliah-Lakhin** [comment]
ok, I can confirm I just faced the same issue on Linux machine. Exactly the same errors with completely different code that previously worked fine.

**Comment by Eliah-Lakhin** [comment]
@C0D3-M4513R, @Rua I figured out the "root" cause. This is in fact my fault as a maintainer.

`vk-sys` of version `0.6.2` was a breaking version despite of its patch version. The breaking change was introduced in this commit(probably): https://github.com/vulkano-rs/vulkano/commit/2f7e7af7ee20b95a9ef8fccb579281f694a3a8a3#diff-8031b49f7bde56ea8973b626dd93561c3cb2d27361e14a055319e2882866015bR3

This is affecting those who use older versions of Vulkano. A quick workaround would be adding the following lines to your `Cargo.toml`:

```
[dependencies.vk-sys]
version = "=0.6.1"
```

After rebuild, make sure that `Cargo.lock` doesn't hold vk-sys of version `0.6.2`.

Normally, we can yank `0.6.2` patch to avoid confusion for the users. Maybe I will do so later. For now this workaround should fix inconsistency between old Vulkano and vk-sys. And I will put a note to #1527.

**Comment by C0D3-M4513R** [comment]
Confirmed. The project, that wasn't compiling, is now compiling, with this fix. Also YANK the version, before more stuff like this appears. People will be confused. because stuff like this happens!

**Comment by Eliah-Lakhin** [comment]
Done. `vk-sys 0.6.2` yank. Code duplicate with version `0.7.0` is published. I believe the issue is now resolved
