### ISSUE TITLE
vulkano 0.24 doesn't use winit 0.25 as release notes suggest

### ISSUE THREAD

**Issue by korteland** [vulkano-rs/vulkano#1613]
*   Version of vulkano: 0.24.0
*   OS: linux
*   GPU (the selected PhysicalDevice): Intel integrated graphics

# Issue

From the release notes for v0.24.0: "Updated winit to 0.25."

Unfortunately, this doesn't seem to work, since compiling some code that also brings in `winit = "0.25"` (from `Cargo.toml`) fails with errors such as:
```
expected struct `winit::window::Window`, found a different struct `winit::window::Window`
   = note: expected reference `&winit::window::Window` (struct `winit::window::Window`)
              found reference `&winit::window::Window` (struct `winit::window::Window`)
   = note: perhaps two different versions of crate `winit` are being used?
```

changing the dependency to `winit = "0.24"` fixes the problem and works fine.

**Comment by Rua** [comment]
Hmm that's odd. With the 0.23 release there was a mistake in how Vulkano got published, but that doesn't seem to have happened this time with 0.24. The Cargo.toml file for Vulkano-win correctly has Vulkano 0.24 and Winit 0.25 as dependencies, and the versions on Crates.io are all 0.24 this time around.

**Comment by korteland** [comment]
thanks for the quick reply. i had a look at the only project on your profile (ferret) and it does indeed build fine with those dependencies. 

this was confusing, so i blew away my cargo cache and `target/` directory and it works fine now. it looks like it might've been a cargo bug, but unfortunately i can't repro it. thanks for spending some time on this
