### ISSUE TITLE
FramebufferBuilder how to add attachements to it given a SwapchainImage ?

### ISSUE THREAD

**Issue by xenoliss** [vulkano-rs/vulkano#1626]
*   Version of vulkano: 0.24.0
*   OS: Windows

# Issue

Hi there, I'm learning Vulkan (and Vulkano) so I might have missed something but while following the vulkano-examples/triangle.rs with Vulkano 0.24 I had to make quite a few changes because of API changes. While I've been able to follow the major part of it I'm stuck when time to create framebuffers has come. I'm also using [this tutorial](https://github.com/bwasty/vulkan-tutorial-rs/blob/master/src/bin/13_framebuffers.rs) as a reference. 

To make it simple **how do I get a valide `attachment` from a `SwapchainImage<Window>`** ? Both [your example](https://github.com/vulkano-rs/vulkano-examples/blob/master/src/bin/triangle.rs#L545) and the [other tutorial](https://github.com/bwasty/vulkan-tutorial-rs/blob/master/src/bin/13_framebuffers.rs#L401) are directly giving the `SwapchainImage<Window>` object to the `add` method of the `FramebufferBuilder` object but on my side it does not compile. 

Since I have linting enabled that shows the object types it could help I guess so here is a screeenshot of my chunk of code with the associated error :

![image](https://user-images.githubusercontent.com/33523487/124160792-ecf27c80-da9c-11eb-86e6-c87659360d28.png)

Thanks for your help !

**Comment by Rua** [comment]
Vulkano-examples looks to be a little outdated with all the breaking changes that have been made to recent Vulkano versions. Vulkano also has its own examples right here: https://github.com/vulkano-rs/vulkano/tree/master/examples. Do those work for you?

**Comment by xenoliss** [comment]
Hi ! Yes it looks better already thanks ! There are still some methods not available like `supported_extensions` on a `PhysicalDevice` object. I'm using vulkano 0.24 so not sure why the api is not the same as in your example. Basically I don't have the `vulkano::device::physical` module while my `Cargo.toml` is :

```
[dependencies]
winit = "0.25.0"
vulkano = "0.24.0"
vulkano-win = "0.24.0"
vulkano-shaders = "0.24.0"
```

**Comment by Rua** [comment]
Vulkano's git version is not 0.24, it has already had some changes since 0.24 was released. You'll want to either use the git version in your project, or use the examples of version 0.24 when it was released.

**Comment by xenoliss** [comment]
This is insane how fast you're replying ! I see. Should I depend on vulkano from the vulkano-rs repo or the original vulkano repo ? What are the differencies (why are there 2 repo actually ) ?

**Comment by Rua** [comment]
You'll want to go with this repository. This is the one where development takes place, and examples here are kept up to date with any changes made elsewhere in the code.

I don't know why there is a separate vulkano-examples repository. It was created by Tomaka, the original creator of Vulkano, so they probably had some purpose for it, but they are no longer active. In principle it's maintained separately from this repository, by different people, so it doesn't necessarily keep up with changes made to the code base here.

**Comment by xenoliss** [comment]
Alright. Might be able to follow along the rest of the tutorial now. Thanks !
