### ISSUE TITLE
Can't create `FramebufferSys`:  cannot initialize a tuple struct which contains private fields

### ISSUE THREAD

**Issue by styleex** [vulkano-rs/vulkano#1636]
*   Version of vulkano: 0.24
Problem: 
Can't create `FramebufferSys`:  cannot initialize a tuple struct which contains private fields

Uses case: 
I need to create my own implementation of `Framebuffer` and `FramebufferBuilder` (with dynamic number of attachments like `FramebufferBuilder.boxed` but with implemented Sync + Send traits), but i cant implement AbstractFramebuffer trait - it return FramebufferSys with private fields. 

I found workaround: create wrapper over `Framebuffer<Box<dyn AttachmentsList>>` with Sync + Send markers, but I think it would be great to be able to implement AbstractFramebuffer.

**Comment by Rua** [comment]
Would #1739 fix your issue? It removes the type parameter from `Framebuffer` so there is no more `FramebufferAbstract` trait.
