### ISSUE TITLE
Does not compile

### ISSUE THREAD

**Issue by Plegeus** [vulkano-rs/vulkano#1645]
![image](https://user-images.githubusercontent.com/77695868/126628786-776c50dd-f785-4662-b1e2-34cb696ad09e.png)

Just added the dependency, empty hello word project...

**Comment by Rua** [comment]
Does this also happen with the latest version of Vulkano?

**Comment by Plegeus** [comment]
in version 0.24.0 I get:

#######################################################################

error[E0658]: use of unstable library feature 'array_value_iter'
  --> C:\Users\timot\.cargo\registry\src\github.com-1ecc6299db9ec823\vulkano-0.24.0\autogen\fns.rs:71:20
   |
71 |     for version in std::array::IntoIter::new(["1_0", "1_1", "1_2"]) {
   |                    ^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: see issue #65798 <https://github.com/rust-lang/rust/issues/65798> for more information

error[E0658]: use of unstable library feature 'array_value_iter'
  --> C:\Users\timot\.cargo\registry\src\github.com-1ecc6299db9ec823\vulkano-0.24.0\autogen\properties.rs:73:5
   |
73 |     std::array::IntoIter::new([
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: see issue #65798 <https://github.com/rust-lang/rust/issues/65798> for more information

error[E0658]: use of unstable library feature 'str_split_once': newly added
   --> C:\Users\timot\.cargo\registry\src\github.com-1ecc6299db9ec823\vulkano-0.24.0\autogen\mod.rs:203:55
    |
203 | ...                   return Some(code.code.rsplit_once(' ').unwrap().1.parse().unwrap());
    |                                             ^^^^^^^^^^^
    |
    = note: see issue #74773 <https://github.com/rust-lang/rust/issues/74773> for more information

error[E0658]: use of unstable library feature 'str_split_once': newly added
  --> C:\Users\timot\.cargo\registry\src\github.com-1ecc6299db9ec823\vulkano-0.24.0\autogen\extensions.rs:77:18
   |
77 |                 .split_once('.')
   |                  ^^^^^^^^^^
   |
   = note: see issue #74773 <https://github.com/rust-lang/rust/issues/74773> for more information

error[E0658]: use of unstable library feature 'str_split_once': newly added
   --> C:\Users\timot\.cargo\registry\src\github.com-1ecc6299db9ec823\vulkano-0.24.0\autogen\extensions.rs:114:58
    |
114 | ...                   let (major, minor) = version.split_once('_').unwrap();
    |                                                    ^^^^^^^^^^
    |
    = note: see issue #74773 <https://github.com/rust-lang/rust/issues/74773> for more information

error[E0658]: use of unstable library feature 'str_split_once': newly added
   --> C:\Users\timot\.cargo\registry\src\github.com-1ecc6299db9ec823\vulkano-0.24.0\autogen\extensions.rs:140:66
    |
140 | ...                   let (major, minor) = version.split_once('_').unwrap();
    |                                                    ^^^^^^^^^^
    |
    = note: see issue #74773 <https://github.com/rust-lang/rust/issues/74773> for more information

error[E0658]: use of unstable library feature 'str_split_once': newly added
   --> C:\Users\timot\.cargo\registry\src\github.com-1ecc6299db9ec823\vulkano-0.24.0\autogen\features.rs:340:46
    |
340 |                 let (major, minor) = version.split_once('_').unwrap();
    |                                              ^^^^^^^^^^
    |
    = note: see issue #74773 <https://github.com/rust-lang/rust/issues/74773> for more information

error[E0658]: use of unstable library feature 'str_split_once': newly added
   --> C:\Users\timot\.cargo\registry\src\github.com-1ecc6299db9ec823\vulkano-0.24.0\autogen\features.rs:369:34
    |
369 |     let (base, suffix) = ty_name.rsplit_once("_features").unwrap();
    |                                  ^^^^^^^^^^^
    |
    = note: see issue #74773 <https://github.com/rust-lang/rust/issues/74773> for more information

error[E0658]: use of unstable library feature 'str_split_once': newly added
   --> C:\Users\timot\.cargo\registry\src\github.com-1ecc6299db9ec823\vulkano-0.24.0\autogen\properties.rs:228:46
    |
228 |                 let (major, minor) = version.split_once('_').unwrap();
    |                                              ^^^^^^^^^^
    |
    = note: see issue #74773 <https://github.com/rust-lang/rust/issues/74773> for more information

error[E0658]: use of unstable library feature 'str_split_once': newly added
   --> C:\Users\timot\.cargo\registry\src\github.com-1ecc6299db9ec823\vulkano-0.24.0\autogen\properties.rs:257:34
    |
257 |     let (base, suffix) = ty_name.rsplit_once("_properties").unwrap();
    |                                  ^^^^^^^^^^^
    |
    = note: see issue #74773 <https://github.com/rust-lang/rust/issues/74773> for more information

error: aborting due to 10 previous errors

For more information about this error, try `rustc --explain E0658`.
error: could not compile `vulkano`

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: build failed

#######################################################################

The previous errors were in version 0.19, which seems to be recommended by vulkano.rs
![image](https://user-images.githubusercontent.com/77695868/126638502-798b7e8b-e030-4850-9770-ed04119952d1.png)

I have to say I am quite new to Rust, but it seems odd that cargo check gives me this even though I didn't write a single line of code yet...

**Comment by Rua** [comment]
Those messages about unstable library features make me think you are using an old version of the Rust compiler. Do the errors go away if you update it?

**Comment by Plegeus** [comment]
I updated the compilers, the errors did in fact go away! thanks so much! :)
