### ISSUE TITLE
Question about subpasses

### ISSUE THREAD

**Issue by RebelAndroid** [vulkano-rs/vulkano#1646]
This is a question, but I don't know how to mark it as such.

*   Version of vulkano: 0.24.0
*   OS: Ubunut 20.04.2
*   GPU (the selected PhysicalDevice): rx 5600 xt
*   GPU Driver: amdgpu-pro-21.10
This is the full code: [main.txt](https://github.com/vulkano-rs/vulkano/files/6880334/main.txt)

I am trying to write a deferred renderer (I was using the deferred example as a reference), but I can't figure out how to get my shader to write into the g-buffer. I can read from it in my shading pass (I can use the clear values to write into it), but I can't write into it in my geometry pass.
The subpass setup looks like this: 
```
let render_pass = Arc::new(
            vulkano::ordered_passes_renderpass!(device.clone(),
                attachments: {
                    final_color: {
                        load: Clear,
                        store: Store,
                        format: swapchain.format(),
                        samples: 1,
                    },
                    depth: {
                        load: Clear,
                        store: Store,
                        format: Format::D32Sfloat,
                        samples: 1,
                    },
                    position: {
                        load: Clear,
                        store: Store,
                        format: Format::R16G16B16A16Sfloat,
                        samples: 1,
                    },
                    normal: {
                        load: Clear,
                        store: Store,
                        format: Format::R16G16B16A16Sfloat,
                        samples: 1,
                    },
                    roughness: {
                        load: Clear,
                        store: Store,
                        format: Format::R8Unorm,
                        samples: 1,
                    },
                    base_color: {
                        load: Clear,
                        store: Store,
                        format: Format::R8G8B8A8Srgb,
                        samples: 1,
                    }
                    
                },
                passes: [
                    {
                        color: [position, normal, roughness, base_color],
                        depth_stencil: {depth},
                        input: []
                    },
                    {
                        color: [final_color],
                        depth_stencil: {},
                        input: [depth, position, normal, roughness, base_color]
                    }
                ]
            )
            .unwrap(),
        );
```
The shader that I want to write to the g-buffer with looks like this: 
```
#version 450

layout(location = 0) in vec3 texture_coords;

layout(location = 0) out vec4 g_world_pos;
layout(location = 1) out vec4 g_world_normal;
layout(location = 2) out float g_roughness;
layout(location = 3) out vec4 g_base_color;

layout(set = 0, binding = 0) uniform samplerCube skybox;



void main(){
    g_world_pos = vec4(texture_coords, 1.0);
    g_world_normal = vec4(0.0);
    g_roughness = 0.0;
    g_base_color = texture(skybox, texture_coords);
}
```
The shader that reads from the g-buffer looks like this:
```
#version 450

layout(location = 0) in vec2 f_pos;

layout(location = 0) out vec4 f_color;

layout(input_attachment_index = 0, set = 0, binding = 0) uniform subpassInput g_depth;
layout(input_attachment_index = 1, set = 0, binding = 1) uniform subpassInput g_world_pos;
layout(input_attachment_index = 2, set = 0, binding = 2) uniform subpassInput g_world_normal;
layout(input_attachment_index = 3, set = 0, binding = 3) uniform subpassInput g_roughness;
layout(input_attachment_index = 4, set = 0, binding = 4) uniform subpassInput g_base_color;

void main() {
    // float depth = subpassLoad(g_depth).x;
    // f_color = vec4(depth, depth, depth, 1.0);
    f_color = subpassLoad(g_base_color);
}
```
the command buffer code is this: 
```
let mut command_buffer_builder = AutoCommandBufferBuilder::primary(self.device.clone(), self.queue.family().clone(), CommandBufferUsage::OneTimeSubmit).unwrap();
        let clear_values = vec![
            [0.0, 0.0, 0.0, 0.0].into(), // final_color
            1.0f32.into(),               // depth
            [0.0, 0.2, 0.2, 0.0].into(), // world position
            [0.1, 0.1, 0.1, 0.0].into(), // world normal
            [0.0].into(),                // roughness
            [0.0, 0.8, 0.8, 1.0].into(), // base color
        ];

        command_buffer_builder.begin_render_pass(self.framebuffers[image_num].clone(), SubpassContents::SecondaryCommandBuffers, clear_values).unwrap();
        //command_buffer_builder.execute_commands(self.geometry_pass());
        command_buffer_builder.execute_commands(self.skybox_pass()).unwrap();
        command_buffer_builder.next_subpass(SubpassContents::SecondaryCommandBuffers).unwrap();
        command_buffer_builder.execute_commands(self.shading_pass(image_num)).unwrap();
        command_buffer_builder.end_render_pass().unwrap();

        let command_buffer = command_buffer_builder.build().unwrap();


        let future = self.previous_frame_end.take().unwrap().join(aquire_future)
        .then_execute(self.queue.clone(), command_buffer).unwrap()
        .then_swapchain_present(self.queue.clone(), self.swapchain.clone(), image_num)
        .then_signal_fence_and_flush();


fn skybox_pass(&mut self) -> SecondaryAutoCommandBuffer{
        let mut builder = AutoCommandBufferBuilder::secondary_graphics(self.device.clone(), self.queue.family(), CommandBufferUsage::MultipleSubmit, self.skybox_pipeline.subpass().clone()).unwrap();
        let pc = self.get_pc_skybox();
        builder.draw(self.skybox_pipeline.clone(), &self.dynamic_state, self.skybox_vertex_buffer.clone(), self.skybox_set.clone(), pc, vec![]).unwrap();
        builder.build().unwrap()
    }


    fn shading_pass(&mut self, num_image: usize) -> SecondaryAutoCommandBuffer{
        let mut builder = AutoCommandBufferBuilder::secondary_graphics(self.device.clone(), self.queue.family(), CommandBufferUsage::MultipleSubmit, self.shading_pipeline.subpass().clone()).unwrap();
        let vertex_data = vec![ShadingVertex{position: (-1.0, -1.0)}, ShadingVertex{position: (1.0, -1.0)}, ShadingVertex{position: (-1.0, 1.0)},
        ShadingVertex{position: (1.0, -1.0)}, ShadingVertex{position: (1.0, 1.0)}, ShadingVertex{position: (-1.0, 1.0)}];
        let vertex_buffer = CpuAccessibleBuffer::from_iter(self.device.clone(), BufferUsage::vertex_buffer(), false, vertex_data.iter().cloned()).unwrap();

        let layout = self.shading_pipeline.layout().descriptor_set_layout(0).unwrap();

        let descriptor_set = PersistentDescriptorSet::start(layout.clone())
        .add_image(self.g_buffer[0].clone()).unwrap()
        .add_image(self.g_buffer[1].clone()).unwrap()
        .add_image(self.g_buffer[2].clone()).unwrap()
        .add_image(self.g_buffer[3].clone()).unwrap()
        .add_image(self.g_buffer[4].clone()).unwrap()
        .build().unwrap();

        builder.draw(self.shading_pipeline.clone(), &self.dynamic_state, vertex_buffer, descriptor_set, (), vec![]);

        builder.build().unwrap()
    }
```
The screen is just the cyan color that I clear the base_color with.
This is my first time using vulkano so I'm sorry if I am missing something obvious.

**Comment by AustinJ235** [comment]
I wonder if there is a sync error going on here.

**Comment by RebelAndroid** [comment]
I tried renderdoc and it looks like g_base_color is being cleared when next_subpass is called. It's hard to tell though, because renderdoc crashes whenever I try to look at the skybox draw call.

**Comment by Rua** [comment]
Does vkconfig with synchronization validation tell you anything?

**Comment by RebelAndroid** [comment]
I tried vkconfig and got this:

Launching Vulkan Application:
- Layers overridden by "Synchronization" configuration.
- Executable Path: /home/christopher/Desktop/rust/vulkan_renderer/target/release/vulkan_renderer
- Working Directory: /home/christopher/Desktop/rust/vulkan_renderer
- Log file: /home/christopher/VulkanSDK/vulkan_renderer.txt

UNASSIGNED-khronos-validation-createinstance-status-message(INFO / SPEC): msgNum: -671457468 - Validation Information: [ UNASSIGNED-khronos-validation-createinstance-status-message ] Object 0: handle = 0x5609deaabdb0, type = VK_OBJECT_TYPE_INSTANCE; | MessageID = 0xd7fa5f44 | Khronos Validation Layer Active:
    Settings File: Found at /home/christopher/.local/share/vulkan/settings.d/vk_layer_settings.txt specified by VkConfig application override.
    Current Enables: VK_VALIDATION_FEATURE_ENABLE_SYNCHRONIZATION_VALIDATION.
    Current Disables: VK_VALIDATION_FEATURE_DISABLE_OBJECT_LIFETIMES_EXT, VK_VALIDATION_FEATURE_DISABLE_CORE_CHECKS_EXT, VK_VALIDATION_FEATURE_DISABLE_API_PARAMETERS_EXT, VK_VALIDATION_FEATURE_DISABLE_UNIQUE_HANDLES_EXT.

    Objects: 1
        [0] 0x5609deaabdb0, type: 1, name: NULL

device found: AMD Radeon RX 5600 XT

validation layer: "Inserted device layer VK_LAYER_KHRONOS_synchronization2 (libVkLayer_khronos_synchronization2.so)"
validation layer: "Inserted device layer VK_LAYER_KHRONOS_validation (libVkLayer_khronos_validation.so)"
validation layer: "Failed to find vkGetDeviceProcAddr in layer libVkLayer_MESA_device_select.so"

using composite alpha mode: Opaque
using format: B8G8R8A8Srgb

vertices: 34834, triangles: 69451

closing window

Process terminated

I don't think it is a synchronization error because the order of events looks correct in renderdoc.

**Comment by Rua** [comment]
That eliminates one possibility at least.

**Comment by RebelAndroid** [comment]
I made this working example from the triangle example, and in renderdoc it looks like the color attachment is not cleared between subpasses. Maybe it's the difference between SubpassContents::Inline and SubpassContents::SecondaryCommandBuffers?
[triangle_deferred.txt](https://github.com/vulkano-rs/vulkano/files/6911576/triangle_deferred.txt)

**Comment by AustinJ235** [comment]
I have been prototyping a new rendering system for Basalt. I think I may be running into a similar issue. I might have something messed up in my code, but I have spent hours trying to figure out why I have ghosting of previous images even after the swapchain has been recreated.

**Comment by Rua** [comment]
I don't know if this is still a problem, but in regard to clearing between subpasses, that's not something Vulkan actually does. It only clears at the start of the whole render pass. To clear attachments in the middle of a render pass, you would use the `clear_attachments` command on command buffers instead. But the documentation does warn against that:
> It is generally preferable to clear attachments by using the `VK_ATTACHMENT_LOAD_OP_CLEAR` load operation at the start of rendering, as it is more efficient on some implementations.
