### ISSUE TITLE
some properties *are* known by every device

### ISSUE THREAD

**Issue by incertia** [vulkano-rs/vulkano#1649]
as per #1605
```
  - To allow for the possibility that not every property is known by the physical device, fields in `Properties` are wrapped by an `Option`.
```
i assume this is being done via [`vkGetPhysicalDeviceProperties2`](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/vkGetPhysicalDeviceProperties2.html), which returns a [`VkPhysicalDeviceProperties2`](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VkPhysicalDeviceProperties2.html), which contains a [`VkPhysicalDeviceProperties`](khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VkPhysicalDeviceProperties.html). from my understanding, the remaining fields, e.g. [`VkPhysicalDeviceDriverProperties`](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VkPhysicalDeviceDriverProperties.html) are optional but the core properties should be not `Option`, especially since the call to [`vkGetPhysicalDeviceProperties2`](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/vkGetPhysicalDeviceProperties2.html) cannot fail.

**Comment by Rua** [comment]
In principle you are right, these should not be an `Option`. But accounting for that in the `properties!` macro is tricky. Do you have any ideas?

**Comment by AustinJ235** [comment]
Macros are tricky never really understood them well, but this would eliminate unwraps where they are redundant.

**Comment by Rua** [comment]
Perhaps, since this code is generated by a build script anyway, we can get rid of the macros entirely and generate the final code directly from the autogen code. True Rust code can be a lot more flexible about what it generates than macros.
