### ISSUE TITLE
ShaderInterfaceEntry.name is Cow<'static, str>

### ISSUE THREAD

**Issue by incertia** [vulkano-rs/vulkano#1652]
is there any reasoning behind this? i am trying to dynamically parse spir-v modules into entries and this seems like an unfortunate design decision.

**Comment by incertia** [comment]
on that note, inside `src/pipeline/vertex/single.rs`
```rust
unsafe impl<T> VertexDefinition for SingleBufferDefinition<T>
where
    T: Vertex,
{
    type BuffersIter = OptionIntoIter<(u32, usize, InputRate)>;
    type AttribsIter = VecIntoIter<(u32, u32, AttributeInfo)>;

    fn definition(
        &self,
        interface: &ShaderInterface,
    ) -> Result<(Self::BuffersIter, Self::AttribsIter), IncompatibleVertexDefinitionError> {
        let attrib = {
            let mut attribs = Vec::with_capacity(interface.elements().len());
            for e in interface.elements() {
                let name = e.name.as_ref().unwrap(); // <--- THIS LINE HERE
```
crashes when you pass in `None` for the name

**Comment by incertia** [comment]
doing even more reading, it appears as if i will need to provide my own `VertexDefinition` to get around this, so the explicit unwrap is probably ok to stay

**Comment by Rua** [comment]
Is the problem that you are being required to provide a name when you don't want/have one?

**Comment by incertia** [comment]
i have some runtime allocated name which is not `'static` that i would like to use
