### ISSUE TITLE
No way of using a different format in an ImageView tahn the image's one

### ISSUE THREAD

**Issue by pac85** [vulkano-rs/vulkano#1666]
As stated in the [official documentation](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VkImageViewCreateInfo.html) "If image was created with the VK_IMAGE_CREATE_MUTABLE_FORMAT_BIT flag, and if the format of the image is not multi-planar, format can be different from the image’s format, but if image was created without the VK_IMAGE_CREATE_BLOCK_TEXEL_VIEW_COMPATIBLE_BIT flag and they are not equal they must be compatible. Image format compatibility is defined in the [Format Compatibility Classes](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#formats-compatibility-classes) section. Views of compatible formats will have the same mapping between texel coordinates and memory locations irrespective of the format, with only the interpretation of the bit pattern changing."

This is important to be able to automatically convert between sRGB and linear RGB and has many other uses, however vulkano assumes that those two are always equal [here](https://docs.rs/vulkano/0.24.0/src/vulkano/image/view.rs.html#146) [here](https://docs.rs/vulkano/0.24.0/src/vulkano/image/view.rs.html#328) and possibly in other places.

**Comment by Rua** [comment]
If I understand correctly, in order for this to be useful, there needs to be support for those image flags first?

**Comment by pac85** [comment]
mutable format seems to be exposed already
