### ISSUE TITLE
Allow for uninitialized sub-buffers within CpuBufferPools

### ISSUE THREAD

**Issue by incertia** [vulkano-rs/vulkano#1672]
This particular use case is for instancing with a dynamic number of objects. The easiest way is to just allocate a large enough pool and then only copy over the data that will be used for the next frame. This can save unnecessary copies during instances the actual data is significantly less than what was allocated.

Unrelated, what would be a good strategy for copying additional data into the buffer if we want to draw more than that number of objects? Do we just allocate another similarly sized buffer?

**Comment by Rua** [comment]
I think the general idea behind `CpuBufferPool` is that you use the buffer you allocate only once or a few times in a single frame, and then drop it. So in your case, you would allocate a subbuffer for your dynamic number of objects, and use it once. Then when you have a different number, you make a new subbuffer and use that. That's the use case it seems to be optimised for.

**Comment by incertia** [comment]
Allocating once per frame doesn't seem like a good idea but maybe. Not that I currently hit the limit, but currently I'm batching things in 4K-sized pools.

```rust
  pub(super) fn draw_commands(
    &self,
    device: Arc<Device>,
    usage: CommandBufferUsage,
    ds: &DynamicState,
  ) -> Result<SecondaryAutoCommandBuffer> {
    let mut builder = AutoCommandBufferBuilder::secondary_graphics(
      device.clone(),
      self.queue.family(),
      usage,
      self.subpass.clone(),
    )?;

    for chunk in self.quads.as_slice().chunks(BATCH_SIZE) {
      let buf = self.quad_pool.next(match chunk.try_into() {
        Ok(arr) => arr,
        Err(_) => {
          let mut arr: [Transform2D; BATCH_SIZE] =
            unsafe { std::mem::MaybeUninit::uninit().assume_init() };
          arr[..chunk.len()].copy_from_slice(chunk);
          arr   // <-- this is a slice with some uninitialized memory that I'd rather
                // not copy into quad_pool.next() and instead just perform a partial copy
        }
      })?;

      builder.draw(
        6,
        chunk.len() as u32,
        0,
        0,
        self.pipeline.clone(),
        ds,
        (self.quad_vb.clone(), buf),
        (),
        (),
      )?;
    }

    Ok(builder.build()?)
  }
```

**Comment by Rua** [comment]
Just to be clear, `CpuBufferPool` doesn't "allocate" every buffer in the Vulkan sense. It creates a single large buffer and then gives you smaller pieces of it. If it runs out of space, it makes a new buffer and discards the old one once there's no more references to it. So in the ideal case, once things stabilise size-wise, there is only one physical Vulkan buffer internally for the whole pool. I think that's very similar to what you're doing, except more convenient?

**Comment by incertia** [comment]
The `CpuBufferPool` strategy definitely seems more ideal. It would just be good to have a more direct API representation of performing partial uploads rather than going through `BufferAccess::try_gpu_lock()`, even if unsafe since it is partial.

**Comment by Rua** [comment]
I'm closing this because as far as I can tell, `CpuBufferPool` fulfills what's needed here.
