### ISSUE TITLE
Improve vulkano-shaders to actually become runnable at runtime and not just proc macros

### ISSUE THREAD

**Issue by incertia** [vulkano-rs/vulkano#1673]
vulkano-shaders is able to do a lot of introspection into a spirv blob and it would be nice to pull out that information dynamically at runtime rather than being forced to use macros at compile time, although keeping the option to use compile time macros would be great. i find myself writing my own spirv blob parser and having to inspire myself a lot from the vulkano-shaders internals to understand what is actually going on.

**Comment by Rua** [comment]
I think you're proposing the same as #1558?

**Comment by incertia** [comment]
Yeah that seems about right. I'll close this.
