### ISSUE TITLE
`vulkano::buffer::BufferUsage::storage_buffer()` implementation missing

### ISSUE THREAD

**Issue by itzmeanjan** [vulkano-rs/vulkano#1675]
# Template

*   Version of vulkano: 0.25.*
*   OS: GNU/Linux
*   GPU (the selected PhysicalDevice): [Intel HD Graphics](http://vulkan.gpuinfo.org/listreports.php?devicename=Intel%28R%29+HD+Graphics+5500+%28BDW+GT2%29)
*   GPU Driver: TODO
*   Upload of a reasonably minimal complete `main.rs` file that demonstrates the issue: TODO

# Issue

Hello, first of all thanks for creating `vulkano`, enabling comfortable interaction with vulkan API, compared to writing vulkan in C. 

I was wondering why in [BufferUsage](https://docs.rs/vulkano/0.25.0/src/vulkano/buffer/usage.rs.html#19-32)::`storage_buffer` not implemented as it's done for other buffer usage patterns like [transfer{src,dst}](https://docs.rs/vulkano/0.25.0/src/vulkano/buffer/usage.rs.html#71-76) ?

**Comment by Rua** [comment]
I don't see a reason why it couldn't be added. Do you want to make a PR?

**Comment by itzmeanjan** [comment]
> Do you want to make a PR?

I've raised one [here](#1676)

**Comment by Rua** [comment]
This is merged now.
