### ISSUE TITLE
A struct with an aray in  a glsl shader will crash vulkano-shaders

### ISSUE THREAD

**Issue by pac85** [vulkano-rs/vulkano#1683]
```
= help: message: called `Option::unwrap()` on a `None` value
```
happens on src/structs.rs:526

**Comment by pac85** [comment]
Yes sorry I should have said that. It was a fixed length array, I can easily  reproduce the bug by pasting the following comment in the vulkan-shaders documentation and running cargo test:
```
mod vs {
    vulkano_shaders::shader!{
        ty: "vertex",
        src: "
#version 450
                                       
layout(location = 0) in vec3 position;
                                       
struct A {
    vec3 ar[3];
};
                                       
void main() {
    A a;
    gl_Position = vec4(a.ar[0], 1.0);
}"
    }
}
# fn main() {}
```

The struct has to be used in order for the error to appear.

**Comment by Rua** [comment]
@AustinJ235 any idea?

**Comment by AustinJ235** [comment]
If it were a vec4 instead would it work? Might be a stride issue.

**Comment by Rua** [comment]
Does this problem still occur with the newest version of Vulkano?

**Comment by pac85** [comment]
> Does this problem still occur with the newest version of Vulkano?

I'm able to reproduce it in the latest version cloned from master
