### ISSUE TITLE
support Zero-Sized-Types 

### ISSUE THREAD

**Issue by rroohhh** [vulkano-rs/vulkano#1686]
Currently there are various parts that assume that the type of a buffer and vertex data are not zero sized.

For example the `Content` impl for `[T]`
https://github.com/vulkano-rs/vulkano/blob/f79814c2f25a70dd1f138c1b3d043940fb40fc16/vulkano/src/memory/mod.rs#L200
Aswell as parts of the validity checking:
https://github.com/vulkano-rs/vulkano/blob/f79814c2f25a70dd1f138c1b3d043940fb40fc16/vulkano/src/command_buffer/validity/vertex_buffers.rs#L34-L36

I am not sure what the correct approach would be here, atleast for the latter. One the one hand, if it is a ZST, any `vertex_buffer.size()` can satisfy any required vertex count, on the other hand the vertex count should probably still match what was specified when the "thing" implementing `dyn BufferAccess` was created, which would in turn necessitate `BufferAccess` to track this number.

Any thoughts?

**Comment by rroohhh** [comment]
Are zero strides actually not allowed? That's unfortunate :(

`std::mem::size_of::<T>()` is const, so in theory it can be used to produce compile time errors (by using the usual indexing into a array trick). However you cannot use `std::mem::size_of<T>()` as const is `T` is generic, which makes this afaict impossible to use in the way `vulkano` would need it currently.

**Comment by Rua** [comment]
There's the `static_assertions` crate, which is well developed and stable. But adding dependencies to Vulkano always requires some thought.

**Comment by rroohhh** [comment]
Ah right you could forbid it atleast in the `impl_vertex` like this:
```patch
diff --git a/vulkano/src/pipeline/vertex/impl_vertex.rs b/vulkano/src/pipeline/vertex/impl_vertex.rs
index 7694b962..dfb71588 100644
--- a/vulkano/src/pipeline/vertex/impl_vertex.rs
+++ b/vulkano/src/pipeline/vertex/impl_vertex.rs
@@ -36,6 +36,8 @@ macro_rules! impl_vertex {
                 use $crate::pipeline::vertex::VertexMemberTy;
                 use $crate::pipeline::vertex::VertexMember;

+                const _: &() = &[(); std::mem::size_of::<$out>()][0];
+
                 $(
                     if name == stringify!($member) {
                         let dummy = <$out>::default();
```

but the error message is not very nice:
```error: any use of this value will cause an error
   --> narui_core/src/vulkano_render/rounded_rect_renderer.rs:148:1
    |
148 | vulkano::impl_vertex!(A);
    | ^^^^^^^^^^^^^^^^^^^^^^^^^ index out of bounds: the length is 1 but the index is 1
    |
    = note: `#[deny(const_err)]` on by default
    = warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!
    = note: for more information, see issue #71800 <https://github.com/rust-lang/rust/issues/71800>
    = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

```
(this is basically doing the same as `static_assertions`, the error message there is not really better)
