### ISSUE TITLE
No method named `set_viewport` found for AutoCommandBufferBuilder

### ISSUE THREAD

**Issue by pintariching** [vulkano-rs/vulkano#1691]
*   Version of vulkano: 0.25.0
*   OS: Ubuntu 21.04
*   GPU (the selected PhysicalDevice): NVIDIA GeForce GTX 1660 SUPER
*   GPU Driver: Nvidia-driver-470
*   Upload of a reasonably minimal complete `main.rs` file that demonstrates the issue: https://github.com/pintariching/vulkano-test

# Issue

I've attached a repo above where I'm getting the error 
```
no method named `set_viewport` found for mutable reference `&mut vulkano::command_buffer::AutoCommandBufferBuilder<PrimaryAutoCommandBuffer>` in the current scope 
```
The error appears in the setup of the `AutoCommandBufferBuilder` on line 261
```
builder
  .begin_render_pass(
  frame_buffers[image_num].clone(),
  SubpassContents::Inline,
  clear_values
  )
  .unwrap()
  .set_viewport(0, [viewport.clone()])	// <-- In this line
  .bind_pipeline_graphics(pipeline.clone())
  .bind_vertex_buffers(0, vertex_buffer.clone())
  .draw(vertex_buffer.len() as u32, 1, 0, 0)
  .unwrap()
  .end_render_pass()
  .unwrap();
```

The funny thing is, if I clone the vulkano repo and run the examples with `cargo run --bin trinagle` it works as it should.
But if I copy the entire file with all the imports and put it into a seperate project everything works up untill this point.

Sorry if it's a stupid mistake on my part, I'm a bit new to all of this graphics programming.

**Comment by AustinJ235** [comment]
That is a vulkano master change, if you're are using the released version view the docs site.

**Comment by melendezd** [comment]
Looks like `set_viewport` was added after the latest release (`0.25.0`) which you have listed as a dependency in your `Cargo.toml`, so it wouldn't show up in the version of vulkano cargo pulls in when you build. You can use [this version of the example](https://github.com/vulkano-rs/vulkano/blob/a6dc45260538ecc6025d8f062cd058245e684cb3/examples/src/bin/triangle.rs) if you'd like to work with release, or have cargo pull the libraries in straight from git if you're a thrill seeker (probably not recommended).
