### ISSUE TITLE
Is it ok for Vulkano-shaders to depend on Vulkano?

### ISSUE THREAD

**Issue by Rua** [vulkano-rs/vulkano#1693]
@AustinJ235 @Eliah-Lakhin I would like to start moving some of the code in Vulkano-shaders to the main Vulkano crate, so that it can be used both by runtime-loaded shaders and shaders compiled with Vulkano-shaders. But to avoid duplication, Vulkano-shaders would need to be able to import some of these items from the main crate. It currently lists Vulkan only as a dev-dependency, but I would like to upgrade this to a full dependency. This would mean that Vulkano-shaders can't be used without Vulkano anymore, but I think that's ok because it outputs Vulkano-specific code anyway and wouldn't be particularly useful without it.

**Comment by Eliah-Lakhin** [comment]
@Rua I think that's fine. But can you please outline what particular changes are you going to do? The thing is I'm currently working on some Vulkano-shaders improvements too.

**Comment by Rua** [comment]
Implementing #1558, but I also wanted to see if I could generate some of the types such as `Instruction` automatically from the SPIR-V grammar JSON file. There is no hurry though, I haven't done any work yet so I'll wait for you to finish.

**Comment by Eliah-Lakhin** [comment]
@Rua ok, sounds good. Just to let you know that I'm currently working on extension of vulkan-shaders to compile several sources at once producing independent generated layout per each source, but keeping all their structs in a single shareable generated `ty` mod.  This feature should resolve a long-standing problem of type-safe interoperability between generated shaders. I probably will finish this work today and provide a PR.
