### ISSUE TITLE
OutOfDeviceMemory on image.exe/teapot.exe GTX 770 4GB

### ISSUE THREAD

**Issue by zaklaus** [vulkano-rs/vulkano#172]
I get following error on my nvidia gtx 770-4gb when using examples. I'm using the latest nvidia drivers (368.69.0) on updated Windows 10 Home x64. Vulkan works on triangle.exe example.

```
W:\vulkano\examples\target\debug>teapot.exe
Using device: GTX 770 (type: DiscreteGpu)
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: OomError(OutOfDeviceMemory)', ../src/libcore\result.rs:746
note: Run with `RUST_BACKTRACE=1` for a backtrace.

W:\vulkano\examples\target\debug>triangle.exe
Using device: GTX 770 (type: DiscreteGpu)

W:\vulkano\examples\target\debug>image.exe
Using device: GTX 770 (type: DiscreteGpu)
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: OomError(OutOfDeviceMemory)', ../src/libcore\result.rs:746
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

**Comment by tomaka** [comment]
Could you run with `RUST_BACKTRACE=1` to see where the unwrap occurs?

**Comment by tomaka** [comment]
The stack trace leads to the moment where we create the transient depth buffer.
I suppose that's caused by lazily-allocated memory, but I'm not sure why.

**Comment by AustinJ235** [comment]
This seems related to https://github.com/vulkano-rs/vulkano/issues/172, closing in favor of that.
