### ISSUE TITLE
Published vulkano 0.26.0 crate has invalid LICENSE-* files

### ISSUE THREAD

**Issue by jmacnak** [vulkano-rs/vulkano#1728]
Downloading https://static.crates.io/crates/vulkano/vulkano-0.26.0.crate, untar'ing the downloaded crate, and inspected the LICENSE-APACHE and LICENSE-MIT shows "../LICENSE-APACHE" and "../LICENSE-MIT" as raw text. Is it possible the latest crate was published from a system which doesn't understand the soft-links?

**Comment by Rua** [comment]
@Eliah-Lakhin I think this can be closed?
