### ISSUE TITLE
Allocation of descriptor sets with variable counts always allocates maximum count

### ISSUE THREAD

**Issue by Rua** [vulkano-rs/vulkano#1740]
The current code in `UnsafeDescriptorPool` simply allocates `descriptor_count` variable descriptors. In other words, always the maximum number allowed. But it should be possible to allocate less than the maximum, which is the whole point of variable counts in the first place. For this, the iterator passed to `alloc` should include both a descriptor set layout and a variable count. The descriptor set builder should then provide this value when allocating a new set for a layout that has a variable count, based on the number of elements that the user inserts into the array.

I tried fixing this myself, but realised that it will break the logic inside `SingleLayoutDescSetPool`. It expects every descriptor set it allocates to have the same number of descriptors, and therefore be interchangeable, so that previously allocated descriptor sets can be recycled. But if there is a variable count, then sets with the same layout could still have differing numbers of descriptors.

The problem could be solved by simply disallowing variable count layouts in `SingleLayoutDescSetPool`, but that's kinda harsh. It could also be solved by grouping the recycled descriptor sets by their variable count. Unfortunately this would lead to fragmentation of the pool, since only future allocations with the exact right variable count could reuse the recycled sets.

**Comment by Eliah-Lakhin** [comment]
Well, I don't have a better idea rather than the fragmentation approach you proposed, but at least it looks better than the current approach with maximum allocation.
