### ISSUE TITLE
Debug information for shaders in vulkano-shaders

### ISSUE THREAD

**Issue by ProtoByter** [vulkano-rs/vulkano#1742]
I was wondering if it'd be possible to add an option to `vulkano-shaders` to turn on debug information in `shaderc-rs`, `shaderc-rs` already has an option for it in `CompileOptions`, `set_generate_debug_info()`, so I was wondering if this could become an option in `vulkano-shaders` since it'd be very useful to be able to see exact lines in tools like NSight Graphics instead of the raw SPIR-V code.
I would do it myself but I'm not very good with procmacros so I'd likely write bad code :P

**Comment by Rua** [comment]
@ProtoByter would you think it's sufficient to enable debug information automatically whenever Vulkano is being built in debug mode, or would you prefer to have an option to enable it in release mode as well?

**Comment by Eliah-Lakhin** [comment]
Perhaps, it would be more reasonable to enable this feature by introducing an optional crate feature.

**Comment by ProtoByter** [comment]
Sorry for the late response, it might be useful for the user to be able to decide whether to enable debug info themselves, since in a certain config, someone might want release CPU code and debug GPU code to only debug the shaders
