### ISSUE TITLE
Make it possible to load shader bytecode with identical entry point names for different execution models

### ISSUE THREAD

**Issue by incertia** [vulkano-rs/vulkano#1752]
It is only [required](https://www.khronos.org/registry/SPIR-V/specs/1.0/SPIRV.html#OpEntryPoint) that `OpEntryPoint` have unique `(name, execution model)`, which lets us link vertex and fragment shader code into a single module, both with the name `"main"`.

We should extend #1747 so that entry points are parameterized by both values, rather than overwriting pre-existing entry points.

**Comment by Eliah-Lakhin** [comment]
Issue closed as resolved in #1753.
