### ISSUE TITLE
use repr(C) in examples

### ISSUE THREAD

**Issue by incertia** [vulkano-rs/vulkano#1755]
I think (at least within the context of vertex buffers and input assembly), we should be explicit and use `repr(C)` in the examples whenever possible. In particular, `repr(Rust)` has the weird quirk that the rust compiler is able to re-order field members. In the below non-sensical example, we can see that `repr(Rust)` will reorder `c` to appear before `a` and `b`, so any input assembler relying on `a` being at offset `0` will fail.

```rust
struct MyStruct {
  a: u8,
  c: u32,
  b: u8,
}

#[repr(C)]
struct MyStruct2 {
  a: u8,
  c: u32,
  b: u8,
}

fn to_bytes<T>(t: &T) -> &[u8]{
  let p: *const T = t;
  let p = p as *const u8;
  unsafe {
    std::slice::from_raw_parts(p, std::mem::size_of::<T>())
  }
}

fn main(){
  dbg!(std::mem::size_of::<MyStruct>());
  dbg!(std::mem::size_of::<MyStruct2>());
  dbg!(to_bytes(&MyStruct { a: 0x55, b: 0xaa, c: 0xffffffff }));
  dbg!(to_bytes(&MyStruct2 { a: 0x55, b: 0xaa, c: 0xffffffff }));
}
```

which outputs

```
[test.rs:23] std::mem::size_of::<MyStruct>() = 8
[test.rs:24] std::mem::size_of::<MyStruct2>() = 12
[test.rs:25] to_bytes(&MyStruct{a: 0x55, b: 0xaa, c: 0xffffffff,}) = [
    255,
    255,
    255,
    255,
    85,
    170,
    0,
    0,
]
[test.rs:26] to_bytes(&MyStruct2{a: 0x55, b: 0xaa, c: 0xffffffff,}) = [
    85,
    0,
    0,
    0,
    255,
    255,
    255,
    255,
    170,
    0,
    0,
    0,
]
```

thoughts?

**Comment by Eliah-Lakhin** [comment]
@incertia What is the purpose of this explicitness? Does it lead to any particular issues?

**Comment by Eliah-Lakhin** [comment]
@incertia Ah, sorry, I just read your comment in the PR(#1757) explaining this.

Sounds reasonable. I will take a closer look in the nearest couple of days, and proceed with the merge.

Thank you for your help in improving our project!
