### ISSUE TITLE
Vulkan Video in Vulkano?

### ISSUE THREAD

**Issue by lmarianski** [vulkano-rs/vulkano#1756]
I'd like to use the `VK_KHR/EXT_video_*` extensions for video encoding, and i see that they're available in the DeviceExtensions struct (except `VK_EXT_video_encode_h265`), but i don't see how i can call the methods from the vulkan documentation, any help would be appreciated.

(Note: i am learning vulkan, so please excuse me if the answer is obvious etc.)
Thanks

**Comment by Rua** [comment]
Vulkano is still very much a work in progress, so there's a lot of things that haven't been implemented yet. I can try to take a look at this sometime. Can you tell me a bit more about these extensions, what they do, how they work etc?

**Comment by lmarianski** [comment]
Fair, here's the info on the extensions: https://www.khronos.org/blog/an-introduction-to-vulkan-video

**Comment by Rua** [comment]
Thanks! It looks like these extensions are currently still regarded as "provisional", meaning their final API and inner details haven't been finalised yet. I think it would be better for Vulkano to wait until they become fully supported.

**Comment by lmarianski** [comment]
Ok, thanks

**Comment by Eliah-Lakhin** [comment]
@lmarianski I will close this thread as we decided not to work on this feature for now. Later it could be reopened. However, if you think you can work on a prototype now or in the future, it is very welcome! :)
