### ISSUE TITLE
Storing vulkano types in a struct

### ISSUE THREAD

**Issue by Ria8651** [vulkano-rs/vulkano#1761]
As the examples are the only up-to-date way to learn how to use vulkano it would be great to have an example showing how to store all the main types. Storing different variables in structs is very useful for making an application. I found these online but some of them don't work in the latest versions. In particular, I've had the most trouble with the rener_pass and graphics_pipeline when passing them into functions and trying to store them.
```rust
struct VulkanoVariables {
    instance: Arc<Instance>,

    events_loop: EventLoop<()>,
    surface: Arc<Surface<Window>>,

    device: Arc<Device>,

    graphics_queue: Arc<Queue>,
    present_queue: Arc<Queue>,

    swap_chain: Arc<Swapchain<Window>>,
    swap_chain_images: Vec<Arc<SwapchainImage<Window>>>,

    render_pass: Arc<RenderPassAbstract + Send + Sync>,
    graphics_pipeline: Arc<ConcreteGraphicsPipeline>,

    swap_chain_framebuffers: Vec<Arc<FramebufferAbstract + Send + Sync>>,

    command_buffers: Vec<Arc<AutoCommandBuffer>>,

    previous_frame_end: Option<Box<GpuFuture>>,
}
```
Thanks

**Comment by Rua** [comment]
For a render pass you need: `Arc<RenderPass>`. For graphics pipeline: `Arc<GraphicsPipeline>`. For framebuffer: `Arc<Framebuffer>`. For a command buffer: `Arc<PrimaryCommandBuffer>`.

**Comment by Ria8651** [comment]
Thanks, that's a lot more intuitive than it used to be.
