### ISSUE TITLE
Validation errors for interactive_fractal example

### ISSUE THREAD

**Issue by Rua** [vulkano-rs/vulkano#1762]
When I run the example through `vkconfig` with validation enabled, I get a series of validation errors like this one:
> VUID-VkWriteDescriptorSet-descriptorType-04152(ERROR / SPEC): msgNum: -1536361367 - Validation Error: [ VUID-VkWriteDescriptorSet-descriptorType-04152 ] Object 0: handle = 0xa2eb680000000026, type = VK_OBJECT_TYPE_DESCRIPTOR_SET; | MessageID = 0xa46cfc69 | vkUpdateDescriptorSets() pDescriptorWrites[0] failed write update validation for VkDescriptorSet 0xa2eb680000000026[] with error: Write update to VkDescriptorSet 0xa2eb680000000026[] allocated with VkDescriptorSetLayout 0x84c0580000000017[] binding #0 failed with error message: Attempted write update to image descriptor failed due to: Descriptor update with descriptorType VK_DESCRIPTOR_TYPE_STORAGE_IMAGE is being updated with invalid imageLayout VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL for image VkImage 0xc4f3070000000021[] in imageView VkImageView 0x301e6c0000000022[]. Allowed layouts are: VK_IMAGE_LAYOUT_GENERAL. The Vulkan spec states: If descriptorType is VK_DESCRIPTOR_TYPE_STORAGE_IMAGE the imageLayout member of each element of pImageInfo must be a member of the list given in Storage Image (https://vulkan.lunarg.com/doc/view/1.2.198.0/linux/1.2-extensions/vkspec.html#VUID-VkWriteDescriptorSet-descriptorType-04152)
    Objects: 1
        [0] 0xa2eb680000000026, type: 23, name: NULL

When updating a descriptor set, Vulkano gets the layout in [this line](https://github.com/vulkano-rs/vulkano/blob/master/vulkano/src/descriptor_set/sys.rs#L302). `descriptor_type` here is `StorageImage` while the image view wraps around an `AttachmentImage`. `AttachmentImage` has this implementation for `descriptor_layouts`:
```rust
    #[inline]
    fn descriptor_layouts(&self) -> Option<ImageDescriptorLayouts> {
        Some(ImageDescriptorLayouts {
            storage_image: ImageLayout::ShaderReadOnlyOptimal,
            combined_image_sampler: ImageLayout::ShaderReadOnlyOptimal,
            sampled_image: ImageLayout::ShaderReadOnlyOptimal,
            input_attachment: ImageLayout::ShaderReadOnlyOptimal,
        })
    }
```
So it's using the `ShaderReadOnlyOptimal` layout when writing the descriptor set, which is incorrect in this case. The problem could maybe be solved by using Vulkano's `StorageImage` type instead of `AttachmentImage`, but I think that errors like this shouldn't happen in safe code regardless.

**Comment by Rua** [comment]
@hakolao do you remember why you decided to use `AttachmentImage` for this purpose? I don't know if it's wrong, but since you're using it as a storage image, `StorageImage` seems to me like the more obvious choice.

**Comment by hakolao** [comment]
@Rua let me get back to you on this a bit later if it is ok. I am now at home battling a human bug 🥲.

**Comment by Rua** [comment]
Oh no, get well soon!

**Comment by hakolao** [comment]
actually, had to check it anyway... Seems there is no good reason based on looking at my code, and storage image seems better suited for the purpose. @Rua

**Comment by Rua** [comment]
Oh, now I see why it was used. It's constructed with the `AttachmentImage::multisampled_with_usage` constructor, which has no equivalent on `StorageImage`.
