### ISSUE TITLE
About the meaning of "submission" in Vulkano

### ISSUE THREAD

**Issue by psionic12** [vulkano-rs/vulkano#1770]
I'm little confused about the term "submission" used in Vulkano's documents.

When I write C++, a submission to me is just an operation that send recorded commands to command queue, nothing more, but I got a feeling that in Vulkano, submission means "submit commands to command queue, and wait the commands to be executed", for example, the doc about `set_fence_signal`:

> Adds an operation that signals a fence after this submission ends.

I'm confused at first, why I need a fence to know the commands is adding to command queue? than I dive into the code, I found that the code calls `fns.v1_0.queue_submit(*queue, 1, &batch, self.fence)`, in vulkan's document, it is said clearly 

> The last parameter references an optional fence that will be signaled when the command buffers finish execution

until that I guess `set_fence_signal` is  "Adds an operation that signals a fence after the commands finished execution."

I'm I right about this? If yes, can I understand all words like "submission finished" as "execution finished"?

**Comment by Rua** [comment]
Yes, perhaps this is unclear. The documentation should be using "execution" for the actual GPU work, and "submission" only to the operation that adds the work.
