### ISSUE TITLE
Trying to understand how to architecture code using Vulkano

### ISSUE THREAD

**Issue by CLOVIS-AI** [vulkano-rs/vulkano#1771]
# Template

If you dont understand something just leave it.
If you can provide more detailed information than the template allows for, please ignore the template and present all of your findings.

*   Version of vulkano: 0.20

# Issue

I'm trying to understand how code using Vulkano should be architectured.

From the examples I've seen, everything is always in a single file, but I'd like to organize my code better. For that, I thought I'd create an `Engine` struct which would combine all Vulkano data (currently, `Instance` and `PhysicalDevice`).

However, this doesn't compile:
```rust
pub struct Engine {
    instance: Arc<Instance>,
    device: PhysicalDevice,
}
```
It fails because `PhysicalDevice` has a lifetime parameter to ensure it lives at least as long as the `Instance` it is linked to (or at least, that's my understanding). Because the `PhysicalDevice` is moved into the `Engine`, which is also one of the owners of the `Instance` (through `Arc`), I don't think it is possible that the `PhysicalDevice` reference on `Instance` ever becomes invalid (am I wrong?), however it seems like the compiler doesn't know that.

Is that not a proper way to architecture the code with Vulkano? Is there a missing syntax bit to tell the compiler that this is safe? When I asked on [StackOverflow](https://stackoverflow.com/a/70219026/5666171), it seems like there are many different ways to solve this pattern, with different tradeoffs, and that the library architecture might impact those as well. What is the pattern recommended by the Vulkano team?

**Comment by Rua** [comment]
In principle, the main things that you want to store is `Instance`, `Device` and `Queue`. After that, you probably need other objects like `Swapchain` and `RenderPass`, but that depends on what your program does.

**Comment by Eliah-Lakhin** [comment]
@CLOVIS-AI First, I would recommend to start with the latest version of Vulkano(0.27.0).

To understand how the complex Vulkano-based architecture can be built you can look at our Interactive Fractal example: https://github.com/vulkano-rs/vulkano/tree/master/examples/src/bin/interactive_fractal This is exactly built to demonstrate how to start building a complex app architecture. At least one of the possible direction.

> It fails because PhysicalDevice has a lifetime parameter

Normally, you don't need to store PhysicalDevice object in the app-timeline. This is a temporary object to obtain the `Device` object and a set of `Queue`s to be stored in long-term.

**Comment by CLOVIS-AI** [comment]
Thanks for your answers, I'm going to look into this.

For future reference, is this a good place to ask these kinds of questions?

**Comment by Rua** [comment]
I can't really think of any other place to ask. Github technically has a "discussions" feature, but it's not enabled here and it might be missed.

**Comment by Eliah-Lakhin** [comment]
@Rua I was thinking to enable them in the past, but is it any better than just usual Issues comments?
