### ISSUE TITLE
Missing Generic ImageAccess Implementation

### ISSUE THREAD

**Issue by AustinJ235** [vulkano-rs/vulkano#1773]
As of https://github.com/vulkano-rs/vulkano/pull/1739/ `ImageAccess` can no longer be implemented on a type and that type be included in an `Arc`.

```
struct ImageWrapper {
    ...
}

impl ImageAccess for ImageWrapper {
    ...
}
```

When `ImageWrapper` is inside `Arc<ImageWrapper>` `ImageAccess` will not be implemented.

The removed implementation:
```
unsafe impl<T> ImageAccess for T
where
    T: SafeDeref + Send + Sync,
    T::Target: ImageAccess,
{
```

**Comment by Rua** [comment]
This is no longer needed within Vulkano since #1739, because everything expects the `Arc` wrapper. Is it creating problems for you?

**Comment by AustinJ235** [comment]
I have a type called `BstImageView`: https://docs.rs/basalt/latest/basalt/image_view/struct.BstImageView.html

This type wraps various types of images and allows me to store them generically. This also provides a tmp system that allows me to lend out images and know when the end user doesn't use them anymore.

**Comment by Rua** [comment]
You can still use `Arc<dyn ImageAccess>` or `Arc<I> where I: ImageAccess`. Will that work?

**Comment by AustinJ235** [comment]
In order for my type to interact with vulkano methods it needs to have ImageAccess directly implemented.

See method https://docs.rs/vulkano/latest/vulkano/command_buffer/synced/struct.SyncCommandBufferBuilder.html#method.blit_image

**Comment by Rua** [comment]
Hmm, and I guess you're not able to wrap your type in an `Arc`? That makes it more difficult then. Was that PR a mistake in hindsight?

**Comment by AustinJ235** [comment]
I think just an oversight. Overall I think it was a good change. I re-added the generic implementation locally and it works. I think as long as we add that back in it won't be a breaking change and we could do a minor release.

I think this is sort of a current limitation of rust. You can't implement foreign traits on your local types that are within an `Arc` since `Arc`'s aren't marked `#[fundemental]`.

With the change to `SingleLayoutDescSetPool` not being able to take variable count descriptors anymore I've noticed another similar situation with traits. I can understand why it wouldn't be implemented. It is fairly difficult to make a generic pool that'd be performant and flexible enough to cover all the uses cases with variable count descriptors.

```
error[E0117]: only traits defined in the current crate can be implemented for arbitrary types
  --> C:\Workspace\basalt\src\interface\render\layer_desc_pool.rs:34:1
   |
34 | unsafe impl DescriptorPool for Arc<LayerDescPool> {
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^------------------
   | |                              |
   | |                              `Arc` is not defined in the current crate
   | impl doesn't use only types from inside the current crate
```

I think it should be possible for end users to make their own descriptor pools. I think that was the original intent with [`build_with_pool`](https://docs.rs/vulkano/latest/vulkano/descriptor_set/persistent/struct.PersistentDescriptorSetBuilder.html#method.build_with_pool) on persistent descriptor sets.

**Comment by Rua** [comment]
If adding it back in works for you, then a PR would be good. When I removed it, I didn't think there would be use cases for users that required it. It may be good to do the same for `BufferAccess` as well.

As for descriptor pools, I completely agree and I have been pondering how to design the API for it for a while now. I will write a new issue with my thoughts.
