### ISSUE TITLE
 The trait bound `Transform: SafeDeref` is not satisfied

### ISSUE THREAD

**Issue by psionic12** [vulkano-rs/vulkano#1781]
*   Version of vulkano: 0.27.1

# Issue

I want to update a uniform buffer, and write like this:
```
command_buffer_builder
 .update_buffer(uniform_buffer_subbuffer.clone(),
                                   vs::ty::Transform {
                                       transform: *Mat4::identity().as_ref(),
                                   }).unwrap()
.begin_render_pass(
...
```
the type "Transform" is generated by vulkano_shaders, and the compiler report and error:
```
error[E0277]: the trait bound `Transform: SafeDeref` is not satisfied
   --> src/main.rs:222:22
    |
222 |                     .update_buffer(uniform_buffer_subbuffer.clone(),
    |                      ^^^^^^^^^^^^^ the trait `SafeDeref` is not implemented for `Transform`
```

I checked the doc, and change to
```
&vs::ty::Transform {
    transform: *Mat4::identity().as_ref(),
}
```

But it requires a static lifetime, which I cannot provide (and I think that's a little wired, I need to update a uniform buffer every frame, but the data must be static).

P.S. The best way to do this may use a push constant, but I'm learning vulkano here, so I want to test with the uniform buffers.

P.P.S: I found that in example teapot, a uniform buffer is created every frame, won't this hurt the performance?

**Comment by Rua** [comment]
In the teapot example, `CpuBufferPool` is used, which doesn't actually create a separate buffer each time, but reuses a single internal buffer and allocates a new one when it's full. So I imagine it's pretty efficient.

I do agree though that the `SafeDeref` requirement is strange. Maybe that should be removed in a future update.

**Comment by psionic12** [comment]
Then may I ask how do you update a uniform buffer? I'm stucking here, and didn't find something like vkmapping

**Comment by psionic12** [comment]
After investigating, I'm coming up with three solutions to update a uniform buffer:
1. use a `CpuBufferPool` like the example of "teapot" does, in this case, you need to create a descriptor set every frame, since vulkano doesn't provide any  modifications for a set. I think this may slightly hurt the performance.
2. call update_buffer (vkCmdUpdateBuffer) on a command buffer, in this case, you need first wrap you uniform data to a box or arc or dyn reference, then you need to make sure your uniform buffer's usage is `uniform_buffer_transfer_destination`. How every the `update_buffer` is designed to update buffers like vertices or images, that's why it takes a static lifetime data, not own it. 
3. modify `CpuAccessableBuffer` by using `write()`, in this case, you must wait the fence at the end of every frame, otherwise the `gpulock` may not release when calling `write()`.
