### ISSUE TITLE
How can I create a command buffer pool and create command buffers from it?

### ISSUE THREAD

**Issue by psionic12** [vulkano-rs/vulkano#1784]
In practice, it is common that create command buffer pools in each thread, then we can get performance benifits, such as reset pools safely. But I didn't find a way of doing this in Vulkano, it seems that there's only one command buffer pool which is called `StandardCommandPoolBuilder`, and it seems that all command buffers are born from it.

So, how can I create a command buffer pool manually?

**Comment by Rua** [comment]
Command pools are now managed by the `StandardCommandBufferAllocator`.
