### ISSUE TITLE
AutoCommandBufferBuilder::new is gone

### ISSUE THREAD

**Issue by CLOVIS-AI** [vulkano-rs/vulkano#1788]
# Template

If you dont understand something just leave it.
If you can provide more detailed information than the template allows for, please ignore the template and present all of your findings.

*   Version of vulkano: 0.27

# Issue

The documentation (https://vulkano.rs/guide/example-operation) explains how to use `AutoCommandBufferBuilder::new`. However, it seems like that function doesn't exist anymore.

Looking at the source code, there is `AutoCommandBufferBuilder::primary`, is this the correct replacement?

**Comment by Rua** [comment]
Yes. The examples on vulkano.rs are unfortunately rather outdated.

**Comment by CLOVIS-AI** [comment]
In https://vulkano.rs/guide/compute-pipeline, the version number is old, but after updating it to 0.27, it seems like the only change is that the function is `your_shader_module::load` instead of `your_shader_module::Shader::load`.

So far, it seems like the outdated parts are details, so it should be easy to fix (at least for that guide). Do you want me to create a PR?

**Comment by Rua** [comment]
Sure, all help is appreciated!

**Comment by CLOVIS-AI** [comment]
What are the recommended defaults for the new `ComputePipeline` constructor?

The example in the guide is:
```rust
let compute_pipeline = Arc::new(ComputePipeline::new(device.clone(), &shader.main_entry_point(), &())
    .expect("failed to create compute pipeline"));
```

but the current signature is:
```rust
    pub fn new<Css, F>(
        device: Arc<Device>,
        shader: EntryPoint,
        specialization_constants: &Css,
        cache: Option<Arc<PipelineCache>>,
        func: F,
    ) -> Result<Arc<ComputePipeline>, ComputePipelineCreationError>
    where
        Css: SpecializationConstants,
        F: FnOnce(&mut [DescriptorSetDesc]),
```

**Comment by Rua** [comment]
The main Vulkano repository has its own set of examples, and those are kept up to date. You can look there to see how things are done.

**Comment by CLOVIS-AI** [comment]
Ah, I see, thanks.

Where are the guides stored? I don't see them in this repo

**Comment by Rua** [comment]
That's the https://github.com/vulkano-rs/vulkano-www repo.

**Comment by CLOVIS-AI** [comment]
Thanks a lot for your answers.
