### ISSUE TITLE
Self-copy tests failing

### ISSUE THREAD

**Issue by Rua** [vulkano-rs/vulkano#1789]
@Amjad50 The test `command_buffer::synced::tests::basic_conflict` is now failing, because a self-copy is no longer triggering an error. That is of course by design, but it means that the test needs to be adjusted a bit. I suggests two tests, `self_copy_overlapping` and `self_copy_not_overlapping`, which should test respectively that the copy fails and succeeds.

**Comment by Amjad50** [comment]
Sorry, I didn't notice that. I'll fix it and also add those tests. Thanks for notifying.
