### ISSUE TITLE
Sync conflicts bug

### ISSUE THREAD

**Issue by Eliah-Lakhin** [vulkano-rs/vulkano#1794]
*   Version of Vulkano: latest `master`.
*   OS: Ubuntu 18.04.6 LTS.
*   GPU (the selected PhysicalDevice): Intel(R) HD Graphics 630 (KBL GT2).
*   GPU Driver: Mesa 20.0.8/Intel open-source Mesa driver.

Within provided configuration some random tests are failing on my local machine. For example, [command_buffer::synced::tests::basic_conflict](https://github.com/vulkano-rs/vulkano/blob/master/vulkano/src/command_buffer/synced/mod.rs#L523) is failing.

The issue originated after merging of #1783 by @fayalalebrun. I was too hurry in merging of the PR, and didn't check tests locally. Even though, in GitHub Actions they pass for all platforms.

To my understanding the test case is correct, so the issue is probably somewhere in the PR implementation.

@fayalalebrun When you have time, please take a look. I can provide more information if needed.

**Comment by fayalalebrun** [comment]
@Eliah-Lakhin I believe the test started failing before my MR. #1782 allowed for buffer copy with the same source and destination, which this test checks to not be possible.

I think this test should fail as well on Github Actions. If it doesn't, perhaps it's not even running.

**Comment by Eliah-Lakhin** [comment]
@fayalalebrun You are right! It's originated in #1782, not #1783.

@Amjad50 Can you take a look, please?

**Comment by Amjad50** [comment]
I already made a PR to fix it #1791.

**Comment by Eliah-Lakhin** [comment]
Damn! This is a duplicated of the #1789 :)

I'm sorry guys. I will review @Amjad50 's PR right now. Perhaps everything already fixed there.

**Comment by Eliah-Lakhin** [comment]
@Amjad50 ok, the PR fixed the issue. It's merged. Thank you!
