### ISSUE TITLE
Is there a working example for using Descriptor sets in v0.27.1?

### ISSUE THREAD

**Issue by bluelightzero** [vulkano-rs/vulkano#1799]
I was trying to use this code as an example: https://github.com/vulkano-rs/vulkano/blob/master/examples/src/bin/teapot/main.rs

    let layout = pipeline.layout().descriptor_set_layouts().get(0).unwrap();
    let set = PersistentDescriptorSet::new(
        layout.clone(),
        [WriteDescriptorSet::buffer(0, uniform_buffer_subbuffer)],
    )
    .unwrap();

But in December, `WriteDescriptorSet` was removed : https://github.com/vulkano-rs/vulkano/pull/1774

The docs are no help, they don't even give an example: https://docs.rs/vulkano/0.27.1/vulkano/descriptor_set/index.html

So what am I supposed to do instead?

**Comment by Rua** [comment]
You can view the repository at the time that 0.27.1 was released, by clicking on "commits" and then finding the 0.27.1 release (unfortunately there is no tag for this release). Here's a link for convenience: https://github.com/vulkano-rs/vulkano/tree/619af8239c1f7f9da6138f2d817f235fe3971142

**Comment by Eliah-Lakhin** [comment]
@bluelightzero In the latest `master` we have changed a way Descriptor Sets being construct. From now on they construct through the constructor function directly(`PersistentDescriptorSet::new`), without the Builder. These are upcoming changes for the next release.

A teapot example for the previous `0.27.1` release with the Builder APIs is here: https://github.com/vulkano-rs/vulkano/blob/619af8239c1f7f9da6138f2d817f235fe3971142/examples/src/bin/teapot/main.rs
