### ISSUE TITLE
Loading a compiled SPV-shader from a buildscript

### ISSUE THREAD

**Issue by ColinTimBarndt** [vulkano-rs/vulkano#1813]
# Template

If you dont understand something just leave it.
If you can provide more detailed information than the template allows for, please ignore the template and present all of your findings.

*   Version of vulkano: 0.27.1
*   OS: Linux Pop!OS
*   GPU (the selected PhysicalDevice): NVIDIA GeForce GTX 1060 6GB
*   GPU Driver: nvidia 470.86

# Issue

I would like to use a build script that compiles my shaders (using shaderc), which outputs the spv-files to the designated `OUT_DIR`. Because the shader macro does not take other macros like `env!("OUT_DIR")` as an argument for the bytes, I cannot use it for this purpose. When I tried loading the shader with `shader::ShaderModule::from_bytes`, it gives me the error `assertion failed: word_count >= 1` in `vulkano-0.27.1/src/shader/spirv.rs:74:17`.

How do I load a compiled shader from the `OUT_DIR` directory?

**Comment by Rua** [comment]
That assertion shouldn't be happening. It either means there's a bug in Vulkano, or the SPIR-V file isn't correct. Could you attach the file here so it can be examined?

**Comment by ColinTimBarndt** [comment]
Sure, This is the compiled shader:
[shader1.vert.spv.gz](https://github.com/vulkano-rs/vulkano/files/7970743/shader1.vert.spv.gz)
Which was built from this source:
```glsl
#version 450

layout (location = 0) in vec2 position;

void main() {
    gl_Position = vec4(position, 0.0, 1.0);
}
```
I was using this code to compile it:
```rs
// (...) kind is Vertex
compiler.compile_into_spirv(source, kind, file_name, "main", None);
// (...)
let ref mut dest = fs::OpenOptions::new()
    .write(true)
    .create(true)
    .open(out_file)?;
dest.write_all(spv.as_binary_u8())?;
dest.flush()?;
```

I confirmed that the output file was included by the compiler.

**Comment by Rua** [comment]
I tried running your shader through the SPIR-V disassembler `spirv-dis` and got this output:
```
$ spirv-dis shader1.vert.spv 
; SPIR-V
; Version: 1.0
; Generator: Google Shaderc over Glslang; 10
; Bound: 27
; Schema: 0
               OpCapability Shader
          %1 = OpExtInstImport "GLSL.std.450"
               OpMemoryModel Logical GLSL450
               OpEntryPoint Vertex %main "main" %_ %position
               OpSource GLSL 450
               OpSourceExtension "GL_GOOGLE_cpp_style_line_directive"
               OpSourceExtension "GL_GOOGLE_include_directive"
               OpName %main "main"
               OpName %gl_PerVertex "gl_PerVertex"
               OpMemberName %gl_PerVertex 0 "gl_Position"
               OpMemberName %gl_PerVertex 1 "gl_PointSize"
               OpMemberName %gl_PerVertex 2 "gl_ClipDistance"
               OpMemberName %gl_PerVertex 3 "gl_CullDistance"
               OpName %_ ""
               OpName %position "position"
               OpMemberDecorate %gl_PerVertex 0 BuiltIn Position
               OpMemberDecorate %gl_PerVertex 1 BuiltIn PointSize
               OpMemberDecorate %gl_PerVertex 2 BuiltIn ClipDistance
               OpMemberDecorate %gl_PerVertex 3 BuiltIn CullDistance
               OpDecorate %gl_PerVertex Block
               OpDecorate %position Location 0
       %void = OpTypeVoid
          %3 = OpTypeFunction %void
      %float = OpTypeFloat 32
    %v4float = OpTypeVector %float 4
       %uint = OpTypeInt 32 0
     %uint_1 = OpConstant %uint 1
%_arr_float_uint_1 = OpTypeArray %float %uint_1
%gl_PerVertex = OpTypeStruct %v4float %float %_arr_float_uint_1 %_arr_float_uint_1
%_ptr_Output_gl_PerVertex = OpTypePointer Output %gl_PerVertex
          %_ = OpVariable %_ptr_Output_gl_PerVertex Output
        %int = OpTypeInt 32 1
      %int_0 = OpConstant %int 0
    %v2float = OpTypeVector %float 2
%_ptr_Input_v2float = OpTypePointer Input %v2float
   %position = OpVariable %_ptr_Input_v2float Input
    %float_0 = OpConstant %float 0
    %float_1 = OpConstant %float 1
%_ptr_Output_v4float = OpTypePointer Output %v4float
       %main = OpFunction %void None %3
          %5 = OpLabel
         %19 = OpLoad %v2float %position
         %22 = OpCompositeExtract %float %19 0
         %23 = OpCompositeExtract %float %19 1
         %24 = OpCompositeConstruct %v4float %22 %23 %float_0 %float_1
         %26 = OpAccessChain %_ptr_Output_v4float %_ %int_0
               OpStore %26 %24
               OpReturn
               OpFunctionEnd
error: 50: Invalid instruction word count: 0
```

The disassembler gives the same error about the instruction word count as Vulkano does. So it appears something is wrong with the generated .spv file.

**Comment by ColinTimBarndt** [comment]
Okay, that's interesting.. maybe it does not write the entire file? I'll investigate that

**Comment by Rua** [comment]
As for using OUT_DIR, does it work like this?
```rust
bytes: concat!(env!("OUT_DIR"), "/shader1.vert.spv"),
```

**Comment by Rua** [comment]
It seems that when `syn` (the crate Vulkano uses to parse vulkano-shaders) is told to parse a string literal, it is very literal (ha!) about what it accepts and doesn't even accept a macro that *evaluates* into a string literal, like `concat!`. It would be nice if there were some way to tell it to evaluate the macro before passing it to vulkano-shaders. Time for me to go puzzle...

**Comment by ColinTimBarndt** [comment]
Yes, that would be great, as it is the same that macros do when defined using `macro_rules!`. I also found my error. It seems that my code that writes the file does not replace the file and instead only overrides from the beginning of the file, so there was excess data at the end. This code works now:
```rs
fs::write(out_file, spv.as_binary_u8())?;
```
