### ISSUE TITLE
Sampler reduction mode causes Sampler2DShadow to not work properly on some drivers

### ISSUE THREAD

**Issue by pac85** [vulkano-rs/vulkano#1826]
please add a condition at [this line](https://github.com/vulkano-rs/vulkano/blob/3ad03f85932a7c29add3ae13d711e66c03607e35/vulkano/src/sampler/mod.rs#L563). If compare is enabled then set it to None.

I don't think this is required by the spec, probably not, but it would work around an annoying bug for me (Intel WhiskeyLake-U GT2 [UHD Graphics 620], archlinux, linux 5.16.8-arch1-1, mesa 21.3.5-1)

**Comment by Rua** [comment]
This isn't the first time I've seen issues with extension structs like that, even when the contents are set to the default values that they would have with the struct not there. I'll see about fixing it soon, but out of curiosity, does the validation layer report anything?

**Comment by pac85** [comment]
Thanks forma taking care of the issue. I've just checked andò it doesn't seem to reporter any issues regarding the sampler ombject in question.
