### ISSUE TITLE
How to provide HMONITOR for full-screen exclusive mode on Windows?

### ISSUE THREAD

**Issue by Rua** [vulkano-rs/vulkano#1830]
Vulkano currently has support for full-screen exclusive mode with swapchains. But when implementing it, one detail seems to have been missed in the specification for `VkSwapchainCreateInfoKHR`:

> VUID-VkSwapchainCreateInfoKHR-pNext-02679
> If the `pNext` chain includes a [VkSurfaceFullScreenExclusiveInfoEXT](https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkSurfaceFullScreenExclusiveInfoEXT.html) structure with its `fullScreenExclusive` member set to `VK_FULL_SCREEN_EXCLUSIVE_APPLICATION_CONTROLLED_EXT`, and `surface` was created using [vkCreateWin32SurfaceKHR](https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/vkCreateWin32SurfaceKHR.html), a [VkSurfaceFullScreenExclusiveWin32InfoEXT](https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkSurfaceFullScreenExclusiveWin32InfoEXT.html) structure **must** be included in the `pNext` chain

The `VkSurfaceFullScreenExclusiveWin32InfoEXT` structure is not used in Vulkano at the moment, which means that creating a swapchain with `FullScreenExclusive::ApplicationControlled` is a spec violation if you use it on Windows. I'm not entirely sure how to solve this issue, though. This structure has a single field which is a `HMONITOR`, a handle for the Windows-specific monitor that should be made full-screen exclusive. This handle can be retrieved from Winit or whatever other API the user is using for their windowing, but Vulkano itself is agnostic to that.

But in what form should Vulkano ask for the `HMONITOR` handle when creating a swapchain? Ash [exposes the type directly](https://docs.rs/ash/latest/ash/vk/type.HMONITOR.html) so we don't have to worry about that part. Unfortunately, Vulkano has no way to check that the handle is valid, as far as I can tell. Is there a way to design it so that it's safe, somehow?

**Comment by AustinJ235** [comment]
Without any massive changes that'd move vulkano away from being window agnostic would be to somehow provide a method on the `SwapchainBuilder` to supply the handle, but this wouldn't be able to check the validity of the handle and therefore would have to be marked unsafe.

**Comment by Rua** [comment]
It would be nice if Vulkano-win could provide a way to do it without any unsafety. `Surface` has various unsafe constructors, but when you let Vulkano-win do it, it calls those constructors internally so that it can verify the handles, then gives you the constructed `Surface`. Maybe something like that could work here too: a wrapper around `HMONITOR` that Vulkano only has an unsafe constructor for, but which Vulkano-win can construct safely.

**Comment by AustinJ235** [comment]
Do you mean verify as in they are not null and the correct type or verifying that it is a valid window by some means. I believe vulkano-win just takes the types as is from either winit or raw-window-handle. It itself doesn't do any verification.

I think it would be helpful to store window handles in the surface, which we could use raw-window-handle for, but the issue is that the type isn't Send/Sync which would be a **huge** breaking change. And if we were to create our own enum variant what are the send/sync requirement for those types?

We could make it "safer" akin to vulkano-win by making the swapchain builder take either a winit window or a raw-window-handle. This also has some quirks in that it adds additional dependencies to the crate.

**Comment by Rua** [comment]
True, Vulkano-win doesn't verify anything, but it can trust that what it gets from winit is valid. It can do the same here (winit exposes `HMONITOR` handles too).

I don't think there is any need for Vulkano to keep window handles in the surface, as there is nothing in Vulkan that needs those handles once the surface has been constructed. `Surface` has a `window` method that returns a reference to the `W` parameter that was provided on construction. If you construct a `Surface` via Vulkano-win, then this will be either a winit `Window` or anything that implements `HasRawWindowHandle`. You can then call methods on this reference as needed.

**Comment by AustinJ235** [comment]
Could we make it so `HasRawWindowHandle` is a trait requirement for `Surface`? This would allow us to call [`raw_window_handle`](https://docs.rs/raw-window-handle/latest/raw_window_handle/trait.HasRawWindowHandle.html#tymethod.raw_window_handle) via the surface and thus have access to it in a safe manor.

Most major windowing crates for rust implement this trait already, so I don't think it would be very breaking.

**Comment by Rua** [comment]
We could, but why would we want to? `HMONITOR` is not exposed via that trait, it's not a window handle but a monitor handle. You get it from Winit's [`MonitorHandle`](https://docs.rs/winit/latest/winit/monitor/struct.MonitorHandle.html) type (`raw_window_handle` has no equivalent AFAIK).
