### ISSUE TITLE
Incorrect type for vk_sys::Result

### ISSUE THREAD

**Issue by Hawk777** [vulkano-rs/vulkano#1835]
The type of `vk_sys::Result` is `u32`. But [error values are negative](https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/chap3.html#fundamentals-returncodes). Shouldn’t it be `i32`?

**Comment by Rua** [comment]
vk_sys has been deprecated for a while, and was removed from the Vulkano repository. I think you may be looking at outdated code somewhere?

**Comment by Hawk777** [comment]
Well, [crates.io](https://crates.io/crates/vk-sys) still says that this is its repository, so this is where I reported the issue.

**Comment by Rua** [comment]
I see, well it's being misleading then, sorry about that. @AustinJ235 @Eliah-Lakhin could that be removed from crates.io or marked as deprecated in some way?

**Comment by CatCode79** [comment]
From what I know it is not easy to remove a crate from crates.io.

Here some solutions:
https://www.reddit.com/r/rust/comments/p1u5hp/removing_my_own_unused_crate_from_cratesio/

IIRC the reason is to be found historically in a mess that happened at npm:
https://blog.npmjs.org/post/141577284765/kik-left-pad-and-npm

**Comment by Hawk777** [comment]
I don’t think it should be removed anyway; [it’s not unused](https://crates.io/crates/vk-sys/reverse_dependencies). Maybe add a README that informs people of the deprecation?

**Comment by Eliah-Lakhin** [comment]
We marked https://github.com/vulkano-rs/vk-sys source repository as archived and deprecated.

**Comment by Rua** [comment]
@Eliah-Lakhin The crates.io entry doesn't point to that repository though. Could that be changed?

**Comment by Eliah-Lakhin** [comment]
I don't think we can change already published versions. Maybe we can publish another one just with updated link.
