### ISSUE TITLE
No examples of how to use CpuBufferPool

### ISSUE THREAD

**Issue by Firstyear** [vulkano-rs/vulkano#1850]
It would be good to have simple examples of how to use CpuBufferPool to get data from a computation.

**Comment by bits0rcerer** [comment]
#867

**Comment by Rua** [comment]
`CpuBufferPool` no longer exists, so this issue is moot.

**Comment by Enyium** [comment]
@Rua: I wanted to chime in before you release a modified API and say that [`CpuBufferPool::from_data()`](https://docs.rs/vulkano/latest/vulkano/buffer/cpu_pool/struct.CpuBufferPool.html#method.from_data) and `CpuBufferPool::from_iter()` weren't named according to convention. You would expect that these functions return a `CpuBufferPool`, not a `CpuBufferPoolSubbuffer`. The [Rust API Guide](https://rust-lang.github.io/api-guidelines/naming.html) indicates the following about these so called conversion constructors, which are without `self` parameter: <code>***This***Type::from_some_***other***_type()</code>.
