### ISSUE TITLE
QueueCreateInfo does not implement Default

### ISSUE THREAD

**Issue by CABrinegar** [vulkano-rs/vulkano#1857]
*   Version of vulkano: 0.29.0

# Issue
Unable to create QueueCreateInfo without satisfying `_ne` field.

vulkano::device::QueueCreateInfo requires `_ne` field, but it is not clear how to fulfill this, as the struct does not implement the `Default` trait as other `_ne` users do.

## Code:
```rust
use vulkano::device::QueueCreateInfo;

let queue_create_info = QueueCreateInfo {
    family: queue_family,
    queues: vec![0.5],
   ..QueueCreateInfo::default()
};
```
## Error:
```
no function or associated item named `default` found for struct `QueueCreateInfo` in the current scope
function or associated item not found in `QueueCreateInfo<'_>`rustc[E0599](https://doc.rust-lang.org/error-index.html#E0599)
```

**Comment by Rua** [comment]
Not all info structures implement `Default`, because sometimes a value doesn't really have a possible default value, in this case `family`. Instead, you can call `QueueCreateInfo::family`, which provides this value and initialises the rest with default values.
