### ISSUE TITLE
Vulkano 0.29: PhysicalDevice::surface_formats failing validation layers

### ISSUE THREAD

**Issue by korteland** [vulkano-rs/vulkano#1858]
*   Version of vulkano: 0.29.0
*   OS: Arch Linux
*   GPU (the selected PhysicalDevice): NVIDIA GeForce GTX 1080
*   GPU Driver: 2139979776
*   Upload of a reasonably minimal complete `main.rs` file that demonstrates the issue: https://github.com/korteland/vulkano-issue-repro

# Issue

It's entirely possible my setup code is wrong, but calling `PhysicalDevice::surface_formats()` with the most minimal possible supporting code causes this validation layer to trip:

```
VUID-VkSurfaceFormat2KHR-sType-sType(ERROR / SPEC): msgNum: -888940125 - Validation Error: [ VUID-VkSurfaceFormat2KHR-sType-sType ] Object 0: VK_NULL_HANDLE, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0xcb03d9a3 | vkGetPhysicalDeviceSurfaceFormats2KHR: parameter pSurfaceFormats[0].sType must be VK_STRUCTURE_TYPE_SURFACE_FORMAT_2_KHR The Vulkan spec states: sType must be VK_STRUCTURE_TYPE_SURFACE_FORMAT_2_KHR (https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#VUID-VkSurfaceFormat2KHR-sType-sType)
```

It should be possible to clone the linked repo, type `cargo run` and observe it, at least on Linux - haven't tested other platforms. It also happens on an Intel iGPU. I verified it's this call causing the problem by adding a panic before that call (no issues) then moving the panic immediately after the call (fails).

I had a quick browse through the code in `src/device/physical.rs`, nothing jumped out at me as causing this.

**Comment by Rua** [comment]
I've reproduced the issue and submitted a fix. Thanks for reporting!

**Comment by korteland** [comment]
Wow, thanks for the quick turnaround! Much appreciated.
