### ISSUE TITLE
No support for vk_ext_debug_utils during instance creation

### ISSUE THREAD

**Issue by jherico** [vulkano-rs/vulkano#1872]
# Template

If you dont understand something just leave it.
If you can provide more detailed information than the template allows for, please ignore the template and present all of your findings.

*   Version of vulkano: 0.29.0
*   OS: Ubuntu 20.04
*   GPU (the selected PhysicalDevice): nVidia RTX 2080
*   GPU Driver: TODO
*   Upload of a reasonably minimal complete `main.rs` file that demonstrates the issue: The triangle example demonstrates it just fine.

# Issue

The library supports enabling debug output after the Vulkan instance has been created with code like this...

```
let debug_report_callback = DebugCallback::new(&instance, MessageSeverity::all(), MessageType::all(), |msg|{
    println!("Debug callback: {:?}", msg.description);
});
```

However, it doesn't support debugging output during _instance_ creation.  In C/C++ this is accomplished by passing the `VkDebugUtilsMessengerCreateInfoEXT` type in the `pNext` chain of the `VkInstanceCreateInfo`.  See [this](https://github.com/KhronosGroup/Vulkan-Samples/blob/master/framework/core/instance.cpp#L317) block of code for an example from the Khronos Vulkan-Samples repository.  

Instance creation failing is one of the hardest issues for new developers to deal with because many tutorials and examples simply assume success.

**Comment by jherico** [comment]
@Rua thanks for the quick turnaround.  However, I had a couple of questions that maybe you can clarify.

First, I don't understand the motivation for supporting an array of `DebugUtilsMessengerCreateInfo` for the instance creation.  I suppose that someone who is writing a rendering system that uses some kind of plugin architecture might want to allow multiple plugins to each define their own callbacks, but it seems like an esoteric use case.

Second, I assumed the desired flow for a simple use case would be something like

```
let debug_create_info = ...
let instance = Instance::with_debug_utils_messengers(create_info, [debug_create_info]).unwrap();
let debug_messenger = DebugUtilsMessenger::new(instance.clone(), debug_create_info);
```

But this approach doesn't work, because passing the `debug_create_info` on the second line counts as a move and so it can't then be used on the third line.  This one may be a result of my inexperience with Rust and there may be some way around it that I'm not yet fluent enough to understand, but right now I seem to have to create a distinct `DebugUtilsMessengerCreateInfo` instance for each of the calls.

**Comment by Rua** [comment]
Vulkan supports multiple messengers, so I figured I might as well make Vulkano support more than one.

You have to create a new `DebugUtilsMessengerCreateInfo` each time, yes, but it implements `Clone` so you can make a copy of it pretty straightforwardly. Note that the reference to the debug callback is now in an `Arc`, so the callback itself can be reused and shared across multiple messengers.

**Comment by jherico** [comment]
@Rua thanks for the feedback.  I could have sworn I tried `clone` and got an error about something not being copyable, but it worked just fine when I tried it now.

There's definitely use cases for calling `DebugUtilsMessenger::new` more than once, but it never even occurred to me that you might want to have more than one callback at instance creation time.  The closest I can find to the spec saying whether multiple instances are valid or not is [here](https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkInstanceCreateInfo.html).  

```
To capture events that occur while creating or destroying an instance, an application can link a [VkDebugReportCallbackCreateInfoEXT](https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkDebugReportCallbackCreateInfoEXT.html) structure or a [VkDebugUtilsMessengerCreateInfoEXT](https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkDebugUtilsMessengerCreateInfoEXT.html) structure to the pNext element of the VkInstanceCreateInfo structure given to vkCreateInstance.
```

Which I regard as ambiguous, even though it uses the singular form, since it also refers to the `pNext` element of `VkInstanceCreateInfo` rather than referencing the `pNext` chain.

My nVidia driver on Ubuntu supports it and calls both callbacks if I provide more than one.  I'll try to find time to try it out on Windows and see if I get the same results.

**Comment by Rua** [comment]
Note further down:
> VUID-VkInstanceCreateInfo-sType-unique
> The `sType` value of each struct in the `pNext` chain **must** be unique, with the exception of structures of type [VkDebugUtilsMessengerCreateInfoEXT](https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkDebugUtilsMessengerCreateInfoEXT.html)

**Comment by jherico** [comment]
Well spotted, thanks
