### ISSUE TITLE
Cannot compile vulkano-shaders

### ISSUE THREAD

**Issue by Devon7925** [vulkano-rs/vulkano#1874]
*   Version of vulkano: 0.29.0
*   OS: Windows 11

# Issue
When trying to run examples, cargo is unable to compile vulkano-shaders.
Top of error:
<img width="826" alt="image" src="https://user-images.githubusercontent.com/22968971/163116990-2b38fd62-f889-4270-9cf5-2a2ebac6a9d7.png">
Bottom of error:
<img width="828" alt="image" src="https://user-images.githubusercontent.com/22968971/163117030-1fca5693-c1f7-4007-b539-5ca916fde62b.png">
Raw paste data: https://pastebin.com/fFuMCH6Z

**Comment by Devon7925** [comment]
Thank you.

**Comment by djxc** [comment]
I also get this error,
vulkan version: 1.3.246.0
vulkano version: 0.33.0
windows 10
I need help
