### ISSUE TITLE
Compute shaders is too slow

### ISSUE THREAD

**Issue by inferrna** [vulkano-rs/vulkano#1895]
*   Version of vulkano: 0.29
*   OS: Ubuntu 20.04
*   GPU (the selected PhysicalDevice): AMD RX560
*   GPU Driver: Both Mesa / AMDVLK

Code example
https://github.com/inferrna/smart_denoise_rs

# Issue

For example denoising of this image (converted to gray) https://github.com/BrutPitt/glslSmartDeNoise/blob/master/image1.png lasts ~2000 ms with example above, but only ~55ms per frame in this demo https://brutpitt.github.io/glslSmartDeNoise/WebGL/wglApp.html . With larger images execution time increases proportionally to size increase.

**Comment by Rua** [comment]
Have you compiled in release mode with optimisations? If so, can you profile the code to see what's eating up all the time?

**Comment by Rua** [comment]
Looking at your flamegraph, most of the time seems to be taken up by initialisation at startup, and not very much of it is actually calls per frame. So I can't really say why your per-frame time is long. However, the initialisation is dominated by the `vkEnumerateInstanceExtensionProperties` API function, which is interesting...

**Comment by JoeOsborn** [comment]
I don't know about the flamegraph's labels, but I found that the image crate and its dependencies when compiled without optimization are really slow, and we pay that cost at initialization time (so maybe the sampler got confused about the stack trace?).
  
When I ran your current code with `cargo run --release ../image.png ../out.png` (and fixed some errors with the buffer sizes needing to be multiplied by 3), it finished in under half a second.  Under development flags, it took about 2 seconds.

**Comment by inferrna** [comment]
Half a second is still too much, especially compared to this frag shader speed: 
![image](https://user-images.githubusercontent.com/4245277/167919170-5ddf0553-8e07-46f7-a8f6-a6476b6bacfa.png)
(my repo is just attempt to port this https://github.com/BrutPitt/glslSmartDeNoise to compute shader)

To make clean about image crate, long initialization, etc.:
If I remove the loop section from shader, then the whole code runs less than 0.1s and just **3ms** computation stage.
```glsl
#version 450

// Original code by Michele Morrone me@michelemorrone.eu / brutpitt@gmail.com
// https://github.com/BrutPitt/glslSmartDeNoise/blob/master/Shaders/frag.glsl
// This software is distributed under the terms of the BSD 2-Clause license

layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;
layout(set = 0, binding = 0) uniform sampler2D image_in;
layout(set = 0, binding = 1, r8ui) uniform writeonly restrict uimage2D image_out;

#define INV_SQRT_OF_2PI 0.39894228040143267793994605993439  // 1.0/SQRT_OF_2PI
#define INV_PI          0.31830988618379067153776752674503

layout(push_constant) uniform Parameters {
    uint Width;
    uint Height;
    float sigma;
    float kSigma;
    float threshold;
} params;

void main() {
    vec2 uv = vec2(gl_GlobalInvocationID.xy);
    const float centrPx = texture(image_in, vec2(gl_GlobalInvocationID.xy) / size).x;

    uint value = uint(round(centrPx));
    imageStore(image_out, ivec2(gl_GlobalInvocationID.xy), uvec4(min(value, 255),0,0,0));     
}
```

**Comment by Rua** [comment]
Vulkano isn't really involved in how shaders execute, it just passes it on to Vulkan, which then handles the rest on the GPU. Vulkano mainly handles validation, but that shouldn't affect the execution time of the actual shader.

**Comment by JoeOsborn** [comment]
This is kind of a pain, but have you tried it as a fragment shader and not a compute shader?  I wonder if there's something in the setup here (either the source or target image format, the local_size.xy, or something) that makes it slow relative to what the vertex shader/fragment shader pair did.
