### ISSUE TITLE
Can't use precompiled shader with optimization

### ISSUE THREAD

**Issue by inferrna** [vulkano-rs/vulkano#1896]
*   Version of vulkano: 0.29
*   OS: Ubuntu 20.04
*   GPU (the selected PhysicalDevice): AMD RX560
*   GPU Driver: Both Mesa / AMDVLK

Code example
https://github.com/inferrna/smart_denoise_rs

# Issue
There are two precompiled shaders in the repo:
`compiled_opt.spv` produced with `./bin/glslc -fshader-stage=compute shader.glsl`
and
`compiled_unopt.spv` produced with `./bin/glslc -fshader-stage=compute -O shader.glsl`

Using unoptimized version in `src/denoise_shader_compiled.rs` works fine but with optimized I got this error at compile stage:

```
1 | / vulkano_shaders::shader! {
2 | |         ty: "compute",
3 | |         bytes: "compiled_opt.spv"
4 | | }
  | | ^
  | | |
  | |_field already declared
  |   `__unnamed` first declared here
```
Using latest glslc from here https://storage.googleapis.com/shaderc/badges/build_link_linux_clang_release.html

**Comment by Rua** [comment]
It seems like the names of variables have been stripped out by optimising it, so when Vulkano is trying to assign names to struct fields, it can't find any names and so it just goes with "unnamed". What it really should do in this case is add numbers so that the names don't conflict anymore.

**Comment by inferrna** [comment]
Passing `-g` to glslc flag seems solved the issue for me:
 `./bin/glslc -g -fshader-stage=compute -O shader.glsl`

But bad naming for unnamed fields is still the issue for vulkano, so I keep this open.
