### ISSUE TITLE
QueueCreateInfo should derive Default?

### ISSUE THREAD

**Issue by CLOVIS-AI** [vulkano-rs/vulkano#1900]
# Template

*   Version of vulkano: 0.29.0

# Issue

`QueueCreateInfo` (simplified):
```rust
struct QueueCreateInfo {
    family: ...,
    queues: ...,
    _ne: crate::NonExhaustive,
}
```

The documentation of `NonExhaustive` says "Structures with a field of this type can only be constructed by calling a function such as Default::default()". The current usage looks like:
```rust
let _ = QueueCreateInfo {
    family,
    queues,
    _ne: Default::default()
};
```

Shouldn't `QueueCreateInfo` derive `Default`, so we could write:
```rust
let _ = QueueCreateInfo {
    family,
    queues,
    ..Default::default()
};
```
That seems more ergonomic to me than having internal Vulkano fields appear in end user code.

**Comment by Rua** [comment]
Not all info structs implement `Default` because not all fields necessarily have sensible default. `QueueCreateInfo` is one of those; note it has a constructor named `family` instead.

**Comment by CLOVIS-AI** [comment]
I see, thanks.
