### ISSUE TITLE
Cannot copy depth buffer

### ISSUE THREAD

**Issue by KeKsBoTer** [vulkano-rs/vulkano#1923]
Hey,

I am trying to copy a depth image to an buffer so that I can export it as an image.

# Issue

I have a depth buffer/image with format D32_SFLOAT (D16_UNORM leads to same issue).

When calling `copy_image_to_buffer` with my depth buffer as a source I get the following error
```
this format cannot accept pixels', .../vulkano-0.29.0/src/command_buffer/validity/copy_image_buffer.rs:154:10
```
The code fails because I cannot get the block size for the format: 
https://github.com/vulkano-rs/vulkano/blob/de1147589eefc678b95885671ed10052bebcd690/vulkano/src/command_buffer/validity/copy_image_buffer.rs#L154

But D32_SFLOAT has a defined block size in the specs and also the xml file used to generate the format code:
```xml
 <format name="VK_FORMAT_D32_SFLOAT" class="D32" blockSize="4" texelsPerBlock="1">
      <component name="D" bits="32" numericFormat="SFLOAT"/>
  </format>
```
 
Why is the block size not defined and how can I work around this issue?
Thanks!

Version of vulkano: 0.29.0

**Comment by Rua** [comment]
Is this issue fixed in the new Vulkano 0.30 release?
