### ISSUE TITLE
failed to create instance: IncompatibleDriver on MacOs

### ISSUE THREAD

**Issue by arsou33** [vulkano-rs/vulkano#1930]
*   Version of vulkano: 0.30.0
*   OS: MacOS Monterey 12.4
*   GPU (the selected PhysicalDevice): Intel UHD Graphics 630 1536 Mo
*   GPU Driver: from vulkansdk-macos-1.3.216.0.dmg with "global install" checkbox selected

```
use vulkano::instance::{Instance, InstanceCreateInfo};

fn main() {
    println!("Hello, vulkan!");
    let info = InstanceCreateInfo::default();
    let instance = Instance::new(info).expect("failed to create instance");
}
```

# Issue

When run the program panic with message : failed to create instance: IncompatibleDriver

I have no idea how to further investigate the problem.

vulkaninfo tools work correctly 

```
==========
VULKANINFO
==========

Vulkan Instance Version: 1.3.216


Instance Extensions: count = 13
===============================
	VK_EXT_debug_report                    : extension revision 10
	VK_EXT_debug_utils                     : extension revision 2
	VK_EXT_metal_surface                   : extension revision 1
	VK_EXT_swapchain_colorspace            : extension revision 4
	VK_KHR_device_group_creation           : extension revision 1
	VK_KHR_external_fence_capabilities     : extension revision 1
	VK_KHR_external_memory_capabilities    : extension revision 1
	VK_KHR_external_semaphore_capabilities : extension revision 1
	VK_KHR_get_physical_device_properties2 : extension revision 2
	VK_KHR_get_surface_capabilities2       : extension revision 1
	VK_KHR_portability_enumeration         : extension revision 1
	VK_KHR_surface                         : extension revision 25
	VK_MVK_macos_surface                   : extension revision 3
...
```

**Comment by Rua** [comment]
In your `InstanceCreateInfo` you need to enable `enumerate_portability`, as shown in the [triangle example](https://github.com/vulkano-rs/vulkano/blob/master/examples/src/bin/triangle.rs#L67-L68).

**Comment by JMicheli** [comment]
I was in the process of grabbing the relevant lines from the triangle example when Rua posted, so here's what that looks like for the next person reading this:

```rs
// Now creating the instance.
    let instance = Instance::new(InstanceCreateInfo {
        enabled_extensions: required_extensions,
        // Enable enumerating devices that use non-conformant vulkan implementations. (ex. MoltenVK)
        enumerate_portability: true,
        ..Default::default()
    })
    .unwrap();
```

**Comment by arsou33** [comment]
Thanks a lot for the quick response. May be a note on the page https://vulkano.rs/guide/initialization could help others.

**Comment by Rua** [comment]
Vulkano 0.30 released only two days ago, and the website hasn't been updated yet for the new version. In the introduction to the guide, version 0.29 is still used.
