### ISSUE TITLE
`UnsafeDescriptorPool` is `Sync`

### ISSUE THREAD

**Issue by marcot1cs** [vulkano-rs/vulkano#1941]
`UnsafeDescriptorPool` is `Sync` even though `VkDescriptorPool` must be externally synchronized, which `UnsafeDescriptorPool` doesn't do. This trickles down to `SingleLayoutDescSetPool`, which is also `Sync` while not being thread-safe.

**Comment by Rua** [comment]
The only methods that access the pool take `&mut self` though, so I don't know if it matters?

**Comment by marcot1cs** [comment]
You're right, I completely missed that! I guess I spent too much time looking at `UnsafeCommandPool` haha. My apologies.
