### ISSUE TITLE
Move towards removing Arcs everywhere

### ISSUE THREAD

**Issue by tomaka** [vulkano-rs/vulkano#195]
This is a long effort that is already work-in-progress.

Instead of using `Arc<Trait>`, everything should be strongly-typed and allow non-Arcs.

**Comment by tomaka** [comment]
To clarify: the preferred method of doing things will remain using `Arc`. However it should be possible to not use Arcs if wanted.

**Comment by tomaka** [comment]
I noticed a problem with replacing `Arc<Device>` with a template parameter `<P: Deref<Target=Device>>`.

All the lowest-level structs `UnsafeBuffer`, `UnsafeImage`, etc. need to hold a pointer to the device in order to destroy themselves in their destructors. If these low-level types were to become generic, I think it would become too complicated to handle.

For example traits like `Buffer` which currently look like this:

```rust
unsafe trait Buffer {
    fn inner(&self) -> &UnsafeBuffer;
}
```

Would become this:

```rust
unsafe trait Buffer {
    type Device;
    fn inner(&self) -> &Self::Device;
}
```

Which has the consequence that you can no longer use a `Box<Buffer>` or `Arc<Buffer>`.

Conclusion: I think that `Device` should be an exception and be always taken by `Arc`.

**Comment by newpavlov** [comment]
How about making methods like `inner` unsafe with comment that `Unsafe*` structures must be destroyed explicitly by user using something like `drop(self, device: &Device)`?

**Comment by Rua** [comment]
#1739 ended up doing the opposite, so this is no longer relevant.
