### ISSUE TITLE
IncompatibleDescriptorType when buffer follows image

### ISSUE THREAD

**Issue by inferrna** [vulkano-rs/vulkano#1954]
<details>
<summary>System info</summary>
<pre>
System:
  Host: zinochka-VPCEJ3L1R Kernel: 5.19.1 x86_64 bits: 64 compiler: gcc
    v: 11.2.0 Desktop: Unity 7.5.1 wm: Compiz dm: LightDM
    Distro: Ubuntu 22.04.1 LTS (Jammy Jellyfish)
CPU:
  Info: dual core model: Intel Core i5-2520M bits: 64 type: MT MCP
    arch: Sandy Bridge rev: 7 cache: L1: 128 KiB L2: 512 KiB L3: 3 MiB
  Speed (MHz): avg: 2494 high: 3191 min/max: 800/3200 cores: 1: 2993
    2: 2993 3: 3191 4: 800 bogomips: 19953
  Flags: avx ht lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx
Graphics:
  Device-1: Intel 2nd Generation Core Processor Family Integrated Graphics
    vendor: Sony driver: i915 v: kernel ports: active: LVDS-1
    empty: DP-1,HDMI-A-1,VGA-1 bus-ID: 00:02.0 chip-ID: 8086:0126
  Device-2: Suyin Sony Visual Communication Camera type: USB
    driver: uvcvideo bus-ID: 1-1.2:3 chip-ID: 064e:a302
  Display: x11 server: X.Org v: 1.21.1.3 compositor: Compiz v: 0.9.14.1
    driver: X: loaded: modesetting alternate: fbdev,vesa gpu: i915
    display-ID: :0 screens: 1
  Screen-1: 0 s-res: 1600x900 s-dpi: 96
  Monitor-1: LVDS-1 model: LG res: 1600x900 dpi: 106 diag: 438mm (17.3")
  OpenGL: renderer: Mesa Intel HD Graphics 3000 (SNB GT2)
    v: 3.3 Mesa 22.0.5 compat-v: 3.1 direct render: Yes
</pre>
</details>

[Modified basic-compute-shader.rs](https://github.com/vulkano-rs/vulkano/files/9333032/basic-compute-shader.rs.gz)
Got this error `DescriptorSetUpdateError(IncompatibleDescriptorType { binding: 0 })`

After adding debug messages to blocks returning IncompatibleDescriptorType in  `fn check_descriptor_write` I found that 
IncompatibleDescriptorType of that buffer actually was an.... StorageImage! Looks impossible, but that is.
Tested under system-default lavapipe driver that can be found in any Ubuntu 22.04 installation.
(I temporally without access to vulkan supporting hw except GPU in my phone.)

**Comment by Rua** [comment]
On line 191, you're getting the layout of set 0, and then you try to create two descriptor sets using the same layout. I assume what you meant to do is get the layout of set 1 before creating the second descriptor set?

**Comment by inferrna** [comment]
Ohh, thank you, now it runs fine. Can you please add (or modify some) example showing usage of 2 different layouts?
Another point of this: first I tried to use two buffers in different layouts same way, but all worked fine. And when I changed one buffer to Image the error appeared. So, there might be needed an additional check of this.

**Comment by Rua** [comment]
How would that be checked, though? Vulkano can't know what you intended to do.
