### ISSUE TITLE
Why is there no device::Features::union()?

### ISSUE THREAD

**Issue by Firestar99** [vulkano-rs/vulkano#1958]
*   Version of vulkano: 0.29.0
*   OS: Ubuntu 22.04

# Issue

Why is there no device::Features::union()?
Device Features are (afaik) all just boolean toggles to enable or disable certain features just like DeviceExtensions or InstanceExtensions do it with extensions. The *Extensions have the functions none(), is_superset_of(), union(), intersection(), difference(), but Device Features has all these functions too except union() (and adding all()). Is there any specific reason for Device Features to not have the union() function?

# Workaround
```rust
fn device_features_union(a: &Features, b: &Features) -> Features {
    Features::all().difference(a).difference(b)
}
```

**Comment by Rua** [comment]
I think it's just an oversight. Ideally there would be implementations of `BitOr`/`BitOrAssign`, `BitAnd`/`BitAndAssign` and `Sub`/`SubAssign`, then named functions wouldn't be needed anymore. Do you want to make a PR?

**Comment by Firestar99** [comment]
Sure thing :D

**Comment by Firestar99** [comment]
Feel free to review
