### ISSUE TITLE
about vulkano_shaders macro question

### ISSUE THREAD

**Issue by ac-khaos** [vulkano-rs/vulkano#1980]
I am a beginner:
When I want to use custom variables to control the Vulkan_shaders Macro:

<img width="419" alt="image" src="https://user-images.githubusercontent.com/45448146/190658162-3e7dc176-4731-4a27-9d69-6cf5984a3669.png">

example:
let type = String::from("vertex");
create_shader_macro!(shader, type, "xxxx.glsl");

rust cannot expand variables in macro

How do, thanks!

**Comment by Rua** [comment]
This isn't possible because of how macros work. Macros are expanded at the time that the program is compiled, whereas variables only get their value when the program is actually run.

**Comment by ac-khaos** [comment]
> This isn't possible because of how macros work. Macros are expanded at the time that the program is compiled, whereas variables only get their value when the program is actually run.

Thanks, from the compiler's perspective, it is true that.
Lisp(Macros) and Javascript(Meta Programming) can do this.
However, since all codes are generated from code, there will always be better design patterns, but I have not found them yet.
