### ISSUE TITLE
[Question]: CpuBufferPool Error

### ISSUE THREAD

**Issue by ac-khaos** [vulkano-rs/vulkano#1994]
<img width="1158" alt="image" src="https://user-images.githubusercontent.com/45448146/191484868-c2b135e4-c52a-403e-bfa7-2d4ae1ad827e.png">

<img width="642" alt="image" src="https://user-images.githubusercontent.com/45448146/191485195-6d88899c-e19f-4e17-82e8-266881b3614d.png">

**Comment by Rua** [comment]
https://github.com/vulkano-rs/vulkano/blob/master/examples/src/bin/shader-types-derive.rs#L64-L70

**Comment by ac-khaos** [comment]
> https://github.com/vulkano-rs/vulkano/blob/master/examples/src/bin/teapot/main.rs#L454-L458

Thanks!
