### ISSUE TITLE
Instance::new fails on OSX, even after installing the SDK: "failed to create instance: IncompatibleDriver"

### ISSUE THREAD

**Issue by VictorTaelin** [vulkano-rs/vulkano#2042]
I'm trying to follow the [Vulkano guide](https://vulkano.rs/guide/initialization) on macOS Monterey Version 12.5.1. I've followed the recommendation on the README, and installed Vulkan SDK for macOS, version 1.3.224.1. The installation was successful, and I was able to run the triangle example on this repository. I've then created a brand new Rust repository with `cargo init`, and added `vulkano=0.31.1` to the dependencies. I've wrote a simple main.rs file that just creates a Vulkano instance, as suggested on the guide:

```rust
use vulkano::VulkanLibrary;
use vulkano::instance::{Instance, InstanceCreateInfo};

fn main() {

  let library = VulkanLibrary::new().expect("no local Vulkan library/DLL");
  let instance = Instance::new(library, InstanceCreateInfo::default()).expect("failed to create instance");

  println!("Hello, world!");
}
```

Compiling and running the program above throws the following error:

```bash
     Running `target/debug/vulk`
thread 'main' panicked at 'failed to create instance: IncompatibleDriver', src/main.rs:7:72
stack backtrace:
   0: rust_begin_unwind
             at /rustc/f5193a9fcc73dc09e41a90c5a2c97fc9acc16032/library/std/src/panicking.rs:556:5
   1: core::panicking::panic_fmt
             at /rustc/f5193a9fcc73dc09e41a90c5a2c97fc9acc16032/library/core/src/panicking.rs:142:14
   2: core::result::unwrap_failed
             at /rustc/f5193a9fcc73dc09e41a90c5a2c97fc9acc16032/library/core/src/result.rs:1785:5
   3: core::result::Result<T,E>::expect
             at /rustc/f5193a9fcc73dc09e41a90c5a2c97fc9acc16032/library/core/src/result.rs:1064:23
   4: vulk::main
             at ./src/main.rs:7:18
   5: core::ops::function::FnOnce::call_once
             at /rustc/f5193a9fcc73dc09e41a90c5a2c97fc9acc16032/library/core/src/ops/function.rs:251:5
```

Why am I getting an "IncompatibleDriver" error? Since the triangle example worked, I expected this to work too. Am I missing something?

Also, the examples here are quite complex, since they deal with windowing and require importing many files. Is there a simpler, single file, compute "hello, world" example that just creates a "USE_HOST_PTR" buffer, launches a kernel to write some data on it, and reads it back to print on host? That would be immensely helpful.

**Comment by Rua** [comment]
MacOS and iOS Vulkan implementations are not fully conformant to the spec, so they are not exposed by default. To access them, you need to set the `enumerate_portability` on `InstanceCreateInfo`. Vulkano's examples all use this, but it seems that the guide doesn't. I think the guide should at least mention this, so I'll bring up the issue.

**Comment by Rua** [comment]
I've made a PR that adds some documentation about this to the page of the `instance` module: #2044.
