### ISSUE TITLE
Vulkano panics with u64 GLSL extension on OSX

### ISSUE THREAD

**Issue by VictorTaelin** [vulkano-rs/vulkano#2045]
I'm trying to run the following shader on macOS Monterey, Version 12.6, Apple M1 Max, Rust 1.66.0-nightly, Vulkano 0.31.0:

```glsl
#version 460
#extension GL_ARB_gpu_shader_int64 : enable

layout(local_size_x = 64, local_size_y = 1, local_size_z = 1) in;

layout(set = 0, binding = 0) buffer Data {
  uint data[];
} buf;

void main() {
  // creates a 64-bit uint, 'foo', with value 12
  
  uint64_t test = 0;
  uint idx = gl_GlobalInvocationID.x;
  buf.data[idx] = 1;
}
```

It panics with the following error:

```
thread 'main' panicked at 'failed to create shader: SpirvCapabilityNotSupported { capability: Int64, reason: RequirementsNotMet(["feature `shader_int64`"]) }', src/main.rs:78:6
``` 

Why isn't the extension supported, if it is available on Metal? I thought the Apple M1 Max had support for 64-bit ints and atomics; is this incorrect? Or should I be using a different extension? Where is that documented?

**Comment by Rua** [comment]
Have you enabled the `shader_int64` feature when creating the device?

**Comment by VictorTaelin** [comment]
I wasn't aware of that. I've tried as in:

```rust
  let (device, mut queues) = Device::new(
      physical,
      DeviceCreateInfo {
          enabled_extensions: DeviceExtensions {
            khr_shader_atomic_int64: true,
            ..Default::default()
          },
          queue_create_infos: vec![QueueCreateInfo {
              queue_family_index,
              ..Default::default()
          }],
          ..Default::default()
      },
  )
  .expect("failed to create device");
```

And now I get a: 

```
failed to create device: ExtensionRestrictionNotMet(ExtensionRestrictionError { extension: "khr_shader_atomic_int64", restriction: NotSupported })
```

Does that mean M1 Max GPUs aren't capable of doing atomic 64-bit operations, or is it just a matter of Vulkan not recognizing it?

**Comment by Rua** [comment]
I mean the `shader_int64` feature, not the `khr_shader_atomic_int64` extension. The former is for 64-bit integers in general, the latter is for atomic operations specifically.

**Comment by VictorTaelin** [comment]
Oh oops, sorry. Yes, you're correct, enabling the `shader_int64` does fix the original issue. I do need 64-bit atomics though, so guess I'm still out of luck?

**Comment by Rua** [comment]
I'm afraid so. When something isn't implemented by a Vulkan drivers, there are multiple reasons why that could be the case. The hardware necessary for implementing it (efficiently, or at all) may be missing, or the hardware may be there but it hasn't been implemented yet in the driver. If you know that the functionality is there in Metal, then it's probably the latter case. You may want to ask the driver writers (MoltenVK?) about it.
