### ISSUE TITLE
Error on building Vulkano 0.32

### ISSUE THREAD

**Issue by nabajour** [vulkano-rs/vulkano#2084]
*   Version of vulkano: 0.32
*   OS: Debian unstable
*   GPU (the selected PhysicalDevice): NVidia 2080  Ti
*   GPU Driver: NVidia
*   Upload of a reasonably minimal complete `main.rs` file that demonstrates the issue: vulkano's examples

# Issue

Trying to port and build my Vulkano code with Vulkano 0.32, I ran into some compilation issues that seem to be internal to Vulkano, from what I understand. I tried to compile the Vulkano examples too, to check if the issues was in my code, and the same error happens:

```
$ cargo build
[ .... ]
   Compiling vulkano v0.32.0 (/home/nab/src/vulkano/vulkano)
   Compiling glutin v0.29.1
   Compiling shaderc v0.8.0
error[E0015]: cannot call non-const fn `parking_lot::lock_api::RwLock::<parking_lot::RawRwLock, Vec<S>>::new` in constants
   --> vulkano/src/memory/allocator/mod.rs:713:17
    |
713 |         blocks: RwLock::new(Vec::new()),
    |                 ^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: calls in constants are limited to constant functions, tuple structs and tuple variants

For more information about this error, try `rustc --explain E0015`.
error: could not compile `vulkano` due to previous error
$
```

I'm working on learning rust, so the error could be on my side, but I tested on my two machines, and with stable and nightly rust. 

Any help on getting vulkano v0.32.0 to compile is welcome. 

Thanks

**Comment by marc0246** [comment]
Hello, can you please run `cargo clean` and try again?

**Comment by nabajour** [comment]
> Hello, can you please run `cargo clean` and try again?

I tried, still getting the same result.

**Comment by marc0246** [comment]
Okay, in that case you will have to remove your `Cargo.lock` file and recompile. It has locked your version of `lock_api` to 0.4.6 or older, where the `RwLock` constructor wasn't `const` yet.

**Comment by nabajour** [comment]
> Okay, in that case you will have to remove your `Cargo.lock` file and recompile. It has locked your version of `lock_api` to 0.4.6 or older, where the `RwLock` constructor wasn't `const` yet.

Awesome, that seems to have fixed it. Totally forgot about the lock file fixing the dependencies version. Sorry for the noob question! Now on to adapt to the latest vulkano breaking changes :-D 

Thanks!
