### ISSUE TITLE
copy_buffer_to_image does not implement Default::default()

### ISSUE THREAD

**Issue by XPCMasterX** [vulkano-rs/vulkano#2092]
*   Version of vulkano: 0.32.1
*   OS: Linux
*   GPU (the selected PhysicalDevice): Intel iGPU
*   GPU Driver: Mesa 2.22.2
*   Upload of a reasonably minimal complete `main.rs` file that demonstrates the issue: 
```rust
.copy_buffer_to_image(CopyBufferToImageInfo {
            src_buffer: img_buffer.clone(),
            dst_image: image.clone(),
            dst_image_layout: ImageLayout::General,
            ..Default::default()
              ^^^^^^^^^^^^^
        })
```

# Issue

When trying to copy a buffer to an image, you need to use `CopyBufferToImageInfo` but `Default` is not implement as a trait so the parameter `_ne` and `regions` are required which normally you would use `Default::default()` for.

**Comment by marc0246** [comment]
This is a design choice. There is no way to implement `Default` because some fields can't have defaults. You must use `CopyBufferToImageInfo::buffer_image`.

**Comment by XPCMasterX** [comment]
Thanks
