### ISSUE TITLE
Mac support

### ISSUE THREAD

**Issue by paspielka** [vulkano-rs/vulkano#2113]
*   Version of vulkano: 0.22.0
*   OS: MacOS bigsur 11.4
*   GPU (the selected PhysicalDevice): None
*   GPU Driver: None
*   Upload of a reasonably minimal complete `main.rs` file that demonstrates the issue: TODO

# Issue

Is there Mac support on Vulkan, because I'm running into issues.

**Comment by Rua** [comment]
Vulkan is supported on Macs via MoltenVK, but the Vulkan standard is not fully supported, some bits are missing. Some extra work is needed to get Vulkan (and therefore Vulkano) up and running, which is described here: https://docs.rs/vulkano/latest/vulkano/instance/index.html#portability-subset-devices-and-the-enumerate_portability-flag

**Comment by paspielka** [comment]
Yeah, newer version works perfectly on Mac thanks.
