### ISSUE TITLE
Fail to load vulkan on mac

### ISSUE THREAD

**Issue by rongcuid** [vulkano-rs/vulkano#2120]
# Template

*   Version of vulkano: 0.32.0
*   OS: Mac OS 13.1
*   GPU (the selected PhysicalDevice): TODO
*   GPU Driver: TODO
*   Upload of a reasonably minimal complete `main.rs` file that demonstrates the issue: just use any example

# Issue

When I try to run a Vulkano program, it fails to load Vulkan:

```
cargo run --bin basic-compute-shader
    Finished dev [unoptimized + debuginfo] target(s) in 0.06s
     Running `/Users/rongcuid/src/vulkano/target/debug/basic-compute-shader`
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: LibraryLoadFailure(DlOpen { desc: "dlopen(libvulkan.1.dylib, 0x0005): tried: \'libvulkan.1.dylib\' (no such file), \'/System/Volumes/Preboot/Cryptexes/OSlibvulkan.1.dylib\' (no such file), \'/usr/lib/libvulkan.1.dylib\' (no such file, not in dyld cache), \'libvulkan.1.dylib\' (no such file), \'/Users/rongcuid/src/vulkano/target/debug/build/shaderc-sys-d1970d87df1501e8/out/lib/libvulkan.1.dylib\' (no such file), \'/Users/rongcuid/src/vulkano/target/debug/deps/libvulkan.1.dylib\' (no such file), \'/Users/rongcuid/src/vulkano/target/debug/libvulkan.1.dylib\' (no such file), \'/Users/rongcuid/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/libvulkan.1.dylib\' (no such file), \'/Users/rongcuid/.rustup/toolchains/stable-aarch64-apple-darwin/lib/libvulkan.1.dylib\' (no such file), \'/Users/rongcuid/lib/libvulkan.1.dylib\' (no such file), \'/usr/local/lib/libvulkan.1.dylib\' (no such file), \'/usr/lib/libvulkan.1.dylib\' (no such file, not in dyld cache)" })', examples/src/bin/basic-compute-shader.rs:36:40
```

The library is in fact under `/opt/local/lib`. I don't know why Vulkano doesn't load it, because I have tried using Vulkan in C and that program can load the library normally.

**Comment by rongcuid** [comment]
It was Macport's problem. I installed directly from the installer and it works. I guess it's your choice to see whether this installtion option should be considered as an additional case

**Comment by Rua** [comment]
I don't know anything about Macs. What in Vulkano's code would need to be changed?

**Comment by rongcuid** [comment]
Maybe Vulkano is not responsible for loading the library. Perhaps the issue is elsewhere, maybe Ash. I will give it a look later.

**Comment by Soth1985** [comment]
LunarG Vulkan SDK installs the libraries to the /usr/local/lib path which dlopen does not search in, to fix can just add it to search path in https://github.com/vulkano-rs/vulkano/blob/a1307b6ef8dbcf77c3479c56bd354de7bc297a2e/vulkano/src/library.rs

```
#[cfg(target_os = "macos")]
            fn get_paths() -> [&'static Path; 4] {
                [
                    Path::new("libvulkan.dylib"),
                    Path::new("libvulkan.1.dylib"),
                    Path::new("libMoltenVK.dylib"),
                    Path::new("/usr/local/lib/libMoltenVK.dylib"),
                ]
            }
```

**Comment by victor-rykov-playrix** [comment]
In RustRover setting environment variable also helps (exporting it to .profile .zprofile does not work)

![image](https://github.com/user-attachments/assets/207199bf-a9a6-4a71-8e5c-20b02c28e621)
