### ISSUE TITLE
Lower Vulkan 1.3 example requirements

### ISSUE THREAD

**Issue by rongcuid** [vulkano-rs/vulkano#2121]
# Template

If you dont understand something just leave it.
If you can provide more detailed information than the template allows for, please ignore the template and present all of your findings.

*   Version of vulkano: TODO
*   OS: TODO
*   GPU (the selected PhysicalDevice): TODO
*   GPU Driver: TODO
*   Upload of a reasonably minimal complete `main.rs` file that demonstrates the issue: TODO

# Issue

The Vulkan 1.3 triangle example doesn't exactly need Vulkan 1.3 API. You can lower the API requirement (for physical devices) to 1.0, and enable `khr_dynamic_rendering` in `DeviceExtensions`.

**Comment by Rua** [comment]
When I made this, I wanted to avoid complicated the example code (since it's meant as an introduction). But maybe you're right, it should work with `khr_dynamic_rendering` too.

**Comment by rongcuid** [comment]
I guess if you rephrase it as "triangle using dynamic rendering", you can say it requires Vulkan 1.3 _or_ the dynamic rendering extension.
