### ISSUE TITLE
DeviceLocalBuffer API doesn't expose sharing mode

### ISSUE THREAD

**Issue by john01dav** [vulkano-rs/vulkano#2126]
DeviceLocalBuffer's constructors don't expose SharingMode, so I didn't even know that this existed at first. It came to my attention when validation layers detected that it was not set correctly. It's set to Exclusive by default, but I need it to be set to Concurrent since I am uploading data to my buffers in a background thread on a background queue, then using them on the main thread in the main queue. 

Looking at the source code, this seems like a fairly easy fix, but adding a parameter is an API change so it warrants discussion before making a PR.

**Comment by Rua** [comment]
I'm guessing that this will be fixed by @marc0246's upcoming buffer refactoring.
