### ISSUE TITLE
Typo in `PrimaryCommandBufferAbstract` docs?

### ISSUE THREAD

**Issue by thanatos** [vulkano-rs/vulkano#2129]
# Template

If you dont understand something just leave it.
If you can provide more detailed information than the template allows for, please ignore the template and present all of your findings.

*   Version of vulkano: 0.32.3
*   OS: (the docs)
*   GPU (the selected PhysicalDevice): N/A
*   GPU Driver: N/A
*   Upload of a reasonably minimal complete `main.rs` file that demonstrates the issue: N/A

# Issue

The docs for [`PrimaryCommandBufferAbstract::execute`](https://docs.rs/vulkano/latest/vulkano/command_buffer/trait.PrimaryCommandBufferAbstract.html#method.execute), as well as [`PrimaryCommandBufferAbstract::execute_after`](https://docs.rs/vulkano/latest/vulkano/command_buffer/trait.PrimaryCommandBufferAbstract.html#method.execute_after) read:

> The command buffer is not actually executed until you call `flush()` on the object. You are encouraged to chain together as many futures as possible before calling `flush()`, and call `.then_signal_future()` before doing so. Note however that once you called `execute()` there is no way to cancel the execution, even if you didn’t flush yet.

There doesn't seem to be any method `then_signal_future`; this is probably meant to refer to one or all of the `then_signal_fence(_*)` or `then_signal_semaphore(_*)` methods.

(There's also some grammatical errors towards the end of the paragraph; I've sent #2128 for those. However, I'm not sure how the bits around "`then_signal_future` are supposed to read, so I didn't fix those, and hence, put that in this issue.)

**Comment by Rua** [comment]
Yeah that looks like a mistake, it should be `then_signal_fence`. Can you fix it as part of your PR?
