### ISSUE TITLE
archived vulkano-examples uses vulkano 0.20.0, but the API has changed significantly

### ISSUE THREAD

**Issue by jrkirby** [vulkano-rs/vulkano#2160]
There's not a problem showing examples of an old API, but it should be made clear, at least in the description that the examples are not up to date with the latest version of vulkano API. If you try using the examples with 0.32.3 version of the crate you will run into numerous issues where 0.20.0 code will not work.

Ideally there would be a repository like vulkano-examples that is up to date with the current version of the crate. But in the meantime, it is crucial to communicate that these examples *do not work* with later versions of the crate.

I'm posting this issue here because issues have been disabled on the vulkano-examples repository.

**Comment by Rua** [comment]
The vulkano-examples repository isn't being maintained and hasn't been in a long time. It's not really intended for anyone to use it anymore.

**Comment by jrkirby** [comment]
You're right, the description actually is clear that it's outdated. Somehow I missed that notice in the description. I was confused myself.
