### ISSUE TITLE
`CpuAccessibleBuffer::from_data` seems to have UB

### ISSUE THREAD

**Issue by yshui** [vulkano-rs/vulkano#2168]
# Issue

It allocates an uninitialized array of bytes, then creates a `&mut` reference to it (via `uninitialized.write()`), which is UB. 
Unless `uninitialized` doesn't mean what I think it means here?

**Comment by Rua** [comment]
Uninitialised memory behaves differently when it is given to you by Vulkan: Rust cannot tell the difference between an uninitialised buffer and a buffer that was initialised with random bytes. Rust will not make any nasty assumptions about it and will treat it as initialised, so it's not UB.

In any case, `CpuAccessibleBuffer` is being removed and replaced by something completely new for the next release.

**Comment by yshui** [comment]
OK, _maybe_ that part is fine (not 100% convinced). But it is actually worse. Because `.write()` calles `BufferContents::from_bytes_mut` with the uninitialized buffer, which is going to be an invalid bit pattern for `T`. Creating such a `&mut T` is UB too.

**Comment by yshui** [comment]
I see. I guess that means `BufferContents` can only be implemented for types that doesn't have invalid bit patterns. That makes sense.

But I still want to point out the unsafe trait `BufferContents` doesn't have any documentation pointing out why it's unsafe, and what are the conditions for implementing it.

**Comment by yshui** [comment]
it does indeed! it has very nice documentation too.

thanks! closing...
