### ISSUE TITLE
UnexpectedImageLayout { allowed: Undefined, requested: PresentSrc }

### ISSUE THREAD

**Issue by ProbabilisticS** [vulkano-rs/vulkano#2185]
*   Version of vulkano: 0.33.0
*   OS: Win 10 x64
*   GPU (the selected PhysicalDevice): NVIDIA GeForce RTX 3060
*   GPU Driver: 531.61
*   Upload of a reasonably minimal complete `main.rs` file that demonstrates the issue: N/A
# Issue
I've been having issues with incorrect image layout transitions (Undefined -> X) since the start of my Vulkano journey about a year ago. After an update to Vulkano version 0.33.0, the software patch I've been using was rendered useless, and as such, I had to come up with a new patch to enable my continued usage of Vulkano. While doing so, I happen to stumble accross this document:

https://github.com/vulkano-rs/vulkano/blob/master/DESIGN.md#image-layouts

In the last paragraph of the linked section, it targets the very issue I've been facing the whole time. However, it seems the document is out-of-date and not applicable anymore.

Is this is common issue with Vulkano? Is there a documented way to resolve it?

All help is welcome!

**Comment by Rua** [comment]
This looks very much like a bug in Vulkano, but I can't say offhand where the problem is, it will need some investigating.

**Comment by ProbabilisticS** [comment]
Not sure if 0.34 did it, but this seems to have been solved. Version 0.34 did solve a couple of other barrier issues aswell 👍 Closing.
