### ISSUE TITLE
The trait `SafeDeref` is not implemented for `UnsafeCommandBuffer`

### ISSUE THREAD

**Issue by Jason0214** [vulkano-rs/vulkano#2257]
- Version of vulkano: "0.33.0"

# Issue 

Rust rookie here. More familiar with Vulkan than rust.. so I was trying to use `UnsafeCommandBuffer` to have thiner abstraction on top of Vulkan API. However, I had issues when trying to send `UnsafeCommandBuffer` for submission through `SubmitInfo`. The `SubmitInfo` struct expects something implements `PrimaryCommandBufferAbstract` trait which is bound to `SafeDeref`. The `UnsafeCommandBuffer` itself is not deref-able, so I tried to wrapped it into Box, however, the `SafeDeref` is still not satisfied. Kindly asking what might go wrong here, and what is the intended way for `UnsafeCommandBuffer` submission?
 
```
        let cmd_buffer  : UnsafeCommandBuffer = ...

        self.queue.queue.with(|queue: QueueGuard| {
            unsafe {
                queue.submit_unchecked(
                    [SubmitInfo{
                        signal_semaphores: vec![],
                        command_buffers: vec![Arc::new(Box::new(cmd_buffer))],
                        wait_semaphores: vec![],
                        ..Default::default()
                    }],
                    Some(fence.clone())
                )
            }
        });
        Ok(())
```

The error I was getting
``` txt
error[E0277]: the trait bound `UnsafeCommandBuffer: SafeDeref` is not satisfied
  --> src/pipelines/cmd.rs:74:47
   |
74 |                         command_buffers: vec![Arc::new(Box::new(cmd_buffer))],
   |                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `SafeDeref` is not implemented for `UnsafeCommandBuffer`
   |
   = help: the following other types implement trait `SafeDeref`:
             &'a T
             Arc<T>
             Box<T>
   = note: required for `UnsafeCommandBuffer` to implement `PrimaryCommandBufferAbstract`
   = note: 1 redundant requirement hidden
   = note: required for `Box<UnsafeCommandBuffer>` to implement `PrimaryCommandBufferAbstract`
   = note: required for the cast from `Box<UnsafeCommandBuffer>` to the object type `dyn PrimaryCommandBufferAbstract<Handle = ash::vk::definitions::CommandBuffer>`
```

**Comment by Rua** [comment]
That's definitely something we need to address. Probably as part of the task graph, but maybe earlier if possible.

**Comment by Jason0214** [comment]
Thanks @Rua and @marc0246.  I found https://github.com/vulkano-rs/vulkano/blob/f4498585ad2935d54dfc00308b72dbabcc789ebf/vulkano/src/command_buffer/traits.rs#L143 is the `PrimaryCommandBufferAbstract` which feels like the impl for this trait, I guess the compiler would try to ''instantiate" base on it? And yes, `UnsafeCommandBuffer` at least does not have `resources_usage()`, so it will fail anyway. This sounds like an easy patch to work around, `resources_usage()` is not used by Vulkan.
On the other hand, I am still a bit unclear on `SafeDeref`, not exact sure how the original https://github.com/vulkano-rs/vulkano/pull/29/files change realizes its change description. And is `UnsafeCommandBuffer` `SafeDerfe`-able?

**Comment by Jason0214** [comment]
Close, because this is not an issue and also not directly related to "taskgraph" mentioned in the discussion.

**Comment by Jason0214** [comment]
@marc0246 Thanks for following up. My original question is about what's the purpose of `SafeDeref`. I noticed that the commit adding SafeDeref mentions  "guarantee that the device was always the same", so I was curious how `SafeDeref` achieves it.  
Based on your last comment and the fact `SafeDeref` is a direct inherit of trait `Deref`.  I guess `SafeDeref` isn't much different from `Deref`.  All my questions have been cleared now 😄
