### ISSUE TITLE
using bytes in shader! fails to build

### ISSUE THREAD

**Issue by the-ssd** [vulkano-rs/vulkano#2279]
*   Version of vulkano: 0.33 and git master
*   OS: Arch Linux
*   GPU: Nvidia
[Archive.zip](https://github.com/vulkano-rs/vulkano/files/12266851/Archive.zip)

# Issue

using bytes in shader macro doesn't work

**Comment by Rua** [comment]
Can you elaborate?

**Comment by the-ssd** [comment]
idk why but it works now
