### ISSUE TITLE
How to write an array of image views to a descriptor set?

### ISSUE THREAD

**Issue by realmayus** [vulkano-rs/vulkano#2294]
*   Version of vulkano: 0.33

Hi, I'm trying to follow [this guide](https://gist.github.com/DethRaid/0171f3cfcce51950ee4ef96c64f59617) on implementing descriptor indexing in order to bind a large number of textures. I have two questions:
1. I'm not sure how to bind my textures (which are image views) to the descriptor set.
I tried using ` WriteDescriptorSet::image_view_array(2, 0, textures)` with `textures` having the type `Vec<Arc<ImageView<ImmutableImage>>>`, but I'm getting this error:

![image](https://github.com/vulkano-rs/vulkano/assets/38134006/58098b57-578b-41bb-8b7c-44242d34c487)

How do I obtain the required type from my textures?

2. How do I enable partially bound descriptor sets in vulkan? The guide mentions the `VK_DESCRIPTOR_BINDING_PARTIALLY_BOUND_BIT` which you're supposed to add to your `VkDescriptorSetLayoutBindingFlagsCreateInfo` but I wasn't able to figure out how to set that with Vulkano. The closest I could find was using the closure in ` GraphicsPipeline::with_auto_layout`, which I'm already using to set some of the other required properties for variable descriptor sets, but I wasn't able to find any flag options there:
```rs
        .with_auto_layout(device.clone(), |x| {
            let binding = x[0].bindings.get_mut(&0).unwrap();
            binding.variable_descriptor_count = true;
            binding.descriptor_type = DescriptorType::UniformBufferDynamic;
            binding.descriptor_count = 32; 
        })
``` 
Thanks in advance!

**Comment by Rua** [comment]
1. You can cast the image view: `tex as Arc<dyn ImageViewAbstract>`
2. Partially bound descriptor sets are not supported yet in Vulkano.

**Comment by realmayus** [comment]
Thanks! Adding to this, how can you dynamically update the variable descriptor count in PersistentDescriptorSets?
I'm using this WriteDescriptorSet to store my textures:
```rs
WriteDescriptorSet::image_view_sampler_array(0, 0, textures)
```
Then, I create a PersistentDescriptorSet:
```rs
                PersistentDescriptorSet::new_variable(
                    descriptor_set_allocator,
                    descriptor_set_layout,
                    var_count,
                    write_desc_set,
                )
```
which I bind after initializing my pipeline. Now let's say we allow the user to import more textures. How can I update the variable descriptor count at runtime such that the descriptor can fit more textures? I'm a bit confused as to why this value has to be provided in the first place, given it's supposed to be a *variable* count. :sweat_smile:
