### ISSUE TITLE
Packed24_8 lacks type safety

### ISSUE THREAD

**Issue by atynagano** [vulkano-rs/vulkano#2324]
# Template

If you dont understand something just leave it.
If you can provide more detailed information than the template allows for, please ignore the template and present all of your findings.

*   Version of vulkano: b4f4089ad31020b38d1da4776eda53bc43318a77
*   OS: TODO
*   GPU (the selected PhysicalDevice): TODO
*   GPU Driver: TODO
*   Upload of a reasonably minimal complete `main.rs` file that demonstrates the issue: TODO

# Issue

Currently `Packed24_8` is used to represent bit fields in `AccelerationStructureInstance::instance_custom_index_and_mask` and `instance_shader_binding_table_record_offset_and_flags`, but this lacks type safety and not user-friendly imao.
I think it would be better to split the AccerelationStructureInstance fields as in VkAccerelationStructureInstanceKHR and pack them in vulkan.

https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkAccelerationStructureInstanceNV.html

**Comment by Rua** [comment]
There is no 24-bit type in Rust, nor does Rust support bitfields. So this is the best we can do, really.

**Comment by atynagano** [comment]
Oh, I forgot AccelerationStructureInstance is uploaded to gpu directly.
So how is Packed24_8<T24, T8>? Actually I suffered from not realizing that I had reversed the high and low when implementing the ray query example.

**Comment by atynagano** [comment]
Hmm, I didn't know how bit fields work on big endian.
