### ISSUE TITLE
Are optimized SPIR-V shaders supported?

### ISSUE THREAD

**Issue by Rismosch** [vulkano-rs/vulkano#2334]
*   Version of vulkano: 0.33.0
*   Version of shaderc-rs: 0.8
*   OS: Windows 10
*   GPU (the selected PhysicalDevice): NVIDIA GeForce RTX 2060
*   GPU Driver: Version 8.1.964.0
*   Upload of a reasonably minimal complete `main.rs` file that demonstrates the issue: TODO

# Issue

I am working on a small personal game engine. I am no pro, and much of this is still fairly new to me, so this could very well be something I don't understand.

I am trying to compile GLSL to SPIR-V and storing the resulting bytes in a file. The GLSL code is stored in seperate files. I am not using the shader macros, and instead compile them with a different program independant of my engine. At runtime, the engine reads the compiled SPIR-V files and creates the according ShaderModules to pass to vulkano. In theory, this seperation between build and runtime allows me to compile the shaders on my machine well ahead of my runtime and also rebuild shaders on the fly and hotswap them while the engine is running. This system works and isn't the issue. I digress.

To compile GLSL to SPIR-V, I am using [shaderc-rs](https://crates.io/crates/shaderc). I've taken note that you can pass several [CompileOptions](https://docs.rs/shaderc/latest/shaderc/struct.CompileOptions.html) into shaderc, one of which is an [OptimizationLevel](https://docs.rs/shaderc/latest/shaderc/enum.OptimizationLevel.html) flag. shaderc generates different SPIR-V when different flags are being set. However, when I try to load shaders that are compiled with the `OptimizationLevel::Size` or `OptimizationLevel::Performance`, vulkano panics with the following message:

> thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', C:\Users\Rismosch\source\repos\ris_engine\vendor\vulkano\src\pipeline\graphics\vertex_input\definition.rs:139:46
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

`OptimizationLevel::Zero` or not setting the OptimizationLevel at all results in no error.

Here's the code which compiles GLSL to SPIR-V: https://github.com/Rismosch/ris_engine/blob/cdd2c168005b30899e639ad5bc532cfbfdfb6766/crates/ris_asset/src/importer/glsl_importer.rs#L35

The highlighted line is specifically the line of code that sets the OptimizationLevel flag. I know the code above contains my own types and shenanigans, but it's the best I can provide for now.

I also included a zip package below. I have a simple vertex and fragment shader, once compiled with no optimization, once compiled with the `OptimizationLevel::Performance` flag, and their original GLSL source code: [shaders.zip](https://github.com/vulkano-rs/vulkano/files/12640909/shaders.zip)

With my untrained eye, the contents of the SPIR-V files are simmilar, but certainly different.

![grafik](https://github.com/vulkano-rs/vulkano/assets/45226631/bacaa422-bbcd-419f-a39a-ceba83e5e4a2)

**Comment by Rua** [comment]
It's certainly our intent to support optimised shaders, but in the past they weren't really taken into account, and we're still trying to fix that.

In your particular case, I'm guessing you're using the `VertexDefinition` trait and `impl_vertex!` macro, both of which rely on matching the name of the variable in the shader with the name of the field in `impl_vertex!`. However, because you've optimised the shader, the names are removed, so this matching is no longer possible. Instead, you need to create a `VertexInputState` value yourself.

**Comment by Rismosch** [comment]
That sounds quite plausible, considering that when the names of the struct on the Rust and Shader side don't match, I get errors. I am currently only deriving from the Vertex trait like this:

    #[derive(BufferContents, Vertex, Default)]
    #[repr(C)]
    pub struct Vertex3d {
        #[format(R32G32B32_SFLOAT)]
        pub position: [f32; 3],
        #[format(R32G32B32_SFLOAT)]
        pub color: [f32; 3],
    }

I am definitely going to play around with the Vertex trait now. I'll try to get things working. And thanks for the quick response :)

**Comment by Rua** [comment]
Meanwhile we're looking into whether we can make `Vertex` and `VertexDefinition` work even if the names have been stripped from the shader.

**Comment by Rismosch** [comment]
After further debugging, I've come to the conclusion that I cannot fix the problem.

The `VertexBufferDescription` returned by the derived `Vertex` trait is fine. The problem is specifically because the names of the `ShaderInterfaceEntry`s are `None`.

This is how I build my pipeline: https://github.com/Rismosch/ris_engine/blob/cdd2c168005b30899e639ad5bc532cfbfdfb6766/crates/ris_video/src/pipeline.rs#L36

`GraphicsPipelineBuilder::build()` calls `VertexDefinition::definition()` internally, and thus accesses the `ShaderInterfaceEntry` of the `EntryPoint`. Since `name` is `None`, the `unwrap()` panics exactly [here](https://docs.rs/vulkano/latest/src/vulkano/pipeline/graphics/vertex_input/definition.rs.html#139).

`ShaderModule` and its `EntryPoint` don't make their members public or allow any kind of modification. Unless I am able to somehow create a custom `ShaderModule`, I see no way how I can fix this myself. So for now I am sticking with unoptimized shaders.

**Comment by Rua** [comment]
Does it panic even if you create a `VertexInputState`?

**Comment by Rismosch** [comment]
Oh, I just realized I can derive from `VertexDefinition` to provide my own `VertexInputState` 😅

I have to try that.

**Comment by Rua** [comment]
`VertexInputState` already implements `VertexDefinition` itself.

**Comment by Rismosch** [comment]
I managed to get it running! For completness sake I am sharing my solution:

I am aware that `VertexInputState` already implements `VertexDefinition`. But since the `unwrap()` happens exactly in the implementation of `VertexDefinition` for `&[VertexBufferDescription]` (links to [docs](https://docs.rs/vulkano/latest/vulkano/pipeline/graphics/vertex_input/trait.VertexDefinition.html#impl-VertexDefinition-for-%26%5BVertexBufferDescription%5D)), I needed to replace exactly that and provide my own implementation.

I took the sourcecode from [here](https://docs.rs/vulkano/latest/src/vulkano/pipeline/graphics/vertex_input/definition.rs.html#121-196) and modified it for my needs. I ended up with code like this:

    #[derive(BufferContents, Vertex, Default)]
    #[repr(C)]
    pub struct Vertex3d {
        #[format(R32G32B32_SFLOAT)]
        pub position: [f32; 3],
        #[format(R32G32B32_SFLOAT)]
        pub color: [f32; 3],
    }

    pub struct CustomVertexDefinition;

    unsafe impl VertexDefinition for CustomVertexDefinition {
        fn definition(
            &self,
            interface: &ShaderInterface,
        ) -> Result<VertexInputState, IncompatibleVertexDefinitionError> {
            let buffer = Vertex3d::per_vertex();

            let bindings = [(
                0u32,
                VertexInputBindingDescription {
                    stride: buffer.stride,
                    input_rate: buffer.input_rate,
                },
            )];

            let mut attributes: Vec<(u32, VertexInputAttributeDescription)> = Vec::new();

            for (binding, element) in interface.elements().iter().enumerate() {
                let infos = match binding {
                    0 => Ok(buffer.members.get("position").unwrap().clone()),
                    1 => Ok(buffer.members.get("color").unwrap().clone()),
                    _ => Err(IncompatibleVertexDefinitionError::MissingAttribute {
                        attribute: String::from("no name"),
                    }),
                }?;

                // TODO: ShaderInterfaceEntryType does not properly support 64bit.
                //       Once it does the below logic around num_elements and num_locations
                //       might have to be updated.
                if infos.num_components() != element.ty.num_components
                    || infos.num_elements != element.ty.num_elements
                {
                    return Err(IncompatibleVertexDefinitionError::FormatMismatch {
                        attribute: String::from("no name"),
                        shader: element.ty,
                        definition: infos,
                    });
                }

                let mut offset = infos.offset as DeviceSize;
                let block_size = infos.format.block_size().unwrap();
                // Double precision formats can exceed a single location.
                // R64B64G64A64_SFLOAT requires two locations, so we need to adapt how we bind
                let location_range = if block_size > 16 {
                    (element.location..element.location + 2 * element.ty.num_elements).step_by(2)
                } else {
                    (element.location..element.location + element.ty.num_elements).step_by(1)
                };

                for location in location_range {
                    attributes.push((
                        location,
                        VertexInputAttributeDescription {
                            binding: 0u32,
                            format: infos.format,
                            offset: offset as u32,
                        },
                    ));
                    offset += block_size;
                }
            }

            Ok(VertexInputState::new()
                .bindings(bindings)
                .attributes(attributes))
        }
    }

and used it like this:

    GraphicsPipeline::start()
        .vertex_input_state(CustomVertexDefinition)
        .vertex_shader(vertex_shader.clone().entry_point("main")?,())
        // ...
        .build(device.clone()),

It definitely isn't the prettiest solution, because this code requires knowledge of the shader, but it works ¯\\\_(ツ)_/¯

Since this solution is specifically tailored to my shader, I don't know how useful this is for you guys. I am just sharing in case it helps.

**Comment by Rua** [comment]
I still don't see why it wouldn't be easier to create `VertexInputState` and not bother with `VertexDefinition` at all. You would never encounter that unwrap.

**Comment by Rismosch** [comment]
Oh I see. I somehow completely missed that `GraphicsPipeline::vertex_input_state()` can simply take a `VertexInputState`. Now this simplifies my code dramatically. This works for me:
```
#[derive(BufferContents, Default)]
#[repr(C)]
pub struct Vertex3d {
    pub position: [f32; 3],
    pub color: [f32; 3],
}

impl Vertex3d {
    pub fn input_state() -> VertexInputState {
        let bindings = [(
            0u32,
            VertexInputBindingDescription {
                stride: 24,
                input_rate: VertexInputRate::Vertex,
            },
        )];

        let attributes = [
            (
                0,
                VertexInputAttributeDescription {
                    binding: 0,
                    format: Format::R32G32B32_SFLOAT,
                    offset: 0,
                },
            ),
            (
                1,
                VertexInputAttributeDescription {
                    binding: 0,
                    format: Format::R32G32B32_SFLOAT,
                    offset: 12,
                },
            ),
        ];

        VertexInputState::new()
            .bindings(bindings)
            .attributes(attributes)
    }
}
```

As I said in the very beginning this is all fairly new to me 😅

I apologize for the confusion and thank you very much for your quick and helpful responses!
