### ISSUE TITLE
SurfaceApi usage is unclear

### ISSUE THREAD

**Issue by Stargateur** [vulkano-rs/vulkano#2337]
[`Surface::from_handle`](https://docs.rs/vulkano/latest/vulkano/swapchain/struct.Surface.html#method.from_handle) now take a `SurfaceApi` but it's unclear how to dynamicly determine this information, specially there is no "Unknown" or "Generic" variant. The documentation is currently empty about `SurfaceApi`. Is this important ? Can I fill a dummy value ?

**Comment by Rua** [comment]
You need to pass the windowing API that was used to create the surface handle. Each of them corresponds to one of the constructor functions of `Surface`. For example, if the handle was created by calling `vkCreateWin32SurfaceKHR` or Vulkano's equivalent `Surface::from_win32`, then you pass `SurfaceApi::Win32`.
