### ISSUE TITLE
uniform buffer Data giving type of unknown and not having allocate_sized() (I can't work out how to title this better!)

### ISSUE THREAD

**Issue by coolcatcoder** [vulkano-rs/vulkano#2339]
*   Version of vulkano: 0.33.0
*   OS: Windows 10
*   GPU (the selected PhysicalDevice): NVIDIA GeForce GTX 750 Ti
*   GPU Driver: (I know this will sound stupid, but I can't find my nvidia login, and as such I'm not allowed to check my driver. Thanks nvidia!)
*   Upload of a reasonably minimal complete `main.rs` file that demonstrates the issue: Here is my repository: [https://github.com/coolcatcoder/vulkan_fun](https://github.com/coolcatcoder/vulkan_fun) It isn't 100% minimal, however I've only just progressed past the 1st triangle tutorial, so it should still be somewhat minimal.

Trying to implement some basic 2d rendering using uniform buffers to hold the aspect ratio. For some reason on line 356 I'm getting an error that allocate_sized() doesn't exist. However I believe the issue is actually more likely to be something to do with line 352 as uniform data has a type of unknown which surely can't be good...

**Comment by Rua** [comment]
`allocate_sized` is a method of the `SubbufferAllocator` type, but you're calling it on the `vertex_shader::Data` type. You need to create a `SubbufferAllocator` first.

**Comment by coolcatcoder** [comment]
Ah thanks!
