### ISSUE TITLE
Docs and Examples: RecordingCommandBuffer

### ISSUE THREAD

**Issue by agreyyy** [vulkano-rs/vulkano#2457]
# Issue 

vulkano 0.34.1.
Issue is not OS or GPU specific so, I will leave it blank. I am new to vulkano and reading though the 1.3 dynamic rendering and non-dynamic rendering triangle examples. In line 604 in the triangle example and line 601 in the 1.3 triangle example, a type called RecordingCommandBuffer is used, however that struct does not exist inside docs.rs of the crate, instead exists the AutoCommandsBufferBuilder::primary and AutoCommandsBufferBuilder::secondary method which from reading issues I know you wanted to change to the RecordingCommandBuffer (just renaming if I understood correctly). Can you please fix these examples with the correct code, or update the docs and crate to have the RecordingCommandBuffer types exist. Thank you. I am still trying to compile the triangles example, but now with the AutoCommandsBufferBuilder, can send my code in when done if you choose to change the examples instead of changing the docs/crate.

**Comment by agreyyy** [comment]
Also, can there please be a little note in the vulkano book`s 7.1 *Window Creation* chapter talking about the "rwh" feature flage of winit, since that can stop the example in the book from compiling due to the HasRawWindowHandle trait not being satisfied by Winit::EventLoop due to RawWindowHandle being different compared to vulkano`s.

**Comment by Rua** [comment]
The examples are correct. These types were added since the last release of Vulkano and therefore don't appear in the documentation yet.
