### ISSUE TITLE
How/when are underlying Vulkan objects destroyed?

### ISSUE THREAD

**Issue by johan-overbye** [vulkano-rs/vulkano#2458]
Say for example there are no more app-side references to my `vulkano::device::Device`, but I hold on to a `vulkano::buffer::Buffer` reference. Is it correct to assume that the `VkDevice` is still alive because the `Buffer` has an `Arc<Device>` somewhere?

If so, is there an idiomatic way to at least assert that my device is destroyed when I expect it to be? I guess I could `try_unwrap` the `Arc<Device>` maybe?

**Comment by Rua** [comment]
Yes, any object that belongs to `Device` will hold a reference to it and keep it alive. Using `try_unwrap` will work.

**Comment by johan-overbye** [comment]
Thanks!
