### ISSUE TITLE
Vulkano Needs `MutableDescriptorSet`

### ISSUE THREAD

**Issue by joshua-holmes** [vulkano-rs/vulkano#2464]
*   Version of vulkano: 0.34.1
*   OS: N/A
*   GPU (the selected PhysicalDevice): N/A
*   GPU Driver: N/A
*   Upload of a reasonably minimal complete `main.rs` file that demonstrates the issue: N/A

# Issue

The `PersistentDescriptorSet` is designed to be immutable (the `update` method is private), which works great if I don't want to update my descriptor set. However, I do, and using `UnsafeDescriptorSet` by itself doesn't work because, unlike with `PersistentDescriptorSet`, I can't bind `UnsafeDescriptorSet` using the `AutoCommandBufferBuilder::bind_descriptor_sets` method, because neither `UnsafeDescriptorSet` nor `Vec<UnsafeDescriptorSet>` implements `DescriptorSetsCollection` trait.

Are there plans to add a `MutableDescriptorSet` struct that implements `DescriptorSetsCollection`, similar to `PersistentDescriptorSet`, but with a public `update` method? If not, can there be plans to do so? I would be happy to implement it and make a PR, if that's helpful. Thanks!

**Comment by Rua** [comment]
This was added by #2404 and will be part of the next Vulkano release, 0.35.

**Comment by joshua-holmes** [comment]
Oh awesome, looking forward to it! Thanks for the response!
