### ISSUE TITLE
Examples Fail to Build Outside of the Vulkano Project

### ISSUE THREAD

**Issue by KalevGonvick** [vulkano-rs/vulkano#2472]
*   Version of vulkano: 0.34.1
*   OS: Win10
*   GPU: 3080
*   GPU Driver: 551.52

# Issue

Taking any example from 0.34.1 Vulcano into an isolated project will not compile because of missing dependencies. Specifically with **_RecordingCommandBuffer_** and **_CommandBufferBeginInfo_**. I tested **_triangle_** and **_basic-compute-shader_**, but I assume any example that uses these dependencies will fail.

Building and running the examples _within_ the Vulkano project works correctly. The issue only happens when you try to use the same structs in another project using Vulkano as a dependency. Also, going back to version 0.33.0 of Vulkano the example code has no issues building and running.

**Comment by Rua** [comment]
`RecordingCommandBuffer` and `CommandBufferBeginInfo` are not part of Vulkano 0.34.1. They are only in the unstable version that has not been released yet. You need to use the examples from the last release.

**Comment by KalevGonvick** [comment]
Ah, ok thanks for the quick response! I will stick with the last release version.
