### ISSUE TITLE
Example for resizing the window

### ISSUE THREAD

**Issue by dylanede** [vulkano-rs/vulkano#248]
Currently I'm unsure how to recreate the swapchain correctly when the window is resized. I tried dropping the old one (including images) and creating a new one, but vulkano panics complaining that the surface still has an existing swapchain. An example showing how to do this properly would be great.

**Comment by tomaka** [comment]
> I tried dropping the old one (including images) and creating a new one, but vulkano panics complaining that the surface still has an existing swapchain.

It probably means that the old images are still stored somewhere, as they hold an Arc to the swapchain. If not, then it's a bug in vulkano.

The "proper" method, though, is to pass the old swapchain as the last parameter when you create the new swapchain. This will still invalidate the old swapchain and images (trying to use them will result in a panic).

I have found out in my project that this aspect is tedious to handle properly. If we just add swapchain recreation in the triangle example, then I think it will not help much as you will face different problems in your real code. In my opinion what vulkano lacks is a real-world complex example.

**Comment by dylanede** [comment]
Yeah, passing in the old swapchain as the last parameter when constructing the new one fixed it for me, however I wasn't keeping any other explicit references to the swapchain images before. Would they be referenced by the submissions list, perhaps, and that was keeping them alive?

**Comment by tomaka** [comment]
> Would they be referenced by the submissions list, perhaps, and that was keeping them alive?

Yes, probably.
