### ISSUE TITLE
Replaying trace of triangle example doesn't display triangle.

### ISSUE THREAD

**Issue by schwa423** [vulkano-rs/vulkano#261]
I'm new to Vulkan, so I'm not sure whether this is a Vulkano issue or a Lunarg SDK issue (feels like the latter, but I'm not experienced enough to prove it)...

When I do the following:

``` sh
cd vulkano/examples
cargo build
cd target/debug
vktrace -p triangle -o triangle.vktrace 
# manually close example window before invoking replay.
vkreplay -t triangle.vktrace
```

... the replayed trace is a solid blue screen.  No red triangle is drawn.  

After hacking `triangle.rs` to use a different clear color each frame, the replay also shows a different color each frame, but still no red triangle.  

(I did this because I was suspicious that the trace was corrupted, and was successfully replaying only the first buffer clear, but nothing afterward).

BTW, this is on Ubuntu 16.04 with a GeForce 1060 and NVIDIA 367.44 drivers.

**Comment by tomaka** [comment]
Uuuhhh I have no idea what could be wrong with either vktrace or vulkano.
