### ISSUE TITLE
Run rustfmt on the code

### ISSUE THREAD

**Issue by tomaka** [vulkano-rs/vulkano#266]
I just tried rustfmt again, and it looks like it produces much better code than before.
I guess it should be possible now to switch the coding style to this library.

This should be done once the `incoming` branch has been merged, otherwise it's going to be a very painful rebase.

**Comment by paulirotta** [comment]
A related practice: IntelliJ community edition (free) works nicely when you define a macro such as CTRL S to run rustfmt before save

**Comment by tyoc213** [comment]
I think this will cover also things like?? https://github.com/tomaka/vulkano/pull/426

**Comment by tomaka** [comment]
I guess so.

I'm also tempted to require PRs to conform to the coding style by adding `cargo fmt --all -- --write-mode=diff` to the travis script. I'm not sure how cumbersome this would be.

**Comment by tyoc213** [comment]
Well, I dont think it takes a lot, if it is easy to setup, you will only need to add maybe an extra contributing file or something to make the note.

**Comment by Rua** [comment]
Rustfmt now regularly gets run on Vulkano, so I'm closing this.
