### ISSUE TITLE
Allow for using a system-installed version of glslang

### ISSUE THREAD

**Issue by svenstaro** [vulkano-rs/vulkano#281]
I think it would make sense to provide a way to use a system-installed version of glslang.

**Comment by tomaka** [comment]
There was already a small discussion in #239 

> glslangValidator is supposed to be an implementation detail, so I'm not sure it's a good idea to try to pick the program from the PATH. For example it could be annoying if shaders compiled differently depending on whether or not you have glslangValidator in your PATH.

**Comment by rukai** [comment]
glsl-to-spirv is no more. https://github.com/vulkano-rs/vulkano/pull/947
