### ISSUE TITLE
Mention GPU boost in timestamp queries documentation

### ISSUE THREAD

**Issue by tomaka** [vulkano-rs/vulkano#293]
Once timestamp queries are implemented, mention this in the docs.

https://developer.nvidia.com/setstablepowerstateexe-%20disabling%20-gpu-boost-windows-10-getting-more-deterministic-timestamp-queries

**Comment by tomaka** [comment]
https://developer.android.com/about/versions/nougat/android-7.0.html#sustained_performance_api

**Comment by Rua** [comment]
#1542 now implements timestamp queries.
