### ISSUE TITLE
Clearing only depth buffer in renderpass causes a crash

### ISSUE THREAD

**Issue by wjvds** [vulkano-rs/vulkano#319]
When I modify the teapot example to load instead of clear the color buffer (changed version: https://gist.github.com/wjvds/6cef931c305b9922a34d0b21d17d5c37, changes on lines 105 and 181), the program will hang while increasing the memory usage until it runs out when creating the command buffers. I am not sure if I am doing something wrong or if this is a bug.

**Comment by tomaka** [comment]
I noticed similar problems in the past, which I attributed to driver bugs.

However the current implementation is not very clean when it comes to command buffers. We'll need to see if it reproduces on the `incoming` once it's finished.

**Comment by rukai** [comment]
Using `Load` there is not valid, as the framebuffer is not initialized. Current vulkano picks up on that and gives the following error
```thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: AccessError { error: ImageNotInitialized { requested: PresentSrc }, command_name: "vkCmdBeginRenderPass", command_param: "attachment 0", command_offset: 0 }```
