### ISSUE TITLE
Skipping uniform binding indices causes crash

### ISSUE THREAD

**Issue by wjvds** [vulkano-rs/vulkano#326]
When I change line 20 of the teapot_vs.glsl shader to `layout(set = 0, binding = 1) uniform Data {`, or create any other shader with multiple uniform bindings where they are not strictly `0,1,2,3, ...` the program crashes when it creates the GraphicsPipeline object without causing a panic or getting a GraphicsPipelineCreationError result (so I assume something goes wrong in C code). I am not familiar enough with vulkan's internals to understand what is going on here, but I would expect that either this is possible (I don't see anything in the GLSL spec that disallows this) or to see a GraphicsPipelineCreationError returned either here, or a failure when vulkano-shaders parses the SPIR-V.

**Comment by tomaka** [comment]
Yes unfortunately for now vulkano doesn't check this. This is yet to be implemented.

**Comment by Rua** [comment]
This is probably fixed nowadays.
