### ISSUE TITLE
Reference implementation for Layer-activation does not compile

### ISSUE THREAD

**Issue by minecrawler** [vulkano-rs/vulkano#336]
When using the [reference code](https://docs.rs/vulkano/0.3.1/vulkano/instance/struct.Instance.html#layers) the following way, the compiler doesn't let me compile the code. `app_nfo` and `extensions` are defined before and work as expected, when the third parameter is set to `None`.

```rust
// ...

let layers_use = instance::layers_list()?.map(|l| l.name());
let inst = Instance::new(Some(&app_nfo), &extensions, layers_use)?;
```

I actually get two independent compiler errors. The first is that `vulkano::instance::layers` is private, hence I cannot even implement `From` for my error handling (so the `?` operator does not work and I had to replace it). The second one is:

```
error[E0271]: type mismatch resolving `<[closure@src/renderer/vulkan__new.rs:55:45: 55:57] as std::ops::FnOnce<(vulkano::instance::LayerProperties,)>>::Output == &&str`
  --> src/renderer/vulkan__new.rs:57:20
   |
57 |             inst = Instance::new(Some(&app_nfo), &extensions, layers_use)?;
   |                    ^^^^^^^^^^^^^ expected str, found &str
   |
   = note: expected type `&str`
   = note:    found type `&&str`
   = note: required because of the requirements on the impl of `std::iter::Iterator` for `std::iter::Map<vulkano::instance::LayersIterator, [closure@src/renderer/vulkan__new.rs:55:45: 55:57]>`
   = note: required by `vulkano::instance::Instance::new`
```

Version info:
rustc: rustc 1.13.0
cargo: cargo 0.13.0 (built 2016-12-10)
Installed from Portage, running on Gentoo Linux

**Comment by tomaka** [comment]
> The first is that vulkano::instance::layers is private

I suppose you mean `LayersListError`. That should be easy to fix.

> The second one is:

Yes unfortunately it's a known problem. The example you linked indicates it:

> // FIXME: this example doesn't run because of ownership problems ; Instance::new() needs a tweak

The problem is that in order to make `Instance::new` easy to use, I made it so that the third parameter is an iterator that produces `&&str`.

Which means that for now you need to build a `Vec<String>` from the list of instances you want, then a `Vec<&str>` that references the first `Vec`, and then you can pass `second_vec.iter()`.

**Comment by minecrawler** [comment]
> I suppose you mean `LayersListError`.

Yes, exactly!

> The example you linked indicates it:

Yeah, I was a little blind there (ups), but still it's a good thing that there's an issue for it, now :) I will try to make a PR, but since I am still quite new to Rust itself, I cannot promise anything...

**Comment by dannyfritz** [comment]
This took me quiet a while to get to something that compiles.

```rust
let layers: Vec<String> = instance::layers_list()
                .unwrap()
                .map(|l| String::from(l.name()))
                .collect();
            let layers: Vec<&str> = layers.iter().map(|ln| ln.as_str()).collect();
            Instance::new(None, &extensions, layers.iter())
                .expect("failed to create Vulkan instance")
```

Is there a clearer way to write this?
