### ISSUE TITLE
Possible lenient extension managment

### ISSUE THREAD

**Issue by Yamakaky** [vulkano-rs/vulkano#368]
In https://github.com/Yamakaky/cendre, I don't announce that I support `VK_KHR_surface` and `VK_KHR_surface`, but the `triangle` example assumes they are supported anyway with calls to the functions these extensions add. I would expect an error from `vulkano`.

**Comment by tomaka** [comment]
Vulkano is supposed to check that the extensions are enabled when creating a surface. The example assumes that the extensions are supported for the sake the simplicity.

**Comment by tomaka** [comment]
It doesn't check for VK_KHR_surface because it's supposed to be a prerequirety of the other VK_KHR_*_surface extension. But I guess that adding a debut assert wouldn't hurt.

**Comment by Yamakaky** [comment]
Sorry, I misstyped: I meant `VK_KHR_swapchain` and `VK_KHR_surface`. For the second one it's not really a problem since vulkano fails if `VK_KHR_xlib_surface` or such are not present. `swapchain` is more problematic though.

**Comment by Yamakaky** [comment]
Confirmation: by enabling the `VK_LAYER_LUNARG_standard_validation`, I get the following error:
```
DL(ERROR): object: 0x0 type: 2 location: 4210 msgCode: 5: While calling vkCreateDevice(), requesting feature #0 in VkPhysicalDeviceFeaturesstruct, which is not available on this device.
DL(ERROR): object: 0x0 type: 2 location: 4221 msgCode: 5: You requested features that are unavailable on this device. You should first query feature availability by calling vkGetPhysicalDeviceFeatures().
```

**Comment by tomaka** [comment]
That's unrelated. Vulkano automatically requests the robust_buffer_access feature because the specs say it is mandatory for implementations to support it.

**Comment by Yamakaky** [comment]
Oh, right ^^
