### ISSUE TITLE
Handle vkGetPhysicalDeviceSurfaceFormatsKHR returning VK_FORMAT_UNDEFINED

### ISSUE THREAD

**Issue by tomaka** [vulkano-rs/vulkano#371]
See https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VkColorSpaceKHR:

> If pSurfaceFormats includes just one entry, whose value for format is VK_FORMAT_UNDEFINED, surface has no preferred format. In this case, the application can use any valid VkFormat value.

**Comment by Rua** [comment]
What is the status on this? Are there any ideas on how to implement it?

**Comment by tomaka** [comment]
I haven't worked on this or am aware of anyone who worked on this.
This requires a change in the APIs of Surface and Swapchain.

**Comment by Rua** [comment]
It seems that this clause is no longer in the Vulkan spec, so I'm closing this.
