### ISSUE TITLE
Expose the MoltenVK ActivateMoltenVKLicenseMVK function somewhere

### ISSUE THREAD

**Issue by tomaka** [vulkano-rs/vulkano#490]

**Comment by ibarrajo** [comment]
Hey @tomaka I just want to thank you for the work you've put into this!

I've barely started playing with Rust and Vulkano, but with a mac, you're a life saver =]

**Comment by casey** [comment]
I believe this can be closed, MoltenVK is now open source and doesn't need a license: https://www.anandtech.com/show/12465/khronos-group-extends-vulkan-portability-with-opensource
