### ISSUE TITLE
Consider google/shaderc for shader compilation.

### ISSUE THREAD

**Issue by dragostis** [vulkano-rs/vulkano#5]
Compiling `libshaderc` [google/shaderc](https://github.com/google/shaderc) might work for better integration.

**Comment by dragostis** [comment]
Oh, and about dynamic size stack-allocated arrays: can't you just have a max-sized [i32; 10] that you can allocate on the stack and used that? It doesn't matter how big it is since it's allocated on the stack.

**Comment by rukai** [comment]
Resolved by https://github.com/vulkano-rs/vulkano/pull/947
