### ISSUE TITLE
Add DynamicDescriptorSets

### ISSUE THREAD

**Issue by tomaka** [vulkano-rs/vulkano#512]
Could get a better name, but I couldn't find one.

The idea is that a `DynamicDescriptorSets` would allocate 3, 4, or more descriptor sets (in a lazy way) that all have the same layout.
At each frame you could then call `dyn_desc_sets.build(...)`, which would lock a descriptor set from that list and write the descriptors to it.
Once a descriptor set is no longer in use by the GPU, it would be returned to the list.

This would be appropriate for situations where you need to change the bound descriptor at each frame, and avoids having to perform a costly allocation every time.

**Comment by dylanede** [comment]
Sounds more like something that should have "pool" in the name, IMO.
