### ISSUE TITLE
Alternative API backend

### ISSUE THREAD

**Issue by kvark** [vulkano-rs/vulkano#525]
gfx-rs has a low-level layer that is being worked on. It's not exactly Vulkan, but could technically be wrapped into Vulkan API in order to provide a more portable solution (that runs on Metal/DX12) than the native Vulkan (see https://github.com/gfx-rs/gfx/issues/1226).

It would be interesting to explore an option to use gfx-rs coreLL with Vulkano as a front-end. I suspect this would require some changes in Vulkano to make sure the backend is swappable.

**Comment by tomaka** [comment]
Vulkano will probably only ever support Vulkan directly, but if gfx implements an FFI (as suggested in https://github.com/gfx-rs/gfx/issues/1226) then vulkano supporting it is just a matter of implementing #361.

**Comment by kvark** [comment]
@tomaka I believe it to be very important to call our portability functions *statically* as opposed to via function pointers (like a regular Vulkan loader exposes). We try very hard to make the most frequently used functions to have a little logic as possible, e.g. drawXXX in Metal/DX does nothing but calls the underlying draw function, so having them inlined could make a difference.

My original (old?) plan was to glue things together using a Vulkan binding generator. I haven't yet verified if this is the right way to go. Can you share your thoughts on how to get right and whether or not you consider this effort worth pursuing (statically dispatched portability calls)? Also, do any of the choices listed in https://github.com/gfx-rs/gfx/issues/2206#issuecomment-402582735 really affect anything on your side, if we are to use Vulkano together with the portability layer?

**Comment by tomaka** [comment]
> My original (old?) plan was to glue things together using a Vulkan binding generator.

It's kind of hard to be generic over both dynamic loading and static loading, but I agree that ideally vulkano should support the latter as well.

I don't really have a plan in mind for this though.

Right now vulkano [allows you to choose how to load the function pointers](https://docs.rs/vulkano/0.9.0/vulkano/instance/loader/index.html), but maybe we may wish to remove this? I'm not sure.

**Comment by Rua** [comment]
This probably will never happen, but Vulkano has since moved to using Ash as a backend.
