### ISSUE TITLE
QueueIter returned by `Device::new` is confusing

### ISSUE THREAD

**Issue by zimond** [vulkano-rs/vulkano#559]
Currently `Device::new` returns a `QueueIter` which is documented as _the queues produces when creating a device_. However it seems that the iterator is just the first queue in the queue family used to create the device. Is it intended to be this?

**Comment by tomaka** [comment]
I'm not sure where the confusion is. Creating a device generates queues, and this iterator returns them.
Right now all the examples only use one queue, so obviously the iterator only returns one element.

**Comment by daiheitan** [comment]
Currently `vk::DeviceQueueCreateInfo`'s `queueCount` attribute is `priorities.len()`.

`priorities` is defined only once for each queue family, which means the `queueCount` for every queue family is only one. How could I ask for multiple queues for every device created?

Maybe I misunderstood something?

**Comment by daiheitan** [comment]
So I think the `queue_families` param of `Device::new` should be having type of `I: IntoIterator<Item = (QueueFamily<'a>, Vec<f32>)>` ?

**Comment by tomaka** [comment]
If you want multiple queues from the same family, you're supposed to pass the same family to `Device::new()` multiple times.

Eg. `Device::new(..., vec![(my_family, 1.0), (my_family, 0.5)]);`

**Comment by daiheitan** [comment]
Wouldn't passing the same family multiple times return the same queue (the first queue in the family) multiple times? I thought that `vkCreateDevice` returns different queues from a family, each assigned with a `priority`

**Comment by daiheitan** [comment]
BTW it seems to be not recommended to feed multiple vkDeviceQueueCreateInfo with the same queue family.

https://www.reddit.com/r/vulkan/comments/4nb5jx/why_does_initialization_fail_here/?st=j4fbt66d&sh=bb671eab

**Comment by tomaka** [comment]
Maybe what's confusing is that vulkano's API is higher-level than the raw vkCreateDevice: https://github.com/tomaka/vulkano/blob/24fe5b18975c401d70f1aecf444317fc49a5c2f7/vulkano/src/device.rs#L205-L243

It was designed this way so that the elements of the iterator returned by `Device::new` match the elements of the iterator passed to the function.

**Comment by daiheitan** [comment]
oh, I finally understand the code here.... Maybe some documentation is needed here. Thanks for your quick explanation.
