### ISSUE TITLE
Put NonZero around Vulkan objects once stable

### ISSUE THREAD

**Issue by tomaka** [vulkano-rs/vulkano#584]
Since Vulkan object never have the value 0, we can put `NonZero` around them once it is stable.

Refs:
https://github.com/rust-lang/rust/issues/27730
https://doc.rust-lang.org/core/nonzero/struct.NonZero.html

**Comment by tomaka** [comment]
I just realized that this wouldn't be *that* useful, since Vulkan objects are usually in `Arc`s. But, well, why not do it anyway.

**Comment by Rua** [comment]
The migration to Ash made this irrelevant.
