### ISSUE TITLE
Consider an `Aligned` wrapper around types in generated struct definitions

### ISSUE THREAD

**Issue by tomaka** [vulkano-rs/vulkano#6]
Example GLSL code:

``` glsl
struct Foo {
    vec3 a;
    f32 b;
}
```

This is the Rust code that is currently generated:

``` rust
#[repr(C)]
#[derive(Default)]
struct Foo  {
    a: [f32; 3],
    _dummy: [u8; 4],
    b: f32,
}
```

But this could be an alternative solution:

``` rust
#[repr(C)]
struct Foo  {
    a: Aligned<[f32; 3], Align16>,
    b: f32,
}
```

Both have their advantages and drawbacks.

**Comment by Rua** [comment]
This solution unfortunately doesn't play nice with Bytemuck, so it's unlikely to be implemented.
