### ISSUE TITLE
Support for multiple vertex buffer inputs

### ISSUE THREAD

**Issue by JohnDoneth** [vulkano-rs/vulkano#629]
Currently, the only choice to pass multiple vertex inputs such as `position`, `normal`, and `texcoord`'s to a shader _that I've discovered_ (Maybe I've missed something in the docs) is to interleave the data within a single vertex buffer and pass that to a shader, while this may be beneficial to cache locality down the line. It's very difficult for beginners with this library like myself to wrap my head around not being able to have separate buffers for each vertex input, which I had gotten accustomed to during OpenGL programming.

I propose some sort of `MultiVertexBufferDefinition` where we can pass _n_ buffers to be used for individual shader inputs whereas we currently have `SingleBufferDefinition` and `TwoBufferDefinition` which is currently unstable and contains `unimplemented!` methods.

**Comment by jeffw387** [comment]
Would this sort of thing require a macro to solve? I'm just a hobbyist in Rust but that's what came to mind here.
