### ISSUE TITLE
Add API to directly create CpuAccessibleBuffer from array/vector

### ISSUE THREAD

**Issue by zimond** [vulkano-rs/vulkano#633]
I don't know if I understood it correctly, currently it seems that if I want to create a buffer from an array, a convert to `Iter` and calling`::from_iter` is the only way. This could be a drawback of performance. Could we use `std::ptr::copy_nonoverlapping` to directly copy the memory without iterating over the array?

**Comment by tomaka** [comment]
You can do that by building the buffer with the `uninitialized_array` method.

However you are presuming that iterating over the array will be slower than using `copy_nonoverlapping`, and I don't think it's the case.

**Comment by daiheitan** [comment]
So I changed my buffer creation code from `Vec::into_iter` + `::from_iter` to `uninitialized_array` + `slice::copy_from_slice` (which uses memcpy internally).

The initialization cost goes from 1380303 ns to 295480 ns. The later seems to be indeed faster.

**Comment by tomaka** [comment]
Is that in release? Unless your buffer is huge, the absolute values look slow.

**Comment by daiheitan** [comment]
I am creating a 800 * 800 * 4 staging buffer to upload an image to GPU. So it could take sometime.
