### ISSUE TITLE
Add support for VK_KHR_dedicated_allocation

### ISSUE THREAD

**Issue by tomaka** [vulkano-rs/vulkano#640]
Has just been made "stable" in Vulkan 1.0.54.

**Comment by tomaka** [comment]
Note that nVidia (who built the extension and are probably the only ones who support it) recommend using dedicated allocations for "render targets" and "very large buffers/images (dozens of MB)".

This is probably what vulkano is going to do by default.

**Comment by tomaka** [comment]
Although a bit off-topic, another thing to discuss is how to handle "pure-win" extensions.
What is mean is that there's no reason not to enable `khr_maintenance1`, `khr_get_memory_requirements2` and `khr_dedicated_allocations` when they are available.
The fact that extensions must be explicitly enabled in Vulkan is to protect application writers from accidentally depend on features from extensions that may not be available everywhere.

**Comment by nicokoch** [comment]
While were discussing extensions...something I also noticed:
How do we deal with dependencies between extensions?
For example - once we support it - what happens if the user enables `VK_KHR_incremental_present`without enabling `VK_KHR_swapchain`?

**Comment by GuildMasterInfinite** [comment]
Perhaps it would be better if we introduce a new `Extension` type? The already supported extensions could be static constants of the `Extension` type. Then we could easily add support for dependencies, something like:

```rust
struct Extension {
  name: &'static str,
  dependencies: Option<&'static [&'static Extension]>
}
```

And then:

```rust
static const VK_KHR_swapchain = Extension {
  name: "VK_KHR_swapchain",
  dependencies: None
};

static const VK_KHR_incremental_present = Extension {
  name: "VK_KHR_incremental_present",
  dependencies: Some(&[&VK_KHR_swapchain])
};
```
