### ISSUE TITLE
Vulkan bools should maybe not map to Rust bool

### ISSUE THREAD

**Issue by tomaka** [vulkano-rs/vulkano#66]
Rust supposes that bools always contain either 0 or 1. A GPU might not write the value `1` when you write `true`, although this needs to be checked from the specs.

**Comment by branan** [comment]
From a quick check of the current spec version, I believe we can be confident in `Bool32` values being the same as Rust `bool` values:

````
VK_TRUE represents a boolean True (integer 1) value, and VK_FALSE a boolean False (integer 0) value.

All values returned from a Vulkan implementation in a VkBool32 will be either VK_TRUE or VK_FALSE.

Applications must not pass any other values than VK_TRUE or VK_FALSE into a Vulkan implementation where a VkBool32 is expected.
```

**Comment by tomaka** [comment]
That's not the same as a bool on the GPU though. I think there's another section that talks about data types on the GPU.

**Comment by Rua** [comment]
Based on #1331, the shader compiler never generates code with `OpTypeBool` in descriptor set bindings anyway. The type *can* be used in specialization constants, but Vulkano-shaders has extra code to handle it there.
