### ISSUE TITLE
Keep track of the current descriptor set, index buffer, and vertex buffers in the sync layer

### ISSUE THREAD

**Issue by tomaka** [vulkano-rs/vulkano#670]
With Vulkan you can do for example: `vkCmdBeginRenderPass`, `vkCmdBindIndexBuffer`, `vkCmdEndRenderPass`, `vkCmdFillBuffer`, `vkCmdBeginRenderPass`, `vkCmdDrawIndexed`, `vkCmdEndRenderPass`.

Assuming that the buffer of `vkCmdFillBuffer` is the same as the one of `vkCmdBindIndexBuffer`, vulkano isn't able to understand that the index buffer is going to be used by `vkCmdDrawIndexed` and will not insert a pipeline barrier. Instead it will add a barrier between `vkCmdBindIndexBuffer` and `vkCmdFillBuffer`, which is useless.

**Comment by tomaka** [comment]
Done in #685 #581 #687 
Will merge when #687 is tested.

**Comment by cmr** [comment]
https://github.com/vulkano-rs/vulkano/pull/687 was merged.
