### ISSUE TITLE
How could I create image with a standard pool replacement?

### ISSUE THREAD

**Issue by zimond** [vulkano-rs/vulkano#673]
Currently it seems that there's no way to create a resource with a memory pool other than the device's standard pool

**Comment by daiheitan** [comment]
related： #14

**Comment by daiheitan** [comment]
Any updates or ideas? @tomaka

**Comment by tomaka** [comment]
The methods to do that are missing, but I marked this issue as easy because all the necessary parts are always there.

**Comment by Rua** [comment]
The memory allocation has been completely overhauled in 0.32, and this should now be possible.
