### ISSUE TITLE
Add support for VK_EXT_depth_range_unrestricted

### ISSUE THREAD

**Issue by tomaka** [vulkano-rs/vulkano#675]

**Comment by tyoc213** [comment]
It is a device extension https://github.com/KhronosGroup/Vulkan-Docs/commit/80af5ce5a24c6801a93efc8c0259436a1a61f45a#diff-27cd4f747a67b2c626c89b762ad031cd

And I guess should be added here https://github.com/tomaka/vulkano/blob/4d28294b55797d1b779e3059345fdcb7d7370b3e/vulkano/src/instance/extensions.rs#L352 what more should be done?

**Comment by Rua** [comment]
This is now implemented.
