### ISSUE TITLE
Add support for VK_KHR_external_memory for inter-device memory access (depends on VK_KHR_external_memory_capabilities)

### ISSUE THREAD

**Issue by nanokatze** [vulkano-rs/vulkano#701]
https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VK_KHR_external_memory

> An application may wish to reference device memory in **multiple Vulkan logical devices** or instances, in multiple processes, and/or in multiple APIs. This extension enables an application to export non-Vulkan handles from Vulkan memory objects such that the underlying resources can be referenced outside the scope of the Vulkan logical device that created them.

The **different logical devices** part makes it possible for Vulkano users to implement multi-device renders etc without performing on-CPU inter-device buffer copies which are only suitable in very few cases and impose high load on CPU.

**Comment by fst3a** [comment]
I think this should be low priority

**Comment by gurchetansingh** [comment]
For those still interested, here's the first stab at this:

https://github.com/vulkano-rs/vulkano/pull/1467

**Comment by Rua** [comment]
This is now more thoroughly implemented, although there's still room for adding more platforms and memory types.
