### ISSUE TITLE
Changes after impl Trait type alias become stable

### ISSUE THREAD

**Issue by tomaka** [vulkano-rs/vulkano#709]
RFC: https://github.com/rust-lang/rfcs/pull/2071

After this RFC gets merged, it will be possible for vulkano users to store strongly-typed structs such as the `GraphicsPipeline<_, _, _>` (as a `impl GraphicsPipelineAbstract`), the `PersistentDescriptorSet<_, _>` (as a `DescriptorSet`) or the struct generated by `single_pass_render_pass!` (as a `impl RenderPassAbstract`).

Therefore we will be able to add associated types and generics to these traits, which allows lots of nice changes:

- `GraphicsPipelineAbstract` will take an associated type `VertexDefinition`, which will finally make strong typing possible for vertex sources.
- Instead of implementing `RenderPass` and `PipelineLayout` directly on the pipeline objects and the framebuffer, add new traits `AsRenderPass` and `AsPipelineLayout` and implement them instead.
- The various `lock()`/`unlock()` functions can be replaced with a proper `Lock` associated type. Also requires the HKTs RFC that was recently approved (which I can't find the link for).

**Comment by MaloJaffre** [comment]
The HKTs RFC is rust-lang/rfcs#1598 which will be merged soon (FCP ended).

**Comment by Rua** [comment]
It seems that Vulkano's designed has changed enough in the meantime that this issue doesn't really make sense anymore.
