### ISSUE TITLE
DynamicState question

### ISSUE THREAD

**Issue by nanokatze** [vulkano-rs/vulkano#710]
How would use of Vecs in DynamicState problem be solved?  Say we have 1000 draw calls, each with DynamicState, it would require 1000 expensive `clone()s` of at least single Vec.  I guess reexporting SmallVec is not very desirable.  I failed to find a way (other than not using DynamicState completely) to avoid clones.

**Comment by fst3a** [comment]
@tomaka do you think passing DynamicState by reference would be good solution?

**Comment by tomaka** [comment]
It wouldn't be a definitive solution but it's a start.

**Comment by Rua** [comment]
`DynamicState` no longer exists, instead each state is set separately with a Vulkan command as in the C API.
