### ISSUE TITLE
Question: create a vulkano organization?

### ISSUE THREAD

**Issue by tomaka** [vulkano-rs/vulkano#714]
People who read this issue: do you think I should create a `vulkano-rs` organization (`vulkano` alone is already taken) and move this repository to `vulkano-rs/vulkano`? What's your opinion?

The repository `vulkano-www` would obviously also be moved there.

**Comment by nicokoch** [comment]
What is the benefit of having a repo reside inside an organization?
This is not meant to be a tacky response, I seriously don't know.

**Comment by tomaka** [comment]
I guess it makes it a bit more "professional-looking"?

**Comment by binary132** [comment]
I agree that having it within an org makes it it more "professional" and seem less like a "personal project."  Plus then you can contribute from a personal fork.

**Comment by fst3a** [comment]
One of the benefits of having separate organization would be that it could be used as collection of vulkano-related libraries (such as, say some "vulkano-external-shaders") aswell.

**Comment by c4augustus** [comment]
There are many upsides and no downsides, really. You'd be the administrator of the organization and still the maintainer of the repos. It's only that the repos would no longer be prefixed by your name, though the history and commits are still almost all you. As fst3a pointed out, It literally is the only way in github to "organize" related repos together.

**Comment by devnought** [comment]
I think you should go forward with it!

**Comment by nicokoch** [comment]
Agreed, seems like a good idea

**Comment by tomaka** [comment]
Well, it's done!
