### ISSUE TITLE
implement MutableImage

### ISSUE THREAD

**Issue by rukai** [vulkano-rs/vulkano#715]
I am currently using ImmutableImage as if it were mutable. (Updating a text cache every frame)
It appears vulkano now has a check for this I am getting:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: AccessError(ExclusiveDenied)', 
```
On this line:
```rust
        let future = previous_frame_end.join(acquire_future)
            .then_execute(queue.clone(), command_buffer).unwrap()
            .then_swapchain_present(queue.clone(), swapchain.clone(), image_num)
            .then_signal_fence_and_flush().unwrap();
```

I guess this means vulkano needs a MutableImage.

**Comment by tomaka** [comment]
There's `StorageImage` for that.
However vulkano also needs an image type for when you want to update an image each frame, and that's not implemented yet.
