### ISSUE TITLE
Create a logo

### ISSUE THREAD

**Issue by tomaka** [vulkano-rs/vulkano#717]
A logo would be nice for the profile page of https://github.com/vulkano-rs, and to put on vulkano.rs

**Comment by derekdreery** [comment]
![vulkano](https://user-images.githubusercontent.com/1392222/28997211-de717c6a-7a06-11e7-8745-d8426637202d.png)

Something like this? I can't post the original image here sorry (svg not allowed) :(

**Comment by derekdreery** [comment]
Or maybe something more sylized like https://previews.123rf.com/images/blacklighttrace/blacklighttrace1409/blacklighttrace140900086/32146274-stylized-illustration-of-a-volcanic-eruption-with-black-clouds-of-smoke-Stock-Vector.jpg

**Comment by HansEberhart** [comment]
![vulkano](https://user-images.githubusercontent.com/30523862/29021681-a5d43e54-7b66-11e7-8319-d86d1dade411.png)

How about this approach?
A material style icon to fit the time and a O which is "lit" (pun intended)

SVG is available and things (color, shape etc.) can be altered to fit your style.

Cheers!

**Comment by derekdreery** [comment]
That looks nice :)

**Comment by DaseinPhaos** [comment]
> A material style icon to fit the time and a O which is "lit"

I'd definitely +1 for this one! Yet for this project maybe something like a rusty O would be more appropriate?

**Comment by HansEberhart** [comment]
> I'd definitely +1 for this one! Yet for this project maybe something like a rusty O would be more appropriate?

> 

Okay, so what about those?

Can still do some changes. Critic is welcome!

![02](https://user-images.githubusercontent.com/30523862/29180752-4978ac7e-7de8-11e7-9e23-20838df1ed86.png)
![03](https://user-images.githubusercontent.com/30523862/29180760-508409be-7de8-11e7-87c5-fe210e02aea2.png)

Cheers!

**Comment by tomaka** [comment]
What about using [this one](https://user-images.githubusercontent.com/30523862/29021681-a5d43e54-7b66-11e7-8319-d86d1dade411.png) but replacing the O with something similar to [this](https://user-images.githubusercontent.com/30523862/29180752-4978ac7e-7de8-11e7-9e23-20838df1ed86.png)?

**Comment by HansEberhart** [comment]
Okay, so like this?

![04](https://user-images.githubusercontent.com/30523862/29223806-2d35b9e0-7ec8-11e7-9f2c-e1adce442cea.png)

The "rust" pattern doesn't look that crisp though, but rather well for the material design approach.

**Comment by derekdreery** [comment]
Maybe the shape of the cog, but the fill of the fire circle (maybe with some flames).

**Comment by HansEberhart** [comment]
Okay, so like this?

![04](https://user-images.githubusercontent.com/30523862/29223806-2d35b9e0-7ec8-11e7-9f2c-e1adce442cea.png)

The "rust" pattern doesn't look that crisp though, but rather well for the material design approach.

**Comment by tomaka** [comment]
I guess we can settler for https://user-images.githubusercontent.com/30523862/29021681-a5d43e54-7b66-11e7-8319-d86d1dade411.png ?

**Comment by BadFactor** [comment]
Of Course not, thats ugly one!

Can someone make a better one?



Gesendet von Mail<https://go.microsoft.com/fwlink/?LinkId=550986> für Windows 10

Von: tomaka<mailto:notifications@github.com>
Gesendet: Dienstag, 15. August 2017 17:43
An: vulkano-rs/vulkano<mailto:vulkano@noreply.github.com>
Cc: Subscribed<mailto:subscribed@noreply.github.com>
Betreff: Re: [vulkano-rs/vulkano] Create a logo (#717)


I guess we can settler for https://user-images.githubusercontent.com/30523862/29021681-a5d43e54-7b66-11e7-8319-d86d1dade411.png ?

**Comment by BadFactor** [comment]
I try to make a new one. It doesnt look right to me. I will post some different looking Logos, in the coming days! Hopefully u all will like it! My Plan is to First tage the Name as Logo and then i will post some non named Logos!, such as the above ones!
