### ISSUE TITLE
uniform sampler2D in uniform buffer object

### ISSUE THREAD

**Issue by SiebenCorgie** [vulkano-rs/vulkano#730]
Hi,

I want to store several textures in an uniform buffer object.
With normal `f32` values (model, view and projection matrix) I did a Struct `Main` like this:
```
pub struct Main {
    pub model : [[f32;4];4],
    pub view : [[f32;4];4],
    pub proj : [[f32;4];4],
}
```
And created a uniform set from this Struct which I can access in the shader like this:
```
layout(set = 0, binding = 0) uniform Data {
    mat4 model;
    mat4 view;
    mat4 proj;
} u_main;
```
However, I want to create a similar Struct for different textures which I want to pass to the shader. I am not sure how to store the images in the Struct definition. 
The documentation mentions a `Image` [trait](https://docs.rs/vulkano/0.5.6/vulkano/image/index.html), but I couldn't find it. I am also not sure if the `CpuBufferPoolSubbuffer` can create the buffer from an `Arc<Image>`.

The Image example uses a single uniform set for a single image. Would it be better to create a uniform set with several textures like:
```
    let set = Arc::new(vulkano::descriptor::descriptor_set::PersistentDescriptorSet::start(pipeline.clone(), 0)
        .add_sampled_image(t_albedo.clone(), sampler.clone()).unwrap()
        .add_sampled_image(t_normal.clone(), sampler.clone()).unwrap()
        .add_sampled_image(t_rough_met.clone(), sampler.clone()).unwrap()
        .build().unwrap()
    );
```
and access them like this?
```
layout(set = 0, binding = 0) uniform sampler2D t_albedo;
layout(set = 0, binding = 1) uniform sampler2D t_normal;
layout(set = 0, binding = 2) uniform sampler2D t_rough_met;
```

Thanks for any help!

-siebencorgie

**Comment by tomaka** [comment]
Hi,

You can't store images in a uniform buffer. It's not a feature that Vulkan or GLSL provide.

> The Image example uses a single uniform set for a single image. Would it be better to create a uniform set with several textures like:
> and access them like this?

Yes, that's what you're supposed to do.

**Comment by SiebenCorgie** [comment]
Okay, thanks for the clarification!
