### ISSUE TITLE
Bug in swapchain staleness?

### ISSUE THREAD

**Issue by lealanko** [vulkano-rs/vulkano#735]
Hi. This is just a remark from browsing the source.

I notice that `Swapchain::stale` is never set to `true`. The field comment suggests that it's supposed to be set when image acquisition from the old chain is made illegal by creating a new descendant chain. So I suppose the `false` in [swapchain.rs:314](https://github.com/vulkano-rs/vulkano/blob/a067f6e89dacef68e965428a388ba432943153fb/vulkano/src/swapchain/swapchain.rs#L314) ought to be `true`?

**Comment by tomaka** [comment]
Yes I think you're right.
We may also want to add return an error here is the value is already true.
