### ISSUE TITLE
The triangle example crashes with UnsupportedDimensions on MacOS 10.12 + MoltenVK

### ISSUE THREAD

**Issue by golddranks** [vulkano-rs/vulkano#738]
I'm using a 2017 MacBook Pro with Intel Iris Graphics 550 1536 MB and a 2560 x 1600 display.

The example builds successfully, and when I run it, it starts fine, printing some messages, including:
`[mvk-info] You require a license for the MoltenVK Vulkan Core feature set. Reverting to evaluation mode`

After that, it panics when creating a new `Swapchain`. The error is `UnsupportedDimensions`. Debug-printing the dimensions passed to the `new` method, the dimensions turn out to be `[2048, 1536]`. The device capabilities are 

```
Capabilities {
	min_image_count: 2,
	max_image_count: Some(2),
	current_extent: Some([1024, 768]),
	min_image_extent: [1024, 768],
	max_image_extent: [1024, 768],
	max_image_array_layers: 1, 
	supported_transforms: SupportedSurfaceTransforms {
		identity: true, 
		rotate90: false, 
		rotate180: false, 
		rotate270: false, 
		horizontal_mirror: false, 
		horizontal_mirror_rotate90: false, 
		horizontal_mirror_rotate180: false, 
		horizontal_mirror_rotate270: false, 
		inherit: false
	}, 
	current_transform: Identity, 
	supported_composite_alpha: SupportedCompositeAlpha {
		opaque: true, 
		pre_multiplied: true, 
		post_multiplied: true, 
		inherit: false
	}, 
	supported_usage_flags: ImageUsage {
		transfer_source: true, 
		transfer_destination: true, 
		sampled: true, 
		storage: true, 
		color_attachment: true, 
		depth_stencil_attachment: false, 
		transient_attachment: false, 
		input_attachment: false
	}, 
	supported_formats: [
		(B8G8R8A8Unorm, SrgbNonLinear),
		(B8G8R8A8Srgb, SrgbNonLinear),
		(R16G16B16A16Sfloat, SrgbNonLinear)
	], 
	present_modes: SupportedPresentModes {
		immediate: false, 
		mailbox: false, 
		fifo: true, 
		relaxed: false
	}
}
```

So it seems that it fails because of the max/min image extent checks.

I'm not knowledgeable enough to determine which of these values are wrong, but if I understand the meaning of `max/min_image_extent` capabilities right, it seems odd to me that the device supports only that. What should I do to fix this or to diagnose the problem further?

**Comment by tomaka** [comment]
Probably a HiDPI problem.

> I'm not knowledgeable enough to determine which of these values are wrong, but if I understand the meaning of max/min_image_extent capabilities right, it seems odd to me that the device supports only that. What should I do to fix this or to diagnose the problem further?

Presumably the device only supports 1024x768 when you create a swapchain on a window whose dimensions are 1024x768. If the window had other dimensions, it would report these dimensions.

**Comment by golddranks** [comment]
Ah, indeed, it sounds like a HiDPI issue; the resolution 2048x1536 is an exact double of 1024x768, and if I adjust the screen scaling, I can make it report things like 2048x1510 and 1024x755, 2040x1190 and 1020x595, which are again, exact doubles.

It gets the larger resolution from the created window and the smaller from the device.

**Comment by golddranks** [comment]
Looking at the API of winit and the source code of the example, I think that it's missing to multiply the resolution with the HiDPI factor. I'm on mobile so I can't test this right now, gonna check this out later.

**Comment by golddranks** [comment]
Oh, okay, so the winit API has both functions for returning pixels and returning points (2048 x 1536 and 1024 x 768 on my machine, respectively.) It seems then that the device capability info is talking about points instead of pixels in this case? Should it be this way? I'd imagine that something that talks about hardware-y things would rather talk in pixels than points, which I take to be a HiDPI abstraction that correspond to multiple hardware pixels.

**Comment by tomaka** [comment]
The problem is that we're talking about MoltenVK, so it's not really an officially-official thing endorsed by Vulkan.

Anyway, I think the best fix is simply to use the `current_extent` instead of the window size.

**Comment by nick70** [comment]
```
let caps = window.surface()
    .capabilities(physical)
    .expect("failure to get surface capabilities");
let mut dimensions = caps.current_extent.unwrap_or([1024, 768]);
```

**Comment by nick70** [comment]
and the application freezes after a while and when i start it up again it freezes immediately with a blue background and a red triangle

**Comment by rtsuk** [comment]
It would be good to get rid of that logging, but since it's in MoltenVK they would have to remove it.

Is there are reason to use a fence with a timeout of zero? If not, getting rid of the zero-timeout fences might quiet things down.

**Comment by tomaka** [comment]
A timeout of zero is used in order to check whether a fence is signalled without blocking the thread.
It's a valid thing to do (the specs even talk explicitly about that case if I remember correctly) and I'd even say that it is probably a very common thing to do.

**Comment by rtsuk** [comment]
Then I guess we should ask the MoltenVK guys to stop logging it all the time.

Unfortunately, fences are not yet supported on Fuchsia so their use generates a log of logging there, too.

**Comment by tomaka** [comment]
> Then I guess we should ask the MoltenVK guys to stop logging it all the time.

Most of the MoltenVK problems should be reported to the MoltenVK people. Unfortunately I'm not really the right person for that, as I don't have any Mac to try things.

**Comment by rtsuk** [comment]
I left a comment in their support forums. 

https://moltengl.com/forums/topic/moltenvk-error-vk_timeout-vulkan-fence-timeout-after-0-nanoseconds/

**Comment by lilianmoraru** [comment]
@tomaka The `UnsupportedDimensions` panic is not related to macOS or MoltenVK.
I am on Linux and I have the same issue.
I was never able to run any of the Vulkano examples(LunarG examples were ok) - I always had only an Intel processor with integrated graphics(because I don't game) - all the examples at one point started panicking because my drivers didn't satisfy the Vulkan API version requirement(before that change, the examples were panicking for some other reasons).
A week ago I got an nVidia card(newer Vulkan) and tried Vulkano examples again but these were panicking anyway, so I decided to ignore it.
Now I stumbled on this and realized that it is the HiDPI issue.
I am on Linux with a 4K monitor and I get this panic:
```
thread 'main' panicked at 'failed to create swapchain: UnsupportedDimensions', /checkout/src/libcore/result.rs:860
stack backtrace:
   0:     0x556be89db423 - std::sys::imp::backtrace::tracing::imp::unwind_backtrace::hcab99e0793da62c7
                               at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1:     0x556be89d8346 - std::sys_common::backtrace::_print::hbfe5b0c7e79c0711
                               at /checkout/src/libstd/sys_common/backtrace.rs:71
   2:     0x556be89dd4ca - std::panicking::default_hook::{{closure}}::h9ba2c6973907a2be
                               at /checkout/src/libstd/sys_common/backtrace.rs:60
                               at /checkout/src/libstd/panicking.rs:355
   3:     0x556be89dd0cb - std::panicking::default_hook::he4d55e2dd21c3cca
                               at /checkout/src/libstd/panicking.rs:371
   4:     0x556be89dd8db - std::panicking::rust_panic_with_hook::ha138c05cd33ad44d
                               at /checkout/src/libstd/panicking.rs:549
   5:     0x556be89dd7b4 - std::panicking::begin_panic::hcdbfa35c94142fa2
                               at /checkout/src/libstd/panicking.rs:511
   6:     0x556be89dd6e9 - std::panicking::begin_panic_fmt::hc09fe500d9b7be81
                               at /checkout/src/libstd/panicking.rs:495
   7:     0x556be89dd677 - rust_begin_unwind
                               at /checkout/src/libstd/panicking.rs:471
   8:     0x556be8a02b2d - core::panicking::panic_fmt::h883a028e9f4b4457
                               at /checkout/src/libcore/panicking.rs:69
   9:     0x556be877e559 - core::result::unwrap_failed::ha1e1d8b7cb93815a
                               at /checkout/src/libcore/macros.rs:29
  10:     0x556be8746e91 - <core::result::Result<T, E>>::expect::hb16888bd05d6e26a
                               at /checkout/src/libcore/result.rs:762
  11:     0x556be8810dfb - triangle::main::h8066a67b6ac93b0f
                               at triangle/main.rs:188
  12:     0x556be89e47ca - __rust_maybe_catch_panic
                               at /checkout/src/libpanic_unwind/lib.rs:98
  13:     0x556be89ddfd0 - std::rt::lang_start::ha09816a4e25587ea
                               at /checkout/src/libstd/panicking.rs:433
                               at /checkout/src/libstd/panic.rs:361
                               at /checkout/src/libstd/rt.rs:59
  14:     0x556be8816b42 - main
  15:     0x7f20bb7af82f - __libc_start_main
  16:     0x556be86e3588 - _start
  17:                0x0 - <unknown>
```

The code from: https://github.com/vulkano-rs/vulkano-examples
The command: `RUST_BACKTRACE=full cargo run --bin triangle`

**Comment by lilianmoraru** [comment]
I hardcoded the size to `[1024, 768]` and it started but instantly went out of memory and almost crashed the system(UI freezed and the music was looping):
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: OutOfHostMemory', /checkout/src/libcore/result.rs:860
```

**Comment by golddranks** [comment]
After a super busy month, I was able to return to this. Giving the `Swapchain::new` method a `[1024, 768]` starts the example app, and it seems to run fine. (There was the earlier comment about memory usage, but mine, on MacOS, seems to run at a steady level.)

So, it's a HiDPI issue, but it's hard to pinpoint yet where the exact issue is.

About the MoltenVK logging thing, I send a supporting comment:
https://moltengl.com/forums/topic/moltenvk-error-vk_timeout-vulkan-fence-timeout-after-0-nanoseconds/#post-1332

**Comment by golddranks** [comment]
@tomaka As a confirmation, did you mean this, mentioned here: https://www.khronos.org/registry/vulkan/specs/1.0/man/html/vkWaitForFences.html

>If timeout is zero, then vkWaitForFences does not wait, but simply returns the current state of the fences. VK_TIMEOUT will be returned in this case if the condition is not satisfied, even though no actual wait was performed.

**Comment by tomaka** [comment]
> is @tomaka able to test this library in a HiDPI environment?

I don't have an HiDPI monitor.

> As a confirmation, did you mean this, mentioned here: https://www.khronos.org/registry/vulkan/specs/1.0/man/html/vkWaitForFences.html

Yes.

**Comment by golddranks** [comment]
So, I think I solved the HiDPI bug. In Vulkano-win, when setting up the `CAMetalLayer`, the scaling factor of the layer has to be set, like this: `layer.set_contents_scale(view.backingScaleFactor());`. However, the wrapper for the `setContentsScale` API wasn't implemented in metal-rs, so I sent a pull request: https://github.com/gfx-rs/metal-rs/pull/10 Hopefully it will be pulled in quickly.

Also, according to the docs ( https://developer.apple.com/documentation/appkit/nsview/1483695-wantslayer ) if you set the layer of the view manually, `setWantsLayer` must be called AFTER the layer has been set:

> In addition to creating a layer-backed view, you can create a layer-hosting view by assigning a layer directly to the view’s layer property. In a layer-hosting view, you are responsible for managing the view’s layer. To create a layer-hosting view, you must set the layer property first and then set this property to true. The order in which you set the values of these properties is crucial.

Currently `setWantsLayers` is set before:

    let view = wnd.contentView();
    view.setWantsLayer(YES);
    view.setLayer(mem::transmute(layer.0)); // Bombs here with out of memory

Fixing these things, it reports the extents of the surface correctly and the resolution is correct.

**Comment by dagit** [comment]
I have a similar issue on linux with an intel gpu (part of my cpu). I don't know if I should start a separate issue. I'll put my details here for now.

It seems that on my card, the min/max extent listed in the capabilities matches the exact size of the window when it's created. Trying to create the swapchain with any other size results in `UnsupportedDimensions`.

I figured this out by adding a `println` inside `swapchain.rs` and comparing that against requested dimensions. I'll see if I can figure out how to make the examples use a size from the current capabilities (`current_extent`?) instead of the window size.

**Comment by dagit** [comment]
```rust
--- a/examples/src/bin/triangle.rs         
+++ b/examples/src/bin/triangle.rs         
@@ -110,8 +110,7 @@ fn main() {            
     // Get the dimensions of the viewport. These variables need to be mutable since the viewport                                                                             
     // can change size.                   
     let mut dimensions = {                
-        let (width, height) = window.window().get_inner_size_pixels().unwrap();       
-        [width, height]                   
+        window.surface().capabilities(physical).unwrap().current_extent.unwrap()      
     };                                    
                                           
     // The next step is to choose which GPU queue will execute our draw commands.     
@@ -185,6 +184,7 @@ fn main() {            
         let format = caps.supported_formats[0].0;                                     
                                           
         // Please take a look at the docs for the meaning of the parameters we didn't mention.                                                                               
+        println!("dimensions = {:#?}", dimensions);                                   
         Swapchain::new(device.clone(), window.surface().clone(), caps.min_image_count, format,                                                                               
                        dimensions, 1, caps.supported_usage_flags, &queue,             
                        SurfaceTransform::Identity, alpha, PresentMode::Fifo, true,    
@@ -340,8 +340,7 @@ void main() {          
         if recreate_swapchain {           
             // Get the new dimensions for the viewport/framebuffers.                  
             dimensions = {                
-                let (new_width, new_height) = window.window().get_inner_size_pixels().unwrap();                                                                              
-                [new_width, new_height]   
+                window.surface().capabilities(physical).unwrap().current_extent.unwrap()                                                                                     
             };                            
                                           
             let (new_swapchain, new_images) = match swapchain.recreate_with_dimension(dimensions) { 
```

This change works for me in the triangle example. It's so small that it seems silly to make a pull request, but I can do that if it would be useful.

**Comment by golddranks** [comment]
dagit: What is the resolution reported by the window dimensions and what is the one reported by the surface capabilities API? Are you using a HiDPI setup? If you manage to start the example, does the resolution look normal or too low/pixely?

**Comment by dagit** [comment]
I'm not using a hidpi display. So it does look normal. The numbers reported by the capabilities matches what I would expect (1024x768). The only discrepancy that was causing issues was that inner pixel size was not exactly equal to the window size and my drivers didn't like that.

**Comment by golddranks** [comment]
So they were off, but only slightly? That sounds like a problem with winit, more than Vulkano. But since Vulkano seems to care about the extent of the surface rather than the size of the window, that change might be good to do.

**Comment by dagit** [comment]
I think winit was correctly calculating the inner size. It was just a few pixels smaller than the window size.

I think the issue here is that my drivers report the expent (min/min) to be equal to the window size. So then trying to use any different size is a problem in vulkano and who knows, maybe it would be an issue for the driver as well. Reusing the `current_extent` is easy and seems to be fool proof.

**Comment by golddranks** [comment]
Huh, I wonder how the Surface is created on Linux? Do you get it directly from the window or do you create it separately, choose the resolution yourself and link it with the Window...?

**Comment by golddranks** [comment]
I expect you are using X. From Vulkano's source/docs:

> Surface::from_xlib
> Creates a Surface from an Xlib window.
> The surface's min, max and current extent will always match the window's dimensions.

That means that if the dimensions are different, it's a bug somewhere. I agree that using the current_extent here is a foolproof thing to do, but that bug should be investigated also.

**Comment by golddranks** [comment]
Okay, so the creation of the surface is handled by the platform-specific extensions, and on X, the surface size is always the window size, you can't affect that. Which means that X just calculates the window size using the whole window size, and expecting the inner area size to match the surface size is wrong. Or so it seems?

**Comment by dagit** [comment]
> expecting the inner area size to match the surface size is wrong.

I agree with that, but I would also expect the driver to be reasonable and accept the window size or something slightly smaller (viewport size?). My only guess is that the driver isn't *required* to do so.

**Comment by golddranks** [comment]
Sent a PR that addresses multiple of the problems discussed in this thread!
