### ISSUE TITLE
Installing libwayland-dev results in invalid window

### ISSUE THREAD

**Issue by newpavlov** [vulkano-rs/vulkano#741]
On Debian 9 with Wayland, Gnome and Mesa drivers installing `libgtk-3-dev` results in this window:
![window](https://user-images.githubusercontent.com/329626/29319251-0dbb2ae8-81dc-11e7-9785-b699480fd35b.png)

Teapot animation runs without problems. This window can not be moved, resized or closed without stopping application.

UPD: Looks like source of the problem is in the `libwayland-dev`, on which gtk3 depends.
UPD2: Probably this is the [issue](https://github.com/tomaka/winit/issues/163), but it's strange why it does not show itself without `libwayland-dev`. Also fullscreen application does not work too. Feel free to close this issue if you think that it should not be here.

**Comment by tomaka** [comment]
This is probably a bug in winit. Please open an issue there.
