### ISSUE TITLE
Add a way to specify location of MoltenVK

### ISSUE THREAD

**Issue by rtsuk** [vulkano-rs/vulkano#744]
If build.rs had something like the diff below, it could locate the MoltonVK framework in a common location and not require moving the static library around. Before I create a pull request for this I'd love feedback from MoltenVK users about how to do this. Is this approach of requiring it to be in the user's home directories Library/Frameworks ok?

```
--- a/vulkano/build.rs
+++ b/vulkano/build.rs
@@ -12,7 +12,10 @@ use std::env;
 fn main() {
     let target = env::var("TARGET").unwrap();
     if target.contains("apple-darwin") {
+        let target = env::var("HOME").unwrap();
+        let home_frameworks = format!("{}/Library/Frameworks", target);
         println!("cargo:rustc-link-lib=c++");
+        println!("cargo:rustc-link-search=framework={}", home_frameworks);
         println!("cargo:rustc-link-lib=framework=MoltenVK");
         println!("cargo:rustc-link-lib=framework=QuartzCore");
         println!("cargo:rustc-link-lib=framework=Metal");
```

**Comment by lilianmoraru** [comment]
https://github.com/purpliminal/rust-dotenv ?(aka, environment variables + `.env` support?)

**Comment by nicokoch** [comment]
IMO, the default should stay as is, but you should be able to configure it via an environment variable.

**Comment by rtsuk** [comment]
@lilianmoraru I'm not sure what purpose rust-dotenv would serve here. The environmental variables in the example are set by Mac OS X.

@nicokoch The default doesn't actually work, I think, because the framework search path on Mac OS X doesn't search arbitrary locations. 

~~~
clang++ -E -x c++ - -v < /dev/null
Apple LLVM version 8.1.0 (clang-802.0.42)
Target: x86_64-apple-darwin16.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
 "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang" -cc1 -triple x86_64-apple-macosx10.12.0 -Wdeprecated-objc-isa-usage -Werror=deprecated-objc-isa-usage -E -disable-free -disable-llvm-verifier -discard-value-names -main-file-name - -mrelocation-model pic -pic-level 2 -mthread-model posix -mdisable-fp-elim -masm-verbose -munwind-tables -target-cpu penryn -target-linker-version 278.4 -v -dwarf-column-info -debugger-tuning=lldb -resource-dir /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/8.1.0 -stdlib=libc++ -fdeprecated-macro -fdebug-compilation-dir /Users/robtsuk/projects/fuchsia/third_party/webkit -ferror-limit 19 -fmessage-length 132 -stack-protector 1 -fblocks -fobjc-runtime=macosx-10.12.0 -fencode-extended-block-signature -fcxx-exceptions -fexceptions -fmax-type-align=16 -fdiagnostics-show-option -fcolor-diagnostics -o - -x c++ -
clang -cc1 version 8.1.0 (clang-802.0.42) default target x86_64-apple-darwin16.7.0
ignoring nonexistent directory "/usr/include/c++/v1"
#include "..." search starts here:
#include <...> search starts here:
 /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1
 /usr/local/include
 /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/8.1.0/include
 /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include
 /usr/include
 /System/Library/Frameworks (framework directory)
 /Library/Frameworks (framework directory)
End of search list.
# 1 "<stdin>"
# 1 "<built-in>" 1
# 1 "<built-in>" 3
# 340 "<built-in>" 3
# 1 "<command line>" 1
# 1 "<built-in>" 2
# 1 "<stdin>" 2
~~~

/System/Library/Frameworks is protected by [System Integrity Protection](https://support.apple.com/en-us/HT204899) and can't be used.

I had tried putting MoltonVK.framework in  /Library/Frameworks, which should have worked, but didn't. Is that what you are thinking of when you mention the default?

I think having a reasonable default install location like $HOME/Library/Frameworks is better than requiring an environmental variable be set. I think allowing an override via an environmental variable is a good idea.

**Comment by tomaka** [comment]
There's also another problem with the build script.
Vulkano allows you to specify at runtime how to load the Vulkan implementation (see https://docs.rs/vulkano/0.5.6/vulkano/instance/loader/index.html).
But right now you can't really use that on MacOS because whatever you do vulkano will always try to link to MoltenVK.

**Comment by nicokoch** [comment]
@rtsuk I just copied moltenvk to /Library/Frameworks. Worked on my mac.

**Comment by rtsuk** [comment]
In that case this is certainly not needed. Thanks @nicokoch.
