### ISSUE TITLE
Wrong values for array in shader

### ISSUE THREAD

**Issue by SiebenCorgie** [vulkano-rs/vulkano#759]
Hi,
I am currently trying to upload some info for several lights at once. 
I usually use an array of `light` for this. 
For vulkano I created a struct representing the buffer like this:
```
pub struct PointLightInfo {
    ///Holds an array of all the point lights currently used
    pub l_point: Vec<LightPointShaderInfo>
}
```

and the light definition looks like this:
```
pub struct LightPointShaderInfo {
    pub color: [f32; 3],
    pub intensity: f32,
}
```
After that I create a descriptor set from the `PointLightInfo` like I would do with any other struct.
In the shader I access the information like this:
struct definition:
```
struct PointLight
{
  vec3 color;
  float intensity;

};
```
and import: 
```
//And the send bindings from rust/vulkano
layout(set = 3, binding = 0) uniform point_lights{
  PointLight p_light[MAX_POINT_LIGHTS];
}u_point_light;
```

At compile time this works and vulkan(o) starts, but when I want to use for instance the `color` value, it is always black.

Any idea why this happens? 
Thanks for any help,

-siebencorgie

**Comment by tomaka** [comment]
The alignment of the `intensity` field is 128 bits on the GPU and only 32 bits on the CPU.
If you change `color` from `[f32; 3]` to `[f32; 4]` (and use dummy values for the fourth element), it should work.

**Comment by tomaka** [comment]
If you use the `#[derive(VulkanoShader)]` thing of vulkano-shaders, it should automatically generate a module named `ty` which contains a struct named `PointLight` which you can use. This struct will automatically have the correct layout.

For example if the [shader here](https://github.com/vulkano-rs/vulkano/blob/94c376c268ffb9a0adaa58cdfd2baa1793b614f2/examples/src/bin/triangle.rs#L212-L223) contained the `PointLight` struct, you could access the generated struct with `vs::ty::PointList`.

**Comment by SiebenCorgie** [comment]
Ah, thanks! I'll have a look.

**Comment by SiebenCorgie** [comment]
Sorry to reopen this. I thought it is clear but it somehow doesn't work.
I thought that it might be the best to always just use a vec4 and pack everything in n * vec4 per struct.
So I changed the struct in rust to 
```
pub struct LightPointShaderInfo {
    pub color: [f32; 4],
    pub intensity: [f32; 4],
}
```
and the shader part to: 
```
struct PointLight
{
  vec4 color;
  vec4 intensity;
};

//And the send bindings from rust/vulkano
layout(set = 3, binding = 0) uniform point_lights{
  PointLight p_light[MAX_POINT_LIGHTS];
}u_point_light;

```
The 4th element of colour is always `1.0` and the 2nd-4th element of `intensity` are as well.
However, I still get only black.
Do I have to align every other struct in the shader like this as well?
I mean I have several more stucts more at descriptor set 0-2 each with something between 1-3 bindings.
Are the descriptor sets and bindings independent from each other alignment wise?

**Comment by tomaka** [comment]
> Do I have to align every other struct in the shader like this as well?

Yes

> Are the descriptor sets and bindings independent from each other alignment wise?

Yes

**Comment by SiebenCorgie** [comment]
Okay, so if one works, for instance this one:
```
layout(set = 2, binding = 1) uniform TextureFactors {
  vec4 albedo_factor;
  vec4 normal_factor;
  vec4 emissive_factor;
  int metal_factor;
  int roughness_factor;
  int occlusion_factor;
} u_tex_fac;
```
Then I can leave it like it is and move to the next one for aligning?

**Comment by tomaka** [comment]
Yes. Alignment is only required because the GPU can only perform aligned loads from the memory. When you have separate buffers there is no link between the two.

Also one thing I didn't mention is that you should really `#[repr(C)]` on your struct, otherwise there is no guarantee that their layout actually matches their definition. Again if you want to make your life easier, you can just use the structs generated by vulkano-shaders.

**Comment by SiebenCorgie** [comment]
Thanks, 
I'll try to use the `#[repr(C)]` (i actually didn't know that this exists). That could also be the explanation why the "for all types vec4/ [f32; 4]" did not work.
If this doesn't work I'll go down the vulkano-shaders road. It just means a bit more code shifting for me.
Thanks for your time!
