### ISSUE TITLE
broken runtime-shader.rs example

### ISSUE THREAD

**Issue by portaloffreedom** [vulkano-rs/vulkano#760]
#757 broke the `runtime-shader.rs` example as in the example both the Vertex and the Fragment shader Layout descriptors have 
```
        fn descriptor(&self, set: usize, binding: usize) -> Option<DescriptorDesc> {
            match (set, binding) { _ => None, }
        }
```

and the `check_desc_against_limits()` function is unwrapping the `None`, resulting in a crash.

**Comment by tomaka** [comment]
Oh thanks for the report.
