### ISSUE TITLE
Is vk-sys usage example exist?

### ISSUE THREAD

**Issue by XX** [vulkano-rs/vulkano#765]
I started learning Vulkan. Can I use vk-sys as binding library for pure Vulkan rust projects? Where can I get tutorials or examples of using it? There is no documentation in vk-sys crate.

**Comment by fst3a** [comment]
You could use Vulkano code as example of usage of raw vulkan.  Otherwise, vk-sys would be used in same way as shown in any plain vulkan (C++ or not) example out there.

**Comment by XX** [comment]
@fst3a How correctly to get acces Vulcan functions through vk-sys? There is special loading system in Vulcano (https://github.com/vulkano-rs/vulkano/blob/master/vulkano/src/instance/loader.rs), but this adapted to use in vulcano crate only (because of using `pub(crate) fn entry_points`). Should I write my own loading system to start using the Vulcan through vk-sys or is there an easier way?

**Comment by fst3a** [comment]
In C++, you normally use some SDK like LunarG that provides a loader which exposes `vkGetInstanceProcAddr`.  Unfortunately, vk-sys provide any so i guess you will need to write your own.  There's also plenty of other "wheels" to reinvent such as vulkan memory allocator etc.  I think it would be wise to reuse some vulkano code where possible.

**Comment by rukai** [comment]
These days [Ash](https://github.com/MaikKlein/ash) is the most usable low level rust vulkan bindings.
