### ISSUE TITLE
Wait for Fences/Semaphores/Events before destruction

### ISSUE THREAD

**Issue by nicokoch** [vulkano-rs/vulkano#769]
The docs state the following for the destructors (valid usage):
`All submitted commands that refer to event/fence/semaphore must have completed execution`.

I'm pretty sure this means we have to call i.e. `WaitForFences` in `drop` in order to not introduce invalid API usage.

**Comment by nicokoch** [comment]
Additionally, this has to be added to `Device::drop` when we destroy the pools

**Comment by tomaka** [comment]
I went with the other approach, which is that the places that submit commands have as safety requirement that the fence/semaphore/event must be kept alive (example: https://github.com/vulkano-rs/vulkano/blob/ceb4ebdc951a8563c1107e0cc21b05258915cb73/vulkano/src/command_buffer/submit/queue_submit.rs#L110-L111).

But I guess that calling `WaitForFences` in a `debug_assert` as an additional check would be ok.

> Additionally, this has to be added to Device::drop when we destroy the pools

Similarly the `Device` can't be destroyed if there's any pending execution.

**Comment by nicokoch** [comment]
Nice, I thought it was an oversight.
Closing this
