### ISSUE TITLE
vukano-shader interpretes bool in glsl as u32 in rust

### ISSUE THREAD

**Issue by SiebenCorgie** [vulkano-rs/vulkano#781]
Hi,
I don't know if this is expected, but I have a struct:
```
layout(set = 2, binding = 0) uniform TextureUsageInfo {
  bool b_albedo;
  bool b_normal;
  bool b_metal;
  bool b_roughness;
  bool b_occlusion;
  bool b_emissive;
} u_tex_usage_info;
```
When I access it in my rust program via:
```
pbr_fragment::ty::TextureUsageInfo{
  b_albedo: true,
  b_normal: true,
  b_metal: true,
  b_roughness: true,
  b_occlusion: true,
  b_emissive: true,
}
```
The rustc/cargo complains:
```
error[E0308]: mismatched types
   --> src/core/resources/material.rs:117:21
    |
117 |                     false
    |                     ^^^^^ expected u32, found bool
```

Is this expected? I mean I can use a "if not 0 interpret as `true` " approach. But I just wanted to be sure it's not a problem on my side. 

-siebencorgie

**Comment by tomaka** [comment]
SPIR-V doesn't allow booleans in structs with external visibility.
What happens here I think is that the GLSL compiler automatically turns booleans into u32s. Therefore this is beyond my control.

**Comment by SiebenCorgie** [comment]
Ah, good to know. So I take the "if not 0" approach.
Thanks!
