### ISSUE TITLE
Blit resulting in SourceFormatNotSupported despite having transfer_source set to true

### ISSUE THREAD

**Issue by LaylConway** [vulkano-rs/vulkano#791]
The docs mention "Can be used as a source for transfers. Includes blits." on transfer_source in ImageUsage, but when actually using an image with this set as a source for blitting this error occurs.

**Comment by LaylConway** [comment]
After a bit of chat on IRC it seems I've been misunderstanding where this error is coming from. I've now verified that the image format I'm using supports being used in blitting as both source and target.
![](http://i.imgur.com/39sd5c3.png)

Looking through the code it *should* already be using optimal tiling features, but I'm still getting this error.

**Comment by LaylConway** [comment]
Further details on the problem: I'm trying to initialize mipmaps in an `ImmutableImage`, however, I can only use the `ImmutableImageInitialization` structure once. I used the image itself as source and destination on the blit commands instead, so I'm figuring there is the problem. However since the initialization structure can only be used once I'm not sure how to resolve this.

**Comment by tomaka** [comment]
You should be able to clone the initialization struct for that, but it's not related to the blit source not supported message.

**Comment by LaylConway** [comment]
The initialization struct does not have Clone implemented.

**Comment by LaylConway** [comment]
I think I found the problem

https://github.com/vulkano-rs/vulkano/blob/master/vulkano/src/command_buffer/validity/blit_image.rs#L53

This if check (and the one below it) do the exact opposite of what they should be doing, throwing a not supported error when it *is* supported.
