### ISSUE TITLE
Including a shader at compile time

### ISSUE THREAD

**Issue by fschutt** [vulkano-rs/vulkano#798]
The problem is that I want to include shaders at compile time, but the `#[src = include_str!("myfile.glsl")]` doesn't seem to work. Is there any way to include shaders directly in the binary, while having the actual shader in a seperate file? Thanks.

```
error: src/graphics/shaders/mod.rs:43: proc-macro derive panicked
help: src/graphics/shaders/mod.rs:43: message: called `Result::unwrap()` on an `Err` value: "failed to parse macro input: \"#[ty = \\\"vertex\\\"]\\n#[src = include_str ! ( \\\"v_utm_line.glsl\\\" )]\\nstruct VertUtmLine;\""
```

**Comment by fschutt** [comment]
Nevermind, just discovered that you can use `#[path = "myshader.glsl"]` instead.

**Comment by canndrew** [comment]
This should probably be mentioned in the tutorial. Having to write the shader in-line is just yukky.
