### ISSUE TITLE
Crash when trying to create an instance

### ISSUE THREAD

**Issue by LordZane** [vulkano-rs/vulkano#815]
I have a i7-4700MQ cpu, with a windows 10 host and arch linux virtual machine with all the neccesary vulkan packages installed. Trying to create an instance fails with `InitializationFailed`. However running a c++ example works fine.

**Comment by tomaka** [comment]
`InitializationFailed` is a failure "for implementation-specific reasons" (quotes from the specs), which isn't very helpful.

**Comment by LordZane** [comment]
Apparently intel dosent have drivers for haswell, oh well, sorry about this
