### ISSUE TITLE
Flaws in VK_EXT_debug_report implementation

### ISSUE THREAD

**Issue by nicokoch** [vulkano-rs/vulkano#821]
Here are some flaws I noticed with the current implementation of debug report:
1. There is a secondary API that allows passing a callback directly during instance creation. This callback will only be active during `vkCreateInstance` and `vkDestroyInstance`. Vulkano does not currently expose this API as far as I'm aware.

2. The spec states
```
/* Section 33.2 of the Vulkan 1.0.59 spec says:
*
*    "callback is an externally synchronized object and must not be
*    used on more than one thread at a time. This means that
*    vkDestroyDebugReportCallbackEXT must not be called when a callback
*    is active."
*/
```

There are currently no mechanisms implemented to prevent this, allowing for invalid API usage.

**Comment by tomaka** [comment]
I guess we will need to remove the whole `DebugCallback` struct, and store the debug callback as part of the instance.

**Comment by Tape** [comment]
This extension is now deprecated in favor of `VK_EXT_debug_utils`. https://vulkan.lunarg.com/doc/view/1.1.73.0/windows/layer_configuration.html#user-content-debugreport

**Comment by Rua** [comment]
Issue 1 has now been solved with a second constructor for `Instance`. Issue 2 was resolved by making `DebugUtilsMessenger` unsafe to construct.
