### ISSUE TITLE
Unable to create StorageImage with depth format

### ISSUE THREAD

**Issue by mabruckner** [vulkano-rs/vulkano#822]
Using `StorageImage::new` fails with `UnsupportedUsage` when the format is `D16Unorm`, but succeeds for `R16Unorm`. I can create `AttachmentImage`s with depth formats, but that also fails when I try to give it the `sampled` usage. Generally it seems that it is not possible to create images that have both the `depth_stencil_attachment` and `sampled` usages.

**Comment by tomaka** [comment]
That's not really something vulkano controls. It's your driver that that it doesn't support these usages.

Although for `StorageImage` the problem is that `new()` enables too many usages by default, and they may not all be supported.

**Comment by mabruckner** [comment]
I got my program to work so I am closing the issue. It turns out I was making some incorrect assumptions about what usages I needed in order to access a depth buffer from a shader.
