### ISSUE TITLE
Vulkano doesn't wait for GPU

### ISSUE THREAD

**Issue by SiebenCorgie** [vulkano-rs/vulkano#831]
Hi,
For some reason my vulkano implementation doesn't wait for the gpu to finish its task, or the gpu isn't doing anything.
The symptom is, that I submit a command buffer in a loop and wait for the gpu in the next iteration of this loop. However the waiting doesn't seam to work because Vulkan reports:
```
DS(ERROR): object: 0x3e type: 7 location: 4087 msgCode: 853543110: Fence 0x3e is in use. The spec valid usage text states 'Any given element of pFences must not currently be associated with any queue command that has not yet completed execution on that queue' (https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VUID-vkResetFences-pFences-01123)
```
for each frame. When trying to submit the next command buffer / frame,

The way I handle the futures is, that I have an `render()` function which has an `Box<GpuFuture>` as argument.
I copy this `Box<T>` localy, apply `cleanup_finished()` on it.
Acquire a second future from the `vulkano::swapchain::acquire_next_image`
after building the command buffer I join the Future from the function argument with the future from the swap chain.
Theh execute the next command buffer on it, add the swapchain present command and finally do `then_signal_fence_and_flush()`.
The returned future of this operation then get returned by the function `update()` and might be submitted for the next frame as argument, or if the renderer should end is used to wait for the GPU one last time.
In code it looks like this:
```
    pub fn render(
        &mut self,
        asset_manager: &mut asset_manager::AssetManager,
        previous_frame: Box<GpuFuture>,
    ) -> Box<GpuFuture>{


        let mut local_previous_frame = previous_frame;

        local_previous_frame.cleanup_finished();


	//check for swapchina etc
        let (image_num, acquire_future) = {...}


	// create command buffer
        let command_buffer = {...}


        let future = local_previous_frame
        .join(acquire_future)
        .then_execute(
            self.queue.clone(), command_buffer
        )
        .expect("failed to execute buffer!")
        .then_swapchain_present(
            self.queue.clone(), self.swapchain.clone(), image_num
        )
        .then_signal_fence_and_flush().expect("failed to flush");

        let new_frame = Box::new(future) as Box<_>;

        new_frame
    }
```

What am I doing wrong?
I recently moved the render loop into its own thread, but the Box never gets moved out of it (well, can't because its a Box<T>).

Thanks for any help!

-siebencorgie

**Comment by tomaka** [comment]
It's entirely possible that the error is a false positive.

**Comment by IcyDefiance** [comment]
I get this error specifically when using `cargo run --release`, and it leaks memory at about 1 MB per second. It's observable on vulkano's triangle example as well.

When I'm not using `--release` then it's fine, no errors and no memory leak.

I'm on Windows with a GTX 780 Ti if that makes any difference.

**Comment by SiebenCorgie** [comment]
Well, I am using --release as well (manly to make the image loading faster).
Just tested without the `--release` flag. The error is gone. 

Rendering works as well.

I am on an intel HD 4600 on Linux via mesa drivers.

**Comment by IcyDefiance** [comment]
It looks like this error happens at [sync/fence.rs:69](https://github.com/vulkano-rs/vulkano/blob/089d0879f7460b89c68de84c37671467ec359c76/vulkano/src/sync/fence.rs#L69) (obviously, because it's the only place `vkResetFences()` is called). However, it only happens with fences that were passed to a queue but never passed to `vkWaitForFences()` afterward.

When running with `--release`, this situation can arise after dropping a `SwapchainAcquireFuture`, because of [swapchain/swapchain.rs:861-872](https://github.com/vulkano-rs/vulkano/blob/089d0879f7460b89c68de84c37671467ec359c76/vulkano/src/swapchain/swapchain.rs#L861-L872). If I change that to a normal `assert!`, the error disappears.

This is probably a bug with the validation thing, not vulkano, but I'm not really sure.

**Comment by tomaka** [comment]
Ah, yes. The behaviour of the validation layer is to automatically report an error if you destroy a fence without checking whether it has been signalled, even though in this situation we know through logic alone that the fence must have been signalled.

**Comment by SiebenCorgie** [comment]
So not a problem on Vulkanos side. More a Vulkan thing?
I guess I can close the issue then.

**Comment by SiebenCorgie** [comment]
I just had the chance to test my program on an Intel I7 6xxx and its integrated card. I don't know what the graphics card is, but I didn't had the issue and also no memory leak.

So seams to be an driver issues indeed.
