### ISSUE TITLE
Syntax for shaders

### ISSUE THREAD

**Issue by porky11** [vulkano-rs/vulkano#836]
Some time ago, when I tried vulkano, the way to define shaders was just inside glsl files.
The way to write them now using the Dummy struct seems a bit weird.
Why can't you just use a macro like this:
```
vulkano_shader!("compute"
#version 450
void main() {})
```

**Comment by tomaka** [comment]
There's no way to provide this syntax in stable Rust today.

**Comment by porky11** [comment]
I thought so. I hope this will become available some time.

**Comment by canndrew** [comment]
@tomaka Have you seen https://github.com/dtolnay/proc-macro-hack ?

**Comment by rukai** [comment]
Fixed by https://github.com/vulkano-rs/vulkano/commit/494a0c30c87e1362fc5e4dce8a403016e5ad4e0a
