### ISSUE TITLE
How to run the examples

### ISSUE THREAD

**Issue by adrianbrink** [vulkano-rs/vulkano#839]
I would like to test the examples but I am running into some problems.

On Linux with a NVIDA 1060 I get this error:
```
➜  vulkano-examples git:(master) cargo run --bin triangle
    Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
     Running `target/debug/triangle`
thread 'main' panicked at 'failed to create Vulkan instance: LoadingError(LibraryLoadFailure("libvulkan.so.1: cannot open shared object file: No such file or directory"))', /checkout/src/libcore/result.rs:860:4
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

Do I need to install something from Vulkan?

On MacOS I get this error:
```
  = note: ld: framework not found MoltenVK
          clang: error: linker command failed with exit code 1 (use -v to see invocation)


error: aborting due to previous error

error: Could not compile `vulkano-examples`.
```

Do I need to install anything on macOS to make it work?

Thank you very much for any help.

**Comment by adrianbrink** [comment]
Update:

On MacOS I dropped the `MoltenVK.framework` into `/Library/Framework/` and it now displays the triangle.

However it constantly spams me with:
```
[***MoltenVK ERROR***] VK_TIMEOUT: Vulkan fence timeout after 0 nanoseconds.
```

**Comment by tomaka** [comment]
> Do I need to install something from Vulkan?

Yes. Depending on your distribution there are drivers to install.

> However it constantly spams me with:

This has already been reported to the MoltenVK people.

**Comment by ul** [comment]
I downloaded Molten 0.19.0, dropped `MoltenVK.framework` into `/Library/Framework/` and `libMoltenVK.dylib` into `/usr/local/lib` (just in case ;-) ), but I get following error when executing `cargo run --bin triangle`:

```
 = note: Undefined symbols for architecture x86_64:
            "_kIOSurfaceWidth", referenced from:
                MVKImage::useIOSurface(__IOSurface*) in MoltenVK(MoltenVK-x86_64-master.o)
            "_kIOSurfaceHeight", referenced from:
                MVKImage::useIOSurface(__IOSurface*) in MoltenVK(MoltenVK-x86_64-master.o)
            "_kIOSurfaceElementWidth", referenced from:
                MVKImage::useIOSurface(__IOSurface*) in MoltenVK(MoltenVK-x86_64-master.o)
            "_kIOSurfaceElementHeight", referenced from:
                MVKImage::useIOSurface(__IOSurface*) in MoltenVK(MoltenVK-x86_64-master.o)
            "_kIOSurfaceIsGlobal", referenced from:
                MVKImage::useIOSurface(__IOSurface*) in MoltenVK(MoltenVK-x86_64-master.o)
            "_kIOSurfaceBytesPerElement", referenced from:
                MVKImage::useIOSurface(__IOSurface*) in MoltenVK(MoltenVK-x86_64-master.o)
            "_IOSurfaceGetBytesPerElement", referenced from:
                MVKImage::useIOSurface(__IOSurface*) in MoltenVK(MoltenVK-x86_64-master.o)
            "_IOSurfaceGetElementWidth", referenced from:
                MVKImage::useIOSurface(__IOSurface*) in MoltenVK(MoltenVK-x86_64-master.o)
            "_IOSurfaceGetHeight", referenced from:
                MVKImage::useIOSurface(__IOSurface*) in MoltenVK(MoltenVK-x86_64-master.o)
            "_IOSurfaceCreate", referenced from:
                MVKImage::useIOSurface(__IOSurface*) in MoltenVK(MoltenVK-x86_64-master.o)
            "_IOSurfaceGetWidth", referenced from:
                MVKImage::useIOSurface(__IOSurface*) in MoltenVK(MoltenVK-x86_64-master.o)
            "_IOSurfaceGetElementHeight", referenced from:
                MVKImage::useIOSurface(__IOSurface*) in MoltenVK(MoltenVK-x86_64-master.o)
          ld: symbol(s) not found for architecture x86_64
          clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by ul** [comment]
Is it realted to #880  ?

**Comment by ul** [comment]
Sorry for the noise, I was trying to run example from `volkano-examples` repo. When I run it from this repo dependecies look more fresh, but I get then another error:

```
  Compiling vulkano-win v0.7.3 (file:///Users/rprakapchuk/Hub/vulkano/vulkano-win)
error[E0599]: no variant named `new` found for type `metal::CAMetalLayer` in the current scope
   --> vulkano-win/src/lib.rs:168:17
    |
168 |     let layer = CAMetalLayer::new();
    |                 ^^^^^^^^^^^^^^^^^ variant not found in `metal::CAMetalLayer`

error: aborting due to previous error

error: Could not compile `vulkano-win`.
```

**Comment by tomaka** [comment]
Oh! Thanks for the investigation.

**Comment by yanchith** [comment]
@ul I had the same problems you had, followed your instructions, but instead of it working I got an linking error: ` = note: ld: framework not found MoltenVK`. I have `MoltenVK.framework` in `Library/Frameworks`.

Do you know which versions of molten are safe to use? It might be related to #880 and #879.

Thanks!

**Comment by yanchith** [comment]
@ul I had the same problems you had, followed your instructions, but instead of it working I got an linking error: ` = note: ld: framework not found MoltenVK`. I have `MoltenVK.framework` in `Library/Frameworks`.

Do you know which versions of molten are safe to use? It might be related to #880 and #879.

Thanks!

**Comment by ul** [comment]
@yanchith I use MoltenVK 0.19.0

**Comment by yanchith** [comment]
Ok. I'll try to figure it out and post the answer here.

**Comment by GabrielMajeri** [comment]
@yanchith Have you tried running the [Vulkan samples](https://github.com/SaschaWillems/Vulkan)? The repo provides some xcode project files which link to MoltenVK.

If that fails to build / run, there might be something wrong with your MoltenVK install.

**Comment by yanchith** [comment]
It fails to be build because of https://github.com/SaschaWillems/Vulkan/issues/423
The search continues :)

**Comment by yanchith** [comment]
I managed to run the Vulkan samples, so MoltenVK appears to be fine. I am going to keep investigating this one post updates here, when I find anything significant.

**Comment by GabrielMajeri** [comment]
@yanchith Since MoltenVK has been recently open-sourced, could you try the examples in [their repository](https://github.com/KhronosGroup/MoltenVK) too? If those don't work, opening an issue there might be best.

**Comment by yanchith** [comment]
So I ran the [Vulkan Samples](https://github.com/SaschaWillems/Vulkan) with MoltenVK 0.19.0, and the locally built 1.0.0 from [MoltenVK](https://github.com/KhronosGroup/MoltenVK). Both ran fine.

However, vulkano seems to have problems linking against both 0.19.0 and 1.0.0 on my machine (the error is the same as the one I posted earlier).

I don't have a deep understanding of how linking to native dependencies works in rust, so I guess I am off to learn that now :) Would appreciate if someone could point me in the right direction though.

**Comment by GabrielMajeri** [comment]
@yanchith You could try adding a [`build.rs`](https://doc.rust-lang.org/cargo/reference/build-scripts.html) file to your Cargo project, with the contents

```rust
fn main() {
  let lib_dir = "/Library/Frameworks/";
  println!("cargo:rustc-link-search=framework={}", lib_dir);
}
```

Assuming the `MoltenVK.Framework` file is there. There should also be a `libMoltenVK.dylib` file in the same directory.

**Comment by yanchith** [comment]
@GabrielMajeri Thanks! It works. I thought `/Library/Frameworks/` was searched by default. But reading the linker invocation, this is not true.

Does it make sense to add this build script to examples? Or perhaps add the line to `vulkano/build.rs`?

**Comment by yanchith** [comment]
Hmm, `man ld` says that `/Library/Frameworks` and `/System/Library/Frameworks` are on the default search paths.

`ld --verbose | grep /Libraries/Frameworks` does not produce anything for me, as it ld has no `--verbose` option (at least not the one I have installed).

**Comment by GabrielMajeri** [comment]
@yanchith I'm not sure where the bug is. I created a pull request which should at least fix linking Vulkano on Mac OS, but the fact those paths are not searched might affect other crates too.

**Comment by yanchith** [comment]
Yeah. It's strange. I'll try to confirm from another mac just in case it's only my system, that's broken.

Thank you for the fix.

**Comment by Pirh** [comment]
> It looks like metal-rs had breaking changes in 0.5. I reverted its version back to 0.4.3 in vulkano-win dependencies and triangle finally compiled and started!

I had to do this exact thing as well. Do the examples need updated, or does the version need rolled back in master? Or something more complicated?

**Comment by yanchith** [comment]
I think it's a minor fix in `vulkano-win`. I will submit the PR soon, unless someone beats me to it.
