### ISSUE TITLE
Is there a generic trait every shader implements from the derive methode?

### ISSUE THREAD

**Issue by SiebenCorgie** [vulkano-rs/vulkano#840]
Hi,

I am currently loading my glsl Shader via the derive method used in the examples.

Now I have two different Shader sets, one pbr and one I want to use for wireframes.
The problem is that both are different types so I can't do something like:
pseudo code:
```
let shader = {
    match wanted_shader_type{
        PBR=> return pbr_shaders,
        WIREFRAME => wireframe_shaders,
    }
};
```

So the only thing I could image now is that every Shader implements a trait so I can return an `Arc<Shader>`.

Any ideas how to handle several shaders like this or at all? 

Thanks in advance!

**Comment by tomaka** [comment]
Hi,

You shouldn't manipulate individual shader. I suggest you manipulate while pipeline object instead.

Pipeline objects all implement the `PipelineObjectAbstract` trait.

**Comment by SiebenCorgie** [comment]
Thanks!

I think I understand what you mean, but sadly [I can't find](https://docs.rs/vulkano/0.7.1/vulkano/?search=PipelineObjectAbstract) the `PipelineObjectAbstract` trait :/ .

I also searched for just `Object` but there is only a `VulkanoObject`

Or do you mean to use the `vulkano::pipeline::shader::EntryPointAbstract` as one part of the pipeline?

**Comment by tomaka** [comment]
Sorry I meant `GraphicsPipelineAbstract` or `ComputePipelineAbstract`.

**Comment by SiebenCorgie** [comment]
Ah, So only manipulate the pipelines as a whole. 

Thanks!
