### ISSUE TITLE
bool push constants in AutoCommandBufferBuilder cause invalid reads

### ISSUE THREAD

**Issue by Ralith** [vulkano-rs/vulkano#841]
A rust `bool` is 1 byte, while a glsl `bool` is 4 bytes. This disagreement in layout causes UB arising from the assumption of memory compatibility in the helper function [`push_constants`](https://github.com/tomaka/vulkano/blob/master/vulkano/src/command_buffer/auto.rs#L1069). It can be worked around by explicitly passing a u32 instead.

It doesn't appear that there's any typechecking done for push constants at all yet, but this is a particularly surprising case.

**Comment by tomaka** [comment]
Note that `vulkano-shaders` will generate a `u32` to match a GLSL bool.

**Comment by Ralith** [comment]
Sounds like this is entirely redundant to the known-missing typechecking then.
