### ISSUE TITLE
Missing Queue Families

### ISSUE THREAD

**Issue by AustinJ235** [vulkano-rs/vulkano#845]
With vulkano the queue families method on the physical device only returns one queue family and one queue in that family (first one in the image). Using vulkan-caps-viewer, it shows that I have 2 queue families with the first having 1 queue and the other 8 queues. Is this intended behavior? This is on linux with an RX 480 using radv. On windows with the RX 480 I get multiple queues as I'd expected.

![families](https://user-images.githubusercontent.com/5326321/31183581-9ce51198-a8ec-11e7-8059-8d07126635be.png)

**Comment by tomaka** [comment]
Could you show your code? It's not an intended behaviour.

**Comment by AustinJ235** [comment]
Ok well I feel rather stupid now. I simplified the code and now they all show up. Just a dumb logic error.
