### ISSUE TITLE
Add some way to implement traits for structs from foreign crates

### ISSUE THREAD

**Issue by porky11** [vulkano-rs/vulkano#850]
Example:
```
extern crate cgmath;

struct Vertex {
    pos: cgmath::Vector3<f32>
}
impl_vertex!(Vertex, pos);
//error:
//the trait `vulkano::pipeline::vertex::VertexMember` is not implemented for `cgmath::Vector3<i32>`
```
The problem is, it is forbidden to implement foreign traits to foreign types
```
unsafe impl vulkano::pipeline::vertex::VertexMember for cgmath::Vector3<f32> {…}
```
You could implement it in this crate, but that would require you to know about all crates containing types, that could be used for this trait.
The cleanest solution would be some way to implement it in a third crate, but there is currently no way to do that. But there seems to be no real effort to solve this. The existing solutions didn't seem that good. I hope, there will be a better solution. I'll try to find one, too.
The most pragmatic is to use a wrapper type, but that's not that usable.

When there are better solutions, it should be fixed.
The same issue also applies to glium.

**Comment by tomaka** [comment]
> The cleanest solution would be some way to implement it in a third crate, but there is currently no way to do that.

IMO the cleanest solution is to simply stick to primitive types, like it's currently the case.

**Comment by porky11** [comment]
This may also be a good solution, I didn't try it that way. Casting them into and from the math types shouldn't be that difficult.

**Comment by GabrielMajeri** [comment]
Since the `cgmath` types are marked with `#[repr(C)]` it should be safe to use [`mem::transmute`](https://doc.rust-lang.org/std/mem/fn.transmute.html) on the whole structure for a zero-cost cast.

**Comment by tomaka** [comment]
Converting is probably zero-cost as well anyway.
