### ISSUE TITLE
Call pipeline without vertex input

### ISSUE THREAD

**Issue by porky11** [vulkano-rs/vulkano#851]
It would be nice to have a way to call the pipeline without input attributes for vertices.
I have data already loaded on the gpu, and just want to use them as vertex data like this:
```
layout(set = 0, binding = 0) buffer b {
    vec3 pos[];
} buf;

void main() {
    gl_Position = vec4(buf.pos[gl_VertexIndex], 1);
}
```
I don't think, there's a way to do that in vulkano yet.
Some Ideas, how this could be done:
Currently this doesn't do anything useful: 
```
struct Vertex;
impl_vertex!(Vertex);
```
A sequence of such empty vertices could be used instead of memory consuming pseudo vertices.
Another idea would be a way to add a new method to the `GraphicsPipelineBuilder` similar to `vertex_input` and `vertex_input_single_buffer` and may be called `ǹo_vertex_input`

**Comment by tomaka** [comment]
You can do that by passing a BufferlessDefinition to `vertex_input`: https://docs.rs/vulkano/0.7.1/vulkano/pipeline/vertex/struct.BufferlessDefinition.html

However that can't be used if you then cast the created pipeline into a `GraphicsPipelineAbstract`.

**Comment by porky11** [comment]
Thanks, this looks good. I'll try it.
