### ISSUE TITLE
Support for dynamic buffers in PersistentDescriptorSet

### ISSUE THREAD

**Issue by Ralith** [vulkano-rs/vulkano#858]
This is useful for when you want to use a single buffer to store a large, statically unknown number of uniforms for efficient allocation and streaming.

I'm happy to implement this myself, but I'd like to know what the desired API is. Adding new dedicated methods to `PersistentDescriptorSetBuilder`(`Array`) for each type starts to get into a combinatorial explosion with the existing buffer vs. buffer view duplication. A `dynamic: bool` argument could be added to the `add_buffer` methods, but this would be a breaking API change.

**Comment by tomaka** [comment]
You don't need to add a `dynamic` parameter to `add_buffer`. The pipeline layout already knows whether the buffer is dynamic.

The most annoying problem with dynamic buffers is how to indicate the actual offset when binding the descriptor set.

**Comment by Ralith** [comment]
Per IRC discussion, unsafe command buffers provide at least *some* way to bind the descriptor set and I'm already using them for other reasons anyway, so the most pressing concern for me is having a means to construct a suitable pipeline.

**Comment by Rua** [comment]
There is now a dynamic-buffers example demonstrating this.
