### ISSUE TITLE
vulkano.rs is down

### ISSUE THREAD

**Issue by Vurich** [vulkano-rs/vulkano#865]
Trying to access http://vulkano.rs/ returns a 503

**Comment by tomaka** [comment]
Thanks the report.

I have no idea what the problem was. The container restarted alone, without me doing anything. The logs don't show any error.

**Comment by cptroot** [comment]
Seems like this might be an issue again. I'm getting a 503 right now.

**Comment by tomaka** [comment]
Thanks. I think I'm just going to use a PaaS service instead.
