### ISSUE TITLE
Rust to spirv

### ISSUE THREAD

**Issue by mnivoliez** [vulkano-rs/vulkano#871]
Hello, first good work achieve here. I had just started to learn to use vulkano and it already amazed me beyond aniything possible (currently working on opengl at school, how to say the step is big and shiny).
I was wondering about the glsl. Currently vulkano use the glsllang provided by Kronos if i'm right. But the Kronos group seems to encourage to develop any compilator to spirv.
In the light of that, shouldn't a rust to spirv compilator be great?
Google seems to work on something like that:  [rspirv](https://github.com/google/rspirv).
I'm relatively new to the domain and barely understand all that so I excuse if the question is stupid.

**Comment by tomaka** [comment]
Hi!
I'm closing to close this, as #353 already covers that (with a worse issue name though).

Basically my opinion is that turning some basic Rust code into SPIR-V wouldn't be difficult, but actually doing something robust and correct will be very hard.
