### ISSUE TITLE
Make it possible to take a winit::Window in vulkano_win

### ISSUE THREAD

**Issue by Shookbelf** [vulkano-rs/vulkano#874]
My problem is the following: I want to separate window and surface/graphics. But since vulkano_win::Window makes the winit::Window private there is no way to keep the winit::Window alive if the vulkano_win::Window goes out of scope.

It's already possible to take the Surface and the Window is an unnecessary type afterwards.

This would be solved by 3afca4f1f64e876a4b5927d4b8be18042e68e7c1

This is probably related to #848 and #844 

Sorry if this is too close to the other two issues, but it's a different view and might be helpful in the design of a solution.

**Comment by tomaka** [comment]
Actually I marked this as "blocked" because vulkano_win is unsafe right now and needs a bit of a rework.

**Comment by Shookbelf** [comment]
Any plans when it will be ready? I've seen you don't want to push the version too often. Would making a private field public (as temporary measure) count as breaking change?

Are there any relatively easy things that can be done to help?
