### ISSUE TITLE
Strange build error: 

### ISSUE THREAD

**Issue by Elzair** [vulkano-rs/vulkano#875]
I am building [a project in Vulkano](https://github.com/Elzair/wargod) (right now, it is mostly the teapot example factored into neat files), and I recently upgraded from the 0.5 version to 0.7. However, I now get a strange build error when creating the `PersistentDescriptorSet` and `AutoCommandBufferBuilder` in the loop:

error[E0277]: the trait bound `std::result::Result<vulkano::buffer::cpu_pool::CpuBufferPoolSubbuffer<vs::ty::Data, std::sync::Arc<vulkano::memory::pool::StdMemoryPool>>, vulkano::memory::DeviceMemoryAllocError>: vulkano::SafeDeref` is not satisfied
   --> src/main.rs:137:18
    |
137 |                 .add_buffer(uniform_buffer_subbuffer).ok().unwrap()
    |                  ^^^^^^^^^^ the trait `vulkano::SafeDeref` is not implemented for `std::result::Result<vulkano::buffer::cpu_pool::CpuBufferPoolSubbuffer<vs::ty::Data, std::sync::Arc<vulkano::memory::pool::StdMemoryPool>>, vulkano::memory::DeviceMemoryAllocError>`
    |
    = note: required because of the requirements on the impl of `vulkano::buffer::BufferAccess` for `std::result::Result<vulkano::buffer::cpu_pool::CpuBufferPoolSubbuffer<vs::ty::Data, std::sync::Arc<vulkano::memory::pool::StdMemoryPool>>, vulkano::memory::DeviceMemoryAllocError>`

error[E0277]: the trait bound `vulkano::descriptor::descriptor_set::PersistentDescriptorSet<std::sync::Arc<vulkano::pipeline::GraphicsPipeline<vulkano::pipeline::vertex::TwoBuffersDefinition<Vertex, Normal>, std::boxed::Box<vulkano::descriptor::PipelineLayoutAbstract + std::marker::Send + std::marker::Sync>, std::sync::Arc<vulkano::framebuffer::RenderPassAbstract + std::marker::Send + std::marker::Sync>>>, ((), vulkano::descriptor::descriptor_set::PersistentDescriptorSetBuf<std::result::Result<vulkano::buffer::cpu_pool::CpuBufferPoolSubbuffer<vs::ty::Data, std::sync::Arc<vulkano::memory::pool::StdMemoryPool>>, vulkano::memory::DeviceMemoryAllocError>>)>: vulkano::descriptor::DescriptorSet` is not satisfied
   --> src/main.rs:152:14
    |
152 |             .draw_indexed(
    |              ^^^^^^^^^^^^ the trait `vulkano::descriptor::DescriptorSet` is not implemented for `vulkano::descriptor::descriptor_set::PersistentDescriptorSet<std::sync::Arc<vulkano::pipeline::GraphicsPipeline<vulkano::pipeline::vertex::TwoBuffersDefinition<Vertex, Normal>, std::boxed::Box<vulkano::descriptor::PipelineLayoutAbstract + std::marker::Send + std::marker::Sync>, std::sync::Arc<vulkano::framebuffer::RenderPassAbstract + std::marker::Send + std::marker::Sync>>>, ((), vulkano::descriptor::descriptor_set::PersistentDescriptorSetBuf<std::result::Result<vulkano::buffer::cpu_pool::CpuBufferPoolSubbuffer<vs::ty::Data, std::sync::Arc<vulkano::memory::pool::StdMemoryPool>>, vulkano::memory::DeviceMemoryAllocError>>)>`
    |
    = help: the following implementations were found:
              <vulkano::descriptor::descriptor_set::PersistentDescriptorSet<L, R, P> as vulkano::descriptor::DescriptorSet>
    = note: required because of the requirements on the impl of `vulkano::descriptor::DescriptorSet` for `std::sync::Arc<vulkano::descriptor::descriptor_set::PersistentDescriptorSet<std::sync::Arc<vulkano::pipeline::GraphicsPipeline<vulkano::pipeline::vertex::TwoBuffersDefinition<Vertex, Normal>, std::boxed::Box<vulkano::descriptor::PipelineLayoutAbstract + std::marker::Send + std::marker::Sync>, std::sync::Arc<vulkano::framebuffer::RenderPassAbstract + std::marker::Send + std::marker::Sync>>>, ((), vulkano::descriptor::descriptor_set::PersistentDescriptorSetBuf<std::result::Result<vulkano::buffer::cpu_pool::CpuBufferPoolSubbuffer<vs::ty::Data, std::sync::Arc<vulkano::memory::pool::StdMemoryPool>>, vulkano::memory::DeviceMemoryAllocError>>)>>`
    = note: required because of the requirements on the impl of `vulkano::descriptor::descriptor_set::DescriptorSetsCollection` for `std::sync::Arc<vulkano::descriptor::descriptor_set::PersistentDescriptorSet<std::sync::Arc<vulkano::pipeline::GraphicsPipeline<vulkano::pipeline::vertex::TwoBuffersDefinition<Vertex, Normal>, std::boxed::Box<vulkano::descriptor::PipelineLayoutAbstract + std::marker::Send + std::marker::Sync>, std::sync::Arc<vulkano::framebuffer::RenderPassAbstract + std::marker::Send + std::marker::Sync>>>, ((), vulkano::descriptor::descriptor_set::PersistentDescriptorSetBuf<std::result::Result<vulkano::buffer::cpu_pool::CpuBufferPoolSubbuffer<vs::ty::Data, std::sync::Arc<vulkano::memory::pool::StdMemoryPool>>, vulkano::memory::DeviceMemoryAllocError>>)>>`

Here is the code in question. What could be happening?

```rust
        let set = Arc::new(
            vulkano::descriptor::descriptor_set::PersistentDescriptorSet
                ::start(pipeline.clone(), 0)
                .add_buffer(uniform_buffer_subbuffer).ok().unwrap()
                .build().unwrap()
        );

        let command_buffer = vulkano::command_buffer::AutoCommandBufferBuilder
            ::primary_one_time_submit(gfx_core.device.clone(),
                                      gfx_core.queue.family()
            ).unwrap()
            .begin_render_pass(
                framebuffer.clone(),
                false,
                vec![
                    [0.0, 0.0, 1.0, 1.0].into(),
                    1f32.into()
                ]).unwrap()
            .draw_indexed(
                pipeline.clone(),
                vulkano::command_buffer::DynamicState {
                    line_width: None,
                    viewports: Some(vec![vulkano::pipeline::viewport::Viewport {
                        origin: [0.0, 0.0],
                        dimensions: [gfx_core.dimensions.read().unwrap().width as f32,
                                     gfx_core.dimensions.read().unwrap().height as f32],
                        depth_range: 0.0 .. 1.0,
                    }]),
                    scissors: None,
                },
                (vertex_buffer.clone(), normals_buffer.clone()), 
                index_buffer.clone(), set.clone(), ()).unwrap()
            .end_render_pass().unwrap()
            .build().unwrap();
```

**Comment by tomaka** [comment]
You're probably missing a few `unwrap()`s when creating your buffers, descriptor sets and so on, because you seem to be passing `Result`s instead of objects themselves.

**Comment by Elzair** [comment]
Got it! Thanks!

**Comment by rukai** [comment]
Looks like this was resolved
