### ISSUE TITLE
Use arbitrary self types (self: Arc<Self>)

### ISSUE THREAD

**Issue by GabrielMajeri** [vulkano-rs/vulkano#878]
I noticed one of Vulkano's design [troubles](https://github.com/vulkano-rs/vulkano/blob/master/TROUBLES.md) was that

> Vulkano users are encouraged to manipulate objects through Arcs. However there is no way to add a method pub fn foo(self: Arc<Self>) to an object 

A recent [pull request](https://github.com/rust-lang/rust/pull/45870) added this feature. It is currently nightly-only, but it does work. It would be cool to switch Vulkano to use this once it becomes stable. See [this Rust playground](https://play.rust-lang.org/?gist=0bb44a5d135ea633bafceb5cdba60134&version=nightly) for an example with `Arc`s.

I've opened this issue to create a tracking list of what needs to be changed for `self: Arc<Self>`.

**Comment by tomaka** [comment]
Great, thanks for the report!
