### ISSUE TITLE
Examples: Swapchain  format selection.

### ISSUE THREAD

**Issue by SiebenCorgie** [vulkano-rs/vulkano#881]
Hi,

While improving my own code I found this section at the triangle example:
```
        // Choosing the internal format that the images will have.
        let format = caps.supported_formats[0].0;

        // Please take a look at the docs for the meaning of the parameters we didn't mention.
        Swapchain::new(device.clone(), window.surface().clone(), caps.min_image_count, format,
                       dimensions, 1, caps.supported_usage_flags, &queue,
                       SurfaceTransform::Identity, alpha, PresentMode::Fifo, true,
None).expect("failed to create swapchain")
```

I am wonder why we can select the first element of the `caps.supported_formats` without knowing anything about it.
As far as I understand the vector it returns the value could potentially be `vulkano::format::Format::R8Uint` which (i guess) doesn't work too well for swapchain images.

Now my question:
Is there any guarantee that the first format is a swapchain suitable format or is it just a guess?

Thanks in advance!

Siebencorgie

**Comment by rukai** [comment]
On my system the only values `caps.supported_formats` contains are `[(B8G8R8A8Srgb, SrgbNonLinear), (B8G8R8A8Unorm, SrgbNonLinear)]`.
Both of these are fine.
Unless a system is found that returns a format is less suitable, then I see no problem with the current implementation.
