### ISSUE TITLE
How to update existing vertex buffer? Prefereably in seperate thread?

### ISSUE THREAD

**Issue by greenmughal** [vulkano-rs/vulkano#885]
How to update existing vertex buffer? Prefereably in seperate thread?
Thanks

**Comment by greenmughal** [comment]
I guess I have to acquire a write lock, send data again and unlock?

**Comment by fst3a** [comment]
Well, it depends on one's usage.

If one updates their vertex buffer rarely, a good way to go about it would be to have DeviceLocalBuffer and upload data to it from a buffer created by CpuBufferPool.  If the buffer is small and updates are not incremental, it would be better to create new buffer (from CpuBufferPool) every time and give the device that.

If one still wants to mutate existing buffer, they will have to keep track of fences(s) in queues that *might* be holding lock to that buffer, wait on those fences, make the thread responsible for queueing wait for one's unlock, lock, update, unlock and then let queueing thread lock.

CpuAccessibleBuffer doesn't expose any way to wait for access anymore and likely ever won't.

**Comment by greenmughal** [comment]
Thanks man for detailed answer.
