### ISSUE TITLE
Panic when resolving depth attachment in the render pass.

### ISSUE THREAD

**Issue by SiebenCorgie** [vulkano-rs/vulkano#886]
Hi,

I wanted to add msaa to my render. 
What I did is: 
create two `AttachmentImage::transient_multisampled()` images with the multi sampling count and the swapchain image dimensions. The depth buffer has the format `vulkano::format::D16Unorm` and the color attachment has the swapchain image fromat.
Then I create an `AttachmentImage::transient()` image for the "unsampled" depth attachment.
Finally, I create the render pass with the following layout:
```
        let renderpass = Arc::new(
            ordered_passes_renderpass!(target_queue.device().clone(),
            attachments: {

                // The first framebuffer attachment is the msaa_color image.
                msaa_color: {
                    load: Clear,
                    store: DontCare,
                    format: swapchain_fromat,
                    samples: 4,
                },
                //the second one is the msaa depth buffer
                msaa_depth: {
                    load: Clear,
                    store: DontCare,
                    format: Format::D16Unorm,
                    samples: 4,
                },

                //the final image
                color: {
                    load: Clear,
                    store: Store,
                    format: swapchain_fromat, 
                    samples: 1, 
                },
                //the depth buffer
                depth: {
                    load: Clear,
                    store: DontCare,
                    format: Format::D16Unorm,
                    samples: 1,
                }
            },
            passes:[
                {
                    color: [msaa_color], 
                    depth_stencil: {msaa_depth},
                    input: [] 
                    resolve: [color, depth],
                }
            ]

        ).expect("failed to create render_pass")

        );
```

As you can see I try to resolve the color attachment to the swapchain image and the depth attachment to a single sampled image. Why? I tried to use a single sampled depth attachment but my window stayed black. I had a look at Sascha Willems vulkan examples and found out that he is creating a multisampled depth attachment as well: (https://github.com/SaschaWillems/Vulkan/blob/master/examples/multisampling/multisampling.cpp from line 253-292)

However, when trying this the renderer panics with:
```
panicked at 'assertion failed: desc.resolve_attachments.is_empty() ||
    desc.resolve_attachments.len() == desc.color_attachments.len()'
```

My question now: Is this expected/ should I resolve depth in another way, or is it just not implemented yet to resolve a depth attachment?

Thanks for any help

-siebencorgie

**Comment by JoshuaBatty** [comment]
Hi @SiebenCorgie did you ever manage to find a work around for this? Having the exact same issue. Cheers

**Comment by SiebenCorgie** [comment]
@JoshuaBatty No I couldn't figure it out. I went with adding another render pass and resolve the image my self via a [tiny shader](https://gitlab.com/Siebencorgie/jakar-engine/blob/deffered_forward_hybrid/data/shader/hdr_sorting.frag#L27).

**Comment by JoshuaBatty** [comment]
No problem thanks for the shader to look at at!

**Comment by AimainaHito** [comment]
For anyone else who might come across this with the same goals:
Since I don't need the single sampled depth buffer for anything else I tried just removing the `depth` attachment and `depth` from `resolve` and it looks like depth testing and MSAA work just fine with only the multisampled depth buffer.
