### ISSUE TITLE
How to extend deferred example to add Sampler?

### ISSUE THREAD

**Issue by greenmughal** [vulkano-rs/vulkano#889]
I came to know that subpass load cannot address specific pixels which i need for various effects, what are the alternatives?

Also how to extend the deferred triangle example to render Position and other data to a sampler image?

**Comment by tomaka** [comment]
If you want to be able to address random pixels and not just the current pixel, then you need to use multiple render passes and not just one.

**Comment by greenmughal** [comment]
Thanks. An example would work. Or atleast please tell me steps. Thanks

**Comment by tomaka** [comment]
Drawing to an image is exactly the same as drawing to a swapchain image. There's an example here: https://github.com/vulkano-rs/vulkano-www/blob/master/examples/guide-triangle.rs
Then after you have drawn to the image, use it as a sampled image.

**Comment by greenmughal** [comment]
Great man

**Comment by greenmughal** [comment]
Btw just for the sake of self promotion, heres my WIP.
Im going to attempt Hemisphere ambient occlusion for the terrain thats why...

If anyone of you have time please contribute to my thread at gamedev..
https://www.gamedev.net/forums/topic/693892-what-it-takes-to-make-a-great-looking-terrain/

![whatsapp image 2017-12-02 at 7 47 27 pm 1](https://user-images.githubusercontent.com/19550918/33550472-252932fe-d8ff-11e7-8ebe-d89041d358a3.jpeg)
![whatsapp image 2017-12-02 at 7 47 27 pm](https://user-images.githubusercontent.com/19550918/33550473-256a707a-d8ff-11e7-9e73-aa17b601f0bd.jpeg)

**Comment by rukai** [comment]
Sounds like this was resolved
