### ISSUE TITLE
Emit throwaway `include_bytes!()` in shader-derive so changes to shader files trigger recompilation

### ISSUE THREAD

**Issue by abonander** [vulkano-rs/vulkano#890]
In [this Reddit discussion](https://www.reddit.com/r/rust/comments/7hffz6/hey_rustaceans_got_an_easy_question_ask_here/dqttf8m/?context=3), the asker was unsure of how to get Cargo to recognize shader files as source files to trigger recompilation. I suggested either emitting `rerun-if-changed` from a build script or using `include_bytes!("<shader file>")` in their Rust code in order for Cargo to detect changes to shader files when deciding whether or not to recompile.

It occurred to me that shader-derive *could* be doing the latter automatically, but I haven't found any discussion on why it doesn't currently. The additional data would inflate debug builds, but the unused rvalues *should* be optimized out in release builds.

**Comment by flaghacker** [comment]
A potential solution should also consider included files, making it a bit harder then just emitting `rerun-if-changed` in the build script.

**Comment by Rua** [comment]
This seems to be fixed by #1523.
