### ISSUE TITLE
Triangle example crashes with UnsupportedDimensions in Ubuntu 17.10

### ISSUE THREAD

**Issue by DiThi** [vulkano-rs/vulkano#892]
And if we replace line 178 with this

    let dimensions = caps.current_extent.unwrap_or(dimensions);

it works for one frame, then the resize event is triggered and it gets stuck in line 352 which ignores the error UnsupportedDimensions assuming it would no longer happen.

Using Kubuntu 17.10 64 bit.
Nvidia 1070 with driver 384.90-0ubuntu3.17.10.1

**Comment by rukai** [comment]
This looks like it was caused by the examples not handling resize at this time. But maybe not hard for me to check as I don't see anything relevant on line 178 in a commit before 2017-12-10. Can you please retest on the latest vulkano? If there is a crash please provide a stacktrace.

**Comment by rukai** [comment]
Over a month without a response
