### ISSUE TITLE
Documentation: is the order of PhysicalDevice::enumerate() always the same on one system?

### ISSUE THREAD

**Issue by LukasKalbertodt** [vulkano-rs/vulkano#899]
(see title). This would be nice to know, e.g. to let the user choose a physical device by id.

**Comment by tomaka** [comment]
In practice, yes. In theory, the list of physical devices can change whenever you create a new instance. However I think that if you enumerate the physical devices of a given instance, the list will always be the same. This would need to be confirmed.

You are supposed to use the `PhysicalDevice::uuid()` method if you want a unique identifier.
