### ISSUE TITLE
Replace `vulkano-shaders` parser with `rspirv`

### ISSUE THREAD

**Issue by GabrielMajeri** [vulkano-rs/vulkano#910]
We currently use the `vulkan-shaders` to parse generated SPIR-V code and to generate Rust code from it.

Instead of having the burden of maintaining a SPIR-V parser, Vulkano should use Google's [rspirv](https://github.com/google/rspirv), which is a Rust implementation of a SPIR-V analyzer.

`rspirv` generates an intermediate representation of the SPIR-V code, which could be then transformed in Rust code.

**Comment by faulesocke** [comment]
Hmm, it looks like rspirv is a google project and whenever you want to get changes upstreamed you are required to have a google account and have to sign a lengthy license agreement with google. Not the most ideal situation, IMO. Of course it is handy, but is it really worth it?

**Comment by Robert42** [comment]
Hey,

https://github.com/google/rspirv gets now redirected to https://github.com/gfx-rs/rspirv

Also the [CONTRIBUTING.md](https://github.com/gfx-rs/rspirv/blob/master/CONTRIBUTING.md) file was modified not to require signing any contracts with google:
https://github.com/gfx-rs/rspirv/commit/63e77fca1b979b93e8f08a40236e0734161436c8#diff-6a3371457528722a734f3c51d9238c13

It may be now worth a second look!

**Comment by Rua** [comment]
Vulkano now has a mostly auto-generated SPIR-V parser, so the burden of maintaining it is fairly minor.
