### ISSUE TITLE
Use `shaderc` for shader compilation

### ISSUE THREAD

**Issue by GabrielMajeri** [vulkano-rs/vulkano#911]
Currently, Vulkano uses `glslangValidator` to generate SPIR-V code, and there is a [pull request](https://github.com/vulkano-rs/vulkano/pull/904) to use `spirv-opt` too.

Instead of using multiple tools, we could use [`shaderc`](https://github.com/google/shaderc) which has official [Rust bindings](https://github.com/google/shaderc-rs).

The advantage is that `shaderc` is meant to be used as a library, not a binary, and it includes all of the `glslang` / `spirv` tools in it.

**Comment by rukai** [comment]
Resolved by https://github.com/vulkano-rs/vulkano/pull/947
