### ISSUE TITLE
MSAA renders at lower color values on AMD + Linux

### ISSUE THREAD

**Issue by rukai** [vulkano-rs/vulkano#912]
https://pastebin.com/RRreQxp6 - I modified the traingle example to add msaa (diff with triangle.rs to quickly see the difference)

Its tested to work fine on Nvidia with linux and windows and also AMD with windows.
However using AMD + Linux causes the color values to be lowered
When the fragment shader does:
*   `f_color = vec4(1.0, 0.0, 0.0, 1.0);` Then we get a triangle of color 0x7f0000 - half of what it should be
*   `f_color = vec4(0.5, 0.0, 0.0, 1.0);` Then we get a triangle of color 0x5e0000 - less then it should be

This sounds like a driver issue but I tested it with the example here: https://github.com/SaschaWillems/Vulkan/blob/master/examples/multisampling/multisampling.cpp
And it seems to work fine. 

Intrestingly there was a bug fixed in said example for AMD but that seems irrelevant as it was only happening due to a second renderpass.

The validation layers dont show anything.

**Comment by nicokoch** [comment]
Are you using radv or the amd driver?

**Comment by rukai** [comment]
I have this installed https://www.archlinux.org/packages/extra/x86_64/vulkan-radeon/
and when I run a vulkano program it prints `WARNING: radv is not a conformat vulkan implementation, testing use only`
I guess that means radv? I dont know the difference.

**Comment by nicokoch** [comment]
There are two different amd vulkan drivers on Linux: radv and amdvlk.

radv is part of the mesa project and developed by independent volunteers
amdvlk is the "official" vulkan driver by amd, it has lately gone open source too.

You could try installing amdvlk (https://aur.archlinux.org/packages/amdvlk-git/) and report back if this solves the problem. If so, it is most likely an issue with radv.
