### ISSUE TITLE
dynamic work group size in compute shaders?

### ISSUE THREAD

**Issue by arianvp** [vulkano-rs/vulkano#914]
You now need to define  the local work group size twice:

once in the shader:
```
layout(local_size_x = 16) in;
```

And once in the kernel invocation:
```
        builder.dispatch([dimensions[0] / 16, dimensions[1] / 16, 1],
                      self.pipeline.clone(),
                      self.next_set(input),
                      ())

```

Apparently glsl (and vulkan) has the concept of a `local_size_x_id` where you then pass the size information at runtime thorugh `VkSpecializationMapEntry` . Such that you don't have to hardcode the size in the shader. However, I can't find support for this in vulkano

See here for an example:
https://www.reddit.com/r/vulkan/comments/5eqgly/has_anybody_got_a_working_example_of_work_group/

**Comment by arianvp** [comment]
Is this the accompanying behaviour in vulkano? https://docs.rs/vulkano/0.7/vulkano/pipeline/shader/trait.EntryPointAbstract.html#associatedtype.SpecializationConstants

**Comment by tomaka** [comment]
Whenever you compile a shader with the vulkano-derive crate, a strict that implements the trait you linked will be generated. You will then have to pass an instance of it when building the pipeline.

I haven't tested if that works with compute shaders invocation size, but I don't see why it shouldn't.

**Comment by arianvp** [comment]
Ahh cool. What is the name of this struct?

**Comment by tomaka** [comment]
It's named `SpecializationConstants`. I thought there was an example of this somewhere, but I can't find it unfortunately.

**Comment by arianvp** [comment]
I'll see if I can turn my experiments in some examples for in the repo.
