### ISSUE TITLE
[Question] Usage of CubeMap

### ISSUE THREAD

**Issue by Kibouo** [vulkano-rs/vulkano#922]
Sorry, new to graphical programming. I'm confused over the usage of a cubemap (when constructing an `ImmutableImage`):

- I assume the image file used as texture has to include all sides of the cube in 1 file? Like an unfolded cube? [(such as these)](https://duckduckgo.com/?q=cubemap&t=ffab&iax=images&ia=images)
- While researching I stumbled upon #260 where Tomaka mentions that cubemaps are equal to a texture 2D. It just has 6 layers. What are layers? DDG wasn't really helpfull.
- Lastly, what information does the `size` parameter of `Dimensions::Cubemap` hold? Rather, what does it want to know the size of?

Thanks in advance!

**Comment by AustinJ235** [comment]
The data for the buffer is the image data of six images appended to each other in the order of: left, right, bottom, top, back, and front (at least that is the order I have). The size of the cubemap is the width of one of the square images.

**Comment by Kibouo** [comment]
By "appended to each other" do you mean that you open 6 different image files and place them after each other in the buffer?

**Comment by AustinJ235** [comment]
Say you load an image into a Vec of u8's, where each value is the color component r, g, b, or a; or any other variant. Just append the next image's data onto that Vec.
