### ISSUE TITLE
[Question] &Arc and self-referencing

### ISSUE THREAD

**Issue by elbaro** [vulkano-rs/vulkano#930]
My main() gets too long, so I defined a struct to include all initialization code:

```
pub struct Vulkan<'a> {
...
    instance: Arc<Instance>,
    surface: Arc<Surface<winit::Window>>,
    physical: PhysicalDevice<'a>,
    device: Arc<Device>,
...
}

impl<'a> Vulkan<'a> {
    pub fn new() -> Vulkan<'a> {
        let instance = {
             ...
            Instance::new(...).expect("failed to create Vulkan instance")
        };
        ...
        let surface = WindowBuilder::new().build_vk_surface(&events_loop, &instance).unwrap();
        let physical = PhysicalDevice::enumerate(&instance).next().expect("no device (supporting vulkan) available");
        ...
        Vulkan {
            instance: instance,
            surface: surface,
            physical: physical,
            ...
        }
}
```

The problem is the local `instance` doesn't live long enough and `physical` needs a reference to it.
Why does `PhysicalDevice` store `&Arc<Instace>` instead of `Arc<Instance>`?

I am new to Rust and I couldn't find a way to work around this.

**Comment by thiolliere** [comment]
In my code I made a similar graphic struct. The `new` function have one arguments: `&vulkan_win::window`
the instance is then get with `.surface().instance()`.

Maybe a solution is to have the window stored into your structure or what I have done is requiring reference to window for method that needs it (new, draw and recreate methods)

**Comment by elbaro** [comment]
Thank you all.

The snippet was a big help. I was writing
```
pub pipeline: Arc<GraphicsPipeline<SingleBufferDefinition<Vertex>,Box<vulkano::descriptor::PipelineLayoutAbstract + std::marker::Sync + std::marker::Send>,Arc<RenderPass<vulkan::Vulkan::new::scope::CustomRenderPassDesc>>>>,
```
(write `Arc<()>`, compile, rustc tells me the correct type, write `Arc<RenderPass<()>>`, repeat)

And now it's as simple as
`pub pipeline: Arc<GraphicsPipelineAbstract + Sync + Send>`

I could remove PhysicalDevice from the struct. When I need it (e.g. window resize), I just recreate it.
```
pub fn reset_swapchain(&mut self) -> bool {
        let physical = PhysicalDevice::enumerate(&self.instance).next().unwrap();
        let dimensions = self.surface.capabilities(physical)
            .expect("failed to get surface capabilities")
            .current_extent.unwrap_or([self.width as u32, self.height as u32]);
        ...
```
