### ISSUE TITLE
Callbacks for GpuFutures?

### ISSUE THREAD

**Issue by gretchenfrage** [vulkano-rs/vulkano#937]
I'm trying to interface vulkano's GpuFutures with my architecture's version of futures. Mine is based on callbacks, so I'm looking for some way to register a cheap callback on the completion of a GpuFuture. Is this possible? I've been looking through the code for a while and I cannot find such a thing.

**Comment by tomaka** [comment]
This is unfortunately not possible because Vulkan itself doesn't support that.

**Comment by gretchenfrage** [comment]
Ok, thanks. Then I'm thinking, as a hack, I could have per-vulkan-queue threads that hold a (non-vulkan) blocking queue of GpuFutures and callbacks in the order that they were added to the vulkan queue, and in a loop, removes a GpuFuture/callback pair, calls `then_signal_fence_flush`, calls `wait`, and then invokes the callback. Does that sound like it would work?

**Comment by tomaka** [comment]
Yes, that should work!

**Comment by gretchenfrage** [comment]
Thank you!
