### ISSUE TITLE
build_vk_surface and winit 0.12.0 fails to build

### ISSUE THREAD

**Issue by polarathene** [vulkano-rs/vulkano#943]
I was trying the image example at: https://github.com/vulkano-rs/vulkano/blob/master/examples/Cargo.toml

vulkano-win is tied to winit 0.11.0? I tried with the latest 0.12.0 and it didn't like the added method trying to be called:

```
error[E0599]: no method named `build_vk_surface` found for type `winit::WindowBuilder` in the current scope
  --> src/main.rs:40:47
   |
40 |     let surface = winit::WindowBuilder::new().build_vk_surface(&events_loop, instance.clone()).unwrap();
   |                                               ^^^^^^^^^^^^^^^^

error: aborting due to previous error

```

**Comment by tomaka** [comment]
> vulkano-win is tied to winit 0.11.0?

Yes unfortunately! `vulkano-win` is tied to a specific major version of `winit` and cannot be used with other versions.

I'm closing this, since there's not much we can do.

**Comment by dannyfritz** [comment]
Can you explain a little bit more about why upgrading the winit dependency isn't possible? Cloning vulkano-win locally and changing the dep allegedly works, so I'm assuming there is some behavior or edge case you are aware of I'm not thinking of.

**Comment by eiglow** [comment]
I'm just running into this issue now, on winit 0.23.0. I'd rather not have to use an ancient version of winit to get this stuff to work.
