### ISSUE TITLE
Please update the bundled glslangValidator in glsl-to-spirv, it is buggy

### ISSUE THREAD

**Issue by hlavaatch** [vulkano-rs/vulkano#944]
Bundled glslangValidator in glsl-to-spirv is generating invalid SPIR-V code for memory barriers, please update to latest version and publish a new glsl-to-spirv crate

Compute shaders using memory barriers compiled with it are reported as invalid by spirv-val:
```
error: 125: MemoryBarrier: Vulkan specification requires Memory Semantics to have one of the following bits set: Acquire, Release, AcquireRelease or SequentiallyConsistent
```

See attachment for repro.
[invalid_spirv_repro.zip](https://github.com/vulkano-rs/vulkano/files/1894281/invalid_spirv_repro.zip)

**Comment by tomaka** [comment]
That is a legitimate concern.
I no longer have access to a Windows machine to build the precompiled Windows binary, however.

If someone (preferably a trusted already-existing constructor) has access to a Windows machine, it would be really nice to handle this! However I will just remove the Windows-specific code and update glslValidator.

**Comment by hlavaatch** [comment]
Here is glslangValidator.exe from the LunarG Vulkan SDK 1.1.70.1, it has digital signature by LunarG
[glslangValidator.zip](https://github.com/vulkano-rs/vulkano/files/1895730/glslangValidator.zip)

**Comment by hlavaatch** [comment]
Btw, the bundled exe seems to be 64bit, what happens on 32bit systems?

**Comment by rukai** [comment]
Resolved by https://github.com/vulkano-rs/vulkano/pull/947
