### ISSUE TITLE
[Question] ThreeBufferDefinition for now?

### ISSUE THREAD

**Issue by JohnDoneth** [vulkano-rs/vulkano#946]
Due to the limitation of the vertex module not having some sort of multi buffer definition just yet for vertex input I was wondering if I should create a pull request for a ThreeBufferDefinition code I have working at the moment in the meantime. 

In the game I am writing I needed to have vertices, normals, and texture coordinates all at the same time so I wrote my own ThreeBufferDefinition and it works as expected, mostly copying from TwoBuffersDefinition.

Let me know what you think?

Thanks for the amazing library!

**Comment by tomaka** [comment]
The two buffers definition was mostly a temporary workaround for the lack of way to do otherwise. I think that it should instead be reworked into a more generic solution.

But thanks for the suggestion!
