### ISSUE TITLE
Tessellation shader failing

### ISSUE THREAD

**Issue by JackYoustra** [vulkano-rs/vulkano#956]
Hello,
Tessellation shaders are supported in the features (1080 latest driver). Trying to compile a tessellation shader fails at runtime. It fails upon the start of the graphics pipeline (and what I think is the start of the compilation from SPIR-V to vendor-specific code).  The strange part is that it fails with a C9999 error "exception during compilation," which suggests it's not a problem with the shader code, but with  either the driver (compilation code) or the glsl to SPIR-V (invalid translation).

Here is the backtrace:
`thread 'main' panicked at 'Vulkan function returned VK_ERROR_INVALID_SHADER_NV', C:\Users\jack\.cargo\registry\src\github.com-1ecc6299db9ec823\vulkano-0.9.0\src\lib.rs:249:40
stack backtrace:
   0: std::sys::windows::backtrace::unwind_backtrace
             at C:\projects\rust\src\libstd\sys\windows\backtrace\mod.rs:65
   1: std::sys_common::backtrace::_print
             at C:\projects\rust\src\libstd\sys_common\backtrace.rs:71
   2: std::sys_common::backtrace::print
             at C:\projects\rust\src\libstd\sys_common\backtrace.rs:59
   3: std::panicking::default_hook::{{closure}}
             at C:\projects\rust\src\libstd\panicking.rs:207
   4: std::panicking::default_hook
             at C:\projects\rust\src\libstd\panicking.rs:223
   5: std::panicking::rust_panic_with_hook
             at C:\projects\rust\src\libstd\panicking.rs:402
   6: std::panicking::begin_panic<str*>
             at C:\projects\rust\src\libstd\panicking.rs:365
   7: vulkano::check_errors
             at C:\Users\jack\.cargo\registry\src\github.com-1ecc6299db9ec823\vulkano-0.9.0\src\lib.rs:249
   8: vulkano::pipeline::graphics_pipeline::builder::GraphicsPipelineBuilder<vulkano::pipeline::vertex::single::SingleBufferDefinition<geomapper::Vertex3D>, vulkano::pipeline::shader::GraphicsEntryPoint<(), geomapper::main::vs::MainInput, geomapper::main::vs::MainOutput, geomapper::main::vs::Layout>, (), vulkano::pipeline::shader::GraphicsEntryPoint<(), geomapper::main::tcs::MainInput, geomapper::main::tcs::MainOutput, geomapper::main::tcs::Layout>, (), vulkano::pipeline::shader::GraphicsEntryPoint<(), geomapper::main::tcs::MainInput, geomapper::main::tcs::MainOutput, geomapper::main::tcs::Layout>, (), vulkano::pipeline::shader::EmptyEntryPointDummy, (), vulkano::pipeline::shader::GraphicsEntryPoint<(), geomapper::main::fs::MainInput, geomapper::main::fs::MainOutput, geomapper::main::fs::Layout>, (), alloc::arc::Arc<vulkano::framebuffer::sys::RenderPass<geomapper::main::scope::CustomRenderPassDesc>>>::with_pipeline_layout<vulkano::pipeline::vertex::single::SingleBufferDefinition<geomapper::Vertex3D>,vulkano::pipeline::shader::GraphicsEntryPoint<(), geomapper::main::vs::MainInput, geomapper::main::vs::MainOutput, geomapper::main::vs::Layout>,(),vulkano::pipeline::shader::GraphicsEntryPoint<(), geomapper::main::tcs::MainInput, geomapper::main::tcs::MainOutput, geomapper::main::tcs::Layout>,(),vulkano::pipeline::shader::GraphicsEntryPoint<(), geomapper::main::tcs::MainInput, geomapper::main::tcs::MainOutput, geomapper::main::tcs::Layout>,(),vulkano::pipeline::shader::EmptyEntryPointDummy,(),vulkano::pipeline::shader::GraphicsEntryPoint<(), geomapper::main::fs::MainInput, geomapper::main::fs::MainOutput, geomapper::main::fs::Layout>,(),alloc::arc::Arc<vulkano::framebuffer::sys::RenderPass<geomapper::main::scope::CustomRenderPassDesc>>,alloc::boxed::Box<PipelineLayoutAbstract>>
             at C:\Users\jack\.cargo\registry\src\github.com-1ecc6299db9ec823\vulkano-0.9.0\src\pipeline\graphics_pipeline\builder.rs:1076
   9: vulkano::pipeline::graphics_pipeline::builder::GraphicsPipelineBuilder<vulkano::pipeline::vertex::single::SingleBufferDefinition<geomapper::Vertex3D>, vulkano::pipeline::shader::GraphicsEntryPoint<(), geomapper::main::vs::MainInput, geomapper::main::vs::MainOutput, geomapper::main::vs::Layout>, (), vulkano::pipeline::shader::GraphicsEntryPoint<(), geomapper::main::tcs::MainInput, geomapper::main::tcs::MainOutput, geomapper::main::tcs::Layout>, (), vulkano::pipeline::shader::GraphicsEntryPoint<(), geomapper::main::tcs::MainInput, geomapper::main::tcs::MainOutput, geomapper::main::tcs::Layout>, (), vulkano::pipeline::shader::EmptyEntryPointDummy, (), vulkano::pipeline::shader::GraphicsEntryPoint<(), geomapper::main::fs::MainInput, geomapper::main::fs::MainOutput, geomapper::main::fs::Layout>, (), alloc::arc::Arc<vulkano::framebuffer::sys::RenderPass<geomapper::main::scope::CustomRenderPassDesc>>>::with_auto_layout
             at C:\Users\jack\.cargo\registry\src\github.com-1ecc6299db9ec823\vulkano-0.9.0\src\pipeline\graphics_pipeline\builder.rs:300
  10: vulkano::pipeline::graphics_pipeline::builder::GraphicsPipelineBuilder<vulkano::pipeline::vertex::single::SingleBufferDefinition<geomapper::Vertex3D>, vulkano::pipeline::shader::GraphicsEntryPoint<(), geomapper::main::vs::MainInput, geomapper::main::vs::MainOutput, geomapper::main::vs::Layout>, (), vulkano::pipeline::shader::GraphicsEntryPoint<(), geomapper::main::tcs::MainInput, geomapper::main::tcs::MainOutput, geomapper::main::tcs::Layout>, (), vulkano::pipeline::shader::GraphicsEntryPoint<(), geomapper::main::tcs::MainInput, geomapper::main::tcs::MainOutput, geomapper::main::tcs::Layout>, (), vulkano::pipeline::shader::EmptyEntryPointDummy, (), vulkano::pipeline::shader::GraphicsEntryPoint<(), geomapper::main::fs::MainInput, geomapper::main::fs::MainOutput, geomapper::main::fs::Layout>, (), alloc::arc::Arc<vulkano::framebuffer::sys::RenderPass<geomapper::main::scope::CustomRenderPassDesc>>>::build<vulkano::pipeline::vertex::single::SingleBufferDefinition<geomapper::Vertex3D>,vulkano::pipeline::shader::GraphicsEntryPoint<(), geomapper::main::vs::MainInput, geomapper::main::vs::MainOutput, geomapper::main::vs::Layout>,(),vulkano::pipeline::shader::GraphicsEntryPoint<(), geomapper::main::tcs::MainInput, geomapper::main::tcs::MainOutput, geomapper::main::tcs::Layout>,(),vulkano::pipeline::shader::GraphicsEntryPoint<(), geomapper::main::tcs::MainInput, geomapper::main::tcs::MainOutput, geomapper::main::tcs::Layout>,(),vulkano::pipeline::shader::EmptyEntryPointDummy,(),vulkano::pipeline::shader::GraphicsEntryPoint<(), geomapper::main::fs::MainInput, geomapper::main::fs::MainOutput, geomapper::main::fs::Layout>,(),alloc::arc::Arc<vulkano::framebuffer::sys::RenderPass<geomapper::main::scope::CustomRenderPassDesc>>>
             at C:\Users\jack\.cargo\registry\src\github.com-1ecc6299db9ec823\vulkano-0.9.0\src\pipeline\graphics_pipeline\builder.rs:161
  11: geomapper::main
             at .\src\main.rs:639
  12: std::rt::lang_start::{{closure}}<()>
             at C:\projects\rust\src\libstd\rt.rs:74
  13: std::rt::lang_start_internal::{{closure}}
             at C:\projects\rust\src\libstd\rt.rs:59
  14: std::panicking::try::do_call<closure,i32>
             at C:\projects\rust\src\libstd\panicking.rs:306
  15: panic_unwind::__rust_maybe_catch_panic
             at C:\projects\rust\src\libpanic_unwind\lib.rs:102
  16: std::panicking::try
             at C:\projects\rust\src\libstd\panicking.rs:285
  17: std::panic::catch_unwind
             at C:\projects\rust\src\libstd\panic.rs:361
  18: std::rt::lang_start_internal
             at C:\projects\rust\src\libstd\rt.rs:58
  19: main
  20: invoke_main
             at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:64
  21: __scrt_common_main_seh
             at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:253
  22: BaseThreadInitThunk
  23: RtlUserThreadStart`

**Comment by JackYoustra** [comment]
This still crashes

**Comment by rukai** [comment]
Can you share an example that triggers the issue.

**Comment by JackYoustra** [comment]
Yes! Here's a demo program I'm using (tessellation branch): [geomapper](https://github.com/j-dong/geomapper). It'll fail when trying to run.

**Comment by rukai** [comment]
Hi, I tested the tessellation branch on windows and it wasn't giving me the error you posted but it was crashing with either a segfault or illegal instruction. I was able to fix it by upgrading to the latest branch, removing set_title (triggers a deadlock in winit), and fixing a bug in your code. I made PR with my changes https://github.com/j-dong/geomapper/pull/1 please let me know if this resolves the issue.

**Comment by JackYoustra** [comment]
Thanks. I've approved your PR and tried building it. It fails to compile the latest version of shaderc (0.3.11) on MSVC 2017. I can't change the version of shaderc (it's taken from a crate dependency), so I can't give any results yet.

**Comment by rukai** [comment]
I'm going to close this issue because it works for me, and you cant test the issue anymore, please reopen if you continue to run into the issue in vulkano 0.11
