### ISSUE TITLE
Unable to run the "triangle" example on macOS.

### ISSUE THREAD

**Issue by akxcv** [vulkano-rs/vulkano#983]
Hi! I've been trying to run some minimal code from the Guides ([here](http://vulkano.rs/guide/initialization)), but I kept crashing with `Undefined symbols for architecture x86_64`.

Then, I decided to run `cube.app` from Lunar Vulkan SDK, and it ran fine.

After that, I tried to run the triangle example from this repository. It crashed in runtime with the following error: 
```
thread 'main' panicked at 'failed to create Vulkan instance: IncompatibleDriver', libcore/result.rs:945:5
```

I'm kind of lost now, could someone please point me in the right direction? 🙏🏻

I am running this on a MacBook Pro Retina 13' Early 2015 with macOS High Sierra 10.13.5.

EDIT: I've copied all the frameworks and dylibs (I believe I got them all) to `/Library/Frameworks`, otherwise I would get different errors.

**Comment by rukai** [comment]
I believe this commit adds support for using the SDK on mac os https://github.com/vulkano-rs/vulkano/pull/948/files
However that commit hasn't made it into a crates.io release yet.
So I would try changing your vulkano dependencies in your cargo.toml to: 
```
vulkano = { git = "https://github.com/vulkano-rs/vulkano" }
vulkano-win = { git = "https://github.com/vulkano-rs/vulkano" }
vulkano-shader-derive = { git = "https://github.com/vulkano-rs/vulkano" }
```

**Comment by akxcv** [comment]
Thanks, I was able to run the code from the guides with vulkano from master branch, however, predictably, the error with `IncompatibleDriver` still persists.

**Comment by akxcv** [comment]
Okay, I got everything working when I set some environment variables:
```
VK_ICD_FILENAMES=.../vulcansdk-macos-1.1.77.0/macOS/etc/vulkan/icd.d/MoltenVK_icd.json 
VK_LAYER_PATH=.../vulcansdk-macos-1.1.77.0/macOS/etc/vulkan/explicit_layer.d
```

Should vulkano work without setting those variables? Should I have copied those files somewhere it can look it up?
