### ISSUE TITLE
"bufferless drawing should not be supplied with buffers"

### ISSUE THREAD

**Issue by Rua** [vulkano-rs/vulkano#996]
I'm doing bufferless drawing, but I'm getting this error message when I draw. It seems that this may be related to the way the command buffer is created:
```
AutoCommandBufferBuilder::primary_simultaneous_use(pipeline.device().clone(), queue.family()).unwrap()
	.begin_render_pass(framebuffer.clone(), false, vec![[0.0, 0.0, 1.0, 1.0].into()]).unwrap()
	.draw(pipeline.clone(),
		DynamicState::none(),
		Vec::new(),
		(),
		(),
	).unwrap()
	.end_render_pass().unwrap()
	.build().unwrap()
```
For the `vertices` argument of `draw` I provide an empty vector, because I have no actual buffer to provide. If I use anything else there such as `()` or `None`, I get a compile error:
```error[E0308]: mismatched types
   --> src/main.rs:409:6
    |
409 |                     (),
    |                     ^^ expected struct `std::vec::Vec`, found ()
    |
    = note: expected type `std::vec::Vec<std::sync::Arc<vulkano::buffer::BufferAccess + std::marker::Send + std::marker::Sync + 'static>>`
               found type `()`
```
I'm not sure what the proper way to handle this is. The compiler demands a `Vec`, but if I provide one then Vulkano gets upset with me.

**Comment by JustinRyanH** [comment]
@Rua I actually came across this issue myself. After digging I found that it was because the GraphicsPipelineAbstract implements the expected type. Right now you'd need to be explicit about what your GraphicsPipeline looks like, but currently I'm trying to investigate other ways round it

**Comment by Rua** [comment]
Has a solution been found for this?

**Comment by faulesocke** [comment]
The solution to this is deeply hidden inside the docs:
> Note that the concrete type of the graphics pipeline using BufferlessDefinition must be visible to the command buffer builder for this to be usable.

https://docs.rs/vulkano/0.19.0/vulkano/pipeline/vertex/struct.BufferlessVertices.html

I ran into this issue because my `Pipeline` was of type `Arc<dyn GraphicsPipelineAbstract>` and the solution was to change this to
```rust
    Arc<
        GraphicsPipeline<BufferlessDefinition, Box<dyn PipelineLayoutAbstract + Send + Sync>, R>,
    >
```
where `R` is the renderpass type.

The `draw` command looks like:
```rust
        cbb.draw(
            self.pipeline.clone(),
            &dynamic_state,
            BufferlessVertices {
                vertices: 3,
                instances: 1,
            },
            desc,
            push_consts,
        )
```

**Comment by Rua** [comment]
Closing this as most of the APIs involved here no longer exist.
